CC1CCC1	cyclobutylmethane	-162.0
[O-][N+]#N	Nitrogen oxide	-90.8
FS(F)(=O)=O	Sulfuryl difluoride	-136.0
CC(C)N(CCC(C(N)=O)(C1=CC=CC=C1)C1=CC=CC=N1)C(C)C	Disopyramide	94.8
CCN1C=C(C(O)=O)C(=O)C2=CC(F)=C(N3CCNC(C)C3)C(F)=C12	Lomefloxacin	240.0
CN(C)C	N,N-dimethylmethanamine	-117.0
ClC(Cl)(Cl)Cl	Tetrachloromethane	-23.0
C#C	Acetylene	-80.8
CC(Cl)Cl	1,1-dichloroethane	-97.0
CC(CO)(CO)[N+]([O-])=O	2-Methyl-2-nitro-1,3-propanediol	150.0
ClC1=CC=CS1	2-CHLOROTHIOPHENE	-72.0
CCCOC(=O)CC	n-Propyl propionate	-76.0
CC(=C)OC(C)=O	Isopropenyl acetate	-93.0
CCCOC=O	n-Propyl formate	-93.0
CC1=C(C=C(C=C1[N+]([O-])=O)[N+]([O-])=O)[N+]([O-])=O	2-Methyl-1,3,5-trinitrobenzene	80.0
CCC1=CC(CC)=CC=C1	m-Diethylbenzene	-84.0
CC(C)=CCCC(C)=O	6-METHYL-5-HEPTEN-2-ONE	-67.0
CCC(C)(C)C(C)C	2,3,3-TRIMETHYLPENTANE	-101.0
CCCC(C)(C)CC	3,3-Dimethylhexane	-126.0
CCCCC(C)(C)C	2,2-DIMETHYLHEXANE	-121.0
CC(=C)C(C)(C)C	2,3,3-TRIMETHYL-1-BUTENE	-110.0
CCC(CC)C(C)C	2-METHYL-3-ETHYLPENTANE	-115.0
CCCCSCC	3-Thiaheptane	-95.0
CCC1=CC=C(C)C(C)=C1	1,2-Dimethyl-4-ethylbenzene	-67.0
CCC(C)(CC)CC	3-METHYL-3-ETHYLPENTANE	-91.0
CC(C)CC(C)C(C)C	2,3,5-TRIMETHYLHEXANE	-128.0
CC(C)CCCC(C)C	2,6-DIMETHYLHEPTANE	-103.0
CC1=C(C)CCCC1	1,2-DIMETHYLCYCLOHEXENE	-84.0
CCCC1CCCCC1	Propylcyclohexane	-95.0
ClC(Cl)=C(Cl)C(Cl)(Cl)Cl	Hexachloropropene	-73.0
CCC1=CC(CC)=CC(C)=C1	1-Methyl-3,5-diethylbenzene	-74.0
CC(C)CC(C)=C	2,4-DIMETHYL-1-PENTENE	-124.0
CCCC(C)=C(C)C	2,3-DIMETHYL-2-HEXENE	-115.0
CC(C)C(C)(C)C(C)C	2,3,3,4-TETRAMETHYLPENTANE	-102.0
CCC1=CCCCC1	1-Ethylcyclohexene	-110.0
ClCC1CC1	(Chloromethyl)cyclopropane	-91.0
CCC1CCCC1C	1-METHYL-2-ETHYLCYCLOPENTANE (TRANS)	-106.0
CC(C)C1CC1	ISOPROPYLCYCLOPROPANE	-113.0
CC#CCC(C)C	5-methyl-2-hexyne	-93.0
CCC1CCC1	Ethylcyclobutane	-143.0
CCCC=CC	cis-2-Hexene	-141.0
COCCOC(C)=O	2-methoxyethyl_acetate	-65.0
CCC1=CC=CN=C1	3-ETHYLPYRIDINE	-77.0
C1CCSC1	TETRAHYDROTHIOPHENE	-96.0
ClCBr	bromo(chloro)methane	-88.0
CC1CO1	2-Methyloxirane	-112.0
CC(=C)C=C	ISOPRENE	-146.0
CCC(C)OC(C)=O	sec-butyl_acetate	-99.0
CCCCCCC(=O)OCC	Ethyl heptanoate	-66.0
CCCC#N	Butyronitrile	-112.0
CCSCC	Diethyl sulfide	-104.0
CCSC	ETHYL METHYL SULFIDE	-106.0
CCCCC#C	1-hexyne	-132.0
CCCCC#CCC	3-OCTYNE	-104.0
CCC1=CN=C(C)C=C1	5-ethyl-2-methylpyridine	-71.0
CCC1=CC=CC=C1Br	1-Bromo-2-ethylbenzene	-68.0
OC(=O)CCC(=O)C1=CC=C(C=C1)C1=CC=CC=C1	Fenbufen	186.0
CCC1=CC=CC=C1	ethylbenzene	-95.0
CCCCCl	1-Chlorobutane	-123.0
C1CC=CC1	cyclopentene	-135.0
CCCCC1=CC=CC=C1	Butylbenzene	-88.0
COCCO	2-METHOXYETHANOL	-85.0
CC1=CC(=O)CC(C)(C)C1	3,5,5-Trimethylcyclohex-2-en-1-one	-8.05
BrCCBr	1,2-dibromoethane	9.95
CCCCCCCCCCCCCCC=C	1-HEXADECENE	4.05
CCCCCCCCCCCCCCC	Pentadecane	9.95
CC(C)OC(=O)\C=C\C(=O)OC(C)C	diisopropyl_fumarate	2.05
CCC1=CC=CC=N1	2-ETHYLPYRIDINE	-63.0
ClCCCBr	1-bromo-3-chloropropane	-59.0
COC(=O)C(Cl)Cl	METHYL DICHLOROACETATE	-52.0
CC(C1=CC=CC=C1)C1=CC=CC=C1	1,1-DIPHENYLETHANE	-17.9
CCC1=CC=C(C)C=C1C	1,3-DIMETHYL-4-ETHYLBENZENE	-63.0
CCC(CC)(CC)CC	3,3-DIETHYLPENTANE	-33.0
ClC1=CC=CC=C1C=C	2-Chlorostyrene	-63.0
CCCCCCCCCS	1-NONANETHIOL	-20.1
CCCCCCCCC(C)C	2-METHYLDECANE	-49.0
ClS(Cl)(=O)=O	Sulfuryl dichloride	-54.0
NCC1=CN=CC=C1	3-(Aminomethyl)pyridine	-21.1
COC(=O)CCl	METHYL CHLOROACETATE	-32.0
CC(=O)OCCC1=CC=CC=C1	2-Phenylethyl acetate	-31.1
CC(C)C1=CC(=CC=C1)C(C)C	m-Diisopropylbenzene	-63.0
CC1=CC=CN=C1	3-Picoline	-18.1
CCCCCCCCCCCCCCCC	Hexadecane	18.1
C1CC[C@H]2CCCC[C@H]2C1	cis-Decahydronaphthalene	-43.0
COC(=O)CC(=O)OC	Dimethyl malonate	-62.0
CCC1=CC=C2C=CC=CC2=C1	2-ethylnaphthalene	-7.4
CC1CC1	cyclopropylmethane	-177.0
[O-][N+](=O)C1=CC(=CC=C1)S(Cl)(=O)=O	3-Nitrobenzenesulfonyl chloride	60.9
CCC1=CC=C(CC)C=C1	1,4-diethylbenzene	-42.9
CC(F)(F)Cl	1-CHLORO-1,1-DIFLUOROETHANE	-131.0
O=C=S	thioxomethanone	-139.0
CC1CC=CC1	4-METHYLCYCLOPENTENE	-161.0
CCC1(C)CCCC1	1-methyl-1-ethylcyclopentane	-144.0
CCC1CC1	Ethylcyclopropane	-149.0
CCC1(C)CC1	1-methyl-1-ethylcyclopropane	-130.0
CC1CC1(C)C	1,1,2-Trimethylcyclopropane	-138.0
CC=CC=C	1,cis-3-pentadiene	-141.0
CNC1=NC2=CC=C(Cl)C=C2C(C2=CC=CC=C2)=[N+]([O-])C1	Chlordiazepoxide	236.0
CCS	ethanethiol	-148.0
CC=C	prop-1-ene	-185.0
ClC1=C(Cl)C(Cl)=C(C(Cl)=C1Cl)C1=C(Cl)C(Cl)=C(Cl)C(Cl)=C1Cl	DECACHLOROBIPHENYL	306.0
CN1CCN(C)C1=O	1,3-Dimethyl-2-imidazolidinone	8.1
CCCCCCCCCCCCCCCCCCBr	1-BROMOOCTADECANE	28.1
CC1=CC=CC(I)=C1	3-Iodotoluene	-27.1
O=CN1CCCCC1	1-Formylpiperidine	-30.9
CCC1=C(C)C=CC=C1C	1,3-DIMETHYL-2-ETHYLBENZENE	-16.1
CC1=CC=CC(C)=C1I	2-Iodo-1,3-dimethylbenzene	11.1
CCC(C)(C)C(C)(C)C	2,2,3,3-TETRAMETHYLPENTANE	-9.9
OCC(F)F	2,2-DIFLUOROETHANOL	-28.1
[O-][N+](=O)C([N+]([O-])=O)([N+]([O-])=O)[N+]([O-])=O	TETRANITROMETHANE	13.9
CC1=CC(N)=CC(C)=C1	3,5-Dimethylaniline	9.9
CC1=C(F)C(F)=C(F)C(F)=C1F	2,3,4,5,6-Pentafluorotoluene	-29.9
CC1=CC=CC=C1C	o-Xylene	-25.1
CC(=C)C1=CC=CC=C1	ALPHA-METHYLSTYRENE	-23.1
CCC1=CC=CC=C1CC	1,2-Diethylbenzene	-31.1
CCCCCCCCCCCCCCCCCC	n-Octadecane	28.1
C1COCCO1	1,4-DIOXANE	11.9
OC(=O)C(F)(F)F	Trifluoroacetic acid	-15.1
N#CCC1=CC=CC=C1	benzyl_cyanide	-23.9
CC1=CC=C(Cl)C(Cl)=C1	3,4-dichlorotoluene	-15.1
ClC1=CC(Cl)=CC=C1	1,3-Dichlorobenzene	-24.9
OCC1=CC=CC=C1	phenylmethanol	-15.1
C1C=CC2=CC=CC=C12	1H-Indene	-1.9
OC1=CC=CC(=C1)C(F)(F)F	3-(Trifluoromethyl)phenol	-1.9
CN(C)C(=O)N(C)C	tetramethylurea	-1.1
CC(Br)C(C)(Br)Br	2,3,3-tribromobutane	1.9
CC1=CC=CC=C1C1=CC=CC=C1	2-METHYLBIPHENYL	-0.1
CC(C)(C)C1=CC=CC=C1O	2-tert-Butylphenol	-6.9
OCCC1=CC=CC=N1	2-(2-Hydroxyethyl)pyridine	-7.9
CCCCCCCCCCCC(=O)OC	METHYL DODECANOATE	5.1
CC1=CC=C(C)C(C)=C1C	1,2,3,4-TETRAMETHYLBENZENE	-6.1
ICCCCI	1,4-Diiodobutane	5.9
CCC(=O)C1=CC=C(C)C=C1	4'-Methylpropiophenone	7.1
CC(C)(C)C1=CC=CC(=N1)C(C)(C)C	2,6-Di-tert-butylpyridine	2.1
CC#CCO	But-2-yn-1-ol	-2.1
C1COCCN1	morpholine	-4.9
CCC1=CC=C(N)C=C1	4-ethylaniline	-4.9
CCN	Ethanamine	-81.1
CCOC(=O)C(C)C	ETHYL ISOBUTYRATE	-88.1
CCCC(=O)OCCC(C)C	Isopentyl butyrate	-73.1
CC(C)COC(C)=O	Isobutyl acetate	-98.9
FC1=CC=C(C=C1)C1=CC=CC=C1	4-FLUOROBIPHENYL	74.1
C#CC1=CC=CC=C1	PHENYLACETYLENE	-44.9
CCCCC(=O)OCC	ethyl valerate	-91.1
CCCCCOC(=O)CCC	pentyl_butyrate	-73.1
CCC(C)C(C)(C)C	2,2,3-TRIMETHYLPENTANE	-112.0
CCCC(C)(C)C	2,2-Dimethylpentane	-124.0
CCCCC(C)C	2-METHYLHEXANE	-118.0
CC(C)(Cl)Cl	2,2-Dichloropropane	-33.9
CCCCSC	2-THIAHEXANE	-97.9
C1C=CCC=C1	1,4-cyclohexadiene	-49.1
CC1(C)CCCC1	1,1-DIMETHYLCYCLOPENTANE	-69.9
CCC(Br)CC	3-BROMOPENTANE	-126.0
CCCCCCCCC#N	octyl_cyanide	-34.1
CCCCCCC(Cl)=O	HEPTANOYL CHLORIDE	-83.9
CC(C)(C)C1CCCCC1	TERT-BUTYLCYCLOHEXANE	-41.1
CCCCCCC(C)CC	3-METHYLNONANE	-84.9
CCCCC(C)=C	2-METHYL-1-HEXENE	-103.0
CCCC(C)(C)C(C)C	2,3,3-TRIMETHYLHEXANE	-117.0
CCC(C)C(C)(C)CC	3,3,4-TRIMETHYLHEXANE	-101.0
CC(=C)C#N	Methacrylonitrile	-35.9
CC1=CC=C(C(F)=C1)[N+]([O-])=O	3-Fluoro-4-nitrotoluene	53.1
CCC(S)CC	3-PENTANETHIOL	-111.0
CC(C)CC1CCCC1	Isobutylcyclopentane	-115.0
CCCCCCC(C)=C	2-Methyl-1-octene	-77.9
CCC(C)CC(O)CC	3-HEPTANOL, 5-METHYL-	-91.1
CC=C(C)C(C)C	3,4-Dimethyl-trans-2-pentene	-124.0
COC(C)OC	Acetaldehyde dimethyl acetal	-113.0
[O-][N+](=O)C1=CC=CC=C1C1=CC=CC=C1	2-Nitrobiphenyl	37.1
CNC	N-Methylmethanamine	-92.1
CCCCCCCCCl	1-CHLOROOCTANE	-57.9
CCCCCCCCS	1-OCTANETHIOL	-49.1
CC(C)(C)C=C	3,3-DIMETHYL-1-BUTENE	-115.0
ClCC(Cl)(Cl)Cl	1,1,1,2-tetrachloroethane	-70.1
CCCCCCCI	1-iodoheptane	-48.1
CC(C)CCO	3-Methylbutan-1-ol	-117.0
COC(=O)C1=CC=C(I)C=C1	Methyl 4-iodobenzoate	115.0
N#CC=CC#N	(2E)-but-2-enedinitrile	96.9
NCC=C	allylamine	-88.1
ClCC1CO1	EPICHLOROHYDRIN	-57.1
SCCS	Ethane-1,2-dithiol	-41.1
CC1=CC(Br)=CC=C1	m-bromotoluene	-39.9
CCCNC(=O)NS(=O)(=O)C1=CC=C(Cl)C=C1	4-chloro-n-(propylcarbamoyl)benzenesulfonamide	128.0
CC1=CC(C)=C(C)C=C1	1,2,4-trimethylbenzene	-43.9
BrCCCBr	1,3-dibromopropane	-34.1
CCCCC#N	VALERONITRILE	-96.1
CCOC(=O)C=C	ethyl acrylate	-71.1
CC(C)(C)I	2-Iodo-2-methylpropane	-38.1
CC(C)(C)C#C	3,3-dimethylbut-1-yne	-78.1
COCOC	dimethoxymethane	-105.0
CC1=CC(Cl)=CC=C1	1-Chloro-3-methylbenzene	-47.9
CCCCCCCC	n-octane	-56.9
C1CCCC1	cyclopentane	-93.9
ClC(Cl)C(Cl)(Cl)Cl	1,1,1,2,2-Pentachloroethane	-28.9
C1=CC=C2N=CC=CC2=C1	Quinoline	-14.9
CCC(C)C	ISOPENTANE	-160.0
[O-][N+](=O)C1=CC(=CC(=C1Cl)[N+]([O-])=O)C#N	4-Chloro-3,5-dinitrobenzonitrile	141.0
OC(=O)CCCC(=O)C1=CC=CC=C1	4-Benzoylbutyric acid	127.0
NC1=CC=CC=C1	aniline	-6.15
N#CC(C1=CC=CC=C1)C1=CC=CC=C1	DIPHENYLACETONITRILE	74.2
CC(F)(F)F	1,1,1-Trifluoroethane	-111.0
CC(C)C1=CC(C)=CC=C1	1-Methyl-3-isopropylbenzene	-63.9
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	DOTRIACONTANE	69.8
COC(=O)C(C)C	METHYL ISOBUTYRATE	-84.8
CCCCC(O)CCC	4-Octanol, (.+-.)-	-40.9
CC1(C)CCCCC1	1,1-Dimethylcyclohexane	-33.1
CC(C)(C)C(C)(C)C	2,2,3,3-TETRAMETHYLBUTANE	101.0
CC(C)C=C(C)C	2,4-DIMETHYL-2-PENTENE	-128.0
CCCCCC(=O)OCCC	n-Propyl hexanoate	-68.8
CCCCCC#N	pentyl_cyanide	-80.2
CCCCCSCCCCC	di-n-pentyl sulfide	-51.1
CCC1=CC(C)=CC(C)=C1	1,3-DIMETHYL-5-ETHYLBENZENE	-84.2
CCCC1=CC=CC=C1C	1-METHYL-2-PROPYLBENZENE	-60.1
CCC1CCCCC1	ethylcyclohexane	-111.0
CCC1=CC(C)=CC=C1C	1,4-Dimethyl-2-ethylbenzene	-53.9
CCCC1CCCC1	Propylcyclopentane	-117.0
CCCCC(C)CCC	4-METHYLOCTANE	-113.0
CC(C)CCC(C)(C)C	2,2,5-Trimethylhexane	-106.0
CCC(C)=C(C)C	2,3-DIMETHYL-2-PENTENE	-118.0
CCCCC(C)CCCC	5-METHYLNONANE	-87.8
CCC(CC)C(C)(C)C	2,2-DIMETHYL-3-ETHYLPENTANE	-99.2
FC1=CC=C(C=C1)C(F)(F)F	4-Fluorobenzotrifluoride	-41.9
CC(C)C#C	3-methyl-1-butyne	-89.8
C=CCC1CCCC1	Allylcyclopentane	-111.0
ClC(=O)C1=CC(=CC(=C1)C(Cl)=O)C(Cl)=O	1,3,5-Benzenetricarbonyl chloride	36.1
CC(C)C(C(C)C)C(C)C	2,4-DIMETHYL-3-ISOPROPYLPENTANE	-81.8
CC(C(C)(C)C)C(C)(C)C	2,2,3,4,4-PENTAMETHYLPENTANE	-38.9
CCC#CC(C)C	2-Methyl-3-hexyne	-117.0
CCC(C)C=CC	4-Methyl-trans-2-hexene	-126.0
CC=CCC(C)C	5-Methyl-trans-2-hexene	-124.0
CCC1=CC=CC=C1Cl	1-CHLORO-2-ETHYLBENZENE	-82.8
CCC(C)O	Butan-2-ol	-115.0
CCCS	1-Propanethiol	-113.0
CC(C)=CC(C)(C)C	2,4,4-TRIMETHYL-2-PENTENE	-106.0
CCOC(=O)CC(C)C	ethyl_isovalerate	-99.2
CCCCCS	1-PENTANETHIOL	-75.8
CCCCCCBr	1-bromohexane	-84.8
CC#CC	2-BUTYNE	-32.1
CCCCSCCCC	Dibutyl sulfide	-79.8
CCC1=CC=C(C)C=C1	4-Ethyltoluene	-62.1
CCC#CC	2-PENTYNE	-109.0
CCCCCCC(C)C	2-METHYLOCTANE	-80.2
ClC=C(Cl)Cl	1,1,2-trichloroethene	-84.8
CC(=O)OCC1=CC=CC=C1	benzyl_acetate	-51.1
ICC=C	ALLYL IODIDE	-99.2
CCOCC	Diethyl ether	-116.0
CC1=CC(C)=CC(C)=C1	Mesitylene	-44.9
CCCCS	butane-1-thiol	-116.0
CCCCCCC=O	heptanal	-43.1
CC(C)CC(C)(C)C	2,2,4-Trimethylpentane	-107.0
CCCI	1-iodopropane	-101.0
CCCCCCCCC=C	Dec-1-ene	-66.2
CCCCCC	Hexane	-95.2
ClC(Cl)(Cl)Br	BROMOTRICHLOROMETHANE	-5.85
CCCCCCCCCCCCCCCC(C)C	2-METHYLHEPTADECANE	5.85
COCC(O)=O	METHOXYACETIC ACID	7.85
CCCCCCCCCCCCC	Tridecane	-5.15
CC(=O)OO	Ethaneperoxoic acid	-0.05
CCCCCCCCCCC1CCCCC1	Decylcyclohexane	-1.85
ClC1=CC=CC=C1I	o-Chloroiodobenzene	0.85
CCCCCCCCCCCCCl	1-CHLORODODECANE	-9.15
CC1=CC(C)=C(C)C(C)=C1	1,2,3,5-TETRAMETHYLBENZENE	-23.9
BrC1=CN=CC=C1	3-Bromopyridine	-27.1
CCCCCCCCCCCl	1-CHLORODECANE	-31.1
CCCCCCCCCCCCCC(=O)OCC	Ethyl tetradecanoate	12.2
BrCC(Br)Br	1,1,2-Tribromoethane	-29.1
[O-][N+](=O)C1=C(F)C=CC(F)=C1	1,4-Difluoro-2-nitrobenzene	-11.8
ClC(Cl)=C(Cl)Cl	tetrachloroethylene	-22.1
CC(C)C1=CC=C(Cl)C=C1	p-chlorocumene	-12.2
CC(C)OC(=O)CC(C)=O	Isopropyl acetoacetate	-27.1
BrC1=CC(I)=CC=C1	m-Bromoiodobenzene	-9.15
IC1=CC=CC=C1	iodobenzene	-31.1
CCCCCCCCCCI	1-IODODECANE	-16.1
N#CC1=CC=CC=C1	benzonitrile	-12.8
CCCCCCCCCC	Decane	-29.9
O=C1NS(=O)(=O)C2=CC=CC=C12	o-Benzoic sulfimide	229.0
CS(=O)(=O)C1=CC=C(C=C1)C(O)C(CO)NC(=O)C(Cl)Cl	P-METHYLSULFONYLAMPHENICOL	165.0
CCCl	Chloroethane	-139.0
CC1=CC=CC=C1S(N)(=O)=O	o-Toluenesulfonamide	156.0
CC1=CC=NC(N)=N1	2-AMINO-4-METHYLPYRIMIDINE	160.0
C[C@H]1CC[C@@H](C)C1	cis-1,3-Dimethylcyclopentane	-134.0
CCC(C)C(C)=C	2,3-DIMETHYL-1-PENTENE	-134.0
CCC(C)(C)C=C	3,3-DIMETHYL-1-PENTENE	-134.0
NC(=O)C1=CC(Br)=CC=C1	m-bromobenzamide	155.0
C[C@H]1[C@H]2CC3=CC=C(O)C=C3[C@]1(C)CCN2CC=C(C)C	Pentazocine	146.0
S1C2=CC=CC=C2SC2=CC=CC=C12	THIANTHRENE	159.0
CC(C)C(C)=C	2,3-DIMETHYL-1-BUTENE	-157.0
C=CCCC=C	1,5-hexadiene	-141.0
CCCC(C)=C	2-Methyl-1-Pentene	-136.0
CCCC(C)C	2-methylpentane	-154.0
CC=C(C)C	2-Methylbut-2-ene	-134.0
ClC1=CC=C(C=C1)C1=CC=C(Cl)C=C1	PCB-15	149.0
CCCCC	Pentane	-130.0
CCN(CC)CC	N,N-Diethylethanamine	-115.0
OC=O	Formic acid	8.16
CCCCC(O)=O	Valeric acid	-33.8
CCC=C	But-1-ene	-185.0
C=C	Ethylene	-169.0
CC1=NN=C(N)S1	5-Methyl-1,3,4-thiadiazol-2-amine	225.0
CCC(C)(O)CC	3-methyl-3-pentanol	-23.8
CCOP(=O)(OCC)OCC	triethyl phosphate	-56.2
N1C=CC=C1	1H-Pyrrole	-23.4
C1CC2=CC=CC=C2C1	indane	-51.2
CC1CCC(=O)CC1	4-METHYLCYCLOHEXANONE	-40.8
CCCCCC(C)(C)O	2-methyl-2-heptanol	-50.2
CC1=CC=C(C)S1	2,5-DIMETHYLTHIOPHENE	-62.8
CCCC1=CC=C(C)C=C1	1-METHYL-4-PROPYLBENZENE	-63.8
CCCCS(=O)CCCC	di-n-butyl sulfoxide	32.8
CCCCCCCCCCl	1-CHLORONONANE	-39.2
CCCCCCC(C)O	2-octanol	-31.8
CC1CCCC1(C)C	1,1,2-Trimethylcyclopentane	-21.8
CCCCCCOC=O	n-Hexyl formate	-62.8
CC(C)C(C)(C)C(C)(C)C	2,2,3,3,4-PENTAMETHYLPENTANE	-36.2
CCOC(=O)CC1=CC=CC=C1	Ethyl Phenylacetate	-29.2
CC1=CC=CS1	2-METHYLTHIOPHENE	-63.2
CCC1=CC=C(Cl)C=C1	1-Chloro-4-ethylbenzene	-62.8
OCC(O)CO	glycerol	18.0
CCCCOC1=CC=CC=C1	butyl_phenyl_ether	-19.2
CC1=CC=CC(=C1)C(C)(C)C	3-tert-Butyltoluene	-41.2
CC(Br)CCCBr	1,4-Dibromopentane	-34.2
C1=CC=NC=C1	pyridine	-41.8
BrC1=CC=CC=C1	bromobenzene	-30.8
CC1=CC=CC(C)=C1C	1,2,3-trimethylbenzene	-25.2
CCCCCCCCCCC	Undecane	-25.8
CC(O)=O	acetic acid	16.8
FC1=C(F)C(F)=C(C#N)C(F)=C1F	Pentafluorobenzonitrile	2.2
ClCC1=C(Cl)C=C(Cl)C=C1	2,4-Dichlorobenzyl chloride	-2.8
CC(C)(O)C#C	2-Methylbut-3-yn-2-ol	2.8
CC(C)C1=CC(=CC(=C1)C(C)C)C(C)C	1,3,5-TRIISOPROPYLBENZENE	-7.2
CC(C)(C)CCC(C)(C)C	2,2,5,5-TETRAMETHYLHEXANE	-12.8
CCCCC(=O)C1=CC=CC=C1	Valerophenone	-9.2
CC1=CC=CC=C1CC1=CC=CC=C1	2-Methyldiphenylmethane	6.8
NCC1=CC=NC=C1	4-(Aminomethyl)pyridine	-7.8
OCCOCCO	DIETHYLENE GLYCOL	-10.2
CCCCCCCCCCC1=CC=CC=C1	DECYLBENZENE	-14.2
NC1=CC(Cl)=CC=C1	3-chloroaniline	-10.2
CCCCCCCCCCCC	DODECANE	-9.8
CN	Methanamine	-93.2
FC(F)(F)F	Tetrafluoromethane	-184.0
CC(C)CCCl	1-CHLORO-3-METHYLBUTANE	-104.0
CC(C)OC(C)=O	Isopropyl acetate	-73.2
CC(C)=C	2-methylprop-1-ene	-140.0
FC1=C(F)C(F)=C(C(F)=C1F)C(F)(F)F	Octafluorotoluene	-65.8
CCOC(Cl)=O	ETHYL CHLOROFORMATE	-80.8
CC(C)C(C)=C(C)C	2,3,4-TRIMETHYL-2-PENTENE	-113.0
CC(C)=C=C	3-METHYL-1,2-BUTADIENE	-114.0
CCC(CC)CC	3-ETHYLPENTANE	-119.0
CCCSSCCC	Di-n-propyl disulfide	-85.8
CCCCCCCCCCCCCCCCCCC(O)=O	Nonadecanoic acid	69.2
NC(=O)C(Cl)Cl	2,2-Dichloroacetamide	99.2
CC(C)(C)CC=C	4,4-DIMETHYL-1-PENTENE	-137.0
CCCCCCCC(C)C	2-METHYLNONANE	-74.8
CCC(C(C)C)C(C)C	2,4-DIMETHYL-3-ETHYLPENTANE	-122.0
CCC1CCCC1	ETHYLCYCLOPENTANE	-138.0
CC(C)C1=CC=CC=C1Cl	o-Chlorocumene	-74.2
CCCCCC(C)CC	3-METHYLOCTANE	-108.0
CC(C)C1CCCC1	ISOPROPYLCYCLOPENTANE	-111.0
CC1CCC(C)(C)C1	1,1,3-trimethylcyclopentane	-142.0
CC1(C)CCC=CC1	4,4-DIMETHYLCYCLOHEXENE	-74.2
CCC(C)(C)CC(C)C	2,4,4-TRIMETHYLHEXANE	-113.0
CC=CC=C	1,trans-3-Pentadiene	-87.2
FC(Br)(Br)Br	Tribromofluoromethane	-73.8
CC1=C(C)CCC1	1,2-Dimethylcyclopentene	-90.2
FC1(F)OC2=CC=CC(=C2O1)C1=CNC=C1C#N	Fludioxonil	199.0
CCC(Br)=C	2-Bromo-1-butene	-133.0
CC(C)CC#C	4-Methyl-1-pentyne	-105.0
CCC=CC(C)C	2-Methyl-trans-3-hexene	-142.0
C=CCNCC=C	diallylamine	-88.2
CCC	Propane	-188.0
CCCCBr	1-bromobutane	-112.0
C1CCC1	CYCLOBUTANE	-90.8
CCCCCCCCCCCCCCCCCCCC(O)=O	Icosanoic acid	75.2
CCCCCI	1-IODOPENTANE	-85.8
CCCC=C(C)C	2-METHYL-2-HEXENE	-130.0
CCCC#CC	2-HEXYNE	-89.8
CCCC=CCC	trans-3-Heptene	-137.0
CN1CCN(CC1)C1=NC2=CC(Cl)=CC=C2NC2=CC=CC=C12	Clozapine	184.0
CCC(Br)CBr	1,2-DIBROMOBUTANE	-65.2
BrCC=C	ALLYL BROMIDE	-119.0
CCOC(C)=O	Ethyl acetate	-83.8
COC(C)(C)C	2-Methoxy-2-methylpropane	-109.0
CCBr	bromoethane	-119.0
CCO	Ethanol	-114.0
CCC(O)=O	Propionic Acid	-20.9
CCC=CC	cis-2-Pentene	-151.0
C1CC1	Cyclopropane	-127.0
CCCCCCC	Heptane	-90.8
CC1=CC=C(CC2=CC=CC=C2)C=C1	4-Methyldiphenylmethane	4.79
C1CCOC1	tetrahydrofuran	-108.0
CCCCCCC=C	1-Octene	-102.0
CC1=CCCCC1	1-methylcyclohexene	-120.0
CCCCC=C	Hex-1-ene	-140.0
COC(=O)C(C)=C	methyl methacrylate	-47.8
C1=CC=C2C=NC=CC2=C1	isoquinoline	26.2
CO	Methanol	-97.8
CC(Br)CBr	1,2-dibromopropane	-55.2
OC1=CC(O)=CC(O)=C1	phloroglucinol, anhydrous	218.0
NCC(O)C1=CC=CC=C1	2-Amino-1-phenylethanol	56.8
OC(=O)C1=CC=CC=N1	2-Picolinic acid	137.0
NCCCCNCCCN	N-(3-aminopropyl)butane-1,4-diamine	23.8
NC1=CC=NC=C1	4-aminopyridine	159.0
COC1=CC(CC(O)=O)=CC=C1O	Homovanillic acid	143.0
CC(=O)NCCCCCC(O)=O	6-Acetamidohexanoic acid	104.0
CCCCCC1=CC2=C(C(O)=C1)C1=C(C=CC(C)=C1)C(C)(C)O2	6,6,9-trimethyl-3-pentyl-6h-benzo[c]chromen-1-ol	76.8
CNC(=O)OC1=CC=CC2=C1OC(C)(C)C2	Carbofuran	151.0
CC12CCC(CC1)C(C)(C)O2	1,8-Cineole	1.25
CNC(=O)CSP(=S)(OC)OC	o,o-dimethyl s-[2-(methylamino)-2-oxoethyl] phosphorodithioate	51.8
OC(=O)CC1=CC=C(C=C1)C1=CC=CC=C1	4-BIPHENYLACETIC ACID	161.0
COP(=S)(OC)OC1=CC=C(SC)C(C)=C1	o,o-dimethyl o-[3-methyl-4-(methylsulfanyl)phenyl] phosphorothioate	7.25
CC(C)C1=CC=C(C)C2=CC=C(C)C2=C1	guaiazulene	31.8
OCC1=CNC2=CC=CC=C12	INDOLE-3-METHANOL	97.8
OC(=O)CCC1=CNC2=CC=CC=C12	Indole-3-propionic acid	134.0
COP(=S)(OC)OC1=CC=C(C=C1)[N+]([O-])=O	o,o-dimethyl o-(4-nitrophenyl) phosphorothioate	35.8
CC(=O)NBr	n-bromoacetamide	104.0
COC1=CC=C(CC2=NC=CC3=C2C=C(OC)C(OC)=C3)C=C1OC	Papaverine	147.0
O=C1C(C(=O)C2=CC=CC=C12)C1=CC=CC=C1	phenindione	150.0
CC(C)(C)C1=CC=C(C=C1)C(O)CCCN1CCC(CC1)C(O)(C1=CC=CC=C1)C1=CC=CC=C1	Terfenadine	147.0
NS(=O)(=O)CC1=NOC2=C1C=CC=C2	Zonisamide	162.0
CC1=CC=C(C=C1)N(CC1=NCCN1)C1=CC(O)=CC=C1	Phentolamine	175.0
CCC1(C(=O)NC(=O)NC1=O)C1=CCCCC1	cyclobarbital	173.0
CC1=CC(C)=NN1	3,5-Dimethyl-1H-pyrazole	107.0
ClC(Cl)C(C1=CC=C(Cl)C=C1)C1=CC=C(Cl)C=C1	1,1'-(2,2-dichloroethane-1,1-diyl)bis(4-chlorobenzene)	109.0
CC[N+]([O-])=O	Nitroethane	-89.2
CC(C)(O)C1CCC(C)(O)CC1	Terpin	158.0
CC1=C(N)C2=C(C=C1)C(=O)C1=CC=CC=C1C2=O	1-Amino-2-methyl-9,10-anthraquinone	205.0
CC1=CC=CC(C(O)=O)=C1O	3-METHYLSALICYLIC ACID	165.0
ClC1=C(Cl)C(=O)C(C#N)=C(C#N)C1=O	2,3-Dichloro-5,6-dicyanobenzoquinone	215.0
OC1=CC=CC=C1C(=O)NC1=CC=CC=C1	salicylanilide	137.0
COC1=C(Cl)C=C(Cl)C=C1Cl	1,3,5-Trichloro-2-methoxybenzene	61.2
CC(=O)C1=CC=CS1	2-ACETYLTHIOPHENE	10.2
OC1=C(C=C(C=C1[N+]([O-])=O)[N+]([O-])=O)[N+]([O-])=O	2,4,6-TRINITROPHENOL	122.0
NC1=NC(=NC(N)=N1)C1=CC=CC=C1	BENZOGUANAMINE	227.0
CC1=CC=C2OC(=O)C=CC2=C1	6-Methylcoumarin	76.2
O=C(OC(=O)C1=CC=CC=C1)C1=CC=CC=C1	BENZOIC ANHYDRIDE	42.2
CCC(C)=NO	N-hydroxybutan-2-imine	-29.8
NC1=CC=CC(=C1)C(F)(F)F	3-(Trifluoromethyl)aniline	5.75
ClC(=O)C1=CC(=CC=C1)C(Cl)=O	Isophthaloyl dichloride	43.8
OCC1=CN=CC=C1	3-pyridinemethanol	-6.75
ClC1=CC=CC=C1NC1=NC(Cl)=NC(Cl)=N1	4,6-Dichloro-N-(2-chlorophenyl)-1,3,5-triazin-2-amine	160.0
C=CC#N	acrylonitrile	-83.8
CC(C)(C)NC(=O)C=C	N-TERT-BUTYLACRYLAMIDE	129.0
CC(C)CC(=O)CC(C)C	2,6-DIMETHYL-4-HEPTANONE	-41.8
BrC1CCCCC1	bromocyclohexane	-56.8
OC1=CN=CC=C1	3-hydroxypyridine	127.0
ClC1=CC=CC=N1	2-chloropyridine	-46.2
CC(C)CCOC=O	isoamyl_formate	-93.2
CCSSCC	DIETHYL DISULFIDE	-102.0
ClCCOCCOCCCl	1,2-BIS(2-CHLOROETHOXY)ETHANE	-31.8
CC(=O)NNC1=CC=CC=C1	N-Acetyl-N'-phenylhydrazine	130.0
CC1=CC(=CC(Br)=C1O)C1(OS(=O)(=O)C2=CC=CC=C12)C1=CC(C)=C(O)C(Br)=C1	4,4'-(1,1-dioxido-3h-2,1-benzoxathiole-3,3-diyl)bis(2-bromo-6-methylphenol)	241.0
C1=CC2=CC=C(N=C2C=C1)C1=NC2=CC=CC=C2C=C1	2,2'-BIQUINOLINE	195.0
OC1=CC=C(Cl)C=C1CC1=CC=CC=C1	2-Benzyl-4-chlorophenol	48.2
CCC1=CC(O)=CC=C1C([O-])=O	Ethyl p-hydroxybenzoate	116.0
[O-][N+](=O)C1=C(Cl)C=CC(=C1)C(F)(F)F	4-chloro-3-nitrobenzotrifluoride	-2.75
CCOC1=CC(C=O)=CC=C1O	3-ethoxy-4-hydroxybenzaldehyde	77.2
[O-][N+](=O)N1CN(CN(C1)[N+]([O-])=O)[N+]([O-])=O	1,3,5-Trinitro-1,3,5-triazinane	205.0
OC1=CC(O)=C(C=C1)C(=O)C1=CC=C(O)C=C1O	2,2',4,4'-Tetrahydroxybenzophenone	201.0
OC(=O)C1=C2C=CC=CC2=NC(=C1)C1=CC=CC=C1	2-Phenylquinoline-4-carboxylic acid	215.0
OC(=O)CCI	3-IODOPROPIONIC ACID	81.8
ClCCCCl	1,3-dichloropropane	-99.8
CC(C)C(O)C(C)(C)CO	2,2,4-TRIMETHYL-1,3-PENTANEDIOL	51.8
C1=CC=C2C=NN=CC2=C1	Phthalazine	90.8
O1C2=CC=CC=C2OC2=CC=CC=C12	Oxanthrene	122.0
[O-][N+](=O)C1=CC(=CC=C1F)S(=O)(=O)C1=CC(=C(F)C=C1)[N+]([O-])=O	Bis(4-fluoro-3-nitrophenyl) sulfone	194.0
FC(F)(F)C1=CC(Cl)=C(Cl)C=C1	3,4-DICHLOROBENZOTRIFLUORIDE	-12.2
NC(=O)C1=CN=C(N)C=C1	6-Aminonicotinamide	247.0
CON(C)C(=O)NC1=CC=C(Cl)C(Cl)=C1	linuron	93.2
CC(=O)NC1=CC=CC(=C1)C(F)(F)F	3'-(trifluoromethyl)acetanilide	105.0
OC(=O)C(F)(F)C(F)(F)C(F)(F)F	Heptafluorobutyric acid	-17.8
OC(=O)C1=CC(=CC=C1)C(F)(F)F	3-(Trifluoromethyl)benzoic acid	105.0
CC1=CC=C(C=C1)S(F)(=O)=O	p-TOLUENESULFONYL FLUORIDE	41.2
CCOCOCC	diethoxymethane	-66.2
OC(=O)C1=CC=NC2=CC=CC=C12	Quinoline-4-carboxylic acid	254.0
O=C1NC(=O)C2=NC=CN=C2N1	2,4-DIHYDROXYPTERIDINE	348.0
O=CC1=CNC2=CC=CC=C12	INDOLE-3-CARBOXALDEHYDE	197.0
OC(=O)C1=COC=C1	3-FUROIC ACID	122.0
C1CC2=CC=CC=C2NC2=CC=CC=C12	Iminodibenzyl	107.0
O=C1OCC=C1	2(5H)-FURANONE	4.25
NC1=CC=CC=N1	2-Aminopyridine	57.8
CC(C)C1=CC=CC=C1C	1-Methyl-2-isopropylbenzene	-71.8
[O-][N+](=O)C1=CC=CC=C1[N+]([O-])=O	O-DINITROBENZENE	118.0
C(SCC1=CC=CC=C1)C1=CC=CC=C1	Dibenzyl sulfide	49.2
CCCCCCCCCCCCCC(=O)CCCCCCCCCCCCC	14-HEPTACOSANONE	77.8
C1C=CC=CC=C1	cycloheptatriene	-79.8
O=C1C=CC2=CC=CC3=C2C1=CC=C3	1H-Phenalen-1-one	154.0
CC(C)C=C	3-Methyl-1-Butene	-168.0
COC1=CC=C(C(O)=O)C(OC)=C1OC	2,3,4-TRIMETHOXYBENZOIC ACID	101.0
BrC1=CC2=CC=CC=C2C2=C1C=CC=C2	9-Bromophenanthrene	64.2
BrCCN1C(=O)C2=CC=CC=C2C1=O	N-(2-BROMOETHYL)PHTHALIMIDE	82.2
CCCC(=O)CC	3-Hexanone	-55.2
CC(C)(C)N=C=S	tert-Butyl isothiocyanate	10.2
CC1CCC=CC1	4-METHYLCYCLOHEXENE	-115.0
CCCCOC=O	n-Butyl formate	-91.8
CCCCCCCCCCCCCCCCCCCCCCCCCCC	n-Heptacosane	59.2
CCC(O)(CC)CC	3-ethyl-3-pentanol	-12.8
COC(=O)C(Cl)(Cl)Cl	METHYL TRICHLOROACETATE	-17.8
[O-][N+](=O)C1=CC=C2CCC3=CC=CC1=C23	5-Nitro-1,2-dihydroacenaphthylene	103.0
CC(=O)OC1=CC=CC=C1[N+]([O-])=O	o-nitrophenyl_acetate	40.2
CCOC(=O)C1=CC=CO1	ETHYL 2-FUROATE	34.2
CC1=CC(=O)OC1=O	Citraconic anhydride	7.75
CC(=O)N[C@@H](CS)C(O)=O	N-Acetyl-L-cysteine	110.0
CCC1=CC=C(C=C1)C(O)=O	4-ETHYLBENZOIC ACID	113.0
CN(C)C1=CC=C(C=C1)C(O)=O	4-(Dimethylamino)benzoic acid	243.0
OC(COC1=CC=CC=C1)COC1=CC=CC=C1	1,3-Diphenoxy-2-propanol	81.8
CC1=CC=C(C=C1)N=C=S	p-Tolyl isothiocyanate	25.2
CCOC1=CC=C(O)C=C1	4-Ethoxyphenol	66.2
CCCCOC	methyl_butyl_ether	-115.0
CCCOCC	ethyl_propyl_ether	-127.0
CCCCCCCCl	1-chloroheptane	-69.8
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	n-Hexatriacontane	76.2
CC[Si](CC)(CC)CC	TETRAETHYLSILANE	-82.2
CC(=O)OC1=CC=CC=C1OC(C)=O	Catechol diacetate	64.2
CC1=CC(C)=C(C)C(O)=C1	2,3,5-Trimethylphenol	93.8
[O-][N+](=O)C1=CC=C(O1)C=O	5-NITRO-2-FURALDEHYDE	35.8
CC1=CC(C)=C(C)C(C)=C1C	pentamethylbenzene	54.2
C1CC2=CC=CC=C2C2=CC=CC=C12	9,10-DIHYDROPHENANTHRENE	34.2
O=P(C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	TRIPHENYLPHOSPHINE OXIDE	156.0
OC(=O)C12CC3CC(CC(C3)C1)C2	Adamantane-1-carboxylic acid	175.0
CC(=O)OC1=CC=CC2=C1C=CC=C2	1-Naphthyl acetate	44.8
CCCCCC(=O)CCCCC	6-UNDECANONE	14.8
CCC1=CC=CC(C)=C1C	1,2-DIMETHYL-3-ETHYLBENZENE	-49.8
NNC(=O)C1=CC=CC=C1O	2-Hydroxybenzhydrazide	148.0
CC(OC1=CC=CC=C1)C(O)=O	2-Phenoxypropionic acid	118.0
N1C2=C(C=C1C1=CC=CC=C1)C=CC=C2	2-Phenylindole	190.0
CC(C)(C)CC(O)=O	3,3-DIMETHYLBUTYRIC ACID	6.25
CC(C)(C)CC(C)(C)C	2,2,4,4-TETRAMETHYLPENTANE	-66.8
NC1=CC=C(C=C1)C(=O)C1=CC=CC=C1	4-Aminobenzophenone	123.0
CCCCCCCCCCCCOC(=O)C1=CC(O)=C(O)C(O)=C1	n-Dodecyl gallate	96.8
ClC1C2=CC=CC=C2CCC2=CC=CC=C12	dibenzosuberyl chloride	107.0
CC(C)(C)C1=CC(=CC(=C1O)C(C)(C)C)C(O)=O	3,5-Di-tert-butyl-4-hydroxybenzoic acid	208.0
CSC(C)C	methyl_isopropyl_sulfide	-102.0
CC1=CC=C(N)N=C1	2-AMINO-5-METHYLPYRIDINE	76.2
CC[Si](Cl)(Cl)CC	DICHLORODIETHYLSILANE	-96.8
OCC1=C(Cl)C=C(Cl)C=C1	2,4-Dichlorobenzyl alcohol	59.2
CCCCCCCCOC1=CC=C(C(=O)C2=CC=CC=C2)C(O)=C1	2-Hydroxy-4-n-octyloxybenzophenone	48.2
BrC1C2=CC=CC=C2C2=CC=CC=C12	9-Bromofluorene	103.0
CC(C)C1=CC=C2C=CC=CC2=C1	2-ISOPROPYLNAPHTHALENE	14.2
BrC1=CC=CC=C1C=C	2-BROMOSTYRENE	-52.8
O=CC1CCCCC1	Cyclohexanecarbaldehyde	34.8
CN1C(=O)C(=O)C2=CC=CC=C12	1-Methylisatin	131.0
CC(=O)C1=CC=CC(Br)=C1	3'-Bromoacetophenone	7.75
CN(C)C(=O)NC1=CC(=CC=C1)C(F)(F)F	fluometuron	164.0
ClC1=NC(Cl)=C(Cl)C(Cl)=C1Cl	pentachloropyridine	125.0
ClC1=CC(Cl)=C(Cl)N=C1Cl	2,3,5,6-TETRACHLOROPYRIDINE	90.8
CC1=CC=C(O)C(=C1)C(C)(C)C	2-tert-butyl-4-methylphenol	51.8
ClC1=CC=CC=C1C=C(C#N)C#N	(2-Chlorobenzylidene)malononitrile	95.2
COC(=O)C1=CC(Cl)=CC=C1Cl	METHYL 2,5-DICHLOROBENZOATE	38.8
BrC1=CSC=C1Br	3,4-DIBROMOTHIOPHENE	4.75
ClC1=CC=C(Cl)S1	2,5-DICHLOROTHIOPHENE	-40.8
CCCCCCCCCCCCCCCCCCC=C	1-EICOSENE	28.8
CCC(C)CC=C	4-METHYL-1-HEXENE	-141.0
CCOC(=O)C(C)(C)C	Ethyl trimethylacetate	-89.8
CCC(CC)C=C	3-ETHYL-1-PENTENE	-127.0
CCCCCCCCCCCCCCCC=C	1-HEPTADECENE	11.2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	TETRATETRACONTANE	87.8
CC1=CC(N)=CC=C1Cl	4-Chloro-3-methylaniline	83.8
Cl[SiH](Cl)Cl	TRICHLOROSILANE	-127.0
CCOC(=O)C1=CC=C(C=C1)N(C)C	Ethyl 4-(dimethylamino)benzoate	63.8
CN1N=NC2=C1C=CC=C2	1-Methyl-1H-benzotriazole	64.8
ClC1=CN=C(Cl)C=C1	2,5-Dichloropyridine	60.8
COC1=CC(Cl)=CC=C1O	4-Chloro-2-methoxyphenol	16.8
CCC1=CC(C)=C(C)C=C1C	1,2,4-trimethyl-5-ethylbenzene	-13.8
OC(=O)CC1=C(N=C(S1)C1=CC=CC=C1)C1=CC=C(Cl)C=C1	FENTIAZAC	161.0
COC1=CC(CCC(C)=O)=CC=C1O	4-(4-Hydroxy-3-methoxyphenyl)-2-butanone	40.8
C(OC1=CC=CC=C1)C1CO1	Glycidyl phenyl ether	3.75
CCCCOC1=CC=C(O)C=C1	4-Butoxyphenol	65.2
CC1(C)CC(=O)CC(=O)C1	5,5-Dimethylcyclohexane-1,3-dione	148.0
O=S(=O)(C1=CC=CC=C1)C1=CC=CC=C1	Diphenyl sulfone	128.0
BrCC(Br)(Br)CBr	1,2,2,3-TETRABROMOPROPANE	10.8
CCC(C)(C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@@H](O)CC(=O)O3)[C@@H]12	Simvastatin	136.0
CC(C)C1(C)N=C(NC1=O)C1=NC=CC=C1C(O)=O	2-(4-isopropyl-4-methyl-5-oxo-4,5-dihydro-1H-imidazol-2-yl)nicotinic acid	171.0
OC(=O)CCC=C	4-Pentenoic acid	-22.2
CCCCCCCCCCCCCC(C)=O	2-Pentadecanone	39.2
OC1=CC=C(C=C)C=C1	p-Vinylphenol	73.2
CC=CC	(2E)-but-2-ene	-105.0
O=C1NC=NC2=CC=CC=C12	4-Hydroxyquinazoline	218.0
CC(=O)NC12CC3CC(CC(C3)C1)C2	1-Acetamidoadamantane	148.0
CN(C)C1=CC=CC2=C1C=CC=C2S(N)(=O)=O	Dansyl amide	220.0
COCCOC1=C(OC)C=C(CC2=CN=C(N)N=C2N)C=C1OC	tetroxoprim	154.0
NC1=NC(Cl)=CC(Cl)=N1	2-Amino-4,6-dichloropyrimidine	220.0
CC1=CC=C(CN)C=C1	4-Methylbenzylamine	12.2
C1=CC=C(C=C1)[Si](C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	Tetraphenylsilane	237.0
O=CC1=CC=C(OC2=CC=CC=C2)C=C1	4-Phenoxybenzaldehyde	24.8
CC1=CC(C=O)=C(C)N1C1=CC=CC=C1	2,5-dimethyl-1-phenylpyrrole-3-carboxaldehyde	88.8
CC1=CC=C(C)N1C1=CC=CC=C1	2,5-Dimethyl-1-phenylpyrrole	49.8
OC1=C(Cl)C(=O)C(O)=C(Cl)C1=O	2,5-dichloro-3,6-dihydroxy-1,4-benzoquinone	283.0
CCCCCCCCCC(Cl)=O	Decanoyl chloride	-34.8
ClC1=NN=C(Cl)C=C1	3,6-Dichloropyridazine	67.8
FC1=C(F)C2=C(C(F)=C1F)C(F)=C(F)C(F)=C2F	Octafluoronaphthalene	87.2
[O-][N+](=O)C1=C(F)C=C(F)C=C1F	1,3,5-Trifluoro-2-nitrobenzene	3.75
NC(=O)C(F)(F)F	2,2,2-Trifluoroacetamide	72.8
FC(F)(F)C1=CC=C(C=O)C=C1	4-(Trifluoromethyl)benzaldehyde	1.75
NC1=CC=CC=C1NC1=CC=CC=C1	N-Phenyl-o-phenylenediamine	79.2
ClC1=CC=C(C=C1)C(=O)CBr	2-Bromo-4'-chloroacetophenone	96.2
COC(=O)C1=CC=CC=C1OC(C)=O	methyl_2-acetoxybenzoate	51.8
C1=CC=C(N=C1)C1=CC=NC=C1	2,4'-Bipyridine	61.2
COC1=CC=C(C=C1)C(=O)C1=CC=CC=C1	4-Methoxybenzophenone	61.8
CCOC(=O)C1=CC=CN=C1	Ethyl Nicotinate	8.75
COC(=O)C1=CC=CC(I)=C1	methyl_3-iodobenzoate	54.2
IC1=CC=C(I)S1	2,5-Diiodothiophene	41.2
FC(F)(F)C1=CC(=CC=C1)C(=O)C1=CC=CC=C1	3-(Trifluoromethyl)benzophenone	52.2
CCOC(=O)C#CC(=O)OCC	Diethyl acetylenedicarboxylate	1.75
CCCCCCCCC(Cl)=O	Nonanoyl chloride	-60.8
NC1=C(C=C(Br)C=C1)[N+]([O-])=O	4-Bromo-2-nitroaniline	112.0
OC(=O)CCCCC=C	6-Heptenoic acid	-6.25
NC(=O)C1=CC=C(F)C=C1	4-Fluorobenzamide	156.0
CCOC(=O)C1=CC2=C(N1)C=CC=C2	Ethyl indole-2-carboxylate	124.0
ClC1=CC(CC#N)=CC=C1	(3-Chlorophenyl)acetonitrile	11.8
BrC1=CN=CC2=CC=CC=C12	4-Bromoisoquinoline	41.2
C1=CC=C(C=C1)C1=NC2=CC=CC=C2N=C1C1=CC=CC=C1	2,3-Diphenylquinoxaline	126.0
CC=C1CCCC1	Ethylidenecyclopentane	-130.0
FC1=CC=C(C=C1)N1CCNCC1	1-(4-Fluorophenyl)piperazine	31.8
CC1=CC(=CC=C1N)C(O)=O	4-Amino-3-methylbenzoic acid	170.0
C[Si]1(O[Si](C)(O[Si](C)(O[Si](C)(O1)C=C)C=C)C=C)C=C	2,4,6,8-Tetramethyl-2,4,6,8-tetravinylcyclotetrasiloxane	-43.2
CCCC#CCC	3-HEPTYNE	-131.0
ClC1=CC(Cl)=NC(Cl)=N1	2,4,6-Trichloropyrimidine	22.8
COC(=O)CCC(O)=O	4-Methoxy-4-oxobutanoic acid	57.8
NC1=CC(Cl)=C(O)C=C1	4-Amino-2-chlorophenol	152.0
O=CC1=CC2=CC=CC=C2C2=C1C=CC=C2	Phenanthrene-9-carboxaldehyde	102.0
O=C1CCC(CC1)C1=CC=CC=C1	4-Phenylcyclohexanone	79.8
CCOC1=CC=C(CC(O)=O)C=C1	4-Ethoxyphenylacetic acid	88.8
CC(=O)C1=CC=C(Br)S1	2-Acetyl-5-bromothiophene	94.8
CC1=CC(Cl)=NC(Cl)=N1	2,4-Dichloro-6-methylpyrimidine	46.2
CCC1=CC=CC(=C1)C1=CC=CC=C1	1-Ethyl-3-phenylbenzene	-27.8
ON1C(=O)CCC1=O	1-hydroxypyrrolidine-2,5-dione	96.8
CCOC(=O)C(=C)C#N	Ethyl 2-cyanoacrylate	-22.2
OC(=O)CCOC1=CC=CC=C1	3-Phenoxypropionic acid	97.8
CSC1=CC=C(C=C1)C(O)=O	4-(Methylthio)benzoic acid	195.0
CC1=CC(=CC=C1Cl)[N+]([O-])=O	2-Chloro-5-nitrotoluene	42.8
NC(=O)C1=C(F)C=CC=C1F	2,6-DIFLUOROBENZAMIDE	147.0
OC1=CC2=C(C=C1)C1=CC=CC=C1N2	2-Hydroxycarbazole	272.0
OC(C(O)=O)C1=CC=C(Br)C=C1	4-Bromomandelic acid	117.0
CCCCCCC(O)CCCC	5-Undecanol	-3.75
CCC1=CCCC1	1-Ethylcyclopentene	-118.0
CCOC1=CC=C(C=C1)C#N	4-Ethoxybenzonitrile	61.8
CC1=C(C=NN1C1=CC=CC=C1)C(O)=O	5-Methyl-1-phenyl-1H-pyrazole-4-carboxylic acid	167.0
COC(=O)C1=CC(Cl)=CC=C1[N+]([O-])=O	Methyl 5-chloro-2-nitrobenzoate	48.8
N#CC1=CNC2=CC=CC=C12	Indole-3-carbonitrile	180.0
CC1=C2C=CC=CC2=NC1C1=CC=CC=C1	3-Methyl-2-phenylindole	91.2
CC(=CCO)C=CC=C(C)C=CC1=C(C)CCCC1(C)C	Retinol	63.2
OC(=O)C1=C(F)C=CC(F)=C1F	2,3,6-Trifluorobenzoic Acid	131.0
COC(=O)C1=CNC2=C1C=CC=C2	Methyl indole-3-carboxylate	151.0
BrC1=CC=C(O1)C=O	5-Bromo-2-furaldehyde	83.8
O=C(\C=C\C=C\C1=CC2=C(OCO2)C=C1)N1CCCCC1	piperine	131.0
CCCCC=CC	trans-2-heptene	-109.0
N[C@@H](CC1=CC=C(O)C(F)=C1)C(O)=O	3-fluoro-L-tyrosine	261.0
NC(=S)C1=C(Cl)C=CC=C1Cl	2,6-Dichlorothiobenzamide	151.0
CCCCC[C@H](O)\C=C\[C@H]1[C@H](O)CC(=O)[C@@H]1CCCCCCC(O)=O	Alprostadil	116.0
CO[C@H]1[C@@H](C[C@@H]2CN3CCC4=C(NC5=C4C=CC(OC)=C5)[C@H]3C[C@@H]2[C@@H]1C(=O)OC)OC(=O)\C=C\C1=CC(OC)=C(OC)C(OC)=C1	methyl (3beta,16beta,17alpha,18beta,20alpha)-11,17-dimethoxy-18-{[(2e)-3-(3,4,5-trimethoxyphenyl)prop-2-enoyl]oxy}yohimban-16-carboxylate	238.0
OC1=CC2=C(C=C1)C=CC(=O)O2	7-hydroxycoumarin	230.0
OC1=CC2=C(C(O)=C1)C(=O)C(O)=C(O2)C1=CC=CC=C1	3,5,7-Trihydroxyflavone	215.0
C[C@H](CCC(O)=O)[C@H]1CC[C@H]2[C@@H]3C[C@H](O)[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C	hyodeoxycholic acid	198.0
CCCC(C)=CC	3-METHYL-CIS-2-HEXENE	-119.0
[O-][N+](=O)C1=CC(\C=C\C(=O)C2=CC=CC=C2)=CC=C1	3-Nitrochalcone	146.0
OC(=O)CCCCCCCCC=C	10-UNDECENOIC ACID	24.2
CC(=O)NC1=CC(C)=CC=C1	N-(3-METHYLPHENYL)ACETAMIDE	65.2
OCC(O)C(O)CO	meso-Erythritol	122.0
CC1=CC(O)=CC(O)=C1	3,5-Dihydroxytoluene	107.0
CC1=CC=NC2=C1C=CC=C2	Lepidine	9.75
CC1=CC=C2C=CC=CC2=N1	Quinaldine	-1.75
ClC1=CC(Br)=CC=C1	1-bromo-3-chlorobenzene	-21.8
OC1=CC=C2C=CC=CC2=C1N=NC1=CC=CC=N1	1-(pyridin-2-yldiazenyl)-2-naphthol	140.0
COC1=CC(C)=CC=C1O	2-METHOXY-4-METHYLPHENOL	5.75
FC1=CC=CC=C1C=O	2-fluorobenzaldehyde	-44.8
C1CC2=CC=CC=C2O1	2,3-dihydrobenzo[b]furan	-21.2
ClC1=CC=C(Cl)C(Cl)=C1Cl	1,2,3,4-tetrachlorobenzene	47.2
CCC1=CC=NC=C1	4-ETHYLPYRIDINE	-90.8
CCC1=CC=C(Br)C=C1	1-Bromo-4-ethylbenzene	-43.2
FC1=CC(F)=C(F)C=C1F	1,2,4,5-tetrafluorobenzene	4.25
COC(=O)C1=CC=CN=C1	methyl nicotinate	42.2
FC1=CC(F)=CC(F)=C1	1,3,5-TRIFLUOROBENZENE	-5.75
CC1=CC=C(Cl)C=C1Cl	2,4-dichlorotoluene	-13.2
NC1=C(F)C(F)=CC(F)=C1F	2,3,5,6-TETRAFLUOROANILINE	31.2
CC(=O)C1=C(C)C=C(C)C(C)=C1	2',4',5'-Trimethylacetophenone	10.2
FC1=CC=CC=C1I	1-Fluoro-2-iodobenzene	-41.8
ClC(Cl)C(=O)C1=CC=CC=C1	2,2-Dichloroacetophenone	20.8
ClCC(=O)C1=CC=C(Cl)C=C1	2,4'-dichloroacetophenone	101.0
COC1=CC=CC(=C1)[N+]([O-])=O	M-NITROANISOLE	38.2
CCOC(=O)C1=CC=C(OC)C(OC)=C1	Ethyl 3,4-dimethoxybenzoate	43.8
OC(=O)CCC(=O)C(O)=O	2-ketoglutaric acid	115.0
OC(=O)CC1=CC(O)=C(O)C=C1	3,4-DIHYDROXYPHENYLACETIC ACID	129.0
N1C=CN=C1	1H-Imidazole	90.2
N1C=CC2=CC=CC=C12	1H-Indole	52.0
CC1=CC=C2C=C3C(C=CC4=C3C=CC=C4)=C3CCC1=C23	3-methyl-1,2-dihydrocyclopenta[ij]tetraphene	180.0
CN(C)CCC=C1C2=CC=CC=C2CCC2=CC=CC=C12	Amitriptyline	196.0
CS(=O)(=O)OCCCCOS(C)(=O)=O	Busulfan	116.0
CC1=CC=C(C=C1)C1=CC(=NN1C1=CC=C(C=C1)S(N)(=O)=O)C(F)(F)F	Celecoxib	158.0
OC1=NC2=C(O1)C=CC(Cl)=C2	5-Chloro-2(3H)-benzoxazolone	191.0
OCC1=CC(=O)C(O)=CO1	kojic acid	154.0
O=CC1=CC=CC=C1C=O	PHTHALALDEHYDE	56.2
CCC1=NC(N)=NC(N)=C1C1=CC=C(Cl)C=C1	5-(4-chlorophenyl)-6-ethylpyrimidine-2,4-diamine	233.0
CO[C@H]1[C@@H](C[C@@H]2CN3CCC4=C(NC5=CC(OC)=CC=C45)[C@H]3C[C@@H]2[C@@H]1C(=O)OC)OC(=O)C1=CC(OC)=C(OC)C(OC)=C1	reserpine	265.0
OC[C@H]1O[C@H](C[C@@H]1O)N1C=C(F)C(=O)NC1=O	2'-Deoxy-5-fluorouridine	150.0
S=C=S	methanedithione	-112.0
CC(C)S	2-PROPANETHIOL	-131.0
C[N+]([O-])=O	Nitromethane	-28.8
OC(=O)C(Br)(Br)Br	Tribromoacetic acid	132.0
O=S1(=O)CC=CC1	2,5-DIHYDROTHIOPHENE 1,1-DIOXIDE	64.8
NC(=O)C=C	acrylamide	84.2
ClS(=O)(=O)C1=CC=CC=C1	BENZENESULFONYL CHLORIDE	14.8
CC(C)(C)C1CCC(=O)CC1	4-tert-Butylcyclohexanone	48.8
CC(=O)C1=CC=C(Br)C=C1	p-Bromoacetophenone	50.8
CCOC1=CC=CC=C1	phenetole	-29.8
CCCC(C)Br	2-BROMOPENTANE	-95.8
O=P(OC1=CC=CC=C1)(OC1=CC=CC=C1)OC1=CC=CC=C1	TRIPHENYL PHOSPHATE	50.2
CC1=CC2=NNN=C2C=C1	5-Methyl-1H-benzotriazole	81.0
CCCCCCCCCCCCBr	1-Bromododecane	-9.75
NC1=CC(Cl)=C(F)C=C1	3-CHLORO-4-FLUOROANILINE	45.8
NC1=CC=C(F)C=C1F	2,4-DIFLUOROANILINE	-7.75
C[Si]1(C)O[Si](C)(C)O[Si](C)(C)O[Si](C)(C)O1	2,2,4,4,6,6,8,8-octamethyl-1,3,5,7,2,4,6,8-tetroxatetrasilocane	17.8
BrC1=CC=CC=C1I	o-Bromoiodobenzene	9.75
C1=CC=C(C=C1)P(C1=CC=CC=C1)C1=CC=CC=C1	TRIPHENYLPHOSPHINE	80.2
CC1=CC=CC=C1C=C	2-Methylstyrene	-68.8
CC1=NC2=C(N1)C=CC=C2	2-methylbenzimidazole	176.0
CCC1=CC=CC(C)=C1	3-Ethyltoluene	-95.8
CCCCCCCC(C)O	2-Nonanol	-35.2
N#CCCCCCCC#N	1,6-Dicyanohexane	-3.25
CCCCCCCCCCCCCCCO	1-Pentadecanol	45.8
CC1=CC=CC(=C1)C1=CC=CC=C1	3-METHYLBIPHENYL	4.75
CCC(=C)CC	2-ETHYL-1-BUTENE	-132.0
O=S1(=O)CCCO1	1,2-oxathiolane 2,2-dioxide	31.8
CC1(C)C2CC1C(=C)CC2	b-pinene	-61.2
[O-][N+](=O)C1=CC=C(OC2=CC=C(Cl)C=C2Cl)C=C1	2,4-Dichloro-1-(4-nitrophenoxy)benzene	70.2
OC(=O)CC1=CC(=CC=C1)[N+]([O-])=O	3-Nitrophenylacetic Acid	119.0
BrC1=CC=CC=C1C#N	o-Bromobenzonitrile	55.2
CCCCCC1CCCCC1	n-pentylcyclohexane	-57.8
BrC1=CC=CC(=C1)C#N	m-Bromobenzonitrile	39.2
CCOC(=O)N1C=CN(C)C1=S	ethyl 3-methyl-2-thionoimidazoline-1-carboxylate	124.0
CCOC(=O)NCCOC1=CC=C(OC2=CC=CC=C2)C=C1	Fenoxycarb	53.2
NC(=O)C1=CC=C(O)C=C1	p-hydroxybenzamide	161.0
CCOC(=O)C(C(=O)OCC)C1=CC=CC=C1	diethyl_phenylmalonate	16.2
FC1=CC=CC=C1C1=CC=CC=C1	2-Fluorobiphenyl	73.8
OC1=CC=CC=C1C(F)(F)F	2-(Trifluoromethyl)phenol	45.8
CC1(CCCCC1)C(O)=O	1-Methylcyclohexanecarboxylic acid	37.8
BrCCCCCCCCBr	1,8-Dibromooctane	15.8
OC(=O)CCCCCCCBr	8-Bromooctanoic acid	38.8
C\C=C\C=C\CO	trans,trans-2,4-Hexadien-1-ol	30.8
CC=CC=CC(O)=O	(2E,4E)-hexa-2,4-dienoic acid	134.0
Cl[C@H]1[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H]1Cl	a-hexachlorocyclohexane	159.0
Cl[C@H]1[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H]1Cl	g-bhc(lindane)	113.0
COC1=CC=C(C=C1)C(C)=O	p-Methoxyacetophenone	38.2
CNCCO	2-(Methylamino)ethanol	-4.75
CCOC1=CC=C(C=O)C=C1	4-ethoxybenzaldehyde	13.8
OCC(F)(F)F	2,2,2-Trifluoroethanol	-43.8
[O-][N+](=O)C1=C(Cl)C(Cl)=CC=C1	2,3-Dichloronitrobenzene	61.8
O=CC1=CC=CC(=C1)C#N	3-cyanobenzaldehyde	76.8
ClC1C=CC2C1C1(Cl)C(Cl)=C(Cl)C2(Cl)C1(Cl)Cl	heptachlor	95.2
CCCC(C)C1(CC)C(=O)NC(=O)NC1=O	pentobarbital	130.0
CCCCNC(=O)NS(=O)(=O)C1=CC=C(C)C=C1	N-(Butylcarbamoyl)-4-methylbenzenesulfonamide	129.0
C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@@H]2C(=O)CO	deoxycorticosterone	142.0
CC(C)C#N	2-METHYLPROPANENITRILE	-71.8
CC(=O)CCl	1-Chloroacetone	-44.8
CCC1=CC2=C(C=C1)C(=O)C1=CC=CC=C1C2=O	2-ETHYLANTHRAQUINONE	109.0
COC1=CC=CC=C1	anisole	-37.2
C1CCC=CC1	cyclohexene	-104.0
CCC(=O)OC	methyl propionate	-87.8
CCCCCCCCCCCCCC	Tetradecane	5.75
OC1=CC=C(C=C1)C#N	4-hydroxybenzonitrile	112.0
COC1=CC=C(NC(=O)N(C)C)C=C1Cl	Metoxuron	127.0
CCCN(CC1CC1)C1=C(C=C(C=C1[N+]([O-])=O)C(F)(F)F)[N+]([O-])=O	PROFLURALIN	32.2
NCCCCN	butane-1,4-diamine	27.2
COC(=O)CCC(=O)OC	DIMETHYL SUCCINATE	19.2
COC(=O)C1=CC=CC=C1N	Methyl 2-aminobenzoate	24.2
COC1=CC(C=O)=CC=C1O	4-Hydroxy-3-methoxybenzaldehyde	81.8
CC1=CC(=CC=C1)[N+]([O-])=O	1-methyl-3-nitrobenzene	15.8
CS(C)=O	dimethyl sulfoxide	18.2
NC(=O)C1=CC=CN=C1	nicotinamide	130.0
CCN1C=C(C(O)=O)C(=O)C2=CC=C(C)N=C12	1-Ethyl-7-methyl-4-oxo-1,4-dihydro-1,8-naphthyridine-3-carboxylic acid	229.0
CC[C@H](C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@@H](O)CC(=O)O3)[C@@H]12	Lovastatin	175.0
CC=CC=O	(2E)-but-2-enal	-76.2
O=C(C(=O)C1=CC=CC=C1)C1=CC=CC=C1	Benzil	94.8
[O-][N+](=O)C1=CC=C(Cl)C=C1	4-chloronitrobenzene	83.8
CCCCOC(=O)C1=CC=C(N)C=C1	butyl 4-aminobenzoate	57.8
CCCCOC(=O)CCC	Butyl butyrate	-91.8
C1CCCCC1	Cyclohexane	6.73
NC=O	FORMAMIDE	2.27
[H]C([H])([H])C([H])([H])[H]	Ethane	-183.0
O=C(CCNNC(=O)C1=CC=NC=C1)NCC1=CC=CC=C1	Nialamide	151.0
FC(Cl)(Cl)Cl	trichloro(fluoro)methane	-111.0
CCCCOC(=O)C=C	n-Butyl acrylate	-64.3
CC(Cl)=C	2-CHLOROPROPENE	-138.0
CC(=C)CCC(C)=C	2,5-DIMETHYL-1,5-HEXADIENE	-75.3
CC(C)C1=CC(C(C)C)=C(C=C1C(C)C)C(C)C	1,2,4,5-Tetraisopropylbenzene	119.0
O1C=CC=C1	furan	-85.3
NC(=O)C1=CC=CC=C1[N+]([O-])=O	2-Nitrobenzamide	176.0
COC1=CC(CC2=CN=C(N)N=C2N)=CC(OC)=C1OC	5-(3,4,5-trimethoxybenzyl)pyrimidine-2,4-diamine	201.0
CCCCCCCCCCCCCCBr	1-Bromotetradecane	5.3
CC1OC(C)OC(C)O1	2,4,6-Trimethyl-1,3,5-trioxane	12.3
OC1=CC=CC=C1Br	o-Bromophenol	5.3
CCCCCCC=CCCCCCCCC(O)=O	9-Hexadecenoic acid	0.2
O=C1CCO1	beta-propiolactone	-33.7
CC(C)(OOC(C)(C)C1=CC=CC=C1)C1=CC=CC=C1	1,1'-(dioxydipropane-2,2-diyl)dibenzene	40.3
NNC1=CC=CC=C1	Phenylhydrazine	19.3
OCCF	2-Fluoroethanol	-26.7
CC(C)(C)C	2,2-Dimethylpropane	-16.7
CCCCCCCCCCCCCCCCCCCCCCCCCC	n-Hexacosane	56.7
O=S1(=O)CCCC1	SULFOLANE	27.3
OCCC#C	But-3-yn-1-ol	-63.3
CN(C)C=O	N,N-DIMETHYLFORMAMIDE	-60.7
CCCCCCCCCCC(O)=O	UNDECANOIC ACID	28.3
ClC(Cl)Cl	Chloroform	-63.3
OC1CCCCCCCCC1	Cyclodecanol	40.2
CN1C(=O)N(C)C(=O)N(C)C1=O	1,3,5-Trimethyl-1,3,5-triazinane-2,4,6-trione	176.0
CC1=CC=NC=C1	4-Picoline	3.33
IC#N	cyanic iodide	146.0
ClC1=CC=CC=C1Br	1-bromo-2-chlorobenzene	-12.7
BrC1=CC2=CC=CC=C2N=C1	3-Bromoquinoline	13.7
CCOC1=CC=CC=C1C(O)=O	2-Ethoxybenzoic acid	20.4
BrCCCOC1=CC=CC=C1	1-Bromo-3-phenoxypropane	10.3
CCC(C1=CC=CC=C1)C1=CC=CC=C1	1,1-DIPHENYLPROPANE	13.7
CCl	Chloromethane	-97.3
C1CO1	Oxirane	-111.0
FC(F)(F)C(F)(F)F	HEXAFLUOROETHANE	-100.0
CC(C)(C)C1=CC=C(O)C(O)=C1	4-tert-Butylcatechol	54.6
OC1=C(C=O)C=C(Cl)C=C1	5-Chlorosalicylaldehyde	101.0
CC1=CC(Br)=CC=C1O	4-Bromo-2-methylphenol	64.3
CC(C)OC(=O)NC1=CC=CC=C1	Isopropyl N-phenylcarbamate	87.7
C1CCCCCCCCCCCCCC1	Cyclopentadecane	61.6
FC1=CC(F)=C(F)C(F)=C1F	1,2,3,4,5-Pentafluorobenzene	-47.6
C=CC=O	Acrylaldehyde	-87.3
BrC1=CC=C(OC2=CC=CC=C2)C=C1	4-Bromodiphenyl ether	18.4
CCN1C=CC(NS(=O)(=O)C2=CC=C(N)C=C2)=NC1=O	Sulfacytine	167.0
OC(C1=CC=CC=C1)C1=CC=C(Cl)C=C1	4-Chlorobenzhydrol	60.4
OC(=O)COC1=CC=C(F)C=C1	4-FLUOROPHENOXYACETIC ACID	105.0
ClC1=CC=C(C=C1)C(C1=CC=CC=C1Cl)C(Cl)(Cl)Cl	2,4'-DDT	74.6
O=C=NC1=CC=C(CC2=CC=C(C=C2)N=C=O)C=C1	1,1'-Methylenebis(4-isocyanatobenzene)	37.6
CCCCC(CC)COC(=O)CCCCC(=O)OCC(CC)CCCC	BIS(2-ETHYLHEXYL) ADIPATE	-67.4
CC(C)OC(C)C	diisopropyl_ether	-86.4
C1OCOCO1	1,3,5-TRIOXANE	60.6
CCCC(O)CCC	4-heptanol	-41.6
CC1=CC=C(C)O1	2,5-DIMETHYLFURAN	-62.4
COC1=CC=CC(O)=C1O	3-METHOXYCATECHOL	42.4
COC(=O)C(O)(C1=CC=CC=C1)C1=CC=CC=C1	Methyl benzilate	75.4
COC1=CC=C(C=O)C2=C1C=CC=C2	4-Methoxy-1-naphthaldehyde	34.4
CC#CC#CC	2,4-HEXADIYNE	67.4
CCOC=C	Ethoxyethene	-115.0
OC1=CC=CC=N1	2-hydroxypyridine	107.0
CCCCCCI	1-IODOHEXANE	-74.6
CC(Cl)=O	ACETYL CHLORIDE	-112.0
CCN(CC)C1=CC=CC=C1	n,n-diethylaniline	-38.4
ClC1=CC=C(C=C1)C1=CC=CC=C1	PCB-3	78.4
CC(O)C(C)(C)C	3,3-dimethyl-2-butanol	5.2
BrC1=CC=CC2=C1C=CC=C2	1-BROMONAPHTHALENE	-1.4
C[C@H]1CC[C@@H](O)CC1	cis-4-Methylcyclohexanol	-9.6
OC(=O)C1=CC(=C(Cl)C=C1)[N+]([O-])=O	4-CHLORO-3-NITROBENZOIC ACID	182.0
C=CCC=C	Penta-1,4-diene	-148.0
C[C@@H]1CC(=O)C=C2CC[C@H](C[C@@]12C)C(C)=C	(4r,4as,6r)-4,4a-dimethyl-6-(prop-1-en-2-yl)-4,4a,5,6,7,8-hexahydronaphthalen-2(3h)-one	36.4
O=C1CCCC1	CYCLOPENTANONE	-51.5
CCCCCCCCCCCCCCCCCC(=O)OC	METHYL STEARATE	39.5
C1C2C=CC1C=C2	2,5-Norbornadiene	-19.6
NCCCCCCCN	1,7-Diaminoheptane	28.4
CCOC(=O)CC	ethyl_propionate	-73.5
CCCCCCOC(C)=O	hexyl_acetate	-80.5
CC(C)C=O	2-Methylpropanal	-65.5
CC(C)C1=CC=C(C)C=C1	1-Isopropyl-4-methylbenzene	-68.5
OC1=CC=C(C=C1)C1CC(=O)C2=C(O)C=C(O)C=C2O1	4',5,7-Trihydroxyflavanone	250.0
O=S=O	Oxosulfane oxide	-72.5
OC(=O)C1=CC=C(O)C=C1O	2,4-dihydroxybenzoic_acid	226.0
CC(N)(CO)CO	2-Amino-2-methylpropane-1,3-diol	110.0
CC1=CC=NC(N)=C1	2-amino-4-methylpyridine	99.5
NC1=CC2=C(C=C1)C1=CC=CC=C1C2	2-Aminofluorene	128.0
COP(=O)(NC(C)=O)SC	Acephate	88.5
NC1=CC=C(C=C1)C(=O)NCC(O)=O	Aminohippurate	199.0
COP(=S)(OC)SCN1N=NC2=CC=CC=C2C1=O	o,o-dimethyl s-[(4-oxo-1,2,3-benzotriazin-3(4h)-yl)methyl] phosphorodithioate	72.5
OC(=O)CCCC1=CC=C(C=C1)N(CCCl)CCCl	4-{4-[bis(2-chloroethyl)amino]phenyl}butanoic acid	64.5
COC1=CC2=C(C=CC(=O)O2)C(OC)=C1	5,7-Dimethoxycoumarin	148.0
CC(=O)N(O)CCCCCNC(=O)CCC(=O)N(O)CCCCCNC(=O)CCC(=O)N(O)CCCCCN	Deferoxamine	140.0
CC(C(O)=O)C1=CC=C(C=C1)N1CC2=CC=CC=C2C1=O	(+/+)-indoprofen	213.0
CC1=C(C=NO1)C(=O)NC1=CC=C(C=C1)C(F)(F)F	leflunomide	166.0
COP(N)(=O)SC	O,S-Dimethyl phosphoramidothioate	45.5
OC(=O)C1=C(NC2=CC=CC(=C2)C(F)(F)F)N=CC=C1	Niflumic acid	204.0
CN1CCN(CCCN2C3=CC=CC=C3SC3=CC=CC=C23)CC1	Perazine	52.5
OC(CCN1CCCCC1)(C1CCCCC1)C1=CC=CC=C1	Trihexylphenedyl	114.0
C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO	Dexamethasone	262.0
OC(=O)C1=C(Cl)C=C(Cl)C=C1Cl	2,4,6-Trichlorobenzoic acid	162.0
OC(=O)C1=C(Cl)C(Cl)=CC=C1	2,3-DICHLOROBENZOIC ACID	168.0
CC1=CC=C(C(O)=O)C(O)=C1	4-METHYLSALICYLIC ACID	178.0
CC(=O)NC1=CC=C2C(CC3=CC=CC=C23)=C1	N-(9H-Fluoren-2-yl)acetamide	194.0
CC[C@]1(O)C[C@H]2C[N@@](C1)CCC1=C(NC3=C1C=CC=C3)[C@@](C2)(C(=O)OC)C1=CC2=C(C=C1OC)N(C=O)[C@@H]1[C@]22CCN3CC=C[C@](CC)([C@@H]23)[C@@H](OC(C)=O)[C@]1(O)C(=O)OC	(2'beta)-22-oxovincaleukoblastine	219.0
O=CC1=CC2=CC=CC=C2C=C1	2-Naphthaldehyde	61.5
C[Si](C)(C)C	TETRAMETHYLSILANE	-99.5
CC1(C)C2CCC1(C)C(=O)C2Br	[1(R)-ENDO]-(+)-3-BROMOCAMPHER	76.5
CCC(C)(O)C#CC(C)(O)CC	3,6-Dimethyl-4-octyn-3,6-diol	53.5
O=C1OC(=O)C2=CC=CC3=C2C1=CC=C3	1,8-Naphthalic Anhydride	270.0
O=C1OCC2=CC=CC=C12	PHTHALIDE	74.5
CC1=C(N)C=CC=C1Cl	3-Chloro-2-methylaniline	1.5
OC(=O)C1=CSC=C1	thiophene-3-carboxylic acid	138.0
N(C1=CC=CC=C1)C1=C2C=CC=CC2=CC=C1	N-phenylnaphthalen-1-amine	61.5
O=C1C2=CC=CC=C2OC2=CC=CC=C12	9H-XANTHEN-9-ONE	176.0
O=C(C1=CC=CC=C1)C1=CC=CC=N1	2-Benzoylpyridine	42.5
CC(=O)OC(OC(C)=O)C1=CC=C(O1)[N+]([O-])=O	5-Nitro-2-furaldehyde diacetate	90.5
COC1=CC=C(CC(O)=O)C=C1OC	(3,4-DIMETHOXYPHENYL)ACETIC ACID	97.5
CCCOC(=O)C1=CC=C(N)C=C1	n-propyl 4-aminobenzoate	74.5
COC1=CC(=CC=C1N)[N+]([O-])=O	2-METHOXY-4-NITROANILINE	140.0
ClS(=O)(=O)C1=CC=C(Br)C=C1	4-Bromobenzenesulfonyl chloride	75.5
ClC1=CC=C(C=C1)S(Cl)(=O)=O	4-Chlorobenzenesulfonyl chloride	51.5
CN(C)C1=CC=C(C=C1)[N+]([O-])=O	N,N-Dimethyl-4-nitroaniline	164.0
ClN=C1C=C(Cl)C(=O)C(Cl)=C1	2,6-dichloro-4-(chloroimino)cyclohexa-2,5-dien-1-one	66.5
N=C(NC1=CC=CC=C1)NC1=CC=CC=C1	1,3-Diphenylguanidine	150.0
ClC1=C(Cl)C=C(C=C1)N=C=O	3,4-DICHLOROPHENYL ISOCYANATE	42.5
CC1=NNC(=O)C1	3-Methyl-2-pyrazolin-5-one	222.0
CC1=CN=CC=N1	2-Methylpyrazine	-29.5
CCCCCCCCCCCCCCCC(=O)OC	METHYL PALMITATE	30.5
OCCCCCCCCCC=C	10-Undecen-1-ol	-2.5
CCCCCCCCCCCCS	1-DODECANETHIOL	-7.5
CCCCCCCCCCCCCCCC(Cl)=O	Palmitoyl chloride	11.5
CCCCCCCCCCCCCCCCBr	1-BROMOHEXADECANE	17.5
OCC(Cl)(Cl)Cl	2,2,2-TRICHLOROETHANOL	18.5
OC(C1=CC=C(Cl)C=C1)(C1=CC=C(Cl)C=C1)C(Cl)(Cl)Cl	2,2,2-Trichloro-1,1-bis(4-chlorophenyl)ethanol	78.0
OC1=CC=CC=C1C(=O)C1=CC=CC=C1	2-Hydroxybenzophenone	39.5
COC1=CC(=CC=C1N)C1=CC=C(N)C(OC)=C1	o-Dianisidine	136.0
COC1=CC(C=O)=CC(OC)=C1O	syringaldehyde	112.0
NC1=CC=C(OC2=CC=CC=C2)C=C1	4-Phenoxyaniline	83.5
C1=CC2=CC3=C(C=C2C=C1)C1=C2C3=CC=CC2=CC=C1	Benzo[k]fluoranthene	216.0
C1=CC=C2N=CN=CC2=C1	Quinazoline	47.5
C1=CC2=CC3=CC=CC=C3N=C2C=C1	acridine	108.0
N1C=CC2=C1N=CC=C2	7-Azaindole	106.0
O1C=NC2=CC=CC=C12	benzoxazole	30.5
C1CN2CCN1CC2	1,4-Diazabicyclo[2.2.2]octane	158.0
OC(=O)CC#N	CYANOACETIC ACID	66.5
OC(=O)C1=C(F)C=CC=C1F	2,6-DIFLUOROBENZOIC ACID	158.0
FC1=CC=CC=C1C(Cl)=O	2-FLUOROBENZOYL CHLORIDE	4.5
OC(=O)C1=CC(F)=CC=C1	3-FLUOROBENZOIC ACID	124.0
N1C(=NC(=C1C1=CC=CC=C1)C1=CC=CC=C1)C1=CC=CC=C1	2,4,5-Triphenylimidazole	276.0
COC1=CC(OC)=C(C=C1OC)C(O)=O	2,4,5-Trimethoxybenzoic acid	144.0
[O-]\[N+](=N/C1=CC=CC=C1)C1=CC=CC=C1	Azoxybenzene	35.5
C1CC2CC1C=C2	Norbornene	45.5
OCCC1=CC=C(O)C=C1	2-(4-Hydroxyphenyl)ethanol	90.5
OCCCCCCCCCCCCCCCC(O)=O	16-Hydroxyhexadecanoic acid	98.5
CCOC(=O)C(O)(C1=CC=C(Cl)C=C1)C1=CC=C(Cl)C=C1	Ethyl bis(4-chlorophenyl)(hydroxy)acetate	36.5
OCCC1=CNC2=CC=CC=C12	Tryptophol	58.5
CC1=CC(C)=C(O)C(C)=C1	2,4,6-Trimethylphenol	72.5
OC(=O)C1=CC(=C(C=C1)[N+]([O-])=O)[N+]([O-])=O	3,4-DINITROBENZOIC ACID	166.0
O=C1CCCC2=CC=CC=C12	1-TETRALONE	7.5
NC(=O)NCC1=CC=CC=C1	benzylurea	148.0
CCCCCCCCC(=O)CCCCCCCC	9-HEPTADECANONE	52.5
CC(C)CC(N)=O	ISOVALERAMIDE	136.0
CC1=CC=CC(=C1N)[N+]([O-])=O	2-METHYL-6-NITROANILINE	95.5
OCC1=CC=NC=C1	4-Pyridinemethanol	53.5
COC(N)=O	METHYL CARBAMATE	54.5
OC(=O)C(Cl)=C	2-Chloroacrylic acid	65.5
CCC(C(O)=O)C(O)=O	ETHYLMALONIC ACID	114.0
OC1=CC=CC(O)=C1[N+]([O-])=O	2-Nitroresorcinol	82.5
OC(=O)C1=C(F)C(F)=C(F)C(F)=C1F	Pentafluorobenzoic acid	102.0
CC1=CC=CC(C(O)=O)=C1C	2,3-Dimethylbenzoic acid	146.0
[O-][N+](=O)C1=CC2=C(C=CC=C2)C(=C1)[N+]([O-])=O	1,3-DINITRONAPHTHALENE	148.0
CN1C(=O)C=CC2=C1C=CC=C2	1-methyl-2-quinolinone	74.5
[O-][N+](=O)C1=CC=C2C(CC3=CC=CC=C23)=C1	2-NITRO-9H-FLUORENE	156.0
[O-][N+](=O)C1=CC=CO1	2-NITROFURAN	30.5
OC(=O)C1=C(C=C(C=C1)[N+]([O-])=O)[N+]([O-])=O	2,4-DINITROBENZOIC ACID	182.0
OC(=O)C(=O)C1=CC=CC=C1	Phenylglyoxylic acid	65.5
CC1=CC=C(C=C1)C1=CC=C(C)C=C1	4,4'-DIMETHYLBIPHENYL	120.0
N#CC1=CC2=CC=CC=C2C=C1	NAPHTHALENE-2-CARBONITRILE	65.5
O=C1CCCN1	2-Pyrrolidinone	23.5
CC1=CC=C(C=C1C)C(O)=O	3,4-Dimethylbenzoic acid	166.0
[O-][S+](CC1=CC=CC=C1)CC1=CC=CC=C1	Dibenzyl sulfoxide	134.0
CCOC1=CC=CC(=C1)C(O)=O	3-Ethoxybenzoic acid	136.0
NC(=O)OCC1=CC=CC=C1	BENZYL CARBAMATE	87.5
CCCOC1=CC=CC=C1	phenyl_propyl_ether	-27.5
CC(CC(O)=O)CC(O)=O	3-Methylglutaric acid	86.5
CC(CCC(O)=O)CC(O)=O	3-METHYLADIPIC ACID	100.0
CCCCCCC#N	HEPTANENITRILE	-63.5
CCCCCCCCCCCCCCCCCCCCCCCCC	n-Pentacosane	53.5
C1=CC=C(C=C1)C(C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	Tetraphenylmethane	282.0
CCOC(=O)C1=CC=C(C=C1)C(=O)OCC	DIETHYL TEREPHTHALATE	44.5
CCC1CCC2C3CCC4CCCCC4(C)C3CCC12C	PREGNANE, (5.BETA.)-	84.0
N#CC(C#N)=C(C#N)C#N	TETRACYANOETHYLENE	198.0
CP(Cl)(Cl)=O	METHYLPHOSPHONIC DICHLORIDE	35.5
CC1=NC=CN1	2-Methylimidazole	144.0
O=C1CC2=CC=CC=C2C(=O)O1	HOMOPHTHALIC ANHYDRIDE	142.0
CC(C)(C)C1=CC(=O)C=C(C1=O)C(C)(C)C	2,6-Di-tert-butyl-P-benzoquinone	66.5
O1C(=NN=C1C1=CC=CC=C1)C1=CC=CC=C1	2,5-Diphenyl-1,3,4-oxadiazole	140.0
CC(C)=CC=C(C)C	2,5-dimethyl-2,4-hexadiene	12.5
CC1=CC(C)=NC(N)=N1	2-AMINO-4,6-DIMETHYLPYRIMIDINE	152.0
CC1=CC(C)=C(C(C)=C1)S(Cl)(=O)=O	mesitylene-2-sulfonyl chloride	55.5
CC(Cl)C(Cl)(Cl)Cl	1,1,1,2-TETRACHLOROPROPANE	-64.5
C=CC1=CC=C2C=CC=CC2=C1	2-VINYLNAPHTHALENE	65.5
NNC1=C(F)C(F)=C(F)C(F)=C1F	Pentafluorophenylhydrazine	75.5
O=C1CCCCCCCCCCC1	CYCLODODECANONE	60.5
CC1=CC=C(C=C1)C(Cl)=O	p-TOLUOYL CHLORIDE	-2.5
S1C2=C(C=CC=C2)N=C1C1=CC=CC=C1	2-Phenylbenzothiazole	114.0
OC1=NC2=CC=CC=C2S1	2-HYDROXYBENZOTHIAZOLE	138.0
[O-][N+](=O)C1=C(Cl)C=CC(=C1)C#N	4-chloro-3-nitrobenzonitrile	99.5
[O-][N+](=O)C1=CC=C(NC2=CC=CC=C2)C(=C1)[N+]([O-])=O	2,4-Dinitro-N-phenylaniline	160.0
COC1=CC=C2C(=O)CCCC2=C1	6-Methoxy-1-tetralone	78.5
CC(=O)C1=CC=NC=C1	4-acetylpyridine	15.5
CC1=CC=NC(=C1)C1=CC(C)=CC=N1	4,4'-Dimethyl-2,2'-bipyridine	174.0
BrC1=C(Br)C(Br)=C(OC2=C(Br)C(Br)=C(Br)C(Br)=C2Br)C(Br)=C1Br	Bis(pentabromophenyl) ether	306.0
NS(=O)(=O)C1=C(Cl)C=CC(=C1)C(O)=O	4-Chloro-3-sulfamoylbenzoic acid	258.0
ClC1=CC(Br)=C(Cl)C=C1	2-BROMO-1,4-DICHLOROBENZENE	34.5
NC(=O)C1=CC=NC=C1	Isonicotinamide	156.0
FC1=CC=C(C=C1)N=C=S	4-Fluorophenyl isothiocyanate	26.5
COC(=O)C1=CC=C(C=C1)C(O)=O	mono-methyl_terephthalate	222.0
OP(=O)(C1=CC=CC=C1)C1=CC=CC=C1	Diphenylphosphinic acid	194.0
NC(N)=NC(=O)C1=C(N)N=C(N)C(Cl)=N1	Amiloride	240.0
COC1=CC=CC(OC)=C1C(C)=O	2',6'-Dimethoxyacetophenone	69.5
OC(=O)CCCCBr	5-Bromovaleric acid	39.5
ClC1=CC=C(C=C1)N=C=S	4-Chlorophenyl isothiocyanate	45.5
ClC1=C(Cl)N=CC=C1	2,3-Dichloropyridine	66.5
OC(=O)CC1=CC=CC=C1Cl	2-chlorophenylacetic_acid	95.5
ClC1=CC(Cl)=CN=C1	3,5-Dichloropyridine	65.5
CC(=O)N1C=CN=C1	1-Acetylimidazole	102.0
OC(=O)C1=C(C=CC(Cl)=C1)[N+]([O-])=O	5-CHLORO-2-NITROBENZOIC ACID	138.0
CCOC(=O)C1=CC=CC=N1	Ethyl picolinate	1.5
OC1=C(Br)C=C(C=O)C=C1Br	3,5-DIBROMO-4-HYDROXYBENZALDEHYDE	182.0
OC1=C(C=C(C=O)C=C1)[N+]([O-])=O	4-Hydroxy-3-nitrobenzaldehyde	142.0
N#CSCC1=CC=CC=C1	Benzyl thiocyanate	42.5
CS(=O)(=O)C1=CC=CC=C1	METHYL PHENYL SULFONE	86.5
NNC(=O)C1=CC=CO1	2-Furoic acid hydrazide	79.5
BrCCCCCCCCCCCCBr	1,12-Dibromododecane	40.5
CCNC1=CC=C(C=C1)[N+]([O-])=O	N-Ethyl-4-nitroaniline	96.5
S=C=NC1=CC=C(C=C1)N=C=S	1,4-Phenylene diisothiocyanate	132.0
CCC1=CC(=C(O)C(=C1)C(C)(C)C)C(C)(C)C	2,6-Di-tert-butyl-4-ethylphenol	43.5
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	n-Tetracontane	81.5
OC(=O)CCCCCBr	6-BROMOHEXANOIC ACID	34.5
OC(=O)C1=CC=C(S1)C(O)=O	THIOPHENE-2,5-DICARBOXYLIC ACID	358.0
O=CN1CCOCC1	4-Formylmorpholine	21.5
CC1=CC=C(CC2=CC=C(C)C=C2)C=C1	4,4'-Dimethyldiphenylmethane	28.5
CC1=C(C(=CC=C1)C(O)=O)[N+]([O-])=O	3-METHYL-2-NITROBENZOIC ACID	222.0
BrCCCN1C(=O)C2=CC=CC=C2C1=O	N-(3-BROMOPROPYL)PHTHALIMIDE	74.5
CCCCCCCC1CCCCC1	HEPTYLCYCLOHEXANE	-30.5
NC(=O)C1=CC=CS1	thiophene-2-carboxamide	182.0
N#CSCSC#N	Methylene bis(thiocyanate)	106.0
NS(=O)(=O)C1=CC=C(C=C1)[N+]([O-])=O	4-Nitrobenzenesulfonamide	180.0
NCC1CCNCC1	4-(Aminomethyl)piperidine	24.5
ClC(=O)C1=CC=CC=C1Br	2-Bromobenzoyl chloride	10.5
NC(=O)C(Br)(Br)C#N	2,2-DIBROMO-2-CYANOACETAMIDE	124.0
CC1(C)C2CCC1(C)C(=O)C2=O	Camphorquinone	200.0
CCCCCCCCCCCCC=O	Tridecanal	14.5
C1COC2=CC=CC=C2OCCOCCOC2=CC=CC=C2OCCO1	DIBENZO-18-CROWN-6	162.0
CCCCCC1=CC=C(O)C=C1	4-n-Pentylphenol	23.5
OCC1=C(Cl)C=CC=C1Cl	2,6-dichlorobenzyl alcohol	97.5
N#CC1=CC2=C(NC=C2)C=C1	INDOLE-5-CARBONITRILE	106.0
CCCCCCCCCCCCCC(=O)OC	Methyl tetradecanoate	18.5
CC1=C(Br)C=C(Br)C=C1Br	2,4,6-Tribromotoluene	69.5
BrC1=CC(CC#N)=CC=C1	m-bromophenylacetonitrile	27.5
OC(=O)C1=CC=CC=C1C1=CC=C(C=C1)C(F)(F)F	4'-(trifluoromethyl)biphenyl-2-carboxylic acid	170.0
OC(=O)CSC1=CC=CC=C1	(Phenylthio)acetic acid	64.5
CC(S)C(O)=O	2-Mercaptopropionic acid	11.5
C1CNCCNCCCNCCNC1	1,4,8,11-Tetraazacyclotetradecane	186.0
O=C1C(=C1C1=CC=CC=C1)C1=CC=CC=C1	2,3-Diphenyl-2-cyclopropen-1-one	120.0
NNS(=O)(=O)C1=CC=CC=C1	Benzenesulfonyl hydrazide	102.0
ClC(=O)N(C1=CC=CC=C1)C1=CC=CC=C1	Diphenylcarbamyl chloride	83.5
[O-][N+](=O)C1=CC=C(C=C1)N=C=O	4-Nitrophenyl isocyanate	57.5
CN1CCC(O)CC1	4-Hydroxy-1-methylpiperidine	28.5
ClC1=CC=CC(=C1)C(=O)C1=CC=CC=C1	m-Chlorobenzophenone	82.5
CC1=CC(Br)=C(C)C=C1Br	2,5-Dibromo-p-xylene	73.5
BrCC1=CC=CC=C1CBr	o-Xylylene dibromide	94.5
C(N(CC1=CC=CC=C1)C1=CC=CC=C1)C1=CC=CC=C1	N,N-Dibenzylaniline	69.5
COC1=CC=C(Cl)C=C1N	5-Chloro-o-anisidine	82.5
NS(=O)(=O)C1=CC=C(Cl)C=C1	4-Chlorobenzenesulfonamide	146.0
OC(=O)CSCC1=CC=CC=C1	(Benzylthio)acetic acid	61.5
CCOC=C(C#N)C#N	Ethoxymethylenemalononitrile	65.5
CC(C)=NO	Acetone oxime	61.5
[O-][N+](=O)C1=CC(=C(F)C=C1F)[N+]([O-])=O	1,5-Difluoro-2,4-dinitrobenzene	73.5
OC(=O)C1=CC=C(OC(F)(F)F)C=C1	4-(Trifluoromethoxy)benzoic acid	152.0
OC(=O)CC1=CC(=CC=C1)C(F)(F)F	3-(Trifluoromethyl)phenylacetic acid	77.5
FC1=CC=C(C=C1)C(Cl)=O	4-Fluorobenzoyl chloride	9.5
CC1=CC=C(F)C=C1[N+]([O-])=O	4-Fluoro-2-nitrotoluene	26.5
CC1=C(C)C(C)=C(CCl)C(C)=C1C	2,3,4,5,6-Pentamethylbenzyl chloride	82.5
S1C=CC=C1C1=CC=CS1	2,2'-Bithiophene	32.5
NC1=CC=CC=C1C=O	2-Aminobenzaldehyde	38.5
O=C(N1C=CN=C1)N1C=CN=C1	1,1'-Carbonyldiimidazole	118.0
N(C1=CC=CC=C1)C1=CC=C(C=C1)C1=CC=C(NC2=CC=CC=C2)C=C1	N,N'-Diphenylbenzidine	248.0
NC1=CC2=C(C=C1)N=CS2	6-Aminobenzothiazole	87.5
BrCC1=CC=C(Br)C=C1	4-Bromobenzyl bromide	62.5
CC#CC(O)=O	2-Butynoic acid	77.5
CC1=CC(=CC=C1O)C1(OC(=O)C2=CC=CC=C12)C1=CC=C(O)C(C)=C1	o-Cresolphthalein	224.0
CCCCS(=O)(=O)CCCC	di-n-butyl sulfone	44.5
CC1=CC(O)=C2C=CC=CC2=N1	4-hydroxy-2-methylquinoline	234.0
OC(=O)C1=C(C=C(C=C1)[N+]([O-])=O)C(O)=O	4-Nitrophthalic acid	162.0
C(C1=CC=CC=C1)C1=CC=C(C=C1)C1=CC=CC=C1	4-BENZYLBIPHENYL	85.5
NC(=O)C1=CC(Cl)=CC=C1	3-Chlorobenzamide	136.0
CC1=CC=C(C=C1)C(=O)CBr	2-Bromo-4'-methylacetophenone	51.5
O=S(=O)(CC1=CC=CC=C1)CC1=CC=CC=C1	Dibenzyl sulfone	152.0
C(OC1=CC=C(OCC2=CC=CC=C2)C=C1)C1=CC=CC=C1	1,4-Dibenzyloxybenzene	128.0
NC(=O)OC1=CC=CC=C1	phenyl carbamate	150.0
CC(=O)OCCCCOC(C)=O	1,4-Diacetoxybutane	12.5
C1=CC=C(C=C1)C(=C(C1=CC=CC=C1)C1=CC=CC=C1)C1=CC=CC=C1	Tetraphenylethylene	224.0
OC(=O)C#CC1=CC=CC=C1	Phenylpropynoic acid	136.0
NC(=O)C1=C(F)C(F)=C(F)C(F)=C1F	2,3,4,5,6-Pentafluorobenzamide	148.0
O=C(C1=CC=CS1)C1=CC=CS1	Di-2-thienyl ketone	89.5
CC(=O)C1=CC=C(C=C1)C(F)(F)F	4'-(Trifluoromethyl)acetophenone	31.5
FC(F)(F)C1=CC=CC=C1C(=O)C1=CC=CC=C1	2-(Trifluoromethyl)benzophenone	60.5
COC1=CC(O)=CC=C1O	2-Methoxyhydroquinone	89.5
COC1=CC=C(C(C)=O)C(OC)=C1	2,4-Dimethoxyacetophenone	40.5
CN1C=CC(=O)N(C)C1=O	1,3-Dimethyluracil	120.0
COC1=CC=CC(C(O)=O)=C1O	2-Hydroxy-3-methoxybenzoic acid	152.0
CC1=CC=CC2=C1NC=C2	7-METHYLINDOLE	84.5
CC1=CC=C(OCC(O)=O)C=C1	4-Methylphenoxyacetic acid	140.0
CCOC(=O)C1=CC=C(O1)[N+]([O-])=O	Ethyl 5-nitro-2-furoate	100.0
C(OC1=CC=CC=C1)C1=CC=CC=C1	Benzyl phenyl ether	39.5
C1=CC=C(C=C1)C1=NN=C(N=C1C1=CC=CC=C1)C1=CC=CC=N1	5,6-diphenyl-3-(pyridin-2-yl)-1,2,4-triazine	192.0
NC1=CC=CC2=C1C=CN=C2	5-Aminoisoquinoline	128.0
[O-][N+](=O)C1=CC=C(C=C1)C(=O)C1=CC=CC=C1	4-Nitrobenzophenone	138.0
C1=CC=C(N=C1)C1=CC=CC(=N1)C1=CC=CC=N1	2,2':6',2''-TERPYRIDINE	90.5
OC1=CC=C(O)C(C=O)=C1	2,5-Dihydroxybenzaldehyde	98.5
BrCCCCOC1=CC=CC=C1	(4-Bromobutoxy)benzene	41.5
COC1=CC=C(OC)C(=C1)C(C)=O	2,5-Dimethoxyacetophenone	19.5
CCOC1=CC=C(C=C1)C(C)(C)COCC1=CC(OC2=CC=CC=C2)=CC=C1	1-{[2-(4-ethoxyphenyl)-2-methylpropoxy]methyl}-3-phenoxybenzene	36.5
OCC1=CC=CC=C1Br	o-Bromobenzyl alcohol	80.5
CC(OC1=CC=CC=C1Cl)C(O)=O	Propanoic acid, 2-(2-chlorophenoxy)-	114.0
OC(=O)CCC(=O)C1=CC=CC=C1	3-Benzoylpropionic acid	118.0
NC(=O)C1=CC=CC=C1C#N	2-Cyanobenzamide	172.0
O=C(NCC1=CC=CC=C1)C1=CC=CC=C1	N-Benzylbenzamide	106.0
OC(=O)C1=C(F)C=C(F)C=C1	2,4-Difluorobenzoic acid	188.0
ClC1=NC=CC=N1	2-Chloropyrimidine	66.5
C1CCC(CC1)NC1=CC=CC=C1	N-Cyclohexylaniline	15.5
NC(=O)C1=CC=C(C=C1)C(F)(F)F	4-(Trifluoromethyl)benzamide	184.0
FC1=CC=CC(F)=C1C#N	2,6-Difluorobenzonitrile	30.5
COC1=CC(=CC(O)=C1OC)C(O)=O	5-hydroxy-3,4-dimethoxybenzoic acid	196.0
CCCCCC(=O)OC(=O)CCCCC	Hexanoic anhydride	-40.5
O=C(C1=CC=CC=C1)C1=CC=C(C=C1)C1=CC=CC=C1	4-Benzoylbiphenyl	100.0
ClC(=O)C1=CC2=CC=CC=C2C=C1	2-Naphthoyl chloride	50.5
COC1=CC=C(C=C1)N=C=S	4-Methoxyphenyl isothiocyanate	18.5
OC(=O)C(CC=C)C(O)=O	Allylmalonic acid	104.0
OCC1=CC=CC=C1C1=CC=CC=C1	2-Biphenylmethanol	49.5
OCC1=CC=C(C=C1)C(O)=O	4-(Hydroxymethyl)benzoic acid	182.0
ClC1=CC(I)=CC(Cl)=C1	1,3-Dichloro-5-iodobenzene	56.5
IC1=CC=C(C=C1)C#N	4-Iodobenzonitrile	126.0
O=CC1=CC=C(C=C1)C1=CC=CC=C1	Biphenyl-4-carboxaldehyde	59.5
[O-][N+](=O)C1=CC=CC(=C1)N=C=O	3-Nitrophenyl isocyanate	51.5
SC(C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	Triphenylmethyl mercaptan	106.0
NC1=NC=C(C=C1)[N+]([O-])=O	2-Amino-5-nitropyridine	188.0
O=CC1=CC=NC2=CC=CC=C12	Quinoline-4-carboxaldehyde	50.5
COC1=CC(=CC=C1O)C#N	4-Hydroxy-3-methoxybenzonitrile	86.5
N#CC1=CC2=C(OCO2)C=C1	Piperonylonitrile	93.5
CC(CO)(CO)C(O)=O	2,2-Bis(hydroxymethyl)propionic acid	190.0
COC1=C(C=O)C2=C(C=CC=C2)C=C1	2-Methoxy-1-naphthaldehyde	83.5
C=CS(=O)(=O)C1=CC=CC=C1	Phenyl vinyl sulfone	68.5
CCC(=O)C1=CC=C(O)C=C1O	2',4'-Dihydroxypropiophenone	99.5
NNC(=O)C1=CC=CC=C1Cl	2-Chlorobenzhydrazide	118.0
NC1=C(C=C(Cl)C=C1)C#N	2-amino-5-chlorobenzonitrile	96.5
CCOC(=O)C(C(=O)OCC)C(=O)OCC	Triethyl methanetricarboxylate	28.5
OC(=O)CC1=C(Cl)C=CC=C1Cl	2,6-Dichlorophenylacetic acid	160.0
C(CP(C1=CC=CC=C1)C1=CC=CC=C1)CP(C1=CC=CC=C1)C1=CC=CC=C1	1,3-Bis(diphenylphosphino)propane	60.5
NCCCN1CCN(CCCN)CC1	1,4-Bis(3-aminopropyl)piperazine	14.5
[O-][N+](=O)C1=CC=C(OC(Cl)=O)C=C1	4-Nitrophenyl carbonochloridate	78.5
CC1=CC=C(N)C=C1Br	3-Bromo-4-methylaniline	26.5
BrC1=CC=CC=C1C1=CC=CC=C1Br	2,2'-Dibromobiphenyl	80.5
CC(=O)OC1=CC=C(C=C1)C(C)=O	4'-Acetoxyacetophenone	53.5
C1COCCOC2=CC=CC=C2OCCOCCO1	Benzo-15-crown-5	79.5
ClC1=CC2=C(C=CN2)C=C1	6-CHLOROINDOLE	89.5
COC1=CC=C(Br)C(OC)=C1	1-Bromo-2,4-dimethoxybenzene	25.5
CC1=CCC(CC1O)C(C)(C)O	trans-p-Menth-6-ene-2,8-diol	130.0
CCCCCCCCCCC1=CC=C(N)C=C1	4-n-Decylaniline	24.5
COC1=CC(Cl)=CC=C1C(O)=O	4-chloro-2-methoxybenzoic_acid	146.0
CCCCCCC(O)C(O)=O	2-Hydroxyoctanoic acid	69.5
O=C1CCCCC1C1=CC=CC=C1	2-Phenylcyclohexanone	57.5
IC1=CC=C(C=O)C=C1	4-iodobenzaldehyde	77.5
CC1=C(C=C(C=C1[N+]([O-])=O)[N+]([O-])=O)C(O)=O	2-Methyl-3,5-dinitrobenzoic acid	206.0
OC(=O)C1=CC(F)=CC(F)=C1	3,5-Difluorobenzoic Acid	122.0
OC(=O)[C@@H]1CCCN1C(=O)OCC1=CC=CC=C1	N-benzyloxycarbonyl-L-proline	76.5
CC(=O)OCC(C(OC(C)=O)C1=CC=CC=C1)[N+]([O-])=O	1,3-Propanediol, 2-nitro-1-phenyl-, diacetate (e	70.5
OCC1CCCNC1	3-Piperidinemethanol	60.5
CC(C)CCC#C	5-Methyl-1-hexyne	-124.0
CCCC1=CC=C(C=C1)C(O)=O	4-n-Propylbenzoic acid	142.0
OC(C=O)C(O)C(O)C(O)C(O)=O	D-Galacturonic acid	166.0
CCOC1=CC=C(I)C=C1	4-Iodophenetole	28.5
ClC1=CC=C(CC#N)C=C1	4-chlorobenzyl_cyanide	30.5
CC1=CC=C(CC(O)=O)C=C1	p-Tolylacetic Acid	92.5
CN1[C@H]2CC[C@@H]1CC(=O)C2	Tropinone	42.5
CC(C)CCCC(C)C1CCC2C3CC(O)C4(O)CC(O)CCC4(C)C3CCC12C	17-(1,5-dimethylhexyl)-10,13-dimethylperhydrocyclopenta[a]phenanthrene-3,5,6-triol	238.0
OC(=O)\C=C\C1=CC=C(Cl)C=C1	p-Chlorocinnamic acid	248.0
COC1=CC=C(\C=C\C(O)=O)C=C1	trans-4-Methoxycinnamic acid	174.0
NNC(=S)NC1=CC=CC=C1	4-Phenyl-3-thiosemicarbazide	138.0
OC(=O)\C=C\C1=CC=C(Br)C=C1	4-bromocinnamic_acid	262.0
O=C1CSC(=S)N1	rhodanine	170.0
COC1=CC(CNC(=O)CCCC\C=C\C(C)C)=CC=C1O	(6e)-n-(4-hydroxy-3-methoxybenzyl)-8-methylnon-6-enamide	65.5
O=C1CC(=O)NC(=S)N1	2-thioxodihydropyrimidine-4,6(1H,5H)-dione	234.0
S=C1NCCS1	2-Mercaptothiazoline	106.0
CCNC(=S)NCC	N,N'-DIETHYLTHIOUREA	77.5
CC12CCC3C(CCC4(C)CC5(CCC34C)OCCO5)C1CCC2=O	5,10,13-trimethyltetradecahydrospiro[cyclopenta[a]phenanthrene-3,2'-[1,3]dioxolan]-17(2h)-one	158.0
CC(=O)OC1CCC2(C)C(C1)CC(=O)C1C3CCC(=O)C3(C)CCC21	7,17-dioxoandrostan-3-yl acetate	164.0
OC[C@@H](O)[C@H](O)[C@H](O)[C@@H](O)C=O	D-galactose	166.0
OC1=C(O)C=C(C=C1)[N+]([O-])=O	4-nitrocatechol	176.0
OC(=O)C1=CC(C=C)=CC=C1	3-vinylbenzoic acid	95.5
CC\C=C\CC(O)=O	trans-3-Hexenoic acid	11.5
OC1=CC=CC=C1C1=NC2=C(S1)C=CC=C2	2-(2-Hydroxyphenyl)benzothiazole	132.0
OC[C@H](O)[C@H](O)[C@H](O)CO	D-ribitol	102.0
OC1=CC=C(C=C1)\N=N\C1=CC=CC=C1	4-Phenylazophenol	154.0
CC(=O)NC1=CC=CC=C1C	2'-Methylacetanilide	110.0
[O-][N+](=O)CC(=O)NC1=CC=CC=C1	2-nitro-n-phenylacetamide	93.5
CCCCOC(=O)CCCCCCCCC(=O)OCCCC	Di-n-butyl sebacate	-10.5
CC1=CC=CC(N)=C1C	2,3-Dimethylaniline	2.5
O=C1OC2=CC=CC=C2C=C1	Coumarin	70.5
CC1=CC=CC(C)=C1Cl	2-Chloro-m-xylene	-35.5
ClC1=C(Cl)C=C(Br)C=C1	4-BROMO-1,2-DICHLOROBENZENE	24.5
CC(C)C1=CC=C(C)C(O)=C1	5-Isopropyl-2-methylphenol	1.5
CC(C)C1=CC=C(CO)C=C1	4-Isopropylbenzyl alcohol	27.5
OC(=O)C1=CC=CC=C1N=NC1=CC=C(O)C=C1	2-[(4-hydroxyphenyl)diazenyl]benzoic acid	206.0
ClCC(=O)CCl	1,3-Dichloroacetone	44.5
CN(C)C1=CC=C(C=C1)N(C)C	N,N,N',N'-TETRAMETHYL-P-PHENYLENEDIAMINE	50.5
CNC1=CC=CC=C1C(=O)OC	METHYL N-METHYLANTHRANILATE	18.5
COC1=CC(=CC=C1)C(C)=O	3'-Methoxyacetophenone	-7.5
CC1=CC=C(CCl)C=C1	4-methyl_benzyl_chloride	4.5
COC1=CC(Cl)=CC=C1N	4-Chloro-o-anisidine	51.5
OC1=CC=C(CC2=CC=CC=C2)C=C1	4-Benzylphenol	83.5
COC(=O)C1=CC(OC)=CC(OC)=C1	methyl_3,5-dimethoxybenzoate	42.5
CCOC(=O)CNC1=CC=CC=C1	N-Phenylglycine ethyl ester	57.5
ClC1=CC(Cl)=C(Br)C=C1	1-Bromo-2,4-dichlorobenzene	26.5
NC1=CC(OC2=CC=CC=C2)=CC=C1	3-Phenoxyaniline	36.5
COC1=C(F)C(F)=C(F)C(F)=C1F	2,3,4,5,6-Pentafluoroanisole	-37.5
N#CC1=CC=CN=C1	Nicotinonitrile	50.5
OC1=CC=C(C=O)C=C1	4-hydroxybenzaldehyde	118.0
CC(C)=O	Acetone	-94.5
CCCCCCCCO	1-octanol	-15.5
NCCCNCCCCNCCCN	Spermine	28.5
C1=CC2=C(N=C1)C1=C(C=CC=N1)C=C2	1,10-phenanthroline, anhydrous	118.0
CC(C)NCC(O)COC1=CC=CC=C1CC=C	Alprenolol	108.0
NCC(CC(O)=O)C1=CC=C(Cl)C=C1	Baclofen	208.0
CCOP(=S)(OCC)OC1=NC(Cl)=C(Cl)C=C1Cl	o,o-diethyl o-(3,5,6-trichloropyridin-2-yl) phosphorothioate	42.0
NC(=O)CI	2-Iodoacetamide	94.0
CN1C(=O)OC(C)(C)C1=O	3,5,5-trimethyloxazolidine-2,4-dione	46.5
FC(F)(F)C(=O)CC(=O)C1=CC=CS1	1-(2-Thenoyl)-3,3,3-trifluoroacetone	42.5
C[C@]12CC[C@H]3[C@@H](CCC4=C3C=CC(O)=C4)[C@@H]1C[C@@H](O)[C@@H]2O	Estriol	282.0
OC(=O)C1=CC(Cl)=C(Cl)C=C1	3,4-DICHLOROBENZOIC ACID	208.0
CCOS(=O)(=O)OCC	Diethyl sulfate	-24.5
CS(C)(=O)=O	Dimethyl sulfone	110.0
CC1=CC=C(C=C1)S(N)(=O)=O	p-Toluenesulfonamide	138.0
CC(C)C1=CC(=C(C)C(Br)=C1O)C1(OS(=O)(=O)C2=CC=CC=C12)C1=CC(C(C)C)=C(O)C(Br)=C1C	4,4'-(1,1-Dioxido-3H-2,1-benzoxathiole-3,3-diyl)bis(2-bromo-6-isopropyl-3-methylphenol)	200.0
CNC(C)=O	N-methylacetamide	27.5
C1=CC=C(C=C1)C1=CC=CC=C1C1=CC=CC=C1	O-TERPHENYL	56.5
CCN1C2=C(C=CC=C2)C2=C1C=CC=C2	9-Ethyl-9H-carbazole	68.5
OC(=O)C1=C2C=CC=CC2=CC=C1	1-Naphthoic Acid	162.0
NC1=CC=C(C=C1)C1=CC=CC=C1	biphenyl-4-amine	53.5
OCC(O)C1=CC=CC=C1	1-Phenyl-1,2-ethanediol	67.5
CC(OC1=C(C)C=C(Cl)C=C1)C(O)=O	MCPP	94.5
O=C(NC1=CC=CC=C1)C1=CC=CC=C1	Benzanilide	164.0
[O-][N+](=O)C1=CC2=C(C=C1)N=CN2	6-Nitro-1H-benzimidazole	208.0
CC1=CC(O)=CC=C1O	2-methylbenzene-1,4-diol	128.0
BrCC(Br)CBr	1,2,3-TRIBROMOPROPANE	16.5
ClCC(Cl)CCl	1,2,3-trichloropropane	-14.5
CC1CCCC1	Methylcyclopentane	-142.0
CC(C)COC(=O)C(C)C	Isobutyl isobutyrate	-80.5
OC(=O)C1=CC(O)=CC=C1	3-hydroxybenzoic_acid	202.0
OC(=O)C1=CC(=CC(=C1)[N+]([O-])=O)[N+]([O-])=O	3,5-DINITROBENZOIC ACID	206.0
COC1=CC=C(C=C1N)[N+]([O-])=O	2-METHOXY-5-NITROANILINE	118.0
[O-][N+](=O)C1=CC(C=O)=CC=C1	m-Nitrobenzaldehyde	58.5
CCOC(=O)C1=CC=C(C=C1)[N+]([O-])=O	ethyl_4-nitrobenzoate	57.5
CNC1=CC=C(C=C1)[N+]([O-])=O	N-methyl-4-nitroaniline	152.0
[O-][N+](=O)C1=CC=C(C=C1)[N+]([O-])=O	P-DINITROBENZENE	174.0
CCN1CCOCC1	4-ETHYLMORPHOLINE	-63.5
C=CCOC1=NC(OCC=C)=NC(OCC=C)=N1	2,4,6-Tris(allyloxy)-1,3,5-triazine	26.5
CC(=O)CC(=O)NC1=CC=CC=C1	3-Oxo-N-phenylbutanamide	85.5
O=CNC1=CC=CC=C1	N-PHENYLFORMAMIDE	46.5
CC(=O)NC1=CC=C(C=C1)[N+]([O-])=O	N-(4-Nitrophenyl)acetamide	216.0
O=C1CCCCCN1	azepan-2-one	69.5
O=C1CCC(=O)O1	dihydrofuran-2,5-dione	120.0
CC1=CC(C)=CC=C1	m-xylene	-47.5
CCCCCCS	1-HEXANETHIOL	-80.5
CCCSCCC	Di-n-propyl sulfide	-102.0
CCCCCCCCCCBr	1-BROMODECANE	-29.5
CCCCCCCCCC=O	Decanal	-5.5
CCCCCCCCCCCCCCO	1-Tetradecanol	39.5
OC1=CC=CC=C1C(=O)OC1=CC=CC=C1	phenyl salicylate	42.5
C1=CC2=CC=CC=CC2=C1	Azulene	99.5
C1=CN=CN=C1	pyrimidine	21.5
[O-][N+](=O)C1=CC(=CC(=C1Cl)[N+]([O-])=O)C(F)(F)F	2-Chloro-1,3-dinitro-5-(trifluoromethyl)benzene	56.5
[O-][N+](=O)C1=CC=C(C=C1)C(F)(F)F	1-Nitro-4-(trifluoromethyl)benzene	39.5
CC(=O)NC1=CC=C(Cl)C=C1	p-Chloroacetanilide	178.0
CCCCl	1-Chloropropane	-122.0
ClCCC#N	3-chloropropionitrile	-50.5
CCC(C)(C)CC	3,3-Dimethylpentane	-134.0
CC(C)=C(C)C	Tetramethylethylene	-74.5
CC(C)C(C)C(C)C	2,3,4-Trimethylpentane	-110.0
[O-][N+](=O)C1=CC=CC=C1Br	1-Bromo-2-nitrobenzene	42.5
BrC1=CC=C(I)C=C1	p-Bromoiodobenzene	91.5
CCCC(C)(C)O	2-methyl-2-pentanol	-102.0
CC1(O)CCCCC1	1-METHYLCYCLOHEXANOL	25.5
BrC(C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	1,1',1''-(Bromomethanetriyl)tribenzene	154.0
OC1=C2C=CC=CC2=C(C=C1[N+]([O-])=O)[N+]([O-])=O	2,4-Dinitro-1-naphthol	132.0
NC1=C(Cl)C=CC=C1Cl	2,6-DICHLOROANILINE	39.5
OC(=O)C1=C(O)C(=CC(=C1)[N+]([O-])=O)[N+]([O-])=O	2-Hydroxy-3,5-dinitrobenzoic acid	170.0
[O-][N+](=O)C1=CC=CC=C1C#N	o-Nitrobenzonitrile	108.0
CC(C)(C)OOC(=O)C1=CC=CC=C1	tert-butyl benzenecarboperoxoate	7.5
CC1=CC(Br)=CC=C1Br	2,5-DIBROMOTOLUENE	5.5
COC(=O)C1=CC=CC(Br)=C1	METHYL 3-BROMOBENZOATE	32.5
OC(=O)C1=CC=CC(C=O)=C1	3-Carboxybenzaldehyde	174.0
[O-][N+](=O)C1=CC(=CC=C1)C#N	M-NITROBENZONITRILE	116.0
COC(=O)C1=CC=C(C=C1)[N+]([O-])=O	methyl_4-nitrobenzoate	95.5
N#CC1=CC(=CC=C1)C#N	1,3-DICYANOBENZENE	162.0
CCCC1=CC=C(O)C=C1	4-n-Propylphenol	21.5
N#CCCC1=CC=CC=C1	3-Phenylpropionitrile	-1.5
CC(C)CC=C	4-methyl-1-pentene	-154.0
OC(=O)CCCCCCCCCCC(O)=O	DODECANEDIOIC ACID	128.0
CCCCCCCCCCCBr	1-BROMOUNDECANE	-9.5
CC1=NC(=CN1)[N+]([O-])=O	2-METHYL-4-NITRO-1H-IMIDAZOLE	252.0
O=C(C1CCCCC1)C1=CC=CC=C1	cyclohexyl_phenyl_ketone	55.5
CCC(C)C=C	3-METHYL-1-PENTENE	-154.0
CN1CCCC1=O	1-methylpyrrolidin-2-one	-23.5
NC1=CC=C(C=C1)C#N	4-Aminobenzonitrile	84.5
OC(C(F)(F)F)C(F)(F)F	1,1,1,3,3,3-HEXAFLUOROPROPAN-2-OL	-3.5
CCCCCCCCCCCCCCC(O)=O	pentadecanoic acid	52.5
CC(C)CCCCC(C)C	2,7-DIMETHYLOCTANE	-54.5
CN(C)C1=CC=NC=C1	N,N-Dimethylpyridin-4-amine	112.0
COC(=O)C1=CC=C(Cl)C=C1	methyl_4-chlorobenzoate	43.5
COC(=O)C1=CC=C(C=O)C=C1	METHYL 4-FORMYLBENZOATE	60.5
OC(=O)CC1=CC=CC(Cl)=C1	m-chlorophenylacetic_acid	78.5
COC1=CC(=CC(OC)=C1OC)C#N	3,4,5-Trimethoxybenzonitrile	93.5
OCCSSCCO	Bis(2-hydroxyethyl) disulfide	25.5
COC1=C(Cl)C(Cl)=CC=C1	2,3-Dichloroanisole	31.5
BrC1=CC=CC=C1C1=CC=CC=C1	2-Bromobiphenyl	1.5
ClC1=CC=CC=C1C(Cl)(Cl)Cl	2-CHLOROBENZOTRICHLORIDE	29.5
ClC1=NC2=C(C=CC=C2)N=C1Cl	2,3-DICHLOROQUINOXALINE	152.0
COC1=CC(OC)=C(C=O)C=C1OC	2,4,5-Trimethoxybenzaldehyde	114.0
OC(=O)C1=C(C(Cl)=CC=C1)[N+]([O-])=O	3-chloro-2-nitrobenzoic_acid	238.0
ClS(Cl)=O	Thionyl dichloride	-104.0
CCC(C)N	2-Aminobutane	-104.0
CC(C)C1=NC=C(N1C)[N+]([O-])=O	IPRONIDAZOLE	60.5
BrC1=CC=C(CC#N)C=C1	p-Bromophenylacetonitrile	47.5
[O-][N+](=O)C1=C(Cl)C=C(Cl)C=C1Cl	1,3,5-Trichloro-2-nitrobenzene	71.5
CCC(=O)OC(=O)CC	Propanoic anhydride	-44.5
CCCCCCCC#N	Octanenitrile	-45.5
CCCCOP(=O)(OCCCC)OCCCC	TRIBUTYL PHOSPHATE	-79.5
COC1=CC(Cl)=CC(Cl)=C1	3,5-DICHLOROANISOLE	40.5
COC1=CC(CO)=CC=C1O	4-(Hydroxymethyl)-2-methoxyphenol	114.0
CCN(CC)C1=CC=C(C=O)C=C1	p-DIETHYLAMINOBENZALDEHYDE	40.5
O=C(C1=CC=CS1)C1=CC=CC=C1	Phenyl(2-thienyl)methanone	56.5
N1C=CN=N1	1H-1,2,3-Triazole	23.5
FC1=C(F)C(F)=C(C(F)=C1F)C1=C(F)C(F)=C(F)C(F)=C1F	Decafluorobiphenyl	67.5
CC(C)C(N)=O	Isobutyramide	128.0
COC1=C(OC)C(=O)C(C)=CC1=O	2,3-Dimethoxy-5-methyl-1,4-benzoquinone	59.0
NC(=O)C1=CC=CC=C1Cl	o-Chlorobenzamide	142.0
OC(=O)C1=CC=C(C=C1)C(=O)C1=CC=CC=C1	4-Benzoylbenzoic acid	198.0
CC1=CC=CC(=C1)C(N)=O	m-Toluamide	95.5
N#CCC1=CC=C(CC#N)C=C1	1,4-Phenylenediacetonitrile	95.5
OCC1=CC(CO)=CC=C1	1,3-Benzenedimethanol	57.5
N#CCC1=CC(CC#N)=CC=C1	1,3-Phenylenediacetonitrile	33.5
NC(=O)C1=CC=C(Br)C=C1	p-bromobenzamide	192.0
COC1=CC=C(C=C1OC)[N+]([O-])=O	1,2-Dimethoxy-4-nitrobenzene	97.5
COC1=CC(OC)=C(C=O)C(OC)=C1	2,4,6-Trimethoxybenzaldehyde	120.0
FC1=C(F)C(F)=C(C(=O)C2=CC=CC=C2)C(F)=C1F	(pentafluorophenyl)(phenyl)methanone	37.5
CC1(O)CCCC1	1-Methylcyclopentanol	36.5
OC(=O)CC1=CC=C(Br)C=C1	4-Bromophenylacetic acid	116.0
CCOC1=CC=CC=C1OCC	1,2-DIETHOXYBENZENE	43.5
NC(=O)C1=CC=C(N)C=C1	p-aminobenzamide	182.0
NC(=O)C1=CC=CC=C1Br	o-Bromobenzamide	160.0
COC1=CC=CC(OC)=C1C	2,6-dimethoxytoluene	39.5
CC(=O)C1=CC=CC(=C1)C#N	3-Acetylbenzonitrile	98.5
SCC1=CC=C(Cl)C=C1	p-chlorobenzyl_mercaptan	19.5
COC(=O)NN	Methyl carbazate	72.5
COC1=CC(OC)=CC(Cl)=C1	5-Chloro-1,3-dimethoxybenzene	34.5
CC1=CC(C)=C(C)C(CCl)=C1C	3-(Chloromethyl)-1,2,4,5-tetramethylbenzene	70.0
COC1=CC(=CC=C1)C(N)=O	m-methoxybenzamide	134.0
OCC1=CC=CC=C1I	o-iodobenzyl_alcohol	91.5
CC(=O)OC1=CC=C(C=C1)C1=CC=CC=C1	4-Acetoxybiphenyl	88.5
CCCC1=CC(O)=NC(S)=N1	6-propyl-2-sulfanylpyrimidin-4-ol	220.0
S=C1N=CNC2=C1NC=N2	6-Mercaptopurine	314.0
CN1\C(=C(/O)NC2=NC=CC=C2)C(=O)C2=C(C=CC=C2)S1(=O)=O	Piroxicam	198.0
ClC1=C(Cl)[C@]2(Cl)[C@@H]3[C@@H]4C[C@@H]([C@H]5O[C@@H]45)[C@@H]3[C@@]1(Cl)C2(Cl)Cl	(1r,2s,3s,6r,7r,8s,9s,11r)-3,4,5,6,13,13-hexachloro-10-oxapentacyclo[6.3.1.1~3,6~.0~2,7~.0~9,11~]tridec-4-ene	176.0
NC(=O)C1=CC(=CC=C1)[N+]([O-])=O	3-Nitrobenzamide	142.0
NCCO	2-aminoethanol	10.5
OCCNCCO	2,2'-Iminodiethanol	28.5
OCCN(CCO)CCO	2,2',2''-Nitrilotriethanol	20.0
ClCCCl	1,2-dichloroethane	-35.5
OCCCO	1,3-PROPANEDIOL	-26.5
CC1=CC=CC(C)=N1	2,6-dimethylpyridine	-6.5
CCOC(=O)CC#N	ethyl_cyanoacetate	-22.5
O=CC1=CC2=C(OCO2)C=C1	piperonal	36.5
CC1=CC=C(N)C=C1C	3,4-Dimethylaniline	50.5
ClC(=O)C1=CC=CO1	2-Furoyl chloride	-1.5
CCOC(=O)CCC(=O)OCC	diethyl_succinate	-20.5
COC1=CC(N)=CC=C1	m-Anisidine	-0.5
CN(C)C1=CC=C(Br)C=C1	4-Bromo-N,N-dimethylaniline	54.5
CC1=CC=CC=C1Cl	2-Chlorotoluene	-35.5
CC1=CC=CC=C1Br	2-Bromotoluene	-27.5
COC1=CC(CC=C)=CC=C1O	4-Allyl-2-methoxyphenol	-9.5
N#CCCCCC#N	1,4-Dicyanobutane	1.5
COC1=CC=CC=C1Br	o-Bromoanisole	2.5
ClC(Cl)C1=CC=CC=C1	a,a-dichlorotoluene	-16.5
C(OCC1=CC=CC=C1)C1=CC=CC=C1	benzyl_ether	3.5
[O-][N+](=O)C1=CC=C(F)C=C1F	2,4-Difluoro-1-nitrobenzene	9.5
ClCCCCCCl	1,5-dichloropentane	-72.5
CC(=O)C1=CC=C(Cl)C=C1Cl	2,4-Dichloroacetophenone	33.5
ClC1=CC=C(C=O)C=C1Cl	3,4-DICHLOROBENZALDEHYDE	43.5
CCOCCOCCOCC	1-Ethoxy-2-(2-ethoxyethoxy)ethane	-44.5
COC1=CC(=CC=C1O)C(C)=O	apocynin	114.0
COC(=O)C1=CC=C(OC)C=C1	methyl_4-methoxybenzoate	49.5
CC(C)(O)C(C)(C)O	PINACOL	43.5
ClC1=CC=CC=C1CC#N	2-chlorobenzyl_cyanide	23.5
COC1=CC=CC=C1C=O	o-Anisaldehyde	37.5
ClC1=CC=CC(C=O)=C1	m-Chlorobenzaldehyde	17.5
[O-][N+](=O)C1=CC(Cl)=CC=C1Cl	2,5-DICHLORONITROBENZENE	55.5
ClCC1=CC=CC=C1CCl	a,a'-dichloro-o-xylene	55.5
CCOC(=O)C1=CC=C(OC)C=C1	Ethyl 4-methoxybenzoate	7.5
COCC1=CC=CC=C1	Benzyl methyl ether	-52.5
ClC1=CC=C(Cl)C(I)=C1	1,4-Dichloro-2-iodobenzene	21.5
[O-][N+](=O)C1=CC=C(Br)C=C1	P-BROMONITROBENZENE	126.0
CC1=CC(Br)=C(C)C=C1	2-Bromo-p-xylene	9.5
OC(=O)CC(O)(CC(O)=O)C(O)=O	citric acid	154.0
CCC=O	Propionaldehyde	-80.5
CN(C)C1=CC=CC=C1	n,n-dimethylaniline	2.5
CCCO	Propan-1-ol	-126.0
CC1=CNC(=O)NC1=O	Thymine	316.0
OC1=CC=C(Cl)C(O)=C1	4-chlorobenzene-1,3-diol	106.0
BrCBr	dibromomethane	-52.5
COC(F)(F)C(Cl)Cl	2,2-Dichloro-1,1-difluoroethyl methyl ether	-35.5
CC1=NC=C(N1CCO)[N+]([O-])=O	2-(2-methyl-5-nitro-1h-imidazol-1-yl)ethanol	160.0
OC1=CC(O)=CC=C1	Resorcinol	110.0
COC1=NC(OC)=NC(NS(=O)(=O)C2=CC=C(N)C=C2)=C1	sulfadimethoxine	204.0
CCOC(N)=O	ETHYL CARBAMATE	48.5
OC(=O)C1=C(Cl)C=CC=C1Cl	2,6-DICHLOROBENZOIC ACID	144.0
C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C	17a-Methyltestosterone	164.0
CCCCCO	Pentan-1-ol	-78.5
CC(C)Cl	2-chloropropane	-118.0
CC(C)(C)O	2-Methylpropan-2-ol	25.5
CCC(C)(C)C	2,2-Dimethylbutane	-99.5
CC(=O)C(C)(C)C	3,3-dimethylbutan-2-one	-52.5
CCC(C)=O	Butan-2-one	-86.5
OC(=O)C=C	acrylic_acid	13.0
CC(C)C(C)C	2,3-Dimethylbutane	-128.0
CC(C)C(O)=O	isobutyric acid	-46.5
ClC(Cl)C(Cl)Cl	1,1,2,2-Tetrachloroethane	-43.5
CC1=CC=CC(C)=C1[N+]([O-])=O	1,3-dimethyl-2-nitrobenzene	15.5
OC(=O)C1=CC=CC=C1I	2-IODOBENZOIC ACID	162.0
CC(C)C1=CC=CC=C1O	2-Isopropylphenol	15.5
OC1=CC=CC2=C1C=CC=C2	1-naphthol	95.5
CCC(=O)C1=CC=CC=C1	propiophenone	18.5
CCOC(=O)C(=O)OCC	DIETHYL OXALATE	-40.5
CC1=CC(C)=C(C)C=C1C	1,2,4,5-Tetramethylbenzene	79.5
CCC(=O)CC	Pentan-3-one	-39.5
[O-][N+](=O)C1=CC=CC=C1	nitrobenzene	5.5
[O-][N+](=O)C1=CC(=CC=C1)[N+]([O-])=O	1,3-Dinitrobenzene	89.5
ON=C1CCCCC1	N-hydroxycyclohexanimine	89.5
CCCN(CCC)CCC	N,N-dipropylpropan-1-amine	-93.5
CCCC1=CC=CC=C1	Propylbenzene	-99.5
CCNC1=CC=CC=C1	n-ethylaniline	-63.5
COC=O	methyl formate	-99.5
CC(=C)CC(C)(C)C	2,4,4-Trimethylpent-1-ene	-93.5
CC1CCCCC1	Methylcyclohexane	-126.0
ClC1=CC=CC=C1	chlorobenzene	-45.5
CCCCN	butan-1-amine	-49.5
CCCCCCCCC	Nonane	-53.5
CCCCCCCCN	1-Octylamine	-0.5
CCCCCCCCCCO	Decan-1-ol	6.5
CCCCCCCCCCCCCCCCCCCC	Icosane	36.5
OC(=O)C(C1=CC=CC=C1)C1=CC=CC=C1	diphenylacetic acid	146.0
OC(=O)CCCCCCC(O)=O	SUBERIC ACID	144.0
CC(C)(C)Cl	2-Chloro-2-methylpropane	-25.5
[CH:1]1=[CH:1][CH:1]=[C:1]([CH:1]=[CH:1]1)C(C1=CC=CC=C1)C1=CC=CC=C1	1,1',1''-methanetriyltribenzene	93.5
CCC(C)=C	2-Methylbut-1-ene	-138.0
CCCCCCCCCCCCCCCCC	HEPTADECANE	21.5
CCCCCCCCCCCCCCCCCCC	NONADECANE	32.5
CCCCCCCCCCCCC=C	Tetradec-1-ene	-12.5
OC(=O)C1=CC(=CC=C1Cl)[N+]([O-])=O	2-chloro-5-nitrobenzoic_acid	166.0
NCCCCCCO	6-Aminohexan-1-ol	56.5
COC1=CC=C(Cl)C(Cl)=C1Cl	2,3,4-Trichloroanisole	69.5
NC1=NC=C2N=CN(COCCO)C2=N1	6-Deoxyacyclovir	188.0
CCC(C)(C)Cl	2-chloro-2-methylbutane	-73.5
[O-][N+](=O)C1=CC=C(CC#N)C=C1	p-Nitrophenylacetonitrile	116.0
COC1=CC(C=O)=CC(OC)=C1	3,5-Dimethoxybenzaldehyde	46.5
O=CC=CC1=CC=CC=C1	(2E)-3-phenylacrylaldehyde	-7.5
NC1=CC(=CC=C1O)[N+]([O-])=O	2-amino-4-nitrophenol	144.0
CC1=CC=C(N)C=C1	p-Toluidine	43.5
ClCC=C	3-chloroprop-1-ene	-134.0
BrC(Br)Br	bromoform	8.5
CCOCCOC(C)=O	2-Ethoxyethyl acetate	-61.5
COC(=O)C1=CC=C(C=C1)C(=O)OC	DIMETHYL TEREPHTHALATE	142.0
CC1=CC=C(Cl)C=C1	1-Chloro-4-methylbenzene	7.5
COC1=CC=C(C=O)C=C1OC	3,4-Dimethoxybenzaldehyde	43.5
CC1=CC(O)=CC(C)=C1Cl	4-chloro-3,5-dimethylphenol	114.0
CC1=CC(O)=CC=C1Cl	4-Chloro-3-methylphenol	66.5
ClCCCCCl	1,4-DICHLOROBUTANE	-37.5
CCCCO	Butan-1-ol	-89.5
CCCCCCCCCC(O)=O	Decanoic acid	31.5
ClC1=CC=CC(Cl)=C1C=O	2,6-Dichlorobenzaldehyde	71.0
COC1=C(OC)C=C(C=C1)C(O)=O	3,4-DIMETHOXYBENZOIC ACID	180.0
OC1=CC=C(C=O)C(O)=C1	2,4-DIHYDROXYBENZALDEHYDE	136.0
CCC#N	Propiononitrile	-92.5
NC1CCCCC1	Cyclohexanamine	-17.5
CCCCC=O	Valeraldehyde	-91.5
OC(=O)C1=CC(=CC=C1)[N+]([O-])=O	3-nitrobenzoic acid	142.0
OC1=CC=C2C=CC=CC2=C1	2-naphthol	122.0
C1=CC=C2C(=C1)C1=CC=CC3=C1C2=CC=C3	Fluoranthene	108.0
O=C1C2=CC=CC=C2C2=CC=CC=C12	9-Fluorenone	83.5
CCNC1=NC(NC(C)(C)C)=NC(SC)=N1	Terbutryn	104.0
[O-][N+](=O)C1=C(Cl)C(Cl)=C(Cl)C=C1	2,3,4-TRICHLORONITROBENZENE	55.5
CC1=CC=C(C=C1N=C=O)N=C=O	2,4-Diisocyanato-1-methylbenzene	20.5
OC1=CC=CC=C1O	Pyrocatechol	106.0
CC1=CC(O)=CC=C1	m-cresol	11.5
ClC1=CC(Cl)=C(Cl)C(Cl)=C1Cl	pentachlorobenzene	85.5
CN(C)C(=O)NC1=CC(Cl)=C(Cl)C=C1	diuron	158.0
CC(C)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C	Cholesterol	148.0
C1C2=CC=CC=C2OC2=CC=CC=C12	XANTHENE	101.0
CN(C)C1=CC=C(C=O)C=C1	4-(dimethylamino)benzaldehyde	74.5
CC(=O)NS(=O)(=O)C1=CC=C(N)C=C1	Sulfacetamide	182.0
BrC1=CC=C(Br)C=C1	1,4-dibromobenzene	87.5
ClC1=CC(Cl)=C(Cl)C=C1Cl	1,2,4,5-Tetrachlorobenzene	140.0
C1=CC=CC=C1	Benzene	5.5
CC(=O)NC1=CC=CC=C1	acetanilide	114.0
CCCOC(=O)C1=CC=C(O)C=C1	Propyl 4-hydroxybenzoate	96.5
SCC1=CC=CC=C1	BENZYL MERCAPTAN	-29.5
O=C1CCC1	CYCLOBUTANONE	-51.5
ClC1=CC=C(C=C1)S(=O)(=O)C1=CC=C(Cl)C=C1	Bis(4-chlorophenyl) sulfone	148.0
CC1=CC(=CC(C)=C1)C(O)=O	3,5-DIMETHYLBENZOIC ACID	171.0
C(CC1CCNCC1)CC1CCNCC1	1,3-bis(4-piperidinyl)propane	66.5
CC(C)C(C)=O	3-Methyl-2-butanone	-92.5
CCCC(C)=O	PENTAN-2-ONE	-77.5
CC1(C)C2CCC(C)(C2)C1=O	(1R)-(-)-Fenchone	5.55
ICI	Diiodomethane	5.55
COC1=CC=CC=C1[N+]([O-])=O	1-Methoxy-2-nitrobenzene	9.95
OC1=CC=CC=C1F	2-Fluorophenol	15.6
O=C(C1=CC=CC=C1)C1=CC=CC=C1	benzophenone	48.5
OC1=CC=CC=C1	Phenol	41.5
CCCCCC=C	1-Heptene	-120.0
CCCCCCCC(O)=O	octanoic acid	16.4
CC1=CC(C)=C(CC(O)=O)C(C)=C1	Mesitylacetic acid	168.0
CCCC	Butane	-138.0
O=C1OC(=O)C2=CC=CC=C12	phthalic anhydride	131.0
BrC=C	Bromoethene	-138.0
OC(=O)CCCCC(O)=O	adipic acid	153.0
OC(C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	TRIPHENYLMETHANOL	164.0
NC1=CC=C(C=C1)C(O)=O	4-Aminobenzoic acid	188.0
[O-][N+](=O)C1=CC=C(F)C(=C1)[N+]([O-])=O	1-FLUORO-2,4-DINITROBENZENE	26.4
O(C1=CC=CC=C1)C1=CC=CC=C1	diphenyl ether	27.4
NC1=CC=C(F)C=C1	4-FLUOROANILINE	-1.4
CCCCCCCCCCCCCC=C	1-PENTADECENE	-3.4
COC1=CC=CC=C1N	2-Methoxyaniline	5.6
OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F	Pentadecafluorooctanoic acid	54.9
FC1=CC=C(C=C1)C#N	4-fluorobenzonitrile	35.4
OCCCCCCCCCO	1,9-Nonanediol	46.4
NC1=CC=CC=C1OC1=CC=CC=C1	2-Phenoxyaniline	46.4
O=C1OC(=O)C=C1	furan-2,5-dione	53.4
NC1=CC=CC2=C1C=CC=C2	1-Aminonaphthalene	48.6
CCCCCCCCCCCCCC(O)=O	MYRISTIC ACID	54.5
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	TRIACONTANE	66.4
O=S(C1=CC=CC=C1)C1=CC=CC=C1	diphenyl_sulfoxide	70.6
CCCC(N)=O	Butyramide	115.0
NC1=CC=C(C=C1)S(N)(=O)=O	sulfanilamide	166.0
COC1=CC=C(CC#N)C=C1OC	3,4-Dimethoxyphenylacetonitrile	63.4
CC1=CC=C(C)C=C1	p-xylene	12.6
C1CSCCS1	1,4-DITHIANE	112.0
CC1=CSC(S)=N1	2-Mercapto-4-methylthiazole	88.7
OC(=O)CCCC(O)=O	glutaric acid	97.2
CN1CCC(CC1)=C1C2=CC=CC=C2C=CC2=CC=CC=C12	Cyproheptadine	112.0
CCCCCCCCCCCCCCCCC(O)=O	HEPTADECANOIC ACID	60.6
ClC1=CC=CC=C1C#N	O-CHLOROBENZONITRILE	45.6
[O-][N+](=O)C1=CC(CBr)=CC=C1	3-nitrobenzyl_bromide	58.6
ClC1=CC=CC=C1Cl	1,2-Dichlorobenzene	-17.4
ClCCBr	1-BROMO-2-CHLOROETHANE	-17.4
CC1=CC=CC(N)=C1	m-Toluidine	-30.6
C1=CC2=CC=C(C=C2C=C1)C1=CC2=CC=CC=C2C=C1	2,2'-BINAPHTHALENE	188.0
N1C=CN=C1C1=CC=CC=C1	2-Phenylimidazole	149.0
OC(=O)C1=CC(I)=CC=C1	m-iodobenzoic_acid	188.0
O=CC1=CC=CC=C1	benzaldehyde	-56.2
CCC1=NN=C(N)S1	2-Amino-5-ethyl-1,3,4-thiadiazole	201.0
OC1=CC(Cl)=CC=C1OC1=CC=C(Cl)C=C1Cl	5-CHLORO-2-(2,4-DICHLOROPHENOXY)PHENOL	56.3
CC1=CC=C2C=CC=CC2=C1	2-methylnaphthalene	33.7
C1OC1C1=CC=CC=C1	2-Phenyloxirane	-36.3
FC1=CC=C(Br)C=C1	1-Bromo-4-fluorobenzene	-16.7
CCCCCCCCCCCCCCCCCCCCCCC	TRICOSANE	48.3
FC1=C(F)C(F)=C(F)C(F)=C1F	Hexafluorobenzene	4.6
CCOC1=CC(OCC)=CC=C1	1,3-Diethoxybenzene	11.7
FC(F)(F)C1=CC=CC=C1Cl	1-Chloro-2-(trifluoromethyl)benzene	-6.7
[O-][N+](=O)C1=CC(Cl)=CC(Cl)=C1	1,3-Dichloro-5-nitrobenzene	64.7
CCOC=O	Ethyl formate	-80.3
OC(=O)C1=CN=CC=C1	nicotinic acid	237.0
S1C=CC=C1	thiophene	-38.7
CF	Fluoromethane	-143.0
COC1=CC=CC=C1N1CCNCC1	1-(2-Methoxyphenyl)piperazine	37.8
CN1CCC(=CC1)C1=CC=CC=C1	1-Methyl-4-phenyl-1,2,3,6-tetrahydropyridine	39.2
CC(C)(OC1=CC=C(Cl)C=C1)C(O)=O	2-(4-chlorophenoxy)isobutyric acid	119.0
NC1=C(C(=NN1C1=C(Cl)C=C(C=C1Cl)C(F)(F)F)C#N)S(=O)C(F)(F)F	5-amino-1-[2,6-dichloro-4-(trifluoromethyl)phenyl]-4-[(trifluoromethyl)sulfinyl]-1H-pyrazole-3-carbonitrile	200.0
COC1=CC=C(C(=O)C2=CC=CC=C2)C(O)=C1	2-Hydroxy-4-methoxybenzophenone	64.8
CNC(=O)OC1=CC=CC=C1OC(C)C	propoxur	90.8
O=C1NC2=CC=CC=C2C=C1	2-Hydroxyquinoline	199.0
CC(C)(C)S	2-METHYL-2-PROPANETHIOL	0.25
ClC(C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	CHLOROTRIPHENYLMETHANE	113.0
N#CC1=CC=CC2=CC=CC=C12	Naphthalene-1-carbonitrile	36.8
NC1=CC=C2C=CC=CC2=C1	naphthalen-2-amine	112.0
BrC1=CC=C(C=C1)C1=CC=CC=C1	4-BROMOBIPHENYL	90.8
OC(=O)C1=CC2=CC=CC=C2C=C1	2-NAPHTHOIC ACID	185.0
CCOC1=CC=C2C=CC=CC2=C1	2-ETHOXYNAPHTHALENE	36.8
OC(=O)[C@@H]1CCC(=O)N1	5-oxo-L-proline	161.0
CC1=CC(=CC=C1N)[N+]([O-])=O	2-methyl-4-nitroaniline	133.0
CCCCCCCCCCCCCO	1-TRIDECANOL	33.2
CC1=C(O)C(=O)C=CO1	3-Hydroxy-2-methyl-4-pyrone	162.0
CC1=CC(=CC=C1N)C1=CC=C(N)C(C)=C1	o-Tolidine	131.0
N#CCC1=CC=CC2=CC=CC=C12	1-Naphthylacetonitrile	33.2
OC1=CC2=CC=CC=C2C(O)=C1	1,3-DIHYDROXYNAPHTHALENE	124.0
CCCCCCCCCCCCCCCC(=O)OC(C)C	ISOPROPYL PALMITATE	12.8
C(SSCC1=CC=CC=C1)C1=CC=CC=C1	Dibenzyl disulfide	70.8
C1=CC2=CC=CC3=C2C1=CC=C3	acenaphthylene	91.8
NNC1=C(Cl)C=CC(Cl)=C1	2,5-Dichlorophenylhydrazine	103.0
OC(=O)C1CSCN1	1,3-Thiazolidine-4-carboxylic acid	196.0
OC(=O)C1=CC=C(C=C1)C(F)(F)F	4-(Trifluoromethyl)benzoic acid	220.0
OC(=O)C1=CC=CS1	THIOPHENE-2-CARBOXYLIC ACID	129.0
CC(C)C1=CC=C(C=C1)C(O)=O	4-Isopropylbenzoic acid	118.0
OC1=C(OC2=C(C=CC=C2)C1=O)C1=CC=CC=C1	3-hydroxyflavone	171.0
[O-][N+](=O)C1=CC=CC2=C1C(=CC=C2)[N+]([O-])=O	1,8-DINITRONAPHTHALENE	172.0
CC1=CC=CC=C1C1=CC=CC=C1C	2,2'-Dimethylbiphenyl	18.8
OC1=C(Br)C=CC=C1Br	2,6-DIBROMOPHENOL	55.8
CC1=CC2=C(C=CC=C2)N=C1	3-METHYLQUINOLINE	15.8
OC(=O)COC1=CC=CC=C1Cl	2-chlorophenoxyacetic acid	149.0
ClC1=CC(=O)C(Cl)=CC1=O	2,5-Dichloro-1,4-benzoquinone	161.0
OC1=CC=C(CC2=CC=C(O)C=C2)C=C1	4,4'-Dihydroxydiphenylmethane	162.0
COC1=CC=C(C=C1O)C(O)=O	3-HYDROXY-4-METHOXYBENZOIC ACID	252.0
[O-][N+](=O)C1=CC2=C(OCO2)C=C1C=O	6-Nitropiperonal	94.2
CCOC(=O)CC1=CNC2=C1C=CC=C2	Ethyl indole-3-acetate	43.8
O=C1OC(=O)C2C3CC(C=C3)C12	cis-5-Norbornene-endo-2,3-dicarboxylic anhydride	165.0
OP(=O)(OC1=CC=CC=C1)OC1=CC=CC=C1	DIPHENYL PHOSPHATE	66.8
O=C1C=CC(=O)N1C1=CC=CC=C1	N-Phenylmaleimide	89.8
CN(C)C(=O)C(C1=CC=CC=C1)C1=CC=CC=C1	N,N-Dimethyl-2,2-diphenylacetamide	134.0
OC1=CC=C(O)C(=C1)C1=CC=CC=C1	2-Phenylhydroquinone	102.0
COC1=CC(=CC(OC)=C1)C(O)=O	3,5-DIMETHOXYBENZOIC ACID	185.0
BrC1=CC2=C(C=C1)C1=CC=CC=C1C2	2-Bromofluorene	113.0
COC(=O)C1=CC(=CC=C1)C(=O)OC	DIMETHYL ISOPHTHALATE	68.2
NC1=C(C=C(C=C1Br)[N+]([O-])=O)[N+]([O-])=O	2-Bromo-4,6-dinitroaniline	153.0
OC1=CC2=C(NC=C2)C=C1	5-Hydroxyindole	108.0
COC(=O)C1=CC=C(O)C=C1O	METHYL 2,4-DIHYDROXYBENZOATE	119.0
ON=C1C2=CC=CC=C2C2=CC=CC=C12	9-Fluorenone oxime	195.0
OC(=O)CCCCC1=CC=CC=C1	5-Phenylvaleric acid	58.2
CCC1=CC=C(O)C=C1O	4-ETHYLRESORCINOL	97.8
CC(=O)CCCC(O)=O	4-Acetylbutyric acid	12.8
OC(=O)C1=CC(OC2=CC=CC=C2)=CC=C1	3-Phenoxybenzoic acid	149.0
OC1=C(Cl)C=C(Br)C=C1	4-BROMO-2-CHLOROPHENOL	49.8
COC1=CC=CC(C#N)=C1OC	2,3-Dimethoxybenzonitrile	45.2
C(N(CC1=CC=CC=C1)CC1=CC=CC=C1)C1=CC=CC=C1	Tribenzylamine	92.2
COC1=CC(N)=CC=C1C	3-Methoxy-4-methylaniline	57.2
ClC1=C2COC(=O)C2=C(Cl)C(Cl)=C1Cl	Fthalide	209.0
S1C=CC=C1C1=CC=C(S1)C1=CC=CS1	2,2':5',2''-Terthiophene	92.8
C[Si]1(C)N[Si](C)(C)N[Si](C)(C)N[Si](C)(C)N1	Octamethylcyclotetrasilazane	96.8
COC1=CC=C(OC)C(=C1)[N+]([O-])=O	1,4-Dimethoxy-2-nitrobenzene	71.8
ClC(=O)C1=C(Cl)C=C(Cl)C=C1	2,4-Dichlorobenzoyl chloride	17.2
CC(CCC(O)=O)(C1=CC=C(O)C=C1)C1=CC=C(O)C=C1	4,4-Bis(4-hydroxyphenyl)valeric acid	172.0
NC1=CC(=C(F)C=C1)[N+]([O-])=O	4-Fluoro-3-nitroaniline	96.8
FC(F)(F)C1=CC=CC(=C1)C#N	3-(Trifluoromethyl)benzonitrile	15.2
OCC(F)(F)C(F)(F)C(F)(F)CO	2,2,3,3,4,4-Hexafluoro-1,5-pentanediol	78.8
FC1=CC=C(C=C)C=C1	4-Fluorostyrene	-35.2
O=C1NN=CC(=O)N1	6-Azauracil	275.0
O=C1CCOC2=CC=CC=C12	4-Chromanone	37.2
COC1=CC=CC=C1OC(=O)C1=CC=CC=C1	2-Methoxyphenyl benzoate	58.2
COC1=CC=C2COC(=O)C2=C1OC	Opianyl	102.0
OC1=CC2=C(C=CC=C2O)C=C1	1,7-Dihydroxynaphthalene	181.0
CCS(=O)(=O)CC	diethyl sulfone	72.8
CCC(=O)C1=CC(O)=CC=C1O	2',5'-Dihydroxypropiophenone	97.2
CCCCOC1=CC=C(C=C1)C(O)=O	4-butoxybenzoic_acid	148.0
CCOC(=O)C(=O)NC1=CC=CC=C1	Ethyl oxanilate	66.2
C[Si](C)(C)[Si](C)(C)C	Hexamethyldisilane	12.8
CC1=CSC(N)=N1	2-Amino-4-methylthiazole	44.8
OC(=O)CCCCCCCCCCCCCCCCCCC(O)=O	1,18-octadecanedicarboxylic acid	126.0
CC1=CC=C(C=C1C)C(=O)C1=CC=CC=C1	3,4-Dimethylbenzophenone	46.8
ON1N=NC2=C1C=CC=C2	1h-benzotriazol-1-ol	158.0
CC(C)(C)C1=CC(=O)C(=O)C(=C1)C(C)(C)C	3,5-Di-tert-butyl-1,2-benzoquinone	114.0
CCCC(=O)NN	Butyric acid hydrazide	44.8
COC1=CC=C(CCCC(O)=O)C=C1	4-(4-Methoxyphenyl)butanoic acid	58.2
CC(=O)C1=CC=C(C)S1	2-Acetyl-5-methylthiophene	26.8
CC1=NNC=C1Br	4-Bromo-3-methyl-1H-pyrazole	75.8
NC1=CC2=C(NN=C2)C=C1	5-Amino-1H-indazole	176.0
OC1=C(F)C=CC=C1F	2,6-Difluorophenol	38.8
ClC(C(=O)C1=CC=CC=C1)C1=CC=CC=C1	Desyl chloride	67.8
CC1(C)OC(=O)CC1C(O)=O	terebinic acid	175.0
CCP(O)(O)=O	Ethylphosphonic acid	60.8
OC(=O)C(=C)C(F)(F)F	2-(Trifluoromethyl)acrylic acid	50.8
OC(=O)C(=CC1=CC=CC=C1)C1=CC=CC=C1	2,3-diphenylacrylic acid	172.0
CC1=NNC(=S)NC1=O	6-Aza-2-thiothymine	219.0
NC1=CC=C(N)C(=C1)[N+]([O-])=O	2-nitrobenzene-1,4-diamine	139.0
OC1=CC=C(C=C1)C1=COC2=C(C(O)=CC(O)=C2)C1=O	4',5,7-Trihydroxyisoflavone	301.0
OC1=CC2=C(C(O)=C1)C(=O)C=C(O2)C1=CC=CC=C1	5,7-Dihydroxyflavone	286.0
COP(=O)(OC)OC(=CCl)C1=C(Cl)C=C(Cl)C(Cl)=C1	Stirofos	96.8
ON=CC1=CC=CC=C1	Benzaldehyde, oxime, (Z)-	35.8
CCCCCCCCC=CCCCCCCCCCCCC(N)=O	(13Z)-docos-13-enamide	78.2
OC(=O)C1=CC2=CC=CC=C2O1	Benzo[b]furan-2-carboxylic acid	193.0
CC(=O)C1=CC=CN=C1	3-ACETYLPYRIDINE	12.8
CN(C)C1=CC=CC(=C1)[N+]([O-])=O	N,N-Dimethyl-3-nitroaniline	59.8
CC1=CC2=C(C=C1C)N=CN2	5,6-Dimethylbenzimidazole	205.0
CCCCCCCCCCCCCCCC(O)=O	palmitic acid	61.8
OC1=C(Cl)C=C(Cl)C2=C1N=CC=C2	5,7-Dichloro-8-hydroxyquinoline	180.0
CCC(=C)C(=O)C1=C(Cl)C(Cl)=C(OCC(O)=O)C=C1	ETHACRYNIC ACID	122.0
CCN1C(=O)C=CC1=O	1-Ethyl-1H-pyrrole-2,5-dione	44.8
OC(=O)CI	IODOACETIC ACID	81.8
BrCC(=O)C1=CC=CC=C1	2-Bromoacetophenone	49.8
OC1(CCCCC1)C#C	1-Ethynyl-1-cyclohexanol	32.2
BrC1=CC=C(C=C1)C(=O)C1=CC=CC=C1	p-Bromobenzophenone	81.8
CC(C)(C)C1=CC=C(C=C1)C(O)=O	4-tert-butylbenzoic_acid	165.0
NC(=O)CC#N	CYANOACETAMIDE	121.0
ClC1=C(Cl)C(Cl)=C(Cl)C2=C1C(=O)OC2=O	4,5,6,7-Tetrachloro-2-benzofuran-1,3-dione	255.0
OC(=O)CCCC1=CNC2=CC=CC=C12	Indole-3-butyric acid	124.0
ClC1=CC=C(C=C1)C(=O)C1=CC=CC=C1	p-Chlorobenzophenone	76.8
NC1=CC=CC(N)=N1	2,6-Diaminopyridine	121.0
CC1=CC=CO1	2-METHYLFURAN	-88.2
OCC1=CC=C(CO)C=C1	1,4-Benzenedimethanol	118.0
OC1=C(C2=CC=CC=C2C=C1)C1=C(O)C=CC2=C1C=CC=C2	1,1'-bi(2-naphthol)	216.0
CC1=CC=C(OC(=O)C2=CC=CC=C2)C=C1	p-tolyl_benzoate	70.8
IC1=CC=C(I)C=C1	1,4-DIIODOBENZENE	131.0
OC(=O)C1=CC=C(C=C)C=C1	p-vinylbenzoic_acid	143.0
NC(=O)C1=C(Cl)C=CC=C1Cl	2,6-DICHLOROBENZAMIDE	198.0
CC(=O)OC1=CC=C(C=C1)C(O)=O	4-acetoxybenzoic_acid	193.0
COC1=CC=C(N)C(OC)=C1	2,4-Dimethoxyaniline	34.2
OC(=O)COC1=CC=CC=C1	phenoxyacetic_acid	99.2
O=CC1=CC=C(C=C1)C#N	4-cyanobenzaldehyde	101.0
OCC(=O)C1=CC=CC=C1	2-hydroxyacetophenone	5.25
OCC1=CC=CC(=C1)[N+]([O-])=O	3-nitrobenzyl_alcohol	31.2
CC(C)(C)OC(=O)NCC(O)=O	Boc-glycine	88.2
NC1=CC(Cl)=C(O)C(Cl)=C1	4-Amino-2,6-dichlorophenol	168.0
NC1=CC=C(C=C1)C1CCCCC1	4-Cyclohexylaniline	53.8
C[C@@H](O)[C@H](C)O	(2r,3s)-butane-2,3-diol	33.8
ClCC=CCCl	trans-1,4-Dichloro-2-butene	2.75
COC1=CC=C(C=C1)C(N)=O	p-methoxybenzamide	166.0
OC1=CC=CC(NC2=CC=CC=C2)=C1	3-Anilinophenol	80.8
NC1=CC=C(O)C=C1	4-aminophenol	188.0
NC1=CC=C(C=C1)S(=O)(=O)C1=CC=C(N)C=C1	4,4'-Diaminodiphenyl sulfone	176.0
CCN(CC)C(=S)SSC(=S)N(CC)CC	1,1',1'',1'''-[disulfanediylbis(carbonothioylnitrilo)]tetraethane	70.8
N1C=NC2=CC=CC=C12	1H-Benzimidazole	170.0
COC(=O)C=C	methyl acrylate	-75.8
OC(=O)C1CCCCC1	cyclohexanecarboxylic acid	30.8
NC1=CC(=CC=C1)[N+]([O-])=O	m-Nitroaniline	113.0
CC(=O)CCC(C)=O	Hexane-2,5-dione	-6.25
CC1=CC(N)=C(N)C=C1	4-methylbenzene-1,2-diamine	88.8
CCCCC(C)=O	Hexan-2-one	-56.2
NC1=C2N=CN([C@@H]3O[C@H](CO)[C@@H](O)[C@H]3O)C2=NC=N1	Adenosine	235.0
OC(=O)C(Cl)(Cl)Cl	TRICHLOROACETIC ACID	56.8
OC(=O)CCl	chloroacetic acid	62.2
NC1=CC=CC=C1N	benzene-1,2-diamine	102.0
[O-][N+](=O)C1=CC(I)=CC=C1	1-Iodo-3-nitrobenzene	37.8
CC1=CC=C(C=C1)C#N	4-METHYLBENZONITRILE	28.8
COC1=CC=C(C=C1)C(O)=O	4-METHOXYBENZOIC ACID	184.0
C1CCC(CC1)N=C=NC1CCCCC1	DCC	35.2
CN1C=CN=C1S	2-Mercapto-1-methylimidazole	146.0
CC(=O)C1=CC=CC=C1	1-Phenylethanone	19.8
NC#N	CYANAMIDE	44.8
C1CC2=CC=CC3=C2C1=CC=C3	Acenaphthene	94.2
CCOC1=CC=C(N)C=C1	4-ETHOXYANILINE	3.2
NCCN1CCOCC1	4-(2-Aminoethyl)morpholine	24.8
ClC1=CC(Cl)=CC(Cl)=C1	1,3,5-trichlorobenzene	64.2
O=CC1=CC(C=O)=CC=C1	Isophthalaldehyde	88.7
CN1C2=C(C=CC=C2)C2=C1C=CC=C2	9-Methyl-9H-carbazole	90.2
CC(C)C1(CC=C)C(=O)NC(=O)NC1=O	aprobarbital	142.0
ClC1=CC=C(C=C1)C(C1=CC=C(Cl)C=C1)C(Cl)(Cl)Cl	4,4'-DDT	109.0
C1CC[C@H]2CCCC[C@@H]2C1	trans-Decahydronaphthalene	-31.1
CCOC(=O)C(NC(C)=O)C(=O)OCC	Diethyl acetamidomalonate	97.2
OC(=O)CCC#C	4-PENTYNOIC ACID	56.9
OCCCCCCCCCCCCO	1,12-DODECANEDIOL	82.2
CC(C)[N+]([O-])=O	2-nitropropane	-92.2
O=C1C=CC(=O)C=C1	1,4-BENZOQUINONE	115.0
CC(C)(C)C1=CC=CC=C1	tert-Butylbenzene	-58.6
CC1=NN=C2CN=C(C3=CC=CC=C3)C3=C(C=CC(Cl)=C3)N12	Alprazolam	229.0
CC1CC(C)C(C)C1	CYCLOPENTANE, 1,2,4-TRIMETHYL-, (1.ALPHA.,2.ALPH	-132.0
CC1=CC=C2C=CC=C(O)C2=N1	8-HYDROXY-2-METHYLQUINOLINE	72.9
ON=C1CCCC1	Cyclopentanone oxime	56.9
CC1=C(C=CC=C1Cl)[N+]([O-])=O	2-Chloro-6-nitrotoluene	36.9
COC(=O)C1=CC=C(OC)C(OC)=C1	methyl_3,4-dimethoxybenzoate	59.9
ClCC1=CC(CCl)=CC=C1	a,a'-dichloro-m-xylene	35.1
CCCCCCCCCCCC(O)=O	Lauric acid	44.1
CC(=O)C(C)=O	biacetyl	-2.1
FC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F	OCTADECAFLUOROOCTANE	-24.1
CC1(C)[C@@H]2CC[C@@]1(C)C(=O)C2	(1R)-Camphor	179.0
OC(=O)CCC1=CC=C(O)C=C1	3-(4-Hydroxyphenyl)propionic acid	130.0
OC1=C(I)C=C(I)C=C1I	2,4,6-TRIIODOPHENOL	159.0
OCCN1CCCCC1	1-(2-Hydroxyethyl)piperidine	16.9
COC(=O)CCCCCCCCCCC(=O)OC	Dimethyl 1,10-decanedicarboxylate	30.9
C1CCC(CC1)NC1CCCCC1	N-Cyclohexylcyclohexanamine	-1.05
CS	METHANETHIOL	-122.0
CC1(C)COC(=O)C1O	d-pantolactone	91.0
OC(=O)CC[N+]([O-])=O	3-Nitropropanoic acid	63.0
NC(=O)C1=C(Cl)C=C(C=C1)[N+]([O-])=O	2-Chloro-4-nitrobenzamide	171.0
COC(=O)C1=C(Cl)C(Cl)=C(C(=O)OC)C(Cl)=C1Cl	DIMETHYL TETRACHLOROTEREPHTHALATE	156.0
S1C2=CC=CC=C2C2=C1C=CC=C2	dibenzothiophene	98.0
NC(=O)C1=CC(=CC(=C1)[N+]([O-])=O)[N+]([O-])=O	3,5-Dinitrobenzamide	183.0
CCNC1=NC(NCC)=NC(Cl)=N1	2-Chloro-4,6-bis(ethylamino)-1,3,5-triazine	227.0
C1=CC2=C(C=C1)C=C1C(C=CC3=C1C=CC=C3)=C2	Tetraphene	159.0
O=C1NC2=CC=CC=C2O1	2-BENZOXAZOLINONE	139.0
NCCS	2-Aminoethanethiol	97.0
OCC(Br)(Br)Br	2,2,2-Tribromoethanol	80.0
CC1(C)NC(=O)NC1=O	5,5-DIMETHYLHYDANTOIN	177.0
ClC1=CC=C(C=C1)S(=O)(=O)C1=CC=CC=C1	4-Chlorodiphenyl sulfone	93.0
O=C1CCC2=CC=CC=C12	1-Indanone	41.0
O=C(OC1=CC=CC=C1)C1=CC=CC=C1C(=O)OC1=CC=CC=C1	diphenyl phthalate	74.0
OC(=O)C1=CC=CC=C1C(=O)C1=CC=CC=C1	2-Benzoylbenzoic acid	128.0
CC1=CC=C(O)C(=C1)C(O)=O	5-METHYLSALICYLIC ACID	152.0
CC(=O)C1=CC=C(O)C=C1O	2',4'-DIHYDROXYACETOPHENONE	145.0
CC1=CC=CC=C1CBr	2-Methylbenzyl bromide	20.0
OC1=CC2=CC=CC=C2C=C1O	2,3-Dihydroxynaphthalene	163.0
O1C(=CN=C1C1=CC=CC=C1)C1=CC=CC=C1	2,5-Diphenyloxazole	73.0
CC1=NC2=CC(C)=CC=C2S1	2,5-Dimethylbenzothiazole	39.0
CC1=CC=CC=C1NC(=N)NC1=CC=CC=C1C	1,3-Di-o-tolylguanidine	178.0
NC1=C(Cl)C=C(C=C1Cl)[N+]([O-])=O	2,6-DICHLORO-4-NITROANILINE	190.0
[O-][N+](=O)C1=CC=C(C=C)C=C1	4-Nitrostyrene	28.0
CCOC1=CC=C(C=C1)[N+]([O-])=O	1-Ethoxy-4-nitrobenzene	59.0
N#CC1=CC=CC=N1	2-cyanopyridine	28.0
CC(OC1=CC=CC(Cl)=C1)C(O)=O	2-(3-CHLOROPHENOXY)PROPIONIC ACID	114.0
OCC(O)COC1=CC=C(Cl)C=C1	3-(4-Chlorophenoxy)-1,2-propanediol	79.0
OC(=O)CCCl	3-CHLOROPROPIONIC ACID	40.0
OC(=O)CCSCCC(O)=O	3,3'-Thiodipropionic acid	130.0
CCCCCCCCCCCCCCCCCC(=O)OCC	ETHYL STEARATE	34.0
NC1=CC=CC2=C1C=C(O)C=C2	8-Amino-2-naphthol	207.0
CC1=NC2=C(S1)C=CC=C2	2-METHYLBENZOTHIAZOLE	13.0
ClC1=CC=C2C(=O)C3=CC=CC=C3C(=O)C2=C1	2-CHLOROANTHRAQUINONE	210.0
OC1=CC=C(C(=O)C2=CC=CC=C2)C(O)=C1	2,4-DIHYDROXYBENZOPHENONE	145.0
OC1=CC(OC(=O)C2=CC=CC=C2)=CC=C1	Resorcinol monobenzoate	133.0
C(CNCC1=CC=CC=C1)NCC1=CC=CC=C1	N,N'-Dibenzylethylenediamine	25.0
C1C2=CC=CC3=C2C2=C(C=CC=C12)C=C3	4H-Cyclopenta[def]phenanthrene	115.0
C1=CC=C2C(C=CC3=C2N=CC=C3)=C1	Benzo[h]quinoline	51.0
CC(=O)NC1=CC=C(F)C=C1	4'-Fluoroacetanilide	153.0
OC1=C(F)C=C(C=C1)[N+]([O-])=O	2-FLUORO-4-NITROPHENOL	120.0
OC(=O)C1=CC=CC=C1C(F)(F)F	2-(Trifluoromethyl)benzoic acid	110.0
CC1=CC=C(N)C=C1F	3-Fluoro-4-methylaniline	32.0
CC(C)C1=CC2=C(C=C1)C1=C(C=C2)C(C)=CC=C1	7-Isopropyl-1-methylphenanthrene	100.0
CCCCCCCCCCCCCCCCCC(=O)CCCCCCCCCCCCCCCCC	18-Pentatriacontanone	88.0
CC(=O)C1=CC=C(O)C(O)=C1O	2',3',4'-TRIHYDROXYACETOPHENONE	172.0
CC(=O)NC1=CC=CC=C1Cl	2'-chloroacetanilide	88.0
O=C1NC(=O)C=C1	MALEIMIDE	93.0
CC(=O)NC1=CC=CC=C1[N+]([O-])=O	2'-NITROACETANILIDE	93.0
COC1=CC=CC=C1OC(=O)OC1=CC=CC=C1OC	Bis(2-methoxyphenyl) carbonate	88.0
CC1=CC=CC2=C1C=CC=C2C	1,5-dimethylnaphthalene	81.0
OC(=O)COC1=CC(Cl)=CC=C1	3-CHLOROPHENOXYACETIC ACID	109.0
CCCCNC(N)=O	n-butylurea	96.0
C=CCSCC=C	DIALLYL SULFIDE	-84.0
CC1=C(N)C=CC=C1[N+]([O-])=O	2-Methyl-3-nitroaniline	91.0
CN(C)C1=CC=CC2=C1C=CC=C2S(Cl)(=O)=O	Dansyl chloride	71.0
[O-][N+](=O)C1=CC=CC2=C1N=CC=C2	8-Nitroquinoline	89.0
OC(=O)C1=C(Br)C=CC(Br)=C1	2,5-DIBROMOBENZOIC ACID	156.0
NC1=C2C=CC=NC2=CC=C1	5-Aminoquinoline	109.0
ClC1=NC2=CC=CC=C2C=C1	2-Chloroquinoline	37.0
CC1=CC=CC(=C1)C1=CC(C)=CC=C1	3,3'-DIMETHYLBIPHENYL	8.0
NC1=CC(=CC(=C1)[N+]([O-])=O)[N+]([O-])=O	3,5-dinitroaniline	162.0
OC(=O)C1=CC=C(C=O)C=C1	p-formyl_benzoic_acid	246.0
OC(=O)CC1=CC(O)=CC=C1	3-Hydroxyphenylacetic acid	131.0
NNC=O	Formic acid hydrazide	56.0
CC(C)(C)C#N	TRIMETHYLACETONITRILE	16.0
CC(C)CCC(O)=O	4-Methylvaleric acid	-34.0
CC1=CC=C(C(O)=C1)[N+]([O-])=O	5-Methyl-2-nitrophenol	54.0
CC(C)(C(O)=O)C1=CC=CC=C1	alpha,alpha-DIMETHYLPHENYLACETIC ACID	80.0
CC1=CC=C2C=CC=C(C2=N1)[N+]([O-])=O	2-Methyl-8-nitroquinoline	139.0
S(SC1=CC=CC=C1)C1=CC=CC=C1	DIPHENYL DISULFIDE	61.0
OC1=C(Cl)C=CC(Cl)=C1Cl	2,3,6-Trichlorophenol	57.0
CC1=CC(=O)C=C(C)O1	2,6-Dimethyl-4-pyrone	133.0
CNC1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C1	[5-Chloro-2-(methylamino)phenyl](phenyl)methanone	95.0
C=CN1C2=C(C=CC=C2)C2=C1C=CC=C2	9-Vinyl-9H-carbazole	64.0
CCCCCCCCCCCC[N+](C)(C)[O-]	dodecyl(dimethyl)amine oxide	132.0
CCCCCCCCCC(C)O	2-Undecanol	1.0
CCCCCCCCCCCC(C)O	2-TRIDECANOL	24.0
COC1=CC=CC(CC(O)=O)=C1	3-Methoxyphenylacetic acid	71.0
OCC1=CC(Cl)=C(Cl)C=C1	3,4-DICHLOROBENZYL ALCOHOL	37.0
CC1=CC=CC(N)=N1	2-Amino-6-methylpyridine	42.0
CCCC#CCCC	4-OCTYNE	-102.0
COC1=CC=C(O)C=C1OC	3,4-DIMETHOXYPHENOL	82.0
ClC1=CC(=CC=C1)C1=CC=CC=C1	3-chlorobiphenyl	17.0
CC(=O)NC1=C(C)C=CC=C1C	2',6'-Dimethylacetanilide	182.0
ClC1=CC=CC(Cl)=N1	2,6-Dichloropyridine	87.0
CCCCCCCCOC1=CC=C(C=C1)C(O)=O	4-n-Octyloxybenzoic acid	102.0
OC1=CC=C(SC2=CC=C(O)C=C2)C=C1	4,4'-Thiodiphenol	154.0
CCCCCCCCCCCCCCCCCCS	1-OCTADECANETHIOL	31.0
CCCCCCCCCCCCCCCCS	1-HEXADECANETHIOL	20.0
OC(=O)C1=C(O)C(Br)=CC(Br)=C1	3,5-DIBROMOSALICYLIC ACID	227.0
OC(=O)C1=CC(Cl)=C(O)C=C1	3-CHLORO-4-HYDROXYBENZOIC ACID	170.0
CC1=C(Br)C=C(Br)C(O)=C1Br	2,4,6-Tribromo-3-methylphenol	83.0
NNC(=O)C1=CC=C(N)C=C1	4-Aminobenzhydrazide	227.0
NNC(=O)C1=CC=C(Br)C=C1	4-Bromobenzhydrazide	167.0
O=C(C1=CC=CC=C1)C1=CC=NC=C1	4-Benzoylpyridine	71.0
O=C=NC1=CC(=CC=C1)N=C=O	1,3-Phenylene diisocyanate	49.0
ClN1C(=O)CCC1=O	N-CHLOROSUCCINIMIDE	149.0
CC(=O)NC1=CC=C(C=C1)C#N	4'-Cyanoacetanilide	206.0
ClC1=C(Cl)C(Br)=CC=C1	1-BROMO-2,3-DICHLOROBENZENE	59.0
BrCC(Br)(CCC#N)C#N	1,2-Dibromo-2,4-dicyanobutane	51.0
SC1=CC=C(Br)C=C1	4-Bromothiophenol	74.0
CCC(=O)C1=CC=C(Br)C=C1	4'-Bromopropiophenone	47.0
BrC1=CC=C(Br)C2=CC=CC=C12	1,4-Dibromonaphthalene	82.0
ClC1=CC=C(C=C1)C(=O)C1=CC=CC=C1Cl	2,4'-Dichlorobenzophenone	66.0
O=C(OC1=CC(OC(=O)C2=CC=CC=C2)=CC=C1)C1=CC=CC=C1	1,3-Dibenzoyloxybenzene	117.0
OC1=CC(O)=C(Cl)C=C1Cl	4,6-Dichlororesorcinol	114.0
OC(=O)C1=C(F)C=CC=C1Cl	2-Chloro-6-fluorobenzoic acid	159.0
NC(=O)C1=CC=CC=C1F	2-FLUOROBENZAMIDE	117.0
CC1=CC(N)=NC(C)=N1	4-Amino-2,6-dimethylpyrimidine	184.0
ClC(=O)C1=CC=C(Br)C=C1	4-Bromobenzoyl chloride	41.0
CC1=CC=C(C=C1)S(=O)(=O)C1=CC=C(C)C=C1	Di-p-tolyl sulfone	158.0
OC(=O)C1=C(C(O)=O)C(=CC=C1)[N+]([O-])=O	3-NITROPHTHALIC ACID	211.0
[O-][N+](=O)C1=CC=CC2=C1C=CN=C2	5-Nitroisoquinoline	109.0
CCOC(=O)C1=CC=CC=C1[N+]([O-])=O	Ethyl 2-nitrobenzoate	29.0
OC1=CC=NC2=CC=CC=C12	4-Hydroxyquinoline	202.0
OCC1=CC=CC=C1CO	1,2-Benzenedimethanol	63.0
COC(=O)CC(=C)C(=O)OC	Dimethyl itaconate	37.0
CCOC(=O)C1=CC(=CC(=C1)[N+]([O-])=O)[N+]([O-])=O	Ethyl 3,5-dinitrobenzoate	93.0
BrCC1=CC(CBr)=CC=C1	m-Xylylene dibromide	76.0
CCCCCCCCCCCCCCCCCC(C)=O	2-NONADECANONE	56.0
OC(=O)COC1=CC=CC=C1C(O)=O	2-(Carboxymethoxy)benzoic acid	190.0
CCCCCCCCCCCCCC(N)=O	n-tetradecanamide	105.0
CC(=O)C1=CC=C2C=CC=CC2=C1O	2-Acetyl-1-naphthol	100.0
OCC1=CC=C(Br)C=C1	p-Bromobenzyl alcohol	77.0
CC1=NNC(=O)NC1=O	6-AZATHYMINE	212.0
ClC1=CC2=C(C=C1Cl)C(=O)OC2=O	5,6-dichlor-2-benzofuran-1,3-dion	187.0
CC(C)(C)C1=CC=C(O)C(N)=C1	2-Amino-4-tert-butylphenol	162.0
C1=CC=C(C=C1)C1=C2C=CC3=C(C=CN=C3C2=NC=C1)C1=CC=CC=C1	4,7-Diphenyl-1,10-phenanthroline	219.0
CCOC1=CC=C(C=C1)C(C)=O	4'-Ethoxyacetophenone	38.0
CC(C)(C)C1=CC(C=O)=CC(=C1O)C(C)(C)C	3,5-Di-tert-butyl-4-hydroxybenzaldehyde	187.0
OC1=CC=C(C=C1)C(C1=CC=C(O)C=C1)(C(F)(F)F)C(F)(F)F	4,4'-(Hexafluoroisopropylidene)diphenol	161.0
[O-][N+](=O)C1=CC=CC=C1F	1-Fluoro-2-nitrobenzene	-7.0
C(P(C1=CC=CC=C1)C1=CC=CC=C1)P(C1=CC=CC=C1)C1=CC=CC=C1	Bis(diphenylphosphino)methane	120.0
OC1=CC=CC2=C1C=CN2	4-HYDROXYINDOLE	99.0
NC1=C(Cl)C=CC(=C1)C(O)=O	3-Amino-4-chlorobenzoic Acid	215.0
CC1=C(OC(=N1)C1=CC=C(C=C1)C1=NC(C)=C(O1)C1=CC=CC=C1)C1=CC=CC=C1	2,2'-(1,4-Phenylene)bis(4-methyl-5-phenyl-1,3-oxazole)	233.0
BrC1=CC(Br)=C(Br)S1	2,3,5-Tribromothiophene	28.0
C(N1C=CN=C1)C1=CC=CC=C1	1-Benzylimidazole	70.0
COC1=CC=CC(=C1C)[N+]([O-])=O	2-Methyl-3-nitroanisole	54.0
COC(=O)C1=CC(Cl)=CC=C1N	Methyl 2-amino-5-chlorobenzoate	68.0
COC1=CC=CC(=C1)C(=O)NN	3-Methoxybenzhydrazide	93.0
NC1=CC=CC(CO)=C1	3-Aminobenzyl alcohol	94.0
ClC1=CC(=CC(Cl)=C1)C#N	3,5-Dichlorobenzonitrile	65.0
ClS(=O)(=O)C1=CC=CS1	Thiophene-2-sulfonyl chloride	29.0
OC1C(O)C2CCC1C2	exo-2-endo-3-norbornanediol	140.0
OC1(CCCC1)C#C	1-Ethynylcyclopentanol	26.0
OCC1C2=CC=CC=C2C2=CC=CC=C12	9-Fluorenylmethanol	105.0
FC(F)(F)C1=CN=C(Cl)C=C1	2-Chloro-5-(trifluoromethyl)pyridine	32.0
CCOC(=O)C(=CC1=CC=CC=C1)C(=O)OCC	Diethyl benzylidenemalonate	31.0
CC1=NN=C(C)S1	2,5-Dimethyl-1,3,4-thiadiazole	64.0
CC(C)C(O)C(C)(C)C	2,2,4-TRIMETHYL-3-PENTANOL	-12.0
CCN1CCNC(=O)C1=O	1-Ethylpiperazine-2,3-dione	109.0
OC1=C(C=C(F)C=C1)[N+]([O-])=O	4-fluoro-2-nitrophenol	74.0
O=C(CCC(=O)C1=CC=CC=C1)C1=CC=CC=C1	1,2-Dibenzoylethane	145.0
OC(=O)CCCC[C@@H]1SC[C@@H]2NC(=O)N[C@H]12	d-biotin	231.0
[O-][N+](=O)C1=CC2=C(COC2=O)C=C1	6-Nitrophthalide	144.0
IC1=CC=CC(C=O)=C1	3-iodobenzaldehyde	57.0
CC(C)(C)C1=CC=C2OC(=NC2=C1)C1=CC=C(S1)C1=NC2=CC(=CC=C2O1)C(C)(C)C	2,2'-thiene-2,5-diylbis(5-tert-butyl-1,3-benzoxazole)	200.0
CCOC(=O)C1=CSC(C)=N1	Ethyl 2-methylthiazole-4-carboxylate	56.0
O=C1CC2=CC=CC=C2N1	OXINDOLE	127.0
CCCC#CC(O)=O	2-Hexynoic acid	26.0
OC(=O)C1=C(F)C(F)=CC=C1	2,3-Difluorobenzoic Acid	163.0
CC1(C)[C@H]2CC[C@]1(C)C(=O)C2	(1s)-camphor	179.0
O[C@H]([C@@H](O)C(O)=O)C(O)=O	(2R,3R)-2,3-dihydroxysuccinic acid	170.0
OC(=O)C1=C(F)C=C(F)C=C1F	2,4,6-Trifluorobenzoic Acid	142.0
NNC(=O)C1=CC(Br)=CC=C1	3-Bromobenzhydrazide	157.0
OC(=O)C1=CC(F)=C(F)C=C1F	2,4,5-Trifluorobenzoic Acid	99.0
FC1=C(F)C(C#N)=C(F)C(C#N)=C1F	2,4,5,6-Tetrafluoroisophthalonitrile	78.0
COC1=CC(\C=C\CO)=CC=C1O	CONIFERYL ALCOHOL	75.0
CCCCNC(=S)NCCCC	N,N'-di-n-Butylthiourea	65.0
CCCOC1CCC2C3C(CCC12C)C1(C)CCC(CC1CC3=O)OCCC	3,17-dipropoxyandrostan-7-one	162.0
OC[C@@H](O)[C@@H](O)[C@@H](O)C=O	D-Ribose	83.0
ON=CC1=CC=C(C=C1)[N+]([O-])=O	Benzaldehyde, 4-nitro-, oxime	129.0
O\N=C\C(=O)C1=CC=CC=C1	Isonitrosoacetophenone	128.0
CC1=CC=C(NC(=O)C2=CC=CC=C2)C=C1	N-p-Tolyl-benzamide	157.0
OC1=CC=C2C=CC=CC2=C1\N=N\C1=CC=CC=C1	1-[(E)-phenyldiazenyl]-2-naphthol	133.0
OCCCCCO	1,5-PENTANEDIOL	-17.0
C1=CC=C(N=C1)C1=CC=CC=N1	2,2'-BIPYRIDINE	71.0
CC(=O)C1C(=O)OC(C)=CC1=O	DEHYDROACETIC ACID	110.0
CCCCCCCCCCCCCCCCCC(=O)OC[C@@H](O)[C@H]1OC[C@H](O)[C@H]1O	1,4-anhydro-6-O-stearoyl-D-glucitol	56.0
C1=CC(=CC=N1)C1=CC=NC=C1	4,4'-Bipyridine	112.0
C1=CC=C2N=CC=NC2=C1	Quinoxaline	29.0
[O-][N+](=O)C1=CC(Br)=CC=C1	M-BROMONITROBENZENE	55.0
ClC1=CC(C=O)=C(Cl)C=C1	2,5-Dichlorobenzaldehyde	57.0
[O-][N+](=O)C1=CC=CC(=C1Cl)[N+]([O-])=O	2-Chloro-1,3-dinitrobenzene	87.0
ClC1CC2C(C1Cl)C1(Cl)C(Cl)=C(Cl)C2(Cl)C1(Cl)Cl	b-Chlordane, trans-Chlordane	105.0
OC(=O)C1=C(O)C(O)=CC=C1	2,3-DIHYDROXYBENZOIC ACID	205.0
OC1=CC(Cl)=CC=C1Cl	2,5-Dichlorophenol	58.0
OCC1=CC(O)=CC=C1	3-hydroxybenzyl_alcohol	72.0
OC(=O)CCCCCC(O)=O	pimelic acid	105.0
OC(=O)C1=CC(Cl)=CC=C1	m-chlorobenzoic_acid	157.0
OC(CC(O)=O)C(O)=O	malic acid	131.0
OC1=CC=CC2=C1N=CC=C2	quinolin-8-ol	75.0
CC(=O)NC1=NN=C(S1)S(N)(=O)=O	Acetazolamide	260.0
CN1N(C(=O)C(N)=C1C)C1=CC=CC=C1	4-amino-1,5-dimethyl-2-phenyl-1,2-dihydro-3H-pyrazol-3-one	108.0
OC1=CC=CC2=C1C(=O)C1=C(O)C=CC=C1C2	1,8-Dihydroxyanthracen-9(10H)-one	180.0
CC(C)(C)C1=CC(O)=C(C=C1O)C(C)(C)C	2,5-Di-tert-butylbenzene-1,4-diol	217.0
OCC1=CC=CC=C1O	2-hydroxybenzyl_alcohol	86.0
OC(=O)C1=CC(Cl)=CC(Cl)=C1	3,5-dichlorobenzoic_acid	187.0
ClC(Cl)Br	bromodichloromethane	-56.0
CC(C)CBr	1-bromo-2-methylpropane	-118.0
CC(C)CN	Isobutylamine	-86.0
ClCC(Cl)Cl	1,1,2-trichloroethane	-36.0
COC1=CC=CC=C1C1=CC=CC=C1	2-Methoxybiphenyl	30.0
CC(=O)NC1=CC=CC=C1C(O)=O	n-acetylanthranilic_acid	185.0
OC1=C(C=C(Cl)C=C1)[N+]([O-])=O	4-chloro-2-nitrophenol	88.0
O=C1C2=CC=CC=C2CC2=CC=CC=C12	anthracen-9(10H)-one	156.0
CC(=O)C1=CC=C(C=C1)C1=CC=CC=C1	4-ACETYLBIPHENYL	121.0
COC1=CC=C2C=CC=CC2=C1	2-METHOXYNAPHTHALENE	73.0
OC(=O)C1=NC2=CC=CC=C2C=C1	QUINALDIC ACID	157.0
S1C=CC2=CC=CC=C12	Benzo[b]thiophene	31.0
CC1=C(N)C=C(N)C=C1	2,4-Diaminotoluene	98.0
CC(C)(C)C1=CC=C(O)C(=C1)C(C)(C)C	2,4-Di-tert-butylphenol	55.5
NS(=O)(=O)C1=CC=CC=C1	benzenesulfonamide	152.0
NC1=CC=CC(=C1)C(O)=O	m-aminobenzoic_acid	174.0
CC1=CC=C(C=C1N)[N+]([O-])=O	2-Methyl-5-nitroaniline	106.0
BrCC(=O)C1=CC=C(Br)C=C1	2-Bromo-1-(4-bromophenyl)ethanone	110.0
O(P(OC1=CC=CC=C1)OC1=CC=CC=C1)C1=CC=CC=C1	TRIPHENYL PHOSPHITE	24.0
CCCCCCCCCCCCCCCCC=C	1-OCTADECENE	17.0
OC(=O)C1=CC=CC=C1C=O	o-formyl_benzoic_acid	98.0
[O-][N+](=O)C1=CC=C(C=C1)C(Cl)=O	4-Nitrobenzoyl chloride	74.0
OC1=CC=C(C=O)C=C1O	3,4-Dihydroxybenzaldehyde	154.0
C1=CN=CC=N1	Pyrazine	54.0
CN[C@@H](C)[C@H](O)C1=CC=CC=C1	(1R,2S)-2-(methylamino)-1-phenylpropan-1-ol	35.0
O=C1CNC(=O)N1	hydantoin	221.0
CC1=CC(C)=C(C(O)=O)C(C)=C1	2,4,6-Trimethylbenzoic acid	153.0
CC1=CC(S)=C(S)C=C1	4-methylbenzene-1,2-dithiol	30.0
S=C=NC1=C2C=CC=CC2=CC=C1	1-ISOTHIOCYANATONAPHTHALENE	57.0
CC(=O)C1=CC=C(C=C1)C(O)=O	4-acetylbenzoic_acid	209.0
OC1=CC(Cl)=CC(Cl)=C1	3,5-Dichlorophenol	67.0
CC1=C(O)C=CC=C1O	2-Methylresorcinol	119.0
CC1=CC=C(C)C(=C1)C(O)=O	2,5-DIMETHYLBENZOIC ACID	133.0
OCC1=CC=CC=C1[N+]([O-])=O	2-nitrobenzyl_alcohol	73.0
NC1=C(Br)C=C(Br)C=C1	2,4-DIBROMOANILINE	79.0
[O-][N+](=O)C1=CC(CCl)=CC=C1	3-nitrobenzyl_chloride	46.0
COC(=O)C1=CC=C(Br)C=C1	Methyl 4-bromobenzoate	80.0
CC(=O)NC1=CC(O)=CC=C1	3-acetamidophenol	147.0
NC1=CC(Cl)=CC(Cl)=C1	3,5-Dichloroaniline	52.0
CCCCCCCBr	1-bromoheptane	-57.0
CCCCCCCCI	1-IODOOCTANE	-45.0
CCCCCCCCCCCCCCCCCCCCC	Henicosane	40.0
ClC1=CC=C(C=O)C(Cl)=C1	2,4-dichlorobenzaldehyde	72.0
C1CCC2=C(C1)NC1=CC=CC=C21	1,2,3,4-Tetrahydrocarbazole	119.0
N#CC1=C2C=CC=CC2=CC2=CC=CC=C12	anthracene-9-carbonitrile	176.0
IC1=CC=C(C=C1)C1=CC=CC=C1	4-IODOBIPHENYL	113.0
NC1=CC=C2C=CC3=CC=CC4=CC=C1C2=C34	pyren-1-amine	117.0
OC1CCCCCCCCCCC1	CYCLODODECANOL	77.0
CCCCCCCCCCC(C)=O	2-dodecanone	20.0
CC1=CC(N)=CC=C1Br	4-BROMO-3-METHYLANILINE	80.0
OC1=CC=C(CC#N)C=C1	4-hydroxybenzyl_cyanide	70.0
ClC(Br)Br	chlorodibromomethane	-21.0
CC1=CC=CC(Cl)=C1Cl	2,3-DICHLOROTOLUENE	5.0
OCCCCCCCCCCO	Decane-1,10-diol	73.0
O=C(OC1=CC=C2C=CC=CC2=C1)C1=CC=CC=C1	2-Naphthyl benzoate	106.0
CC(C)(C)C1=CC=C(N)C=C1	4-tert-Butylaniline	16.0
CC1=CN=CN=C1	5-Methylpyrimidine	31.0
ClCC(CCl)(CCl)CCl	pentaerythrityl_tetrachloride	96.0
CC1=CC=C(C=C1Br)[N+]([O-])=O	2-Bromo-4-nitrotoluene	77.0
CC(Br)C(Br)C(O)=O	2,3-Dibromobutyric acid	86.0
COC1=CC=CC=C1C1=CC=CC=C1OC	2,2'-Dimethoxybiphenyl	155.0
SC1=NC2=C(S1)C=CC=C2	1,3-Benzothiazole-2-thiol	180.0
CC(=O)NC1=CC=C(Cl)C=C1F	4'-Chloro-2'-fluoroacetanilide	156.0
SC1=CC=CC=N1	Pyridine-2-thiol	128.0
NC1=CC=C(C=C1N)[N+]([O-])=O	4-nitrobenzene-1,2-diamine	200.0
CC(=O)O[C@@H]1C2=C(C)[C@H](C[C@@](O)([C@@H](OC(=O)C3=CC=CC=C3)[C@@H]3[C@@]4(CO[C@@H]4C[C@H](O)[C@@]3(C)C1=O)OC(C)=O)C2(C)C)OC(=O)[C@H](O)[C@@H](NC(=O)C1=CC=CC=C1)C1=CC=CC=C1	(2alpha,5beta,7beta,10beta,13alpha)-4,10-diacetoxy-13-{[(2r,3s)-3-(benzoylamino)-2-hydroxy-3-phenylpropanoyl]oxy}-1,7-dihydroxy-9-oxo-5,20-epoxytax-11-en-2-yl benzoate	216.0
CCOC(=O)CCCCC(=O)OCC	diethyl_adipate	-19.0
CC(=O)C1=CC=C(Cl)C=C1	4'-Chloroacetophenone	19.0
O=C1C2=CC=CC=C2C(=O)C2=CC=CC=C12	anthraquinone	285.0
NC1=CC(N)=CC=C1	m-Phenylenediamine	64.0
ClCC1=CC=CC=C1	benzyl_chloride	-44.0
[O-][N+](=O)C1=CC=C(F)C=C1	1-Fluoro-4-nitrobenzene	22.0
ClC(Cl)(Cl)C#N	Trichloroacetonitrile	-43.0
CC1=CC(C)=C(Br)C=C1C	5-Bromo-1,2,4-trimethylbenzene	72.0
N#CCC#N	MALONONITRILE	33.0
COC1=CC=C(CO)C=C1	4-methoxybenzyl_alcohol	25.0
NC1=C(Br)C=C(Br)C=C1Br	2,4,6-TRIBROMOANILINE	121.0
FC(F)(F)C(=O)OC(=O)C(F)(F)F	Trifluoroacetic anhydride	-64.0
N#CCCC#N	SUCCINONITRILE	55.0
CCOC1=CC=C(OCC)C=C1	1,4-Diethoxybenzene	71.0
NC1=CC=CC(Cl)=C1Cl	2,3-DICHLOROANILINE	23.0
BrC1=CC=CC=C1C=O	o-Bromobenzaldehyde	21.0
COC1=CC=C(C=C1OC)C(C)=O	3,4-DIMETHOXYACETOPHENONE	50.0
CC(N)=O	acetamide	80.0
CC1=CC=CC=C1	Toluene	-94.0
ClC1=CC=CC(Cl)=C1C#N	2,6-dichlorobenzonitrile	144.0
CC(C)O	2-Propanol	-89.0
NC1=CC=CC=C1O	o-Aminophenol	175.0
ClCCl	Dichloromethane	-96.0
CC1(C)C2CCC(C2)C1=C	2,2-Dimethyl-3-methylenebicyclo[2.2.1]heptane	51.0
NC1=CC=C(Cl)C=C1[N+]([O-])=O	4-CHLORO-2-NITROANILINE	117.0
CC1=CC=C(C=C1C)[N+]([O-])=O	1,2-Dimethyl-4-nitrobenzene	30.0
[O-][N+](=O)C1=CC=C(CCl)C=C1	1-(Chloromethyl)-4-nitrobenzene	72.0
CCCCC(=O)CC	Heptan-3-one	-38.0
CCCCNCCCC	N-butylbutan-1-amine	-61.0
CCCCCCCCCCCCO	Dodecan-1-ol	25.0
C1CCCCCCCCCCC1	CYCLODODECANE	60.0
OC1=CC=C(I)C=C1	4-Iodophenol	93.0
COC1=CC=CC=C1C(O)=O	o-anisic_acid	100.0
NC1=CC=CC(O)=C1	3-aminophenol	124.0
N#CC1=CC=C(C=C1)C#N	Terephthalonitrile	225.0
O=CC1=CC=C(C=O)C=C1	Terephthaldicarboxaldehyde	116.0
COC(=O)C1=CC(OC)=C(OC)C(OC)=C1	methyl_3,4,5-trimethoxybenzoate	84.0
CC(C)[C@@H]1CC[C@@H](C)C[C@H]1O	(1R,2S,5R)-2-Isopropyl-5-methylcyclohexanol	43.0
ClC1=CC(Cl)=C(Cl)C=C1C1=CC=CC=C1	2,4,5-TRICHLOROBIPHENYL	77.0
COC(=O)C1=CC=CC(=C1)[N+]([O-])=O	Methyl 3-nitrobenzoate	79.0
CC(=O)C1=CC=C(C=C1)C#N	4-acetylbenzonitrile	58.0
NC1=CC=C(CC#N)C=C1	4-aminobenzyl_cyanide	45.0
COC1=CC=C(\C=C\C)C=C1	1-methoxy-4-[(1E)-prop-1-en-1-yl]benzene	22.0
CCOC(=O)\C=C\C(=O)OCC	diethyl (2E)-but-2-enedioate	1.0
OC1=CC=CC(O)=C1O	benzene-1,2,3-triol	133.0
CC(C)(C)C1=CC=C(O)C=C1	4-tert-Butylphenol	99.0
OCCOC1=CC=CC=C1	2-phenoxyethanol	13.0
COC(=O)C1=CC=CC=C1O	methyl salicylate	-8.0
BrCC1=CC=CC=C1	(Bromomethyl)benzene	-3.0
NC1=CC=CC=C1[N+]([O-])=O	2-nitroaniline	72.0
[O-][N+](=O)C1=CC=CC=C1Cl	1-Chloro-2-nitrobenzene	33.0
CCOC(=O)CC(C)=O	ethyl 3-oxobutanoate	-44.0
COC1=CC=C(N)C=C1	4-METHOXYANILINE	58.0
NC1=CC(Cl)=CC=C1Cl	2,5-Dichloroaniline	49.0
COC1=CC=C(C=O)C=C1	p-Anisaldehyde	0.0
CCOC(=O)C1=CC=CC=C1N	Ethyl 2-aminobenzoate	14.0
CC(=O)\C=C\C1=CC=CC=C1	trans-4-Phenyl-3-buten-2-one	41.0
C1=CC=C(C=C1)N=NC1=CC=CC=C1	(E)-Diphenyldiazene	68.0
OC1=NC=C(F)C(O)=N1	5-fluorouracil	282.0
CCCCC1C(=O)N(N(C1=O)C1=CC=CC=C1)C1=CC=CC=C1	Phenylbutazone	106.0
NC1=CC=C(C=C1)S(=O)(=O)NC1=CC=CC=N1	sulfapyridine	191.0
CN(C)C(=O)NC1=CC=CC=C1	fenuron	133.0
CCCCCCCCCCC=C	Dodec-1-ene	-36.0
OC(=O)C1=CC=CC=C1[N+]([O-])=O	2-NITROBENZOIC ACID	147.0
[O-][N+](=O)C1=CC=CC=C1CC#N	(2-Nitrophenyl)acetonitrile	83.0
COC(=O)\C=C\C(=O)OC	dimethyl (2E)-but-2-enedioate	103.0
CC1=CC=C(C)C(O)=C1	2,5-Dimethylphenol	75.0
OC1=CC=C(C=C1)C1=CC=CC=C1	Biphenyl-4-ol	166.0
COC1=CC2=C(C=C1)N(C(=O)C1=CC=C(Cl)C=C1)C(C)=C2CC(O)=O	Indomethacin	159.0
OC1=CC(Cl)=C(Cl)C=C1	3,4-Dichlorophenol	67.0
COC1=CC=C(O)C=C1	4-Methoxyphenol	56.0
OC(=O)C1=CC(Br)=CC=C1	3-Bromobenzoic Acid	156.0
N(C1=CC=CC=C1)C1=CC=CC=C1	diphenylamine	53.0
BrC1=CC(Br)=CC(Br)=C1	1,3,5-Tribromobenzene	123.0
OC(=O)\C=C\C1=CC=CC=C1	(2E)-3-phenylacrylic acid	134.0
OC1=CC(Cl)=CC=C1	3-Chlorophenol	33.0
CCC1(C(=O)NC(=O)NC1=O)C1=CC=CC=C1	Phenobarbital	175.0
NC(=O)C1=CC=CC=C1O	salicylamide	141.0
C1=CC=C(C=C1)C1=CC=CC=C1	biphenyl	70.0
OC1=CC=CC=C1[N+]([O-])=O	2-nitrophenol	45.0
C1=CC=C2C(C=CC3=CC=CC=C23)=C1	Phenanthrene	100.0
CCCCCCCCCCCCCCCCCCCCO	1-EICOSANOL	65.0
CC1(C)C(CCC1(C)C(O)=O)C(O)=O	Camphoric acid	188.0
BrC1=CC=CC=C1Br	1,2-dibromobenzene	6.05
FC(F)(F)C1=CC=CC=C1	(Trifluoromethyl)benzene	-28.1
O=CC1=CC=CO1	2-Furaldehyde	-37.0
CCCCCC(O)=O	HEXANOIC ACID	-2.95
CCCCCCCC=C	1-Nonene	-82.1
NC(=O)C1=CC=CC2=CC=CC=C12	naphthalene-1-carboxamide	207.0
C=C(C1=CC=CC=C1)C1=CC=CC=C1	1,1-DIPHENYLETHYLENE	7.1
CC=CC1=CC=CC=C1	trans-1-Phenyl-1-propene	-28.2
CCOC(=O)C=CC(=O)OCC	diethyl (2Z)-but-2-enedioate	-9.9
OCCOCCOCCOCCO	2,2'-[oxybis(ethane-2,1-diyloxy)]diethanol	-5.1
OC1=CC=CC=CC1=O	Tropolone	51.9
FC1=CC=CC=C1	fluorobenzene	-41.1
OC1=C(F)C(F)=C(F)C(F)=C1F	Pentafluorophenol	33.9
CCCCCCCCCCCCCCCCCCCCCCCCCCCCC	NONACOSANE	64.8
COC(=O)C(=O)OC	dimethyl_oxalate	53.1
CC1=CC=C(C(=C1)[N+]([O-])=O)[N+]([O-])=O	3,4-dinitrotoluene	57.1
CCC(=O)C1=CC=C(Cl)C=C1	4'-Chloropropiophenone	36.1
NC1=CC=CC(=C1)C#N	3-Aminobenzonitrile	53.1
CC(C)C1=CC=C(O)C=C1	4-isopropylphenol	61.1
CC(C)C(=O)C1=CC=CC=C1	Isobutyrophenone	-0.15
C1CCC(CC1)C1=CC=CC=C1	Cyclohexylbenzene	6.15
CCCCCCCCC(O)=O	NONANOIC ACID	11.2
COC(=O)CCCCC(=O)OC	Dimethyl adipate	9.15
COC1=CC(=CC(OC)=C1OC)C(O)=O	3,4,5-TRIMETHOXYBENZOIC ACID	171.0
ClC1=CC=CC(Cl)=C1Cl	1,2,3-trichlorobenzene	53.8
CC1=CC(C)=CN=C1	3,5-Lutidine	-7.8
C(C1=CC=CC=C1)C1=CC=NC=C1	4-Benzylpyridine	11.2
CC\C=C\CC	trans-3-Hexene	-114.0
CC1=CC=C(C=C1)C(O)=O	4-Methylbenzoic acid	181.0
CC(=O)NO	acetohydroxamic acid	89.2
CC1(C)OC(=O)NC1=O	5,5-Dimethyloxazolidine-2,4-dione	77.8
OC1=C(CC2=C(Cl)C(Cl)=CC(Cl)=C2O)C(Cl)=C(Cl)C=C1Cl	2,2'-Methylenebis(3,4,6-trichlorophenol)	165.0
OC[C@H]1O[C@@](CO)(O[C@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)[C@@H](O)[C@@H]1O	sucrose	187.0
Cl[Si](C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	Chlorotriphenylsilane	92.8
ClC1=CC=C(C=C1)C(=O)C1=CC=C(Cl)C=C1	4,4'-Dichlorobenzophenone	146.0
OC(=O)C1=CC2=CC=CC=C2C=C1O	3-Hydroxy-2-naphthoic acid	221.0
OC(=O)C1=C(O)C=CC(=C1)[N+]([O-])=O	5-Nitrosalicylic acid	231.0
CC(C)C(=O)OC(=O)C(C)C	Isobutyric anhydride	-54.8
ClC(=O)C1=CC=C(C=C1)C(Cl)=O	Terephthaloyl chloride	82.2
N(C(NC1=CC=CC=C1)=NC1=CC=CC=C1)C1=CC=CC=C1	N,N',N''-Triphenylguanidine	145.0
O=NN1CN2CN(C1)CN(C2)N=O	3,7-dinitroso-1,3,5,7-tetraazabicyclo[3.3.1]nonane	206.0
NC1=CC=C(CC2=CC=C(N)C=C2)C=C1	4,4'-DIAMINODIPHENYLMETHANE	91.2
C(C1=CC=CC=C1)C1=CC=CC=N1	2-Benzylpyridine	11.2
NC1=NC=CC=N1	2-Aminopyrimidine	126.0
CC(O)CNCC(C)O	DIISOPROPANOLAMINE	43.2
CC1=CC=C(O)C(=C1)[N+]([O-])=O	4-methyl-2-nitrophenol	35.2
O1C2=CC=CC=C2SC2=CC=CC=C12	Phenoxathiine	58.2
OC(=O)C1=CC=CC=C1F	2-FLUOROBENZOIC ACID	125.0
O=C1CCCC(=O)C1	1,3-Cyclohexanedione	104.0
OC(C(=O)C1=CC=CO1)C1=CC=CO1	2,2'-Furoin	137.0
COC1=CC=C(Cl)C=C1Cl	2,4-Dichloroanisole	27.2
NC1=CC2=CC=CC=C2N=C1	3-aminoquinoline	92.8
O=C1CCC(=O)N1	succinimide	125.0
OC(=O)CCBr	3-Bromopropionic acid	61.2
[O-][N+](=O)C1=CC=CS1	2-NITROTHIOPHENE	45.2
CC1=CC2=C(C=CC=N2)C=C1	7-methylquinoline	37.8
CCNC(=O)NCC	N,N'-Diethylurea	111.0
CCCCCCCCCCCCCCCCCCCCCCCCCCCC	n-Octacosane	63.2
CCCCCCCCCCCCCCCCCCCCCCO	docosan-1-ol	71.2
O=C1CCCCN1	DELTA-VALEROLACTAM	38.2
C(SC1=CC=CC=C1)C1=CC=CC=C1	BENZYL PHENYL SULFIDE	42.2
OC1CCCCC1O	1,2-CYCLOHEXANEDIOL-CIS	101.0
CC1=CC=CN=C1N	2-Amino-3-methylpyridine	32.2
BrC1=CC=C(C=C1)N=C=S	4-Bromophenyl isothiocyanate	59.2
CC(=O)CC(C)(C)NC(=O)C=C	Diacetone Acrylamide	56.2
CC1(C)CC(C)(C2=CC=CC=C12)C1=CC=CC=C1	1,3,3-Trimethyl-1-phenylindan	51.2
CC(C)(CC(O)=O)CC(O)=O	3,3-DIMETHYLGLUTARIC ACID	102.0
COC1=CC=C(N)C=C1Cl	3-Chloro-p-anisidine	51.2
ClC1=C(Cl)C(Cl)=C(Cl)S1	Tetrachlorothiophene	29.2
CC1=C(C2=C(C=C1)C(=O)C1=CC=CC=C1C2=O)[N+]([O-])=O	2-methyl-1-nitro-9,10-anthraquinone	269.0
OCC1=CC(Cl)=CC(Cl)=C1	3,5-DICHLOROBENZYL ALCOHOL	79.2
ClC(=O)CCCCCCCCC(Cl)=O	Sebacoyl chloride	-3.75
CN(C)CC1=CC(=C(O)C(=C1)C(C)(C)C)C(C)(C)C	2,6-di-tert-Butyl-4-(dimethylaminomethyl)phenol	92.2
C1CNCCNC1	Homopiperazine	42.2
CC1=CC=C(C=C1)C(=O)C1=CC=C(C)C=C1	4,4'-Dimethylbenzophenone	95.2
CNC(=O)NC(C)=O	n-(methylcarbamoyl)acetamid	179.0
COC1=CC=C(C=C1)C(=O)OC(=O)C1=CC=C(OC)C=C1	4-Methoxybenzoic anhydride	95.8
COC(=O)C1=CC2=C(C=CC=C2)C=C1O	Methyl 3-hydroxy-2-naphthoate	74.2
[O-][N+](=O)C1=CC=CC=C1SSC1=CC=CC=C1[N+]([O-])=O	Bis(2-nitrophenyl) disulfide	195.0
CC(=C)C1=CC=C(C=C1)C(C)=C	p-Diisopropenylbenzene	64.8
BrC1=C(Br)C(Br)=C(Br)S1	Tetrabromothiophene	116.0
CC(=O)O[Si](C)(OC(C)=O)OC(C)=O	Triacetoxy(methyl)silane	41.8
ClC1=CN=CC(Cl)=N1	2,6-Dichloropyrazine	55.2
COC1=CC=C(C(OC)=C1)[N+]([O-])=O	2,4-dimethoxy-1-nitrobenzene	75.2
C[C@H](NC(=O)OC(C)(C)C)C(O)=O	boc-alanine	80.8
[O-][N+](=O)C1=CC(Cl)=C(Cl)C(Cl)=C1	1,2,3-trichloro-5-nitrobenzene	71.2
NC1=CC2=C(CCC2)C=C1	5-aminoindane	36.2
COC(C(=O)C1=CC=CC=C1)C1=CC=CC=C1	benzoin_methyl_ether	48.2
CC(=O)OC[C@H]1O[C@H](Br)[C@H](OC(C)=O)[C@@H](OC(C)=O)[C@@H]1OC(C)=O	2-O-Acetyl-3-O-bromo-D-glucose	88.2
OCC1=CC=C(O1)C=O	5-Hydroxymethyl-2-furaldehyde	32.8
C[Si](C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	methyltriphenylsilane	68.2
COC1=CC=C(OC)C(N)=C1	2,5-DIMETHOXYANILINE	81.2
NC1=CC(Cl)=C(Cl)C=C1Cl	2,4,5-Trichloroaniline	95.2
BrCC1=CC=C(CBr)C=C1	1,4-Bis(bromomethyl)benzene	143.0
OC(=O)COC1=CC=C(Cl)C=C1Cl	(2,4-dichlorophenoxy)acetic acid	139.0
NC(=O)C1=CC(N)=CC=C1	m-aminobenzamide	114.0
COC1=CC=CC=C1OCC(O)CO	3-(2-Methoxyphenoxy)-1,2-propanediol	79.8
C1CCN2N=NN=C2CC1	6,7,8,9-Tetrahydro-5H-tetrazolo[1,5-a]azepine	58.8
CCOS(=O)(=O)C1=CC=C(C)C=C1	ethyl_p-toluenesulfonate	33.2
CC1=CNC2=CC=CC=C12	3-Methyl-1H-indole	95.0
COC1=CC=CC(OC)=C1O	2,6-Dimethoxyphenol	55.2
CC(=O)C1=CC=C(O)C=C1	4-hydroxyacetophenone	108.0
COC1=CC(=CC=C1O)C(O)=O	4-HYDROXY-3-METHOXYBENZOIC ACID	213.0
CN(C)C1=CC=C(C=C1)\N=N\C1=CC=CC=C1C(O)=O	2-{(E)-[4-(dimethylamino)phenyl]diazenyl}benzoic acid	182.0
COC1=CC(=CC(OC)=C1O)C(O)=O	4-Hydroxy-3,5-dimethoxybenzoic acid	206.0
ClCC(=O)C1=CC=CC=C1	2-CHLORO-1-PHENYLETHANONE	55.2
CC(C)=CC(O)=O	3,3-Dimethylacrylic acid	68.2
[O-][N+](=O)C1=CC=CC=C1C=O	o-Nitrobenzaldehyde	44.8
CC1=CC=C(CO)C=C1	4-methylbenzyl_alcohol	60.2
BrC1=CC=C(OC2=CC=C(Br)C=C2)C=C1	Bis(4-bromophenyl) ether	59.2
CC(C)(C)C1=CC=CC(=C1O)C(C)(C)C	2,6-DI-TERT-BUTYLPHENOL	37.8
O=C1OC2(OC=C(C2=O)C2=CC=CC=C2)C2=CC=CC=C12	4'-Phenyl-3H,3'H-spiro[2-benzofuran-1,2'-furan]-3,3'-dione	156.0
O=C(CC#N)C1=CC=CC=C1	Benzoylacetonitrile	81.8
CC1=CC=C(Cl)C(N)=C1	2-chloro-5-methylaniline	30.8
CC1=CC(=O)C=C(C)C1=O	2,6-Dimethyl-1,4-benzoquinone	71.2
CC(=O)C1=CC=CC=C1C(O)=O	2-acetylbenzoic_acid	116.0
OCC1=CC=C(C=C1)[N+]([O-])=O	4-nitrobenzyl_alcohol	95.2
COC1=CC=C(C=C1O)[C@@H]1CC(=O)C2=C(O)C=C(O)C=C2O1	3',5,7-Trihydroxy-4'-methoxyflavanone	229.0
NC1=CC=C(C=C)C=C1	4-Aminostyrene	24.8
OC1C2=CC=CC=C2C2=CC=CC=C12	9H-Fluoren-9-ol	155.0
S=C(NC1=CC=CC=C1)NC1=CC=CC=C1	1,3-Diphenylthiourea	153.0
COC1=CC=C2C[C@@H]3[C@@H]4C=C[C@H](O)[C@@H]5OC1=C2[C@]45CCN3C	(5alpha,6alpha)-3-methoxy-17-methyl-7,8-didehydro-4,5-epoxymorphinan-6-ol	156.0
NCCCCCCN	HEXANE-1,6-DIAMINE	40.2
NC1=CC(Br)=CC=C1	m-Bromoaniline	17.2
NC1=C(Cl)C=C(Cl)C=C1	2,4-dichloroaniline	62.2
CC(C)C1=CC=C(C)C=C1O	thymol	50.2
CC(=O)C1=CC(N)=CC=C1	m-aminoacetophenone	97.2
COC1=CC(OC)=CC(OC)=C1	1,3,5-Trimethoxybenzene	53.2
COC1=CC=C(C=C1)C#N	4-methoxybenzonitrile	60.2
OC1=CC=C(C=C1)C1(OC(=O)C2=CC=CC=C12)C1=CC=C(O)C=C1	phenolphthalein	261.0
[O-][N+](=O)C1=C(Cl)C(Cl)=C(Cl)C(Cl)=C1Cl	PENTACHLORONITROBENZENE	143.0
NC1=CC=CC=C1C1=CC=CC=C1	biphenyl-2-amine	50.2
CC1=CC=C(C=C1[N+]([O-])=O)[N+]([O-])=O	1-Methyl-2,4-dinitrobenzene	69.8
NC(=O)C1=CC=C(C=C1)[N+]([O-])=O	4-NITROBENZAMIDE	201.0
OC1=CC=CC(=C1)C#N	3-Cyanophenol	80.8
NC1=CC=C(Cl)C=C1	4-chloroaniline	71.2
OC(=O)C1=CC=C(O)C=C1	4-Hydroxybenzoic Acid	216.0
COC1=CC(\C=C\C(=O)C2=CC=CC=C2O)=CC=C1O	2',4-dihydroxy-3-methoxychalcone	128.0
NC1=CC=C(C=C1)S(=O)(=O)NC1=NC=CS1	Sulfathiazole	201.0
BrC1=CC(Br)=C(Br)C=C1	1,2,4-tribromobenzene	43.2
ClC1=CC=C(C=O)C=C1	4-chlorobenzaldehyde	47.2
C1=CC=C2C(=C1)C1=CC=CC=C1C1=CC=CC=C21	triphenylene	198.0
NCCN	Ethane-1,2-diamine	9.8
[O-][N+](=O)C1=CC=CC(=C1)C(F)(F)F	3-Nitrobenzotrifluoride	-3.7
CCC(=O)C(C[C@H](C)N(C)C)(C1=CC=CC=C1)C1=CC=CC=C1	Methadone	100.0
OC(=O)C(O)(C1=CC=CC=C1)C1=CC=CC=C1	hydroxy(diphenyl)acetic acid	150.0
C1=CC2=C3C4=C1C=CC1=C4C4=C(C=C1)C=CC1=C4C3=C(C=C2)C=C1	Coronene	439.0
BrC1=CC=C(C=C)C=C1	4-BROMOSTYRENE	6.35
OCCOC1=CC2=CC=CC=C2C=C1	2-(2-Naphthoxy)ethanol	75.3
OC1CCC2=CC=CC=C12	1-INDANOL	53.4
CC(=O)C1=CC=C(C=C1)[N+]([O-])=O	p-Nitroacetophenone	80.4
OC1=CC=CC=C1Cl	2-chlorophenol	8.4
O[Si](C1=CC=CC=C1)(C1=CC=CC=C1)C1=CC=CC=C1	Triphenylsilanol	153.0
CCCCCCCO	Heptan-1-ol	-34.6
CC(=O)C(O)=O	2-Oxopropanoic acid	12.4
CCCCCCCCCC#N	Decanonitrile	-16.4
ClC1=CC=C(Cl)C=C1	1,4-dichlorobenzene	53.5
NC1CCCC1	Cyclopentylamine	-84.2
CC1=CC=CC(O)=C1O	3-methylcatechol	66.5
CCCCCCCCCC1=CC=C(O)C=C1	4-n-Nonylphenol	43.5
NC1=NC=CS1	2-aminothiazole	91.5
NC(=O)NO	hydroxyurea	142.0
O=C1CSC(=O)N1	2,4-Thiazolidinedione	126.0
OC(=O)CC(S)C(O)=O	Mercaptosuccinic acid	150.0
N(C1=CC=CC=C1)C1=CC=C(NC2=CC=CC=C2)C=C1	N,N'-Diphenyl-p-phenylenediamine	146.0
NC(=O)CCl	2-Chloroacetamide	120.0
CC(C)(C1=CC=C(O)C=C1)C1=CC=C(O)C=C1	bisphenol A	154.0
OC1=C2C(=O)C3=CC=CC=C3C(=O)C2=C(O)C=C1	1,4-Dihydroxyanthraquinone	198.0
O=C1C(=O)C2=CC=CC3=C2C1=CC=C3	Acenaphthenequinone	260.0
OC1=C(C=O)C=C(Br)C=C1Br	3,5-Dibromosalicylaldehyde	84.5
O=C1NC2=CC=CC=C2C1=O	1H-INDOLE-2,3-DIONE	202.0
BrCC(Br)C1=CC=CC=C1	(1,2-DIBROMOETHYL)BENZENE	73.5
CC(=O)CC(=O)C1=CC=CC=C1	Benzoylacetone	57.5
CC1=CC2=C(N1)C=CC=C2	2-Methylindole	59.5
CC1=CC=C(Cl)C=C1N	5-Chloro-2-methylaniline	24.5
ClS(=O)(=O)C1=CC=C(I)C=C1	4-Iodobenzenesulfonyl chloride	83.5
CC(C)NC1=CC=C(NC2=CC=CC=C2)C=C1	N-Isopropyl-N'-phenyl-p-phenylenediamine	75.5
CC(C)(O)CCC(C)(C)O	2,5-DIMETHYL-2,5-HEXANEDIOL	90.5
CCOC(=O)CCCCCCCCC(=O)OCC	diethyl_sebacate	3.5
[O-][N+](=O)C1=CC=CC(=C1)C(Cl)=O	3-Nitrobenzoyl chloride	34.5
C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=CC=C1	P-QUATERPHENYL	318.0
O=C(NNC1=CC=CC=C1)NNC1=CC=CC=C1	n'',n'''-diphenylcarbonohydrazide	172.0
OC(=O)CC1=CC=C(F)C=C1	4-FLUOROPHENYLACETIC ACID	84.5
OC1=C(C=CC(F)=C1)[N+]([O-])=O	5-fluoro-2-nitrophenol	34.5
CC1=CC=C(O)C(O)=C1	4-Methylcatechol	66.5
C1COCOC1	1,3-DIOXANE	-43.5
O=C1C=C(OC2=C1C=CC=C2)C1=CC=CC=C1	Flavone	98.5
NC1=C(Cl)C(Cl)=C(Cl)C(Cl)=C1Cl	PENTACHLOROANILINE	234.0
ClN=C1C=C(Br)C(=O)C(Br)=C1	2,6-Dibromoquinone-4-chloroimide	81.5
NC1=CC2=C(C=C1)N=CC=C2	6-Aminoquinoline	116.0
CC(=O)NC1=CC=CC(Cl)=C1	3'-Chloroacetanilide	78.5
[O-][N+](=O)C1=CC=CC2=C1C=CC=C2[N+]([O-])=O	1,5-DINITRONAPHTHALENE	218.0
CNC(=O)C1=CC=CC=C1	N-methylbenzamide	80.5
CCCCC(N)=O	Valeramide	104.0
C1=CN(C=C1)C1=CC=CC=C1	1-Phenylpyrrole	60.5
CCCCCCCCCCCCCCCCCCCCCCCC	n-Tetracosane	52.5
O=C1CCCCC1=O	1,2-Cyclohexanedione	38.5
CCCCP(=O)(CCCC)CCCC	Tri-n-butylphosphine oxide	65.5
CC1=CC=C2N=C(C)C=CC2=C1	2,6-Dimethylquinoline	58.5
COC1=CC=C2NC=CC2=C1	5-Methoxyindole	55.5
CC(=O)NN	Acetic hydrazide	65.5
CCCCCCCCC(C)O	2-DECANOL	-3.5
CS(=O)C1=CC=CC=C1	Methyl phenyl sulfoxide	30.5
O=C1C2=CC=CC=C2CCC2=CC=CC=C12	Dibenzosuberone	31.5
C(OC1=CC=C2NC=CC2=C1)C1=CC=CC=C1	5-Benzyloxyindole	100.0
CC(=O)C1=CC(C)=CC=C1O	2'-Hydroxy-5'-methylacetophenone	48.5
O1C(=CN=C1C1=CC=C(C=C1)C1=NC=C(O1)C1=CC=CC=C1)C1=CC=CC=C1	1,4-Bis(5-phenyloxazol-2-yl)benzene	244.0
C=CC1=CC=C(C=C1)C1=CC=CC=C1	4-VINYLBIPHENYL	118.0
OC(=O)C1=CC(Cl)=C(O)C(Cl)=C1	3,5-Dichloro-4-hydroxybenzoic acid	266.0
NC1=C(C=C(C=C1Cl)[N+]([O-])=O)[N+]([O-])=O	6-Chloro-2,4-dinitroaniline	156.0
OCC1=CC=CC2=CC=CC=C12	1-NAPHTHALENEMETHANOL	62.5
CCN1C(=O)C2=CC=CC=C2C1=O	N-Ethylphthalimide	77.5
CC(=O)NC1=CC=CC(=C1)[N+]([O-])=O	3'-Nitroacetanilide	154.0
CCCCCCCCP(=O)(CCCCCCCC)CCCCCCCC	Trioctylphosphine oxide	53.5
CCOC1=CC=CC=C1O	2-Ethoxyphenol	27.5
COC1=CC=C(N)C(=C1)[N+]([O-])=O	4-Methoxy-2-nitroaniline	126.0
OC(=O)CC1=CC(F)=CC=C1	3-Fluorophenylacetic acid	44.5
COC1=CC=C(C)C=C1OC	3,4-Dimethoxytoluene	25.5
CCCCCCCCC#CCCCCCCCC(O)=O	9-Octadecynoic acid	46.5
COC1=CC=C(C=O)C(C(O)=O)=C1OC	2-carboxy-3,4-dimethoxybenzaldehyde	148.0
CNC1=CC=CC=C1[N+]([O-])=O	N-Methyl-2-nitroaniline	36.5
OCCCCCCCCO	1,8-OCTANEDIOL	61.5
NNC1=C(F)C(F)=CC(F)=C1F	2,3,5,6-Tetrafluorophenylhydrazine	90.5
CC1=CC(Cl)=NC(Cl)=C1C#N	2,6-dichloro-3-cyano-4-methylpyridine	112.0
BrCC1=CC2=CC=CC=C2C=C1	2-(Bromomethyl)naphthalene	54.5
O1C(=CC=C1C1=CC=CC=C1)C1=CC=CC=C1	2,5-Diphenylfuran	89.5
C1=CC=C(C=C1)C1=CC=C2C=CC=CC2=N1	2-Phenylquinoline	84.5
CC(=O)C1=CC=C(OCC(O)=O)C=C1	4-Acetylphenoxyacetic acid	174.0
[O-][N+](=O)C1=CC=C(C=C1)N=C=S	4-Nitrophenyl isothiocyanate	110.0
OC(=O)C1=C(F)C=CC(F)=C1	2,5-Difluorobenzoic Acid	132.0
NC(=O)C1=CC=C(C=C1)C#N	4-cyanobenzamide	226.0
FC(F)(F)C1=CC=CC=C1CC#N	2-(Trifluoromethyl)phenylacetonitrile	31.5
O=S(=O)(CC1=CC=CC=C1)C1=CC=CC=C1	BENZYL PHENYL SULFONE	148.0
NC1=CC(Br)=CC=C1Br	2,5-Dibromoaniline	52.5
CC1=C(C)C(C)=C(Br)C(C)=C1C	Bromopentamethylbenzene	164.0
O=CC1=NC2=CC=CC=C2C=C1	Quinoline-2-carboxaldehyde	69.5
COC1=CC2=CC=C(OC)C=C2C=C1	2,6-Dimethoxynaphthalene	152.0
CC(C(O)=O)(C1=CC=CC=C1)C1=CC=CC=C1	Diphenylpropionic acid	174.0
CCOC(=O)C1=CNN=C1N	Ethyl 3-amino-1H-pyrazole-4-carboxylate	104.0
CCCCCCCCCCCCCCC(C)O	2-HEXADECANOL	45.5
CCOC1=CC=C2C=CC=CC2=C1C=O	2-Ethoxy-1-naphthaldehyde	114.0
CC(C)(C)C(=O)CC#N	trimethylacetylacetonitrile	69.5
CC1CNCC(C)O1	2,6-Dimethylmorpholine	-86.5
N#CC1=CC=CC=C1C1=CC=CC=C1	o-cyanobiphenyl	39.5
O=C(OCC1=CC=CC=C1)C1=CC=CC=C1C(=O)OCC1=CC=CC=C1	DIBENZYL PHTHALATE	42.5
C[C@H](CCC(O)=O)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3C[C@H](O)[C@]12C	cholic acid	200.0
O=C1CCCCCCCCCCCCCCO1	Pentadecanolide	33.5
CCC(=O)C1=CC(F)=C(O)C(F)=C1	1-(3,5-difluoro-4-hydroxyphenyl)propan-1-one	128.0
CC(=O)OC1=CC=C(C=C1)C1=CC=C(OC(C)=O)C=C1	4,4'-diacetoxybiphenyl	162.0
NC1=C(Cl)C=CC(Cl)=C1C(O)=O	2-Amino-3,6-dichlorobenzoic acid	154.0
OCC=CCO	cis-2-Butene-1,4-Diol	5.5
COC(=O)C1=CC=C(Cl)C(=C1)[N+]([O-])=O	Methyl 4-chloro-3-nitrobenzoate	81.5
OC(=O)\C=C\C1=CC=CC=C1[N+]([O-])=O	trans-2-Nitrocinnamic acid	246.0
O=C\C=C\C1=CC=CO1	3-(2-Furyl)acrolein	52.5
N#C\C=C\C1=CC=CC=C1	trans-Cinnamonitrile	20.5
CC1=NN=C(S)S1	2-Mercapto-5-methyl-1,3,4-thiadiazole	186.0
NC(=S)NS(=O)(=O)C1=CC=C(N)C=C1	Sulfathiourea	180.0
NC1=CC(=C(O)C=C1)[N+]([O-])=O	4-amino-2-nitrophenol	128.0
NNC(=O)C1=CC=CC=C1[N+]([O-])=O	2-Nitrobenzhydrazide	122.0
ON=C(C(O)C1=CC=CC=C1)C1=CC=CC=C1	(2e)-2-(hydroxyimino)-1,2-diphenylethanol	152.0
ClC1=CC=C(C=C1)C(=O)\C=C\C1=CC=CC=C1	4'-chlorochalcone	97.5
N[C@@H](CC1=CC(O)=CC=C1)C(O)=O	L-m-Tyrosine	266.0
CC(=O)NC1=CC=C(C)C=C1	4'-Methylacetanilide	150.0
OC(=O)C(Cl)=C(Cl)Cl	Trichloroacrylic acid	74.5
OC(=O)C(F)(F)Cl	Chlorodifluoroacetic acid	23.5
ClC(=O)CCC(Cl)=O	SUCCINYL CHLORIDE	18.5
COC1=CC=C(C=C1)N=NC1=CC=CC=C1	(e)-1-(4-methoxyphenyl)-2-phenyldiazene	54.5
OC(=O)CC1=CC=C(O)C=C1	4-hydroxyphenylacetic acid	150.0
OCC(O)=O	Glycol acid	78.5
CCCCCCCCCCCCCCCCCC(O)=O	stearic acid	69.5
CC(Cl)(Cl)Cl	1,1,1-Trichloroethane	-31.5
IC(I)I	IODOFORM	120.0
CC(C)(C)C(O)=O	Trimethylacetic acid	34.5
O=C1C2=CC=CC=C2C2=C3C(C=CC=C13)=CC=C2	7H-benzo[de]anthracen-7-one	172.0
CC1=CC=C(Cl)C=C1[N+]([O-])=O	4-Chloro-2-nitrotoluene	37.5
CC1=CC=C(C(C)=C1)[N+]([O-])=O	2,4-Dimethyl-1-nitrobenzene	7.5
ClC(C1=CC=CC=C1)C1=CC=CC=C1	CHLORODIPHENYLMETHANE	17.5
N1N=C2C=CC=CC2=N1	1H-Benzotriazole	97.0
CC1=C(Cl)C=C(N)C=C1	3-Chloro-4-methylaniline	24.5
NC1=CC(Cl)=CC=C1O	5-CHLORO-2-HYDROXYANILINE	142.0
FC(F)(F)C1=CC=C(Cl)C=C1	1-CHLORO-4-(TRIFLUOROMETHYL)BENZENE	-34.5
OC(=O)C1=CC=C(C=C1Cl)[N+]([O-])=O	2-chloro-4-nitrobenzoic_acid	140.0
N#CC1=CC=NC=C1	Isonicotinonitrile	77.5
CC(=O)NC1=CC=C(Br)C=C1	p-Bromoacetanilide	168.0
C(COC1=CC=CC=C1)OC1=CC=CC=C1	1,2-DIPHENOXYETHANE	96.5
ClCC1=CC=C(Cl)C=C1	4-chlorobenzyl_chloride	29.5
ClC1=CC=C(Br)C=C1	p-Bromochlorobenzene	66.5
CCCCCCCCCCCCCCCCCCO	1-Octadecanol	59.5
CC1(C)N(Cl)C(=O)N(Cl)C1=O	1,3-dichloro-5,5-dimethylimidazolidine-2,4-dione	134.0
C1CCCCCCC1	cyclooctane	13.5
OC(=O)C1=CC(Cl)=CC=C1O	5-chlorosalicylic_acid	172.0
NC(=N)NC#N	1-Cyanoguanidine	210.0
CC1CCC2CC1C2(C)C	pinane, endo exo	-51.5
C1C2=CC=CC=C2CC2=CC=CC=C12	9,10-dihydroanthracene	110.0
COC1=CC=C(C=C1)C1=CC=CC=C1	4-METHOXYBIPHENYL	89.5
OC(=O)CC1=CC=CC=C1O	2-Hydroxyphenylacetic acid	148.0
NC1=CC=CC=C1I	o-Iodoaniline	56.5
OC1=C(Br)C=C(Br)C=C1	2,4-Dibromophenol	38.5
OC(=O)C1=CC=C(I)C=C1	p-iodobenzoic_acid	272.0
BrC1=CC=C(C=C1)C#N	p-Bromobenzonitrile	112.0
ClC1=CC=C(C=C1)C#N	p-Chlorobenzonitrile	93.5
CCCCCCCCCCCCCCCCCCCCCC	DOCOSANE	43.5
NC1=CC=C(Cl)C(=C1)[N+]([O-])=O	4-Chloro-3-nitroaniline	102.0
CCCCCCCCCCCCC(O)=O	TRIDECANOIC ACID	43.0
OC(=O)C1=CC=C(O1)[N+]([O-])=O	5-Nitro-2-furoic acid	186.0
NC1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C1	(2-amino-5-chlorophenyl)(phenyl)methanone	97.5
COC1=CC=C2N=C(N)SC2=C1	6-methoxy-1,3-benzothiazol-2-amine	164.0
[O-][N+](=O)C1=CC(=CC=C1)C1=CC=CC=C1	3-nitrobiphenyl	60.5
OC(=O)C1=C(Cl)C(=CC=C1)[N+]([O-])=O	2-chloro-3-nitrobenzoic_acid	182.0
NC1=CC(=CC=C1Cl)[N+]([O-])=O	2-chloro-5-nitroaniline	120.0
OCC1=CC=CC=C1Cl	2-CHLOROBENZYL ALCOHOL	71.5
CC(C)C1=CC(=C(C)C=C1O)C1(OC(=O)C2=CC=CC=C12)C1=CC(C(C)C)=C(O)C=C1C	3,3-Bis(4-hydroxy-5-isopropyl-2-methylphenyl)-2-benzofuran-1(3H)-one	252.0
OC(=O)C1=CC=C(C=C1)C1=CC=CC=C1	Biphenyl-4-carboxylic acid	226.0
COC1=CC=C(OC)C(C=O)=C1	2,5-Dimethoxybenzaldehyde	50.5
COC1=CC(=O)C=C(OC)C1=O	2,6-Dimethoxy-1,4-benzoquinone	254.0
COC1=CC=C(C=O)C(OC)=C1	2,4-dimethoxybenzaldehyde	70.5
COC1=CC=C(I)C=C1	p-Iodoanisole	51.5
FC(F)(F)C1=CC=C(C=C1)C(=O)C1=CC=CC=C1	4-(Trifluoromethyl)benzophenone	116.0
OC(=O)C1=CC=CC=C1C1=CC=CC=C1	Biphenyl-2-carboxylic acid	114.0
BrC1=CC=C(C=C1)C(=O)C1=CC=C(Br)C=C1	4,4'-Dibromobenzophenone	176.0
CC(=O)C1=CC=C(Cl)C(Cl)=C1	3,4-dichloroacetophenone	74.5
COC(=O)C1=CC=CC(O)=C1	methyl_3-hydroxybenzoate	72.5
COC1=CC=C2N=CC=C([C@@H](O)[C@@H]3C[C@@H]4CC[N@]3C[C@@H]4C=C)C2=C1	Quinine	176.0
OC(=O)\C=C\C1=CC=CC(Br)=C1	m-bromocinnamic_acid	178.0
O=C(\C=C\C1=CC=C2C=CC=CC2=C1)/C=C/C1=CC=C2C=CC=CC2=C1	(1e,4e)-1,5-di(2-naphthyl)-1,4-pentadien-3-one	244.0
OC(=O)CBr	Bromoacetic Acid	48.5
OCCOCCOCCO	2,2'-[ethane-1,2-diylbis(oxy)]diethanol	-5.5
CCC1=CC=CC=C1N	2-Ethylaniline	-45.5
ClC1=CC=C(I)C=C1	p-Chloroiodobenzene	55.5
OC1=CC(Br)=CC=C1	m-Bromophenol	31.5
CCCCCCC1=CC=C(O)C=C1O	4-hexylbenzene-1,3-diol	66.5
CC1=CC(C)=NC(C)=C1	2,4,6-Trimethylpyridine	-44.5
NC1=CC=CC=C1Br	o-Bromoaniline	30.5
CC1=CC(C)=C(Br)C(C)=C1	2-Bromomesitylene	0.5
CC(C)(C)C1=CC=C(Br)C=C1	1-Bromo-4-tert-butylbenzene	17.5
NC1=CC=CC=C1C(O)=O	2-aminobenzoic acid	146.0
CCCC=O	Butyraldehyde	-97.5
[O-][N+](=O)C1=CC=C(C=O)C=C1	p-Nitrobenzaldehyde	106.0
CN1C(C)=NC=C1[N+]([O-])=O	dimetridazole	138.0
C[C@]12CC(=O)[C@H]3[C@@H](CCC4=CC(=O)C=C[C@]34C)[C@@H]1CC[C@]2(O)C(=O)CO	Prednisone	236.0
OC(=O)C1=CC=C(Cl)C=C1	4-Chlorobenzoic Acid	242.0
CI	iodomethane	-65.5
CCCCC1(CC)C(=O)NC(=O)NC1=O	Butethal	127.0
OC(C1=CC=CC=C1)C1=CC=CC=C1	Diphenylmethanol	67.5
CC(=O)C1=CC=C2C=CC=CC2=C1	2'-Acetonaphthone	54.5
COC(=O)C1=CC=CC=C1	methyl benzoate	-13.5
CC1=CC=C(C=C1)S(Cl)(=O)=O	4-Methylbenzenesulfonyl chloride	69.5
CCCCCCC(O)=O	HEPTANOIC ACID	-7.5
CCCCCCCCCC(C)=O	Undecan-2-one	13.5
CCCCOCCCC	dibutyl ether	-96.5
CC(=O)NC1=CC=CC=C1O	N-(2-hydroxyphenyl)acetamide	206.0
COC(=O)OC	Dimethyl carbonate	2.5
ICCI	1,2-DIIODOETHANE	81.5
[O-][N+](=O)C1=CC=C(I)C=C1	1-Iodo-4-nitrobenzene	174.0
CC(=O)C1=CC=C(I)C=C1	4'-Iodoacetophenone	84.5
OCCCCCCO	1,6-HEXANEDIOL	43.5
[O-][N+](=O)C1=CC=C(Cl)C(=C1)[N+]([O-])=O	1-Chloro-2,4-dinitrobenzene	51.5
CC1=CC(Cl)=C(C)C=C1Cl	2,5-Dichloro-p-xylene	69.5
OC1=CC=C(Cl)C=C1	4-Chlorophenol	42.5
O=C(CC1=CC=CC=C1)CC1=CC=CC=C1	1,3-Diphenylacetone	33.5
[O-][N+](=O)C1=CC(Cl)=CC=C1	1-Chloro-3-nitrobenzene	44.5
CC(=O)C1=CC=CC(=C1)[N+]([O-])=O	1-(3-Nitrophenyl)ethanone	79.5
CCCC(O)=O	butyric acid	-6.5
OC1=CC=C(C=C1)[N+]([O-])=O	p-Nitrophenol	114.0
CCCOC(C)=O	Propyl acetate	-93.5
OC(=O)C1=CC=CC=C1Cl	2-Chlorobenzoic Acid	140.0
CCCCCCCCCO	Nonan-1-ol	-5.5
O=C1C2=CC=CC=C2SC2=CC=CC=C12	Thioxanthen-9-one	210.0
C1=CC=C(C=C1)C#CC1=CC=CC=C1	1,1'-ethyne-1,2-diyldibenzene	61.5
OC(=O)C1CC1	CYCLOPROPANECARBOXYLIC ACID	17.0
CC1=CC(O)=CC(C)=C1	3,5-Dimethylphenol	64.0
O=C(OCC1=CC=CC=C1)C1=CC=CC=C1	Benzyl benzoate	19.5
CC1=CC=C(C=C1)[N+]([O-])=O	1-Methyl-4-nitrobenzene	52.5
OC(=O)CCC(O)=O	succinic acid	186.0
OC(C(=O)C1=CC=CC=C1)C1=CC=CC=C1	benzoin	136.0
OC1=C(Cl)C=C(Cl)C=C1	2,4-dichlorophenol	43.5
OC1=CC=CC(Cl)=C1Cl	2,3-Dichlorophenol	57.5
C1=CC=C2C(=C1)C=C1C=CC3=C4C(C=CC2=C14)=CC=C3	benzo[a]pyrene	178.0
OC(=O)CC1=CC=CC=C1	phenylacetic_acid	77.5
C1=CC2=CC3=CC=CC=C3C=C2C=C1	Anthracene	216.0
C(=C/C1=CC=CC=C1)\C1=CC=CC=C1	trans-Stilbene	124.0
CN1C=NC2=C1C(=O)N(C)C(=O)N2C	Caffeine	236.0
CCCC=C	Pent-1-ene	-164.0
CCI	iodoethane	-110.0
CCCCCCOCCO	2-(n-hexyloxy)ethanol	-43.5
CCCCCCCCCCCCCCCCCCN	octadecan-1-amine	54.5
CCC(C)=CC	3-Methyl-trans-2-pentene	-136.0
CC1=CC=CC=C1O	o-cresol	31.4
CCCCCCCCCCCC(=O)CCCCCCCCCCC	12-Tricosanone	68.6
CCC(N)=O	PROPIONAMIDE	79.7
CC1=CC=CC=N1	2-METHYLPYRIDINE	-68.3
CCCCC1CCCCC1	BUTYLCYCLOHEXANE	-76.3
CC1=CC=CC(C)=C1O	2,6-Dimethylphenol	47.4
CC1=CC(=CC=C1)C(O)=O	3-Methylbenzoic acid	110.0
CCCCCCCCCCCCI	1-IODODODECANE	-1.35
CC1=NS(=O)(=O)C2=CC(Cl)=CC=C2N1	diazoxide	329.0
NC(N)=O	Urea	134.0
ClC1=CC=CC=C1C=O	2-chlorobenzaldehyde	10.7
NC1=CC=C(Br)C=C1	4-Bromoaniline	64.7
CCC1(CCC(=O)NC1=O)C1=CC=CC=C1	glutethimide	85.8
OC(=O)C1=CC=CC=C1NC1=CC=CC=C1	N-Phenylanthranilic Acid	185.0
CC1=CC=C(C=C1)S(=O)(=O)NC1CCCCC1	N-CYCLOHEXYL-4-METHYLBENZENESULFONAMIDE	86.2
CC(C)CNCC(C)C	DIISOBUTYLAMINE	-75.2
COC	Dimethyl ether	-140.0
OC(=O)C1=C(O)C(Cl)=CC(Cl)=C1	3,5-DICHLOROSALICYLIC ACID	222.0
CN(C)C1=CC=C(C=C1)C(=O)C1=CC=CC=C1	4-Dimethylaminobenzophenone	90.8
COC1=CC=C(C(C)=O)C(O)=C1	2'-Hydroxy-4'-methoxyacetophenone	50.8
NN1C=NN=C1	4-Amino-1,2,4-triazole	84.2
O=NC1=CC=CC=C1	NITROSOBENZENE	66.8
CC(C)(O)C(O)=O	2-HYDROXYISOBUTYRIC ACID	80.8
CN(C)C(N)=O	N,N-Dimethylurea	182.0
O=CC1=CC=CN1	PYRROLE-2-CARBOXALDEHYDE	44.8
C=CCN1C(=O)N(CC=C)C(=O)N(CC=C)C1=O	1,3,5-Triallyl-1,3,5-triazinane-2,4,6-trione	22.2
CC1=CC=C(O)C=C1Cl	3-Chloro-4-methylphenol	53.8
OP(O)(=O)C1=CC=CC=C1	PHENYLPHOSPHONIC ACID	163.0
OC1(CCCCC1)C1=CC=CC=C1	1-Phenylcyclohexanol	61.8
OP(O)(=O)CP(O)(O)=O	Methylenediphosphonic acid	201.0
CCCCCCCCCCCCCC=O	tetradecyl_aldehyde	22.2
O=C=NC1=CC=C(C=C1)N=C=O	1,4-Diisocyanatobenzene	95.8
CCCCCCCCOC(=O)C1=CC(O)=C(O)C(O)=C1	n-Octyl gallate	101.0
CN(C=O)C1=CC=CC=C1	N-Methylformanilide	12.8
CCOC1=CC=C(C=O)C=C1OC	4-Ethoxy-3-methoxybenzaldehyde	62.8
NC1=CC=CC2=C1C(N)=CC=C2	1,8-Diaminonaphthalene	64.8
CCC1=NC(C)=CN1	2-Ethyl-4-methylimidazole	48.8
ClC(=O)C(C1=CC=CC=C1)C1=CC=CC=C1	Diphenylacetyl chloride	54.8
CC(=O)NC(=O)CN	N-Acetylglycinamide	140.0
CS(=O)(=O)C1=CC=C(C=C1)C(O)=O	4-(Methylsulfonyl)benzoic acid	271.0
C\C(=C\C(O)=O)C(O)=O	Citraconic acid	91.8
CCC\C=C\C(O)=O	trans-2-Hexenoic acid	34.8
CC(=O)NC1=CC=C(N)C=C1	4'-Aminoacetanilide	165.0
ClC(=O)C1=CC=CC=C1C(Cl)=O	PHTHALOYL CHLORIDE	13.8
NC1=CN=CC=C1	3-Aminopyridine	62.8
NC1=C(Cl)C=C(Cl)C=C1Br	2-BROMO-4,6-DICHLOROANILINE	81.8
NC1=C(N)C=NC=C1	3,4-Diaminopyridine	218.0
CCO[Si](OCC)(OCC)OCC	Tetraethyl orthosilicate	-84.2
OCC1=C(F)C(F)=C(F)C(F)=C1F	2,3,4,5,6-Pentafluorobenzyl alcohol	35.8
CC1=CC=C2NC=NC2=C1	5-Methylbenzimidazole	114.0
CC1=CC=C(C=C1)C1=CC=CC=C1	4-Methylbiphenyl	47.8
CP(O)(O)=O	METHYLPHOSPHONIC ACID	107.0
C(NC1=NC=NC2=C1NC=N2)C1=CC=CC=C1	N-Benzyl-9H-purin-6-amine	231.0
CC1=CC=CNC1=O	3-Methyl-2-pyridone	140.0
NNC(=O)NN	Carbonohydrazide	156.0
FC(F)(F)C1=CC=C(CC#N)C=C1	4-(Trifluoromethyl)phenylacetonitrile	46.8
NCCCCCO	5-Amino-1-pentanol	36.8
[O-][N+](=O)C1=CC(Br)=CC=C1Br	2,5-Dibromonitrobenzene	83.8
CC(N)=S	Ethanethioamide	114.0
C[C@H](O)CN	(2s)-1-amino-2-propanol	23.2
OC1=CC=CC=C1C=NC1=CC=CC=C1	Salicylideneaniline	49.2
OC(=O)C1=CC=CO1	2-furoic acid	132.0
COC1=CC=C(Br)C=C1	p-Bromoanisole	11.8
NC1=CC=C(C=C1[N+]([O-])=O)[N+]([O-])=O	2,4-Dinitroaniline	178.0
BrCCCCBr	1,4-DIBROMOBUTANE	-18.2
OC(=O)CC1=CC=C(Cl)C=C1	4-chlorophenylacetic_acid	105.0
OC(=O)C1=CC(Cl)=CC=C1Cl	2,5-DICHLOROBENZOIC ACID	154.0
COC(=O)C1=CC=CC=C1C(=O)OC	dimethyl phthalate	3.75
CC1=CC(N)=C(C)C=C1	2,5-Dimethylaniline	13.8
CC1=CC=C(Br)C=C1	1-Bromo-4-methylbenzene	26.8
COC1=CC=CC(C=O)=C1O	2-Hydroxy-3-methoxybenzaldehyde	42.8
[O-][N+](=O)C1=CC=C(Cl)C=C1Cl	2,4-Dichloro-1-nitrobenzene	32.2
OC1=C(Cl)C=C(Cl)C(Cl)=C1	2,4,5-trichlorophenol	67.2
OC1=CC=C(F)C=C1	4-fluorophenol	46.2
CC1=C2C=CC=CC2=CC2=CC=CC=C12	9-methylanthracene	79.8
C[C@]12CC(=O)[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@]2(O)C(=O)CO	Cortisone	224.0
CC1=CC=CC(O)=C1C	2,3-DIMETHYLPHENOL	73.2
ClC1=CC(Cl)=C(Cl)C(Cl)=C1	1,2,3,5-tetrachlorobenzene	53.2
NC(=O)C1=CC=CC=C1	benzamide	128.0
CC1=C(C)C(C)=C(C)C(C)=C1C	hexamethylbenzene	166.0
COC(=O)C1=CC=C(N)C=C1	Methyl 4-aminobenzoate	112.0
OC1=C(Cl)C=CC=C1Cl	2,6-Dichlorophenol	66.8
CCOC1=CC=C(NC(C)=O)C=C1	phenacetin	136.0
CCCCOC(=O)C1=CC=C(O)C=C1	Butyl 4-hydroxybenzoate	70.2
OCCN1CCOCC1	4-(2-Hydroxyethyl)morpholine	0.2
CC(C)C1CCC(C)CC1	Cyclohexane, 1-methyl-4-(1-methylethyl)-, cis-	-88.1
OC(=O)CCCCCCCCC(O)=O	sebacic acid	133.0
OC1=CC(F)=CC=C1	3-fluorophenol	11.8
CCC(C)(CO)CO	2-Ethyl-2-methyl-1,3-propanediol	42.1
CC(C)CC(O)=O	ISOVALERIC ACID	-31.1
OC1CCCC1	CYCLOPENTANOL	-18.1
C[C@]12CC[C@H]3[C@@H](CCC4=C3C=CC(O)=C4)[C@@H]1CCC2=O	estrone	257.0
FC(F)(F)CC(F)(F)F	1,1,1,3,3,3-Hexafluoropropane	-96.1
COC(=O)C1=CC=C(C)C=C1	methyl_4-methylbenzoate	35.1
COC1=CC=CC=C1CC#N	o-methoxy_phenylacetonitrile	67.9
NC1=CC=C2C=C3C=CC=CC3=CC2=C1	anthracen-2-amine	237.0
ClC1=C(Cl)C(Cl)=C(Cl)C(Cl)=C1Cl	hexachlorobenzene	230.0
[O-][N+](=O)NC1=NCCN1CC1=CN=C(Cl)C=C1	Imidacloprid	142.0
CCCCCCCC(=O)OCC	ethyl_octanoate	-45.0
FC(C(F)(F)F)C(F)(F)F	1,1,1,2,3,3,3-Heptafluoropropane	-129.0
C1=CC=C(C=C1)C1=CC=C(C=C1)C1=CC=CC=C1	1,1':4',1''-TERPHENYL	212.0
OC1=CC=C(Br)C=C1	p-Bromophenol	64.5
NCCC(O)=O	BETA-ALANINE	198.0
CCCC(N)C(O)=O	DL-Norvaline	305.0
NCCC1=CNC2=CC=CC=C12	tryptamine	116.0
COC1=CC=C(NC(C)=O)C=C1	4'-Methoxyacetanilide	129.0
CCCCC(CC)COP(=O)(OCC(CC)CCCC)OCC(CC)CCCC	TRIS(2-ETHYLHEXYL) PHOSPHATE	-72.0
O=C1NC(=O)C2=CC=CC=C12	phthalimide	236.0
CN(C)C1=CC=C(C=C1)C(=O)C1=CC=C(C=C1)N(C)C	Michler's ketone	177.0
CCN(CC)C1=CC=C2C(C)=CC(=O)OC2=C1	7-(Diethylamino)-4-methyl-2H-chromen-2-one	72.0
OC(=O)C1=CC2=C(OCO2)C=C1	PIPERONYLIC ACID	231.0
CC1=CC(=CC(C)=C1)C(C)(C)C	5-tert-Butyl-m-xylene	-20.0
OC1=CC=C(NCC2=CC=CC=C2)C=C1	4-(Benzylamino)phenol	86.0
C1CCNCC1	piperidine	-9.0
ClC1=C(Cl)C2(Cl)C3C(C(=O)OC3=O)C1(Cl)C2(Cl)Cl	Chlorendic Anhydride	235.0
NC1=NC2=CC=CC=C2S1	2-AMINOBENZOTHIAZOLE	130.0
C1=CC2=C(C=C1)C1=CC3=C(C=CC=C3)C3=C1C2=CC=C3	benzo[e]acephenanthrylene	166.0
NNC(=O)NC1=CC=CC=C1	4-phenylsemicarbazide	126.0
CC(C)C(C)(C)O	2,3-dimethyl-2-butanol	-12.0
ClCC1=CC=CC=C1Cl	2-Chlorobenzyl chloride	-15.0
OC1=CC=C(C=C1Cl)[N+]([O-])=O	2-chloro-4-nitrophenol	108.0
OC1=C(C=O)C2=CC=CC=C2C=C1	2-Hydroxy-1-naphthaldehyde	81.0
CC1=CC=C(C=C1)P(C1=CC=C(C)C=C1)C1=CC=C(C)C=C1	Tri(p-tolyl)phosphine	147.0
NC1=CC=C(C=C1C(=O)C1=CC=CC=C1)[N+]([O-])=O	2-Amino-5-nitrobenzophenone	165.0
OCC1=CC(OC2=CC=CC=C2)=CC=C1	(3-Phenoxyphenyl)methanol	8.0
OCC(CO)(CO)COCC(CO)(CO)CO	Dipentaerythritol	219.0
OC(=O)CC=C	Vinylacetic acid	-37.0
OC1=C(C=O)C=C(C=C1)[N+]([O-])=O	2-Hydroxy-5-nitrobenzaldehyde	127.0
OC(=O)C(F)(F)C(F)(F)C(O)=O	Tetrafluorosuccinic acid	117.0
CC(=O)N[C@@H](CC1=CC=C(O)C=C1)C(O)=O	N-ACETYL-L-TYROSINE	151.0
OC(=O)C1=CC(O)=C(C=C1)[N+]([O-])=O	3-HYDROXY-4-NITROBENZOIC ACID	232.0
[O-][N+](=O)C1=CC=C(OC(=O)C2=CC=CC=C2)C=C1	4-Nitrophenyl benzoate	141.0
O=C1CCCCCCCCC1	CYCLODECANONE	26.0
CC1=CC(C)=C(C)C(Br)=C1C	1-Bromo-2,3,5,6-tetramethylbenzene	58.0
OCC1=C(O)C=CC(Br)=C1	5-Bromo-2-hydroxybenzyl alcohol	111.0
COC1=CC=CC=C1C(=O)C1=CC=CC=C1	2-Methoxybenzophenone	39.0
COC(=O)C1=CC(Cl)=CC=C1O	Methyl 5-chloro-2-hydroxybenzoate	48.0
CCN(C(C)C)C(C)C	N-ethyl-N-isopropylpropan-2-amine	-48.0
C[Si](C)(C)C#C[Si](C)(C)C	Bis(trimethylsilyl)acetylene	24.0
OC1=CC2=C(C=C1)C=C(O)C=C2	2,6-Dihydroxynaphthalene	222.0
N(\C=N\C1=CC=CC=C1)C1=CC=CC=C1	N,N'-Diphenylformamidine	140.0
CCOC(=O)C(O)(C1=CC=CC=C1)C1=CC=CC=C1	Ethyl benzilate	32.0
O=CC1=CC=CC=C1C#N	2-Cyanobenzaldehyde	106.0
O[C@@H]([C@@H]1C[C@@H]2CC[N@]1C[C@@H]2C=C)C1=C2C=CC=CC2=NC=C1	(8alpha,9R)-Cinchonan-9-ol	202.0
OC(=O)CC1=CC=C(C=C1)C(F)(F)F	4-(Trifluoromethyl)phenylacetic acid	82.0
OC(=O)\C=C\C1=CC=CC=C1C(F)(F)F	2-(Trifluoromethyl)cinnamic acid	204.0
CC12CCC3C(CCC4CC(CCC34C)OCC3=CC=CC=C3)C1CCC2=O	3-(benzyloxy)androstan-17-one	218.0
O=C(OCC1=CC=CC=C1)\C=C\C1=CC=CC=C1	Benzyl cinnamate	37.0
COC1=CC=C(C=C1)C1=CC(=O)C2=C(O)C(OC)=C(O)C=C2O1	5,7-Dihydroxy-6-methoxy-2-(4-methoxyphenyl)-4H-chromen-4-one	223.0
NC1=CC=C(C=CC2=CC=C(C=C2)[N+]([O-])=O)C(=C1)[N+]([O-])=O	3-nitro-4-[(e)-2-(4-nitrophenyl)ethenyl]aniline	200.0
OC[C@@H](O)[C@H]1O[C@@H]2O[C@@H](O[C@@H]2[C@H]1O)C(Cl)(Cl)Cl	1,2-O-[(1R)-2,2,2-trichloroethylidene]-alpha-D-glucofuranose	185.0
FC(F)(F)C(=O)C(F)(F)F	1,1,1,3,3,3-Hexafluoroacetone	-127.0
CC1=CC=CC=C1CCl	1-(Chloromethyl)-2-methylbenzene	0.0
OC1=CC=C(NC2=CC=CC=C2)C=C1	4-Hydroxydiphenylamine	71.0
CC1=CC=NC(C)=C1	2,4-Lutidine	-62.0
CCN(CC)C1=CC=C(Br)C=C1	4-Bromo-N,N-diethylaniline	36.0
CC(C)(C)CO	Neopentyl Alcohol	52.0
CCC(C)(C)O	2-METHYL-2-BUTANOL	-10.0
ClC1=CC=CC2=C1C(=O)C1=CC=CC=C1C2=O	1-CHLOROANTHRAQUINONE	161.0
NC1=CC=CC2=C1C(=O)C1=CC=CC=C1C2=O	1-Amino-9,10-anthraquinone	252.0
CC(C)C1=CC(Cl)=C(C)C=C1O	4-chloro-2-isopropyl-5-methylphenol	61.0
CC1=CC=CC=C1CO	2-methylbenzyl_alcohol	37.0
O=C1CCN(N1)C1=CC=CC=C1	1-phenylpyrazolidin-3-one	124.0
CN(C)C1=CC=CC(O)=C1	3-(Dimethylamino)phenol	84.0
CC1=CC(=CC(C)=C1)[N+]([O-])=O	5-nitro-1,3-dimethylbenzene	73.0
O=C(OC1=CC=CC=C1)OC1=CC=CC=C1	DIPHENYL CARBONATE	81.0
CC(C)CC(C)C	2,4-dimethylpentane	-121.0
CCCCCCCCCCC=O	UNDECANAL	-2.0
ClC(=O)C1=CC=C(Cl)C=C1	4-CHLOROBENZOYL CHLORIDE	14.0
C1CCOCC1	tetrahydropyran	-47.0
CCCCCCCCCCN	decan-1-amine	15.0
OC(=O)C(S)C(S)C(O)=O	2,3-disulfanylsuccinic acid	195.0
OC1=C(I)C=C(C=C1I)[N+]([O-])=O	2,6-Diiodo-4-nitrophenol	155.0
FC1=C2C=CC=CC2=CC=C1	1-FLUORONAPHTHALENE	-11.0
CC(C)(C)Br	tert-Butyl bromide	-18.0
CN=C=S	Isothiocyanatomethane	34.0
CC(C)(C)C1=CC=CC(O)=C1	3-tert-butylphenol	43.0
CC(=O)CCC(O)=O	LEVULINIC ACID	31.0
CCCCCC(C)C	2-Methylheptane	-107.0
OC1=C(Br)C(Br)=C(Br)C(Br)=C1Br	pentabromophenol	228.0
CC(C)(O)C1=CC=CC=C1	2-Phenyl-2-propanol	34.0
[O-][N+](=O)C1=CC=C(C=C1)C#N	P-NITROBENZONITRILE	147.0
CC1=CC(=CC=C1)C#N	m-Tolunitrile	-25.0
OC1=CC=C(OC2=CC=CC=C2)C=C1	4-phenoxyphenol	82.0
CC(=O)C1=CC=CO1	1-(2-Furyl)ethanone	31.0
CC1=CC(Cl)=CC=C1O	4-chloro-2-methylphenol	49.0
N#CC1=CC=C(C=C1)C1=CC=C(C=C1)C#N	biphenyl-4,4'-dicarbonitrile	236.0
OC(=O)C1=CC=CC(=C1)C#N	3-cyanobenzoic_acid	221.0
CC1(C)OC(=O)CC(=O)O1	Isopropylidene malonate	96.0
CC1=CC=C(C=C1)C(N)=O	p-Toluamide	161.0
CC1=CC(Cl)=NC2=C1C=CC=C2	2-Chloro-4-methylquinoline	57.0
CC(=O)OC1=CC=C(OC(C)=O)C=C1	1,4-Diacetoxybenzene	123.0
NC1=CC=CC=C1C#N	2-Aminobenzonitrile	49.0
CC(=O)NC1=CC=C(C=O)C=C1	4-Acetamidobenzaldehyde	158.0
CCCCCCCCC(=O)CC	3-UNDECANONE	11.0
COC1=CC=C(C=NC2=CC=CC=C2)C=C1	N-(4-Methoxybenzylidene)aniline	63.0
CN(C)C1=CC=C(\C=N\C2=CC=CC=C2)C=C1	N-(4-Dimethylaminobenzylidene)aniline	98.0
C1CCCC=CCC1	Cyclooctene	-14.0
COC1=CC=C(\C=C\C(=O)C2=CC=CC=C2)C=C1	4-Methoxychalcone	77.0
C1CNCCN1	Piperazine, anhydrous	108.0
CCOCCOCCO	2-(2-Ethoxyethoxy)ethanol	-78.0
COCCOCCOC	2-methoxyethyl_ether	-66.0
OC1=CC=CC(C=O)=C1	3-hydroxybenzaldehyde	106.0
ClCCOC1=CC=CC=C1	2-Phenoxyethyl chloride	26.0
COC1=CC=CC=C1O	2-Methoxyphenol	30.0
OC(=O)CCCC1=CC=CC=C1	4-Phenylbutyric acid	50.0
O=C1C(=O)C2=CC=CC=C2C2=CC=CC=C12	Phenanthrene-9,10-dione	208.0
CC1=CC=CC(C)=C1N	2,6-Dimethylaniline	10.0
CC(C)CC(C)=O	4-Methylpentan-2-one	-82.0
CCCCCCN	hexan-1-amine	-21.0
OCC(CO)(CO)CO	Pentaerythritol	260.0
C1C2=CC=CC=C2C2=CC3=CC=CC=C3C=C12	2,3-Benzofluorene Benzo[b]fluorene	210.0
COC1=CC=CC(=C1)C(O)=O	3-METHOXYBENZOIC ACID	105.0
CC1=C(C=CC=C1[N+]([O-])=O)[N+]([O-])=O	2-Methyl-1,3-dinitrobenzene	64.0
[O-][N+](=O)C1=CC=CC=C1CCl	1-(Chloromethyl)-2-nitrobenzene	49.0
COC1=C(Cl)C(Cl)=C(Cl)C(Cl)=C1	2,3,4,5-TETRACHLOROANISOLE	86.0
CC(=O)NC1=CC=C(C=C1)C(O)=O	4-Acetamidobenzoic acid	258.0
CC(=O)C1=CC(=CC=C1)C(C)=O	m-diacetylbenzene	34.0
[O-][N+](=O)C1=CC=C(OC2=C(C=C(C=C2)C(F)(F)F)[N+]([O-])=O)C=C1	FLUORODIFEN	92.0
CCC1=CC=C(O)C=C1	4-Ethylphenol	45.0
[O-][N+](=O)C1=CC=CC=C1I	1-Iodo-2-nitrobenzene	52.0
OC1=CC=CC=C1C1=CC=CC=C1	Biphenyl-2-ol	58.0
ClC(Cl)(Cl)C1=CC=CC=C1	(Trichloromethyl)benzene	-6.0
OCC=CC1=CC=CC=C1	(2E)-3-phenylprop-2-en-1-ol	32.0
COC1=CC=C(OC)C=C1	1,4-dimethoxybenzene	58.0
N1C2=CC=CC=C2C2=CC=CC=C12	carbazole	245.0
O=C(OC1=CC=CC=C1)C1=CC=CC=C1	phenyl_benzoate	69.0
CN(C)C(=O)NC1=CC=C(Cl)C=C1	monuron	172.0
BrC1=CC(Br)=C(Br)C=C1Br	1,2,4,5-Tetrabromobenzene	180.0
NC1=CC=C(C=C1)[N+]([O-])=O	4-nitroaniline	148.0
C1=CC=C2C(C=CC3=CC4=C(C=CC5=CC=CC=C45)C=C23)=C1	Dibenz[ah]anthracene	268.0
OC(=O)C1=CC=CC=C1Br	2-BROMOBENZOIC ACID	148.0
OC1=CC(=CC=C1)[N+]([O-])=O	3-nitrophenol	96.0
OC(=O)C1=CC=C(Br)C=C1	4-Bromobenzoic Acid	254.0
NS(=O)(=O)C1=C(Cl)C=C(NCC2=CC=CO2)C(=C1)C(O)=O	Furosemide	206.0
[O-][N+](=O)C1=CC(Cl)=C(Cl)C=C1	3,4-Dichloronitrobenzene	41.0
C(CC1=CC=CC=C1)C1=CC=CC=C1	bibenzyl	53.0
N1C2=CC=CC=C2SC2=CC=CC=C12	Phenothazine	186.0
COC(=O)C1=CC=C(O)C=C1	Methyl 4-hydroxybenzoate	129.0
CCOC(=O)C1=CC=C(N)C=C1	ethyl 4-aminobenzoate	90.0
C=CC=C	Buta-1,3-diene	-111.0
CC#N	Acetonitrile	-45.9
CCCCOCCO	2-butoxyethanol	-76.9
CCCCCCCCCCCCCCCCCO	heptadecan-1-ol	55.9
CC1=CC=CC(C=C)=C1	3-Methylstyrene	-84.2
CC(O)(C#C)C1=CC=CC=C1	2-Phenyl-3-butyn-2-ol	50.1
CC1=CC=CC=C1C(O)=O	2-Methylbenzoic acid	106.0
BrCCCCCCBr	1,6-Dibromohexane	-0.15
IC1=CC(I)=CC=C1	1,3-DIIODOBENZENE	38.2
OCCCCO	Butane-1,4-diol	18.2
CC1CCC(C)C1C	CYCLOPENTANE, 1,2,3-TRIMETHYL-, (1.ALPHA.,2.ALPH	-114.0
OCC(Br)(CO)[N+]([O-])=O	2-Bromo-2-nitropropane-1,3-diol	129.0
O=C(CCC(=O)OCC1=CC=CC=C1)OCC1=CC=CC=C1	DIBENZYL SUCCINATE	47.2
COC1=CC=C(C(=O)C2=CC=C(OC)C=C2O)C(O)=C1	2,2'-Dihydroxy-4,4'-dimethoxybenzophenone	137.0
OC(=O)C1=C(O)C(I)=CC(I)=C1	3,5-diiodosalicylic acid	233.0
FC1=CC=C(C=C1)C(=O)C1=CC=C(F)C=C1	4,4'-Difluorobenzophenone	106.0
OC(=O)C1=CC=CC=C1C1=CC=CC=C1C(O)=O	diphenic acid	231.0
OC(=O)C1=CC=CC=C1C1=C2C=C(Br)C(=O)C(Br)=C2OC2=C(Br)C(O)=C(Br)C=C12	2-(2,4,5,7-tetrabromo-6-hydroxy-3-oxo-3h-xanthen-9-yl)benzoic acid	298.0
CCCCCCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCC	Glycerol tripalmitate	64.2
OCCCCCCCO	1,7-Heptanediol	20.2
CC1(C)C2CCC(C)(C2)C1O	Bicyclo 2.2.1 heptan-2-ol, 1,3,3-trimethyl-, (1R	45.8
CC(=O)N1CCOCC1	N-ACETYLMORPHOLINE	12.2
CCCCCCCCCCCCCCCCC#C	1-Octadecyne	24.8
O=C1C=CC(=O)C2C3CC(C=C3)C12	tricyclo[6.2.1.0~2,7~]undeca-4,9-diene-3,6-dione	75.2
CCOC(=O)C(NC=O)C(=O)OCC	Diethyl formamidomalonate	50.8
SC1=NC=CN1	2-Mercaptoimidazole	227.0
COC(=O)[C@@H]1[C@H]2CC[C@@H](C[C@@H]1OC(=O)C1=CC=CC=C1)N2C	Cocaine	95.8
CC(C)(Br)C(O)=O	2-Bromoisobutyric acid	46.2
OC(=O)C(Cl)Br	Bromochloroacetic acid	29.2
CN(C)C1=CC=C(CC2=CC=C(C=C2)N(C)C)C=C1	4,4'-Methylenebis(N,N-dimethylaniline)	89.2
CN(C)CC(O)=O	N,N-DIMETHYLGLYCINE	183.0
OC(=O)CCCCCCCC(O)=O	azelaic acid	104.0
N1C2=CC=CC=C2N=C1C1=CSC=N1	2-(1,3-thiazol-4-yl)-1h-benzimidazole	300.0
CC1CNC(C)CN1	Piperazine, 2,5-dimethyl-, cis-	116.0
NC1=C(Cl)C=C(Cl)C=C1Cl	2,4,6-trichloroaniline	76.2
OP(O)(=O)CCCl	2-Chloroethylphosphonic acid	72.2
OC1C2=CC=CC=C2OC2=CC=CC=C12	9H-Xanthen-9-ol	125.0
COC1=CC=C2N=CC=C([C@H](O)[C@H]3C[C@@H]4CC[N@]3C[C@@H]4C=C)C2=C1	quinidine	172.0
CC(C)(N)CO	2-Amino-2-methylpropan-1-ol	27.8
COC1=CC=CC(OC)=C1OC	1,2,3-trimethoxybenzene	46.2
OC1=CC=C(O)C=C1	Hydroquinone	173.0
OC1=CC=CC=C1C#N	Salicylonitrile	95.8
OCCCl	2-chloroethanol	-65.2
CC\N=C1/N\C(NC(Cl)=N1)=N\C(C)C	atrazine	175.0
CC1=CC(NS(=O)(=O)C2=CC=C(N)C=C2)=NO1	sulfamethoxazole	169.0
OC1=CC=CC=C1I	2-IODOPHENOL	40.8
C1=CC2=C3C(=C1)C1=CC=CC4=C1C(=CC=C4)C3=CC=C2	perylene	276.0
C1C2=CC=CC=C2C2=CC=CC=C12	Fluorene	114.0
CC=O	acetaldehyde	-126.0
CC(C)(C)C(O)C(OC1=CC=C(Cl)C=C1)N1C=NC=N1	TRIADIMENOL	136.0
FC1=CC=C(Cl)C=C1	1-Chloro-4-fluorobenzene	-24.4
OC1=CC=NC=C1	4-hydroxypyridine	147.0
ClCCOCCCl	1-Chloro-2-(2-chloroethoxy)ethane	-49.5
FC(F)F	Fluoroform	-158.0
OC1CCCCC1	cyclohexanol	23.5
OC1=C(Br)C=C(Br)C2=C1N=CC=C2	5,7-Dibromo-8-hydroxyquinoline	198.0
CCCC(C)C1(CC=C)C(=O)NC(=O)NC1=O	Secobarbital	97.5
N[C@@H](CC1=CNC=N1)C(O)=O	L-histidine	284.0
CC(C)(C)OO	TERT-BUTYL HYDROPEROXIDE	-5.5
COS(=O)(=O)OC	DIMETHYL SULFATE	-29.5
CC1=CC=C2C(=O)C3=CC=CC=C3C(=O)C2=C1	2-Methylanthraquinone	174.0
OC(=O)CC1=C(Cl)C(Cl)=CC=C1Cl	(2,3,6-Trichlorophenyl)acetic acid	158.0
ClS(=O)(=O)C1=CC2=CC=CC=C2C=C1	Naphthalene-2-sulfonyl chloride	78.5
OC(=O)COCC(O)=O	Diglycolic acid	146.0
CCCCCCCCCCCCN(C)C	N,N-DIMETHYLDODECYLAMINE	-17.5
OC(=O)C1=CC(=CC=C1)C(O)=O	isophthalic_acid	344.0
CC(=O)NC1=CC=CC(F)=C1	3'-Fluoroacetanilide	85.5
O=C(CC1=CC=CC=C1)C1=CC=CC=C1	Deoxybenzoin	57.5
OCC1=CC2=C(OCO2)C=C1	3,4-(Methylenedioxy)benzyl alcohol	55.5
CC1=CC=CC=C1C(N)=O	o-Toluamide	144.0
OC(=O)C1=CC2=C(C=C1)C(=O)OC2=O	1,2,4-Benzenetricarboxylic anhydride	164.0
CC(C)C(Br)C(O)=O	2-Bromoisovaleric acid	41.5
NC1=CC=CC2=C1N=CC=C2	8-Aminoquinoline	67.5
[O-][N+](=O)C1=C2C=CC=CC2=CC2=CC=CC=C12	9-NITROANTHRACENE	144.0
[O-][N+](=O)C1=CC=CC2=C1C(=O)NC2=O	3-NITROPHTHALIMIDE	216.0
O=C1C=C(OC2=C1C=CC1=CC=CC=C21)C1=CC=CC=C1	2-Phenyl-4H-benzo[h]chromen-4-one	156.0
O=C1CC2=CC=CC=C2C1	2-INDANONE	56.5
CC1=CNC=N1	4-Methylimidazole	53.5
CCCCP(CCCC)CCCC	Tributylphosphine	-62.5
OC1=CC2=C(CCCC2)C=C1	5,6,7,8-tetrahydro-2-naphthol	59.5
CC1=CC2=C(C=CC=C2)C=N1	3-Methylisoquinoline	65.5
ClC1=CC=C(SSC2=CC=C(Cl)C=C2)C=C1	BIS(4-CHLOROPHENYL) DISULFIDE	70.5
OC1=CC2=C(CCC2)C=C1	5-INDANOL	55.5
CC(=O)C1=CC2=C(O1)C=CC=C2	2-acetylbenzo[b]furan	73.5
OC1=CC2=C(C=C1)C1(OC(=O)C3=CC=CC=C13)C1=CC=C(O)C=C1O2	fluorescein	318.0
CC1OC1C	OXIRANE, 2,3-DIMETHYL-, TRANS-	-82.5
OC(=O)C1=CC=C(CBr)C=C1	4-(BROMOMETHYL)BENZOIC ACID	228.0
OC(=O)COC1=CC=C(Cl)C=C1	4-chlorophenoxyacetic acid	162.0
NC1=C2C(=O)C3=CC=CC=C3C(=O)C2=C(N)C=C1	1,4-Diaminoanthraquinone	266.0
CC1=CC(C)=C(Br)C(C)=C1NC(=O)CN(CC(O)=O)CC(O)=O	(3-bromo-2,4,6-trimethylphenylcarbamoyl)methyliminodiacetic acid	196.0
ClC(=O)CCC1=CC=CC=C1	3-Phenylpropionyl chloride	-4.5
CC1(C)N(CO)C(=O)NC1=O	1-Hydroxymethyl-5,5-dimethylhydantoin	102.0
C1CN2CCCC3=C2C(C1)=CC=C3	Julolidine	37.5
FC1=C(F)C(=O)C(F)=C(F)C1=O	2,3,5,6-tetrafluoro-1,4-benzoquinone	182.0
NC1=NC=NC=C1	4-Aminopyrimidine	152.0
CCNC(=O)C(=O)NCC	N,N'-Diethyloxamide	178.0
BrC1=CC(=CC=C1)C(=O)C1=CC=CC=C1	3-brombenzophenone	78.5
CN1C(=O)CCC1=O	N-METHYLSUCCINIMIDE	68.5
OC(=O)CCCCCC1=CC=CC=C1	6-Phenylhexanoic acid	20.5
CC1=CC(N)=C2C=CC=CC2=N1	4-Amino-2-methylquinoline	166.0
COC1=CC=C(OC)C(C)=C1	2,5-Dimethoxytoluene	17.5
CO[C@@H]1O[C@H](CO)[C@H](O)[C@H](O)[C@H]1O	Methyl beta-D-galactopyranoside	174.0
ClC(Cl)(Cl)OC(=O)OC(Cl)(Cl)Cl	Triphosgene	81.5
IC1=CC=C(CC#N)C=C1	4-iodophenylacetonitrile	50.5
O[C@@H]([C@H](O)C(O)=O)C(O)=O	(2S,3S)-2,3-Dihydroxysuccinic acid	170.0
COC(=O)CS(=O)(=O)C1=CC=CC=C1	Methyl phenylsulfonylacetate	32.5
NC(=O)C1=CC=C(C=C1)C1=CC=CC=C1	biphenyl-4-carboxamide	226.0
NC(=S)NC1=CC=CC=C1	1-phenylthiourea	152.0
CN1N=NN=C1S	5-Mercapto-1-methyltetrazole	124.0
O=C(C=C1CC2=CC=CC=C12)C1=CC=CC=C1	(2E)-2-bicyclo[4.2.0]octa-1,3,5-trien-7-ylidene-1-phenylethanone	52.5
CCOC(=O)C1=CC=CC(=C1)[N+]([O-])=O	Ethyl 3-nitrobenzoate	44.5
NC(CC(O)=O)C(O)=O	ASPARTIC ACID	272.0
ClC1=CC2=C(C=C1)N(C1CCN(CCCN3C(=O)NC4=CC=CC=C34)CC1)C(=O)N2	5-chloro-1-{1-[3-(2-oxo-2,3-dihydro-1H-benzimidazol-1-yl)propyl]piperidin-4-yl}-1,3-dihydro-2H-benzimidazol-2-one	240.0
CCC1(C(C)C)C(=O)NC(=O)NC1=O	probarbital	200.0
OC(=O)CC1=CC=CC2=CC=CC=C12	1-Naphthylacetic acid	132.0
OC1=CC=C(C=C1)C1=CC=C(O)C=C1	4,4'-Dihydroxybiphenyl	280.0
CCOC(=O)CCl	ETHYL CHLOROACETATE	-23.5
COCC(C)O	1-Methoxypropan-2-ol	-97.5
CCCCCCC(C)=O	2-octanone	-18.5
CCCCCCCN	1-Heptylamine	-20.5
CCCCCCCCCCCCCCCCCCCCCC(O)=O	DOCOSANOIC ACID	78.5
C[Si]1(C)O[Si](C)(C)O[Si](C)(C)O1	2,2,4,4,6,6-Hexamethyl-1,3,5,2,4,6-trioxatrisilinane	62.5
BrC1=CC=C2C=CC=CC2=C1	2-bromonaphthalene	56.5
NC(=O)C1=CC=C(Cl)C=C1	p-chlorobenzamide	176.0
CC(=O)C1=CNC2=C1C=CC=C2	3-Acetylindole	192.0
C1=CC=C(C=C1)C1=C2C=CC=CC2=C(C2=CC=CC=C2)C2=CC=CC=C12	9,10-DIPHENYLANTHRACENE	248.0
ClC1=CC=CC(Cl)=C1Br	1-BROMO-2,6-DICHLOROBENZENE	63.5
ClC1=CC(C=O)=CC(Cl)=C1	3,5-Dichlorobenzaldehyde	65.5
COC(=O)C1=CC=C(C=C1)C#N	Methyl 4-cyanobenzoate	64.5
CC1=CC(O)=CC=C1Br	4-Bromo-3-methylphenol	61.5
CCOC(=O)C1=CC(C)=NN1	Ethyl 3-methyl-1H-pyrazole-5-carboxylate	84.5
SC1=NC2=CC=CC=C2N1	1H-Benzimidazole-2-thiol	298.0
[O-][N+](=O)C1=CC=C(O1)\C=N\N1CC(=O)NC1=O	nitrofurantoin	266.0
NC(=O)C1=CC=CC=C1N	o-Aminobenzamide	110.0
NCCNCCN	N-(2-aminoethyl)ethane-1,2-diamine	-37.5
CC1=CC=C(O)C(C)=C1	2,4-Dimethylphenol	24.5
CCCCC(CC)COC(=O)C1=CC=CC=C1C(=O)OCC(CC)CCCC	bis-2-ethylhexyl_phthalate	-52.5
CC1=CC(=O)C2=CC=CC=C2C1=O	2-Methyl-1,4-naphthoquinone	104.0
C[C@]12C[C@H](O)[C@H]3[C@@H](CCC4=CC(=O)C=C[C@]34C)[C@@H]1CC[C@]2(O)C(=O)CO	Prednisolone	238.0
[O-][N+](=O)C1=CC=CC2=CC=CC=C12	1-nitronaphthalene	59.5
CCCC(=O)OCC	ethyl butyrate	-95.5
C1CCC2=CC=CC=C2C1	1,2,3,4-Tetrahydronaphthalene	-33.5
CC(C)(C1=CC=CC=C1)C1=CC=C(O)C=C1	4-(2-phenylpropan-2-yl)phenol	72.5
OCC1=CC=C(Cl)C=C1	(4-Chlorophenyl)methanol	72.5
[O-][N+](=O)C1=CC(C=C)=CC=C1	1-Nitro-3-vinylbenzene	-7.5
CC(C)(CO)CO	2,2-Dimethylpropane-1,3-diol	128.0
OC(=O)C1=CC(=CC=C1O)C1=CC=C(F)C=C1F	Diflunisal	213.0
CC(C=CC=C(C)C=CC1=C(C)CCCC1(C)C)=CC=CC=C(C)C=CC=C(C)C=CC1=C(C)CCCC1(C)C	beta,beta-Carotene	180.0
OC(=O)C1=CC=C(C=C1)[N+]([O-])=O	4-nitrobenzoic acid	240.0
O=C1N(C2CCC(=O)NC2=O)C(=O)C2=CC=CC=C12	Thalidomide	272.0
C[C@]12CC[C@H]3[C@@H](CCC4=C3C=CC(O)=C4)[C@@H]1CC[C@@H]2O	Estradiol	176.0
OC1=C(Cl)C=C(Cl)C=C1Cl	2,4,6-trichlorophenol	67.5
NC1=CC=CC=C1C(F)(F)F	2-(TRIFLUOROMETHYL)ANILINE	-31.5
CCOC(=O)C1=CC=C(O)C=C1	Ethyl 4-hydroxybenzoate	116.0
CCC(C)=CC	3-Methyl-cis-2-pentene	-137.0
