CN(C)C(=O)c1ccc(cc1)OC	4-methoxy-N,N-dimethyl-benzamide	-11.01
CN(C)C(=O)c1ccc(cc1)OC	4-methoxy-N,N-dimethyl-benzamide	-11.01
CN(C)C(=O)c1ccc(cc1)OC	4-methoxy-N,N-dimethyl-benzamide	-11.01
CN(C)C(=O)c1ccc(cc1)OC	4-methoxy-N,N-dimethyl-benzamide	-11.01
CN(C)C(=O)c1ccc(cc1)OC	4-methoxy-N,N-dimethyl-benzamide	-11.01
CS(=O)(=O)Cl	methanesulfonyl chloride	-4.87
CS(=O)(=O)Cl	methanesulfonyl chloride	-4.87
CS(=O)(=O)Cl	methanesulfonyl chloride	-4.87
CS(=O)(=O)Cl	methanesulfonyl chloride	-4.87
CS(=O)(=O)Cl	methanesulfonyl chloride	-4.87
CC(C)C=C	3-methylbut-1-ene	1.83
CC(C)C=C	3-methylbut-1-ene	1.83
CC(C)C=C	3-methylbut-1-ene	1.83
CC(C)C=C	3-methylbut-1-ene	1.83
CC(C)C=C	3-methylbut-1-ene	1.83
CCc1cnccn1	2-ethylpyrazine	-5.45
CCc1cnccn1	2-ethylpyrazine	-5.45
CCc1cnccn1	2-ethylpyrazine	-5.45
CCc1cnccn1	2-ethylpyrazine	-5.45
CCc1cnccn1	2-ethylpyrazine	-5.45
CCCCCCCO	heptan-1-ol	-4.21
CCCCCCCO	heptan-1-ol	-4.21
CCCCCCCO	heptan-1-ol	-4.21
CCCCCCCO	heptan-1-ol	-4.21
CCCCCCCO	heptan-1-ol	-4.21
Cc1cc(cc(c1)O)C	3,5-dimethylphenol	-6.27
Cc1cc(cc(c1)O)C	3,5-dimethylphenol	-6.27
Cc1cc(cc(c1)O)C	3,5-dimethylphenol	-6.27
Cc1cc(cc(c1)O)C	3,5-dimethylphenol	-6.27
Cc1cc(cc(c1)O)C	3,5-dimethylphenol	-6.27
CC(C)C(C)C	2,3-dimethylbutane	2.34
CC(C)C(C)C	2,3-dimethylbutane	2.34
CC(C)C(C)C	2,3-dimethylbutane	2.34
CC(C)C(C)C	2,3-dimethylbutane	2.34
CC(C)C(C)C	2,3-dimethylbutane	2.34
CCCC(C)(C)O	2-methylpentan-2-ol	-3.92
CCCC(C)(C)O	2-methylpentan-2-ol	-3.92
CCCC(C)(C)O	2-methylpentan-2-ol	-3.92
CCCC(C)(C)O	2-methylpentan-2-ol	-3.92
CCCC(C)(C)O	2-methylpentan-2-ol	-3.92
C[C@@H]1CCCC[C@@H]1C	1,2-dimethylcyclohexane	1.58
C[C@@H]1CCCC[C@@H]1C	1,2-dimethylcyclohexane	1.58
C[C@@H]1CCCC[C@@H]1C	1,2-dimethylcyclohexane	1.58
C[C@@H]1CCCC[C@@H]1C	1,2-dimethylcyclohexane	1.58
C[C@@H]1CCCC[C@@H]1C	1,2-dimethylcyclohexane	1.58
CC[C@H](C)O	butan-2-ol	-4.62
CC[C@H](C)O	butan-2-ol	-4.62
CC[C@H](C)O	butan-2-ol	-4.62
CC[C@H](C)O	butan-2-ol	-4.62
CC[C@H](C)O	butan-2-ol	-4.62
C(Br)Br	dibromomethane	-1.96
C(Br)Br	dibromomethane	-1.96
C(Br)Br	dibromomethane	-1.96
C(Br)Br	dibromomethane	-1.96
C(Br)Br	dibromomethane	-1.96
CC[C@H](C(C)C)O	2-methylpentan-3-ol	-3.88
CC[C@H](C(C)C)O	2-methylpentan-3-ol	-3.88
CC[C@H](C(C)C)O	2-methylpentan-3-ol	-3.88
CC[C@H](C(C)C)O	2-methylpentan-3-ol	-3.88
CC[C@H](C(C)C)O	2-methylpentan-3-ol	-3.88
CCc1ccccn1	2-ethylpyridine	-4.33
CCc1ccccn1	2-ethylpyridine	-4.33
CCc1ccccn1	2-ethylpyridine	-4.33
CCc1ccccn1	2-ethylpyridine	-4.33
CCc1ccccn1	2-ethylpyridine	-4.33
CCCCC(=O)OCC	ethyl pentanoate	-2.49
CCCCC(=O)OCC	ethyl pentanoate	-2.49
CCCCC(=O)OCC	ethyl pentanoate	-2.49
CCCCC(=O)OCC	ethyl pentanoate	-2.49
CCCCC(=O)OCC	ethyl pentanoate	-2.49
c1ccc(cc1)S	benzenethiol	-2.55
c1ccc(cc1)S	benzenethiol	-2.55
c1ccc(cc1)S	benzenethiol	-2.55
c1ccc(cc1)S	benzenethiol	-2.55
c1ccc(cc1)S	benzenethiol	-2.55
CC(=CCC/C(=C\CO)/C)C	(2Z)-3,7-dimethylocta-2,6-dien-1-ol	-4.78
CC(=CCC/C(=C\CO)/C)C	(2Z)-3,7-dimethylocta-2,6-dien-1-ol	-4.78
CC(=CCC/C(=C\CO)/C)C	(2Z)-3,7-dimethylocta-2,6-dien-1-ol	-4.78
CC(=CCC/C(=C\CO)/C)C	(2Z)-3,7-dimethylocta-2,6-dien-1-ol	-4.78
CC(=CCC/C(=C\CO)/C)C	(2Z)-3,7-dimethylocta-2,6-dien-1-ol	-4.78
c1ccc2c(c1)CCC2	indane	-1.46
c1ccc2c(c1)CCC2	indane	-1.46
c1ccc2c(c1)CCC2	indane	-1.46
c1ccc2c(c1)CCC2	indane	-1.46
c1ccc2c(c1)CCC2	indane	-1.46
CCOc1ccccc1	ethoxybenzene	-2.22
CCOc1ccccc1	ethoxybenzene	-2.22
CCOc1ccccc1	ethoxybenzene	-2.22
CCOc1ccccc1	ethoxybenzene	-2.22
CCOc1ccccc1	ethoxybenzene	-2.22
c1cc(ccc1O)Br	4-bromophenol	-5.85
c1cc(ccc1O)Br	4-bromophenol	-5.85
c1cc(ccc1O)Br	4-bromophenol	-5.85
c1cc(ccc1O)Br	4-bromophenol	-5.85
c1cc(ccc1O)Br	4-bromophenol	-5.85
CCCC(C)(C)C	2,2-dimethylpentane	2.88
CCCC(C)(C)C	2,2-dimethylpentane	2.88
CCCC(C)(C)C	2,2-dimethylpentane	2.88
CCCC(C)(C)C	2,2-dimethylpentane	2.88
CCCC(C)(C)C	2,2-dimethylpentane	2.88
CC(=O)OCCOC(=O)C	2-acetoxyethyl acetate	-6.34
CC(=O)OCCOC(=O)C	2-acetoxyethyl acetate	-6.34
CC(=O)OCCOC(=O)C	2-acetoxyethyl acetate	-6.34
CC(=O)OCCOC(=O)C	2-acetoxyethyl acetate	-6.34
CC(=O)OCCOC(=O)C	2-acetoxyethyl acetate	-6.34
CCOP(=S)(OCC)SCSP(=S)(OCC)OCC	ethion	-6.1
CCOP(=S)(OCC)SCSP(=S)(OCC)OCC	ethion	-6.1
CCOP(=S)(OCC)SCSP(=S)(OCC)OCC	ethion	-6.1
CCOP(=S)(OCC)SCSP(=S)(OCC)OCC	ethion	-6.1
CCOP(=S)(OCC)SCSP(=S)(OCC)OCC	ethion	-6.1
C1CCCC(CC1)O	cycloheptanol	-5.48
C1CCCC(CC1)O	cycloheptanol	-5.48
C1CCCC(CC1)O	cycloheptanol	-5.48
C1CCCC(CC1)O	cycloheptanol	-5.48
C1CCCC(CC1)O	cycloheptanol	-5.48
COC(=O)C1CC1	methyl cyclopropanecarboxylate	-4.1
COC(=O)C1CC1	methyl cyclopropanecarboxylate	-4.1
COC(=O)C1CC1	methyl cyclopropanecarboxylate	-4.1
COC(=O)C1CC1	methyl cyclopropanecarboxylate	-4.1
COC(=O)C1CC1	methyl cyclopropanecarboxylate	-4.1
c1ccc(cc1)C#N	benzonitrile	-4.1
c1ccc(cc1)C#N	benzonitrile	-4.1
c1ccc(cc1)C#N	benzonitrile	-4.1
c1ccc(cc1)C#N	benzonitrile	-4.1
c1ccc(cc1)C#N	benzonitrile	-4.1
CCCCC#N	pentanenitrile	-3.52
CCCCC#N	pentanenitrile	-3.52
CCCCC#N	pentanenitrile	-3.52
CCCCC#N	pentanenitrile	-3.52
CCCCC#N	pentanenitrile	-3.52
CC(C)(C)O	2-methylpropan-2-ol	-4.47
CC(C)(C)O	2-methylpropan-2-ol	-4.47
CC(C)(C)O	2-methylpropan-2-ol	-4.47
CC(C)(C)O	2-methylpropan-2-ol	-4.47
CC(C)(C)O	2-methylpropan-2-ol	-4.47
CC(C)C(=O)C(C)C	2,4-dimethylpentan-3-one	-2.74
CC(C)C(=O)C(C)C	2,4-dimethylpentan-3-one	-2.74
CC(C)C(=O)C(C)C	2,4-dimethylpentan-3-one	-2.74
CC(C)C(=O)C(C)C	2,4-dimethylpentan-3-one	-2.74
CC(C)C(=O)C(C)C	2,4-dimethylpentan-3-one	-2.74
CCC=O	propanal	-3.43
CCC=O	propanal	-3.43
CCC=O	propanal	-3.43
CCC=O	propanal	-3.43
CCC=O	propanal	-3.43
CN(C)C=O	N,N-dimethylformamide	-7.81
CN(C)C=O	N,N-dimethylformamide	-7.81
CN(C)C=O	N,N-dimethylformamide	-7.81
CN(C)C=O	N,N-dimethylformamide	-7.81
CN(C)C=O	N,N-dimethylformamide	-7.81
Cc1ccc(cc1)C	p-xylene	-0.8
Cc1ccc(cc1)C	p-xylene	-0.8
Cc1ccc(cc1)C	p-xylene	-0.8
Cc1ccc(cc1)C	p-xylene	-0.8
Cc1ccc(cc1)C	p-xylene	-0.8
C=CCC=C	penta-1,4-diene	0.93
C=CCC=C	penta-1,4-diene	0.93
C=CCC=C	penta-1,4-diene	0.93
C=CCC=C	penta-1,4-diene	0.93
C=CCC=C	penta-1,4-diene	0.93
Cc1cccc(c1C)Nc2ccccc2C(=O)O	2-(2,3-dimethylphenyl)aminobenzoic acid	-6.78
Cc1cccc(c1C)Nc2ccccc2C(=O)O	2-(2,3-dimethylphenyl)aminobenzoic acid	-6.78
Cc1cccc(c1C)Nc2ccccc2C(=O)O	2-(2,3-dimethylphenyl)aminobenzoic acid	-6.78
Cc1cccc(c1C)Nc2ccccc2C(=O)O	2-(2,3-dimethylphenyl)aminobenzoic acid	-6.78
Cc1cccc(c1C)Nc2ccccc2C(=O)O	2-(2,3-dimethylphenyl)aminobenzoic acid	-6.78
CN(C)C(=O)c1ccccc1	N,N-dimethylbenzamide	-9.29
CN(C)C(=O)c1ccccc1	N,N-dimethylbenzamide	-9.29
CN(C)C(=O)c1ccccc1	N,N-dimethylbenzamide	-9.29
CN(C)C(=O)c1ccccc1	N,N-dimethylbenzamide	-9.29
CN(C)C(=O)c1ccccc1	N,N-dimethylbenzamide	-9.29
CCNCC	N-ethylethanamine	-4.07
CCNCC	N-ethylethanamine	-4.07
CCNCC	N-ethylethanamine	-4.07
CCNCC	N-ethylethanamine	-4.07
CCNCC	N-ethylethanamine	-4.07
CC(C)(C)c1ccc(cc1)O	4-tert-butylphenol	-5.91
CC(C)(C)c1ccc(cc1)O	4-tert-butylphenol	-5.91
CC(C)(C)c1ccc(cc1)O	4-tert-butylphenol	-5.91
CC(C)(C)c1ccc(cc1)O	4-tert-butylphenol	-5.91
CC(C)(C)c1ccc(cc1)O	4-tert-butylphenol	-5.91
CC(C)CCOC=O	isopentyl formate	-2.13
CC(C)CCOC=O	isopentyl formate	-2.13
CC(C)CCOC=O	isopentyl formate	-2.13
CC(C)CCOC=O	isopentyl formate	-2.13
CC(C)CCOC=O	isopentyl formate	-2.13
CCCCCCCCCCO	decan-1-ol	-3.64
CCCCCCCCCCO	decan-1-ol	-3.64
CCCCCCCCCCO	decan-1-ol	-3.64
CCCCCCCCCCO	decan-1-ol	-3.64
CCCCCCCCCCO	decan-1-ol	-3.64
CCC(=O)OCC	ethyl propanoate	-2.68
CCC(=O)OCC	ethyl propanoate	-2.68
CCC(=O)OCC	ethyl propanoate	-2.68
CCC(=O)OCC	ethyl propanoate	-2.68
CCC(=O)OCC	ethyl propanoate	-2.68
CCCCCCCCC	nonane	3.13
CCCCCCCCC	nonane	3.13
CCCCCCCCC	nonane	3.13
CCCCCCCCC	nonane	3.13
CCCCCCCCC	nonane	3.13
CC(=O)NC	N-methylacetamide	-10.0
CC(=O)NC	N-methylacetamide	-10.0
CC(=O)NC	N-methylacetamide	-10.0
CC(=O)NC	N-methylacetamide	-10.0
CC(=O)NC	N-methylacetamide	-10.0
CCCCCCCC=C	non-1-ene	2.06
CCCCCCCC=C	non-1-ene	2.06
CCCCCCCC=C	non-1-ene	2.06
CCCCCCCC=C	non-1-ene	2.06
CCCCCCCC=C	non-1-ene	2.06
c1ccc2cc(ccc2c1)O	naphthalen-2-ol	-8.11
c1ccc2cc(ccc2c1)O	naphthalen-2-ol	-8.11
c1ccc2cc(ccc2c1)O	naphthalen-2-ol	-8.11
c1ccc2cc(ccc2c1)O	naphthalen-2-ol	-8.11
c1ccc2cc(ccc2c1)O	naphthalen-2-ol	-8.11
c1cc(c(cc1Cl)Cl)Cl	1,2,4-trichlorobenzene	-1.12
c1cc(c(cc1Cl)Cl)Cl	1,2,4-trichlorobenzene	-1.12
c1cc(c(cc1Cl)Cl)Cl	1,2,4-trichlorobenzene	-1.12
c1cc(c(cc1Cl)Cl)Cl	1,2,4-trichlorobenzene	-1.12
c1cc(c(cc1Cl)Cl)Cl	1,2,4-trichlorobenzene	-1.12
C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O	(2R,3R,4R,5R)-Hexan-1,2,3,4,5,6-hexol	-23.62
C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O	(2R,3R,4R,5R)-Hexan-1,2,3,4,5,6-hexol	-23.62
C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O	(2R,3R,4R,5R)-Hexan-1,2,3,4,5,6-hexol	-23.62
C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O	(2R,3R,4R,5R)-Hexan-1,2,3,4,5,6-hexol	-23.62
C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O	(2R,3R,4R,5R)-Hexan-1,2,3,4,5,6-hexol	-23.62
CCCC(=O)OC	methyl butanoate	-2.83
CCCC(=O)OC	methyl butanoate	-2.83
CCCC(=O)OC	methyl butanoate	-2.83
CCCC(=O)OC	methyl butanoate	-2.83
CCCC(=O)OC	methyl butanoate	-2.83
c1ccc(c(c1)C=O)O	2-hydroxybenzaldehyde	-4.68
c1ccc(c(c1)C=O)O	2-hydroxybenzaldehyde	-4.68
c1ccc(c(c1)C=O)O	2-hydroxybenzaldehyde	-4.68
c1ccc(c(c1)C=O)O	2-hydroxybenzaldehyde	-4.68
c1ccc(c(c1)C=O)O	2-hydroxybenzaldehyde	-4.68
C1CNC1	azetidine	-5.56
C1CNC1	azetidine	-5.56
C1CNC1	azetidine	-5.56
C1CNC1	azetidine	-5.56
C1CNC1	azetidine	-5.56
CCCNCCC	N-propylpropan-1-amine	-3.65
CCCNCCC	N-propylpropan-1-amine	-3.65
CCCNCCC	N-propylpropan-1-amine	-3.65
CCCNCCC	N-propylpropan-1-amine	-3.65
CCCNCCC	N-propylpropan-1-amine	-3.65
c1ccc(cc1)N	aniline	-5.49
c1ccc(cc1)N	aniline	-5.49
c1ccc(cc1)N	aniline	-5.49
c1ccc(cc1)N	aniline	-5.49
c1ccc(cc1)N	aniline	-5.49
C(F)(F)(F)F	tetrafluoromethane	3.12
C(F)(F)(F)F	tetrafluoromethane	3.12
C(F)(F)(F)F	tetrafluoromethane	3.12
C(F)(F)(F)F	tetrafluoromethane	3.12
C(F)(F)(F)F	tetrafluoromethane	3.12
CC[C@@H](C)CO	2-methylbutan-1-ol	-4.42
CC[C@@H](C)CO	2-methylbutan-1-ol	-4.42
CC[C@@H](C)CO	2-methylbutan-1-ol	-4.42
CC[C@@H](C)CO	2-methylbutan-1-ol	-4.42
CC[C@@H](C)CO	2-methylbutan-1-ol	-4.42
c1ccc(c(c1)O)I	2-iodophenol	-6.2
c1ccc(c(c1)O)I	2-iodophenol	-6.2
c1ccc(c(c1)O)I	2-iodophenol	-6.2
c1ccc(c(c1)O)I	2-iodophenol	-6.2
c1ccc(c(c1)O)I	2-iodophenol	-6.2
COc1cccc(c1O)OC	2,6-dimethoxyphenol	-6.96
COc1cccc(c1O)OC	2,6-dimethoxyphenol	-6.96
COc1cccc(c1O)OC	2,6-dimethoxyphenol	-6.96
COc1cccc(c1O)OC	2,6-dimethoxyphenol	-6.96
COc1cccc(c1O)OC	2,6-dimethoxyphenol	-6.96
CCC#C	but-1-yne	-0.16
CCC#C	but-1-yne	-0.16
CCC#C	but-1-yne	-0.16
CCC#C	but-1-yne	-0.16
CCC#C	but-1-yne	-0.16
c1ccc(cc1)C(F)(F)F	trifluoromethylbenzene	-0.25
c1ccc(cc1)C(F)(F)F	trifluoromethylbenzene	-0.25
c1ccc(cc1)C(F)(F)F	trifluoromethylbenzene	-0.25
c1ccc(cc1)C(F)(F)F	trifluoromethylbenzene	-0.25
c1ccc(cc1)C(F)(F)F	trifluoromethylbenzene	-0.25
NN	hydrazine	-9.3
NN	hydrazine	-9.3
NN	hydrazine	-9.3
NN	hydrazine	-9.3
NN	hydrazine	-9.3
Cc1ccccn1	2-methylpyridine	-4.63
Cc1ccccn1	2-methylpyridine	-4.63
Cc1ccccn1	2-methylpyridine	-4.63
Cc1ccccn1	2-methylpyridine	-4.63
Cc1ccccn1	2-methylpyridine	-4.63
CCNc1nc(nc(n1)Cl)NCC	simazine	-10.22
CCNc1nc(nc(n1)Cl)NCC	simazine	-10.22
CCNc1nc(nc(n1)Cl)NCC	simazine	-10.22
CCNc1nc(nc(n1)Cl)NCC	simazine	-10.22
CCNc1nc(nc(n1)Cl)NCC	simazine	-10.22
c1ccc2c(c1)Oc3cc(c(cc3O2)Cl)Cl	2,3-dichlorodibenzo-p-dioxin	-3.56
c1ccc2c(c1)Oc3cc(c(cc3O2)Cl)Cl	2,3-dichlorodibenzo-p-dioxin	-3.56
c1ccc2c(c1)Oc3cc(c(cc3O2)Cl)Cl	2,3-dichlorodibenzo-p-dioxin	-3.56
c1ccc2c(c1)Oc3cc(c(cc3O2)Cl)Cl	2,3-dichlorodibenzo-p-dioxin	-3.56
c1ccc2c(c1)Oc3cc(c(cc3O2)Cl)Cl	2,3-dichlorodibenzo-p-dioxin	-3.56
CCCCCCCCN	octan-1-amine	-3.65
CCCCCCCCN	octan-1-amine	-3.65
CCCCCCCCN	octan-1-amine	-3.65
CCCCCCCCN	octan-1-amine	-3.65
CCCCCCCCN	octan-1-amine	-3.65
N	ammonia	-4.29
N	ammonia	-4.29
N	ammonia	-4.29
N	ammonia	-4.29
N	ammonia	-4.29
c1ccc(c(c1)C(F)(F)F)C(F)(F)F	1,2-bis(trifluoromethyl)benzene	1.07
c1ccc(c(c1)C(F)(F)F)C(F)(F)F	1,2-bis(trifluoromethyl)benzene	1.07
c1ccc(c(c1)C(F)(F)F)C(F)(F)F	1,2-bis(trifluoromethyl)benzene	1.07
c1ccc(c(c1)C(F)(F)F)C(F)(F)F	1,2-bis(trifluoromethyl)benzene	1.07
c1ccc(c(c1)C(F)(F)F)C(F)(F)F	1,2-bis(trifluoromethyl)benzene	1.07
COC(=O)c1ccc(cc1)O	methyl paraben	-9.51
COC(=O)c1ccc(cc1)O	methyl paraben	-9.51
COC(=O)c1ccc(cc1)O	methyl paraben	-9.51
COC(=O)c1ccc(cc1)O	methyl paraben	-9.51
COC(=O)c1ccc(cc1)O	methyl paraben	-9.51
CCCCCc1ccccc1	pentylbenzene	-0.23
CCCCCc1ccccc1	pentylbenzene	-0.23
CCCCCc1ccccc1	pentylbenzene	-0.23
CCCCCc1ccccc1	pentylbenzene	-0.23
CCCCCc1ccccc1	pentylbenzene	-0.23
CC(F)F	1,1-difluoroethane	-0.11
CC(F)F	1,1-difluoroethane	-0.11
CC(F)F	1,1-difluoroethane	-0.11
CC(F)F	1,1-difluoroethane	-0.11
CC(F)F	1,1-difluoroethane	-0.11
c1ccc(cc1)n2c(=O)c(c(cn2)N)Cl	5-Amino-4-chloro-2-phenylpyridazin-3(2H)-one	-16.43
c1ccc(cc1)n2c(=O)c(c(cn2)N)Cl	5-Amino-4-chloro-2-phenylpyridazin-3(2H)-one	-16.43
c1ccc(cc1)n2c(=O)c(c(cn2)N)Cl	5-Amino-4-chloro-2-phenylpyridazin-3(2H)-one	-16.43
c1ccc(cc1)n2c(=O)c(c(cn2)N)Cl	5-Amino-4-chloro-2-phenylpyridazin-3(2H)-one	-16.43
c1ccc(cc1)n2c(=O)c(c(cn2)N)Cl	5-Amino-4-chloro-2-phenylpyridazin-3(2H)-one	-16.43
C=CC=C	butadiene	0.56
C=CC=C	butadiene	0.56
C=CC=C	butadiene	0.56
C=CC=C	butadiene	0.56
C=CC=C	butadiene	0.56
CN(C)C	N,N-dimethylmethanamine	-3.2
CN(C)C	N,N-dimethylmethanamine	-3.2
CN(C)C	N,N-dimethylmethanamine	-3.2
CN(C)C	N,N-dimethylmethanamine	-3.2
CN(C)C	N,N-dimethylmethanamine	-3.2
CCCCCC(=O)N	hexanamide	-9.31
CCCCCC(=O)N	hexanamide	-9.31
CCCCCC(=O)N	hexanamide	-9.31
CCCCCC(=O)N	hexanamide	-9.31
CCCCCC(=O)N	hexanamide	-9.31
CC(C)CO[N+](=O)[O-]	isobutyl nitrate	-1.88
CC(C)CO[N+](=O)[O-]	isobutyl nitrate	-1.88
CC(C)CO[N+](=O)[O-]	isobutyl nitrate	-1.88
CC(C)CO[N+](=O)[O-]	isobutyl nitrate	-1.88
CC(C)CO[N+](=O)[O-]	isobutyl nitrate	-1.88
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)NCCO	1-(2-hydroxyethylamino)-9,10-anthraquinone	-14.21
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)NCCO	1-(2-hydroxyethylamino)-9,10-anthraquinone	-14.21
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)NCCO	1-(2-hydroxyethylamino)-9,10-anthraquinone	-14.21
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)NCCO	1-(2-hydroxyethylamino)-9,10-anthraquinone	-14.21
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)NCCO	1-(2-hydroxyethylamino)-9,10-anthraquinone	-14.21
C(CO[N+](=O)[O-])O	2-(nitrooxy)ethan-1-ol	-8.18
C(CO[N+](=O)[O-])O	2-(nitrooxy)ethan-1-ol	-8.18
C(CO[N+](=O)[O-])O	2-(nitrooxy)ethan-1-ol	-8.18
C(CO[N+](=O)[O-])O	2-(nitrooxy)ethan-1-ol	-8.18
C(CO[N+](=O)[O-])O	2-(nitrooxy)ethan-1-ol	-8.18
CCCCCCC(=O)C	octan-2-one	-2.88
CCCCCCC(=O)C	octan-2-one	-2.88
CCCCCCC(=O)C	octan-2-one	-2.88
CCCCCCC(=O)C	octan-2-one	-2.88
CCCCCCC(=O)C	octan-2-one	-2.88
CN1CCNCC1	1-methylpiperazine	-7.77
CN1CCNCC1	1-methylpiperazine	-7.77
CN1CCNCC1	1-methylpiperazine	-7.77
CN1CCNCC1	1-methylpiperazine	-7.77
CN1CCNCC1	1-methylpiperazine	-7.77
CCN	ethanamine	-4.5
CCN	ethanamine	-4.5
CCN	ethanamine	-4.5
CCN	ethanamine	-4.5
CCN	ethanamine	-4.5
C1C=CC=CC=C1	cyclohepta-1,3,5-triene	-0.99
C1C=CC=CC=C1	cyclohepta-1,3,5-triene	-0.99
C1C=CC=CC=C1	cyclohepta-1,3,5-triene	-0.99
C1C=CC=CC=C1	cyclohepta-1,3,5-triene	-0.99
C1C=CC=CC=C1	cyclohepta-1,3,5-triene	-0.99
c1ccc2c(c1)Cc3ccccc3C2	9,10-dihydroanthracene	-3.78
c1ccc2c(c1)Cc3ccccc3C2	9,10-dihydroanthracene	-3.78
c1ccc2c(c1)Cc3ccccc3C2	9,10-dihydroanthracene	-3.78
c1ccc2c(c1)Cc3ccccc3C2	9,10-dihydroanthracene	-3.78
c1ccc2c(c1)Cc3ccccc3C2	9,10-dihydroanthracene	-3.78
CC(Cl)Cl	1,1-dichloroethane	-0.84
CC(Cl)Cl	1,1-dichloroethane	-0.84
CC(Cl)Cl	1,1-dichloroethane	-0.84
CC(Cl)Cl	1,1-dichloroethane	-0.84
CC(Cl)Cl	1,1-dichloroethane	-0.84
COc1cccc(c1)O	3-methoxyphenol	-7.66
COc1cccc(c1)O	3-methoxyphenol	-7.66
COc1cccc(c1)O	3-methoxyphenol	-7.66
COc1cccc(c1)O	3-methoxyphenol	-7.66
COc1cccc(c1)O	3-methoxyphenol	-7.66
c1cc2cccc3c2c(c1)CC3	acenaphthene	-3.15
c1cc2cccc3c2c(c1)CC3	acenaphthene	-3.15
c1cc2cccc3c2c(c1)CC3	acenaphthene	-3.15
c1cc2cccc3c2c(c1)CC3	acenaphthene	-3.15
c1cc2cccc3c2c(c1)CC3	acenaphthene	-3.15
CCCCCCCCBr	1-bromooctane	0.52
CCCCCCCCBr	1-bromooctane	0.52
CCCCCCCCBr	1-bromooctane	0.52
CCCCCCCCBr	1-bromooctane	0.52
CCCCCCCCBr	1-bromooctane	0.52
c1ccc(cc1)CO	phenylmethanol	-6.62
c1ccc(cc1)CO	phenylmethanol	-6.62
c1ccc(cc1)CO	phenylmethanol	-6.62
c1ccc(cc1)CO	phenylmethanol	-6.62
c1ccc(cc1)CO	phenylmethanol	-6.62
c1c(c(=O)[nH]c(=O)[nH]1)Br	5-bromouracil	-18.17
c1c(c(=O)[nH]c(=O)[nH]1)Br	5-bromouracil	-18.17
c1c(c(=O)[nH]c(=O)[nH]1)Br	5-bromouracil	-18.17
c1c(c(=O)[nH]c(=O)[nH]1)Br	5-bromouracil	-18.17
c1c(c(=O)[nH]c(=O)[nH]1)Br	5-bromouracil	-18.17
CCCC	n-butane	2.1
CCCC	n-butane	2.1
CCCC	n-butane	2.1
CCCC	n-butane	2.1
CCCC	n-butane	2.1
CCl	chloromethane	-0.55
CCl	chloromethane	-0.55
CCl	chloromethane	-0.55
CCl	chloromethane	-0.55
CCl	chloromethane	-0.55
CC(C)CBr	1-bromo-2-methyl-propane	-0.03
CC(C)CBr	1-bromo-2-methyl-propane	-0.03
CC(C)CBr	1-bromo-2-methyl-propane	-0.03
CC(C)CBr	1-bromo-2-methyl-propane	-0.03
CC(C)CBr	1-bromo-2-methyl-propane	-0.03
CC(C)SC(C)C	2-isopropylsulfanylpropane	-1.21
CC(C)SC(C)C	2-isopropylsulfanylpropane	-1.21
CC(C)SC(C)C	2-isopropylsulfanylpropane	-1.21
CC(C)SC(C)C	2-isopropylsulfanylpropane	-1.21
CC(C)SC(C)C	2-isopropylsulfanylpropane	-1.21
CCCCCCC	heptane	2.67
CCCCCCC	heptane	2.67
CCCCCCC	heptane	2.67
CCCCCCC	heptane	2.67
CCCCCCC	heptane	2.67
c1cnc[nH]1	imidazole	-9.63
c1cnc[nH]1	imidazole	-9.63
c1cnc[nH]1	imidazole	-9.63
c1cnc[nH]1	imidazole	-9.63
c1cnc[nH]1	imidazole	-9.63
c1cc2c(cc1Cl)Oc3cc(c(c(c3O2)Cl)Cl)Cl	1,2,3,7-tetrachlorodibenzo-p-dioxin	-3.84
c1cc2c(cc1Cl)Oc3cc(c(c(c3O2)Cl)Cl)Cl	1,2,3,7-tetrachlorodibenzo-p-dioxin	-3.84
c1cc2c(cc1Cl)Oc3cc(c(c(c3O2)Cl)Cl)Cl	1,2,3,7-tetrachlorodibenzo-p-dioxin	-3.84
c1cc2c(cc1Cl)Oc3cc(c(c(c3O2)Cl)Cl)Cl	1,2,3,7-tetrachlorodibenzo-p-dioxin	-3.84
c1cc2c(cc1Cl)Oc3cc(c(c(c3O2)Cl)Cl)Cl	1,2,3,7-tetrachlorodibenzo-p-dioxin	-3.84
CC[C@H](C)n1c(=O)c(c([nH]c1=O)C)Br	bromacil	-9.73
CC[C@H](C)n1c(=O)c(c([nH]c1=O)C)Br	bromacil	-9.73
CC[C@H](C)n1c(=O)c(c([nH]c1=O)C)Br	bromacil	-9.73
CC[C@H](C)n1c(=O)c(c([nH]c1=O)C)Br	bromacil	-9.73
CC[C@H](C)n1c(=O)c(c([nH]c1=O)C)Br	bromacil	-9.73
C(I)I	diiodomethane	-2.49
C(I)I	diiodomethane	-2.49
C(I)I	diiodomethane	-2.49
C(I)I	diiodomethane	-2.49
C(I)I	diiodomethane	-2.49
CCCN(CCC)C(=O)SCCC	N,N-dipropyl(propylsulfanyl)formamide	-4.13
CCCN(CCC)C(=O)SCCC	N,N-dipropyl(propylsulfanyl)formamide	-4.13
CCCN(CCC)C(=O)SCCC	N,N-dipropyl(propylsulfanyl)formamide	-4.13
CCCN(CCC)C(=O)SCCC	N,N-dipropyl(propylsulfanyl)formamide	-4.13
CCCN(CCC)C(=O)SCCC	N,N-dipropyl(propylsulfanyl)formamide	-4.13
C[N+](=O)[O-]	nitromethane	-4.02
C[N+](=O)[O-]	nitromethane	-4.02
C[N+](=O)[O-]	nitromethane	-4.02
C[N+](=O)[O-]	nitromethane	-4.02
C[N+](=O)[O-]	nitromethane	-4.02
CCOC	methoxyethane	-2.1
CCOC	methoxyethane	-2.1
CCOC	methoxyethane	-2.1
CCOC	methoxyethane	-2.1
CCOC	methoxyethane	-2.1
COC(CCl)(OC)OC	2-chloro-1,1,1-trimethoxy-ethane	-4.59
COC(CCl)(OC)OC	2-chloro-1,1,1-trimethoxy-ethane	-4.59
COC(CCl)(OC)OC	2-chloro-1,1,1-trimethoxy-ethane	-4.59
COC(CCl)(OC)OC	2-chloro-1,1,1-trimethoxy-ethane	-4.59
COC(CCl)(OC)OC	2-chloro-1,1,1-trimethoxy-ethane	-4.59
CC(C)C	isobutane	2.3
CC(C)C	isobutane	2.3
CC(C)C	isobutane	2.3
CC(C)C	isobutane	2.3
CC(C)C	isobutane	2.3
CC(C)CC(=O)O	3-methylbutanoic acid	-6.09
CC(C)CC(=O)O	3-methylbutanoic acid	-6.09
CC(C)CC(=O)O	3-methylbutanoic acid	-6.09
CC(C)CC(=O)O	3-methylbutanoic acid	-6.09
CC(C)CC(=O)O	3-methylbutanoic acid	-6.09
CCOP(=O)(OCC)O/C(=C/Cl)/c1ccc(cc1Cl)Cl	2-chloro-1-(2,4-dichlorophenyl)ethenyl diethyl phosphate	-7.07
CCOP(=O)(OCC)O/C(=C/Cl)/c1ccc(cc1Cl)Cl	2-chloro-1-(2,4-dichlorophenyl)ethenyl diethyl phosphate	-7.07
CCOP(=O)(OCC)O/C(=C/Cl)/c1ccc(cc1Cl)Cl	2-chloro-1-(2,4-dichlorophenyl)ethenyl diethyl phosphate	-7.07
CCOP(=O)(OCC)O/C(=C/Cl)/c1ccc(cc1Cl)Cl	2-chloro-1-(2,4-dichlorophenyl)ethenyl diethyl phosphate	-7.07
CCOP(=O)(OCC)O/C(=C/Cl)/c1ccc(cc1Cl)Cl	2-chloro-1-(2,4-dichlorophenyl)ethenyl diethyl phosphate	-7.07
CCCCl	1-chloropropane	-0.33
CCCCl	1-chloropropane	-0.33
CCCCl	1-chloropropane	-0.33
CCCCl	1-chloropropane	-0.33
CCCCl	1-chloropropane	-0.33
CCCSCCC	1-propylsulfanylpropane	-1.28
CCCSCCC	1-propylsulfanylpropane	-1.28
CCCSCCC	1-propylsulfanylpropane	-1.28
CCCSCCC	1-propylsulfanylpropane	-1.28
CCCSCCC	1-propylsulfanylpropane	-1.28
CCC[C@H](CC)O	hexan-3-ol	-4.06
CCC[C@H](CC)O	hexan-3-ol	-4.06
CCC[C@H](CC)O	hexan-3-ol	-4.06
CCC[C@H](CC)O	hexan-3-ol	-4.06
CCC[C@H](CC)O	hexan-3-ol	-4.06
CC#N	acetonitrile	-3.88
CC#N	acetonitrile	-3.88
CC#N	acetonitrile	-3.88
CC#N	acetonitrile	-3.88
CC#N	acetonitrile	-3.88
CN(CC(F)(F)F)c1ccccc1	N-methyl-N-(2,2,2-trifluoroethyl)aniline	-1.92
CN(CC(F)(F)F)c1ccccc1	N-methyl-N-(2,2,2-trifluoroethyl)aniline	-1.92
CN(CC(F)(F)F)c1ccccc1	N-methyl-N-(2,2,2-trifluoroethyl)aniline	-1.92
CN(CC(F)(F)F)c1ccccc1	N-methyl-N-(2,2,2-trifluoroethyl)aniline	-1.92
CN(CC(F)(F)F)c1ccccc1	N-methyl-N-(2,2,2-trifluoroethyl)aniline	-1.92
[C@@H](C(F)(F)F)(OC(F)F)Cl	2-chloro-2-(difluoromethoxy)-1,1,1-trifluoro-ethane	0.1
[C@@H](C(F)(F)F)(OC(F)F)Cl	2-chloro-2-(difluoromethoxy)-1,1,1-trifluoro-ethane	0.1
[C@@H](C(F)(F)F)(OC(F)F)Cl	2-chloro-2-(difluoromethoxy)-1,1,1-trifluoro-ethane	0.1
[C@@H](C(F)(F)F)(OC(F)F)Cl	2-chloro-2-(difluoromethoxy)-1,1,1-trifluoro-ethane	0.1
[C@@H](C(F)(F)F)(OC(F)F)Cl	2-chloro-2-(difluoromethoxy)-1,1,1-trifluoro-ethane	0.1
C=CCCC=C	hexa-1,5-diene	1.01
C=CCCC=C	hexa-1,5-diene	1.01
C=CCCC=C	hexa-1,5-diene	1.01
C=CCCC=C	hexa-1,5-diene	1.01
C=CCCC=C	hexa-1,5-diene	1.01
Cc1cccc(c1)C	m-xylene	-0.83
Cc1cccc(c1)C	m-xylene	-0.83
Cc1cccc(c1)C	m-xylene	-0.83
Cc1cccc(c1)C	m-xylene	-0.83
Cc1cccc(c1)C	m-xylene	-0.83
CC(=O)OC	methyl acetate	-3.13
CC(=O)OC	methyl acetate	-3.13
CC(=O)OC	methyl acetate	-3.13
CC(=O)OC	methyl acetate	-3.13
CC(=O)OC	methyl acetate	-3.13
COC(c1ccccc1)(OC)OC	trimethoxymethylbenzene	-4.04
COC(c1ccccc1)(OC)OC	trimethoxymethylbenzene	-4.04
COC(c1ccccc1)(OC)OC	trimethoxymethylbenzene	-4.04
COC(c1ccccc1)(OC)OC	trimethoxymethylbenzene	-4.04
COC(c1ccccc1)(OC)OC	trimethoxymethylbenzene	-4.04
CCOC(=O)c1ccccc1	ethyl benzoate	-3.64
CCOC(=O)c1ccccc1	ethyl benzoate	-3.64
CCOC(=O)c1ccccc1	ethyl benzoate	-3.64
CCOC(=O)c1ccccc1	ethyl benzoate	-3.64
CCOC(=O)c1ccccc1	ethyl benzoate	-3.64
CCCS	propanethiol	-1.1
CCCS	propanethiol	-1.1
CCCS	propanethiol	-1.1
CCCS	propanethiol	-1.1
CCCS	propanethiol	-1.1
CCCCCC(=O)C	heptan-2-one	-3.04
CCCCCC(=O)C	heptan-2-one	-3.04
CCCCCC(=O)C	heptan-2-one	-3.04
CCCCCC(=O)C	heptan-2-one	-3.04
CCCCCC(=O)C	heptan-2-one	-3.04
CC1(Cc2cccc(c2O1)OC(=O)NC)C	carbofuran	-9.61
CC1(Cc2cccc(c2O1)OC(=O)NC)C	carbofuran	-9.61
CC1(Cc2cccc(c2O1)OC(=O)NC)C	carbofuran	-9.61
CC1(Cc2cccc(c2O1)OC(=O)NC)C	carbofuran	-9.61
CC1(Cc2cccc(c2O1)OC(=O)NC)C	carbofuran	-9.61
c1ccc(cc1)CBr	benzyl bromide	-2.38
c1ccc(cc1)CBr	benzyl bromide	-2.38
c1ccc(cc1)CBr	benzyl bromide	-2.38
c1ccc(cc1)CBr	benzyl bromide	-2.38
c1ccc(cc1)CBr	benzyl bromide	-2.38
CCCCCC(=O)OCC	ethyl hexanoate	-2.23
CCCCCC(=O)OCC	ethyl hexanoate	-2.23
CCCCCC(=O)OCC	ethyl hexanoate	-2.23
CCCCCC(=O)OCC	ethyl hexanoate	-2.23
CCCCCC(=O)OCC	ethyl hexanoate	-2.23
CCCOC	1-methoxypropane	-1.66
CCCOC	1-methoxypropane	-1.66
CCCOC	1-methoxypropane	-1.66
CCCOC	1-methoxypropane	-1.66
CCCOC	1-methoxypropane	-1.66
CN1CCOCC1	4-methylmorpholine	-6.32
CN1CCOCC1	4-methylmorpholine	-6.32
CN1CCOCC1	4-methylmorpholine	-6.32
CN1CCOCC1	4-methylmorpholine	-6.32
CN1CCOCC1	4-methylmorpholine	-6.32
c1cc(cc(c1)O)C#N	3-hydroxybenzonitrile	-9.65
c1cc(cc(c1)O)C#N	3-hydroxybenzonitrile	-9.65
c1cc(cc(c1)O)C#N	3-hydroxybenzonitrile	-9.65
c1cc(cc(c1)O)C#N	3-hydroxybenzonitrile	-9.65
c1cc(cc(c1)O)C#N	3-hydroxybenzonitrile	-9.65
c1cc(c(cc1c2c(c(cc(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,4,5-tetrachloro-3-(3,4-dichlorophenyl)benzene	-4.38
c1cc(c(cc1c2c(c(cc(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,4,5-tetrachloro-3-(3,4-dichlorophenyl)benzene	-4.38
c1cc(c(cc1c2c(c(cc(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,4,5-tetrachloro-3-(3,4-dichlorophenyl)benzene	-4.38
c1cc(c(cc1c2c(c(cc(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,4,5-tetrachloro-3-(3,4-dichlorophenyl)benzene	-4.38
c1cc(c(cc1c2c(c(cc(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,4,5-tetrachloro-3-(3,4-dichlorophenyl)benzene	-4.38
CCCc1ccccc1	propylbenzene	-0.53
CCCc1ccccc1	propylbenzene	-0.53
CCCc1ccccc1	propylbenzene	-0.53
CCCc1ccccc1	propylbenzene	-0.53
CCCc1ccccc1	propylbenzene	-0.53
Cn1cnc2c1c(=O)n(c(=O)n2C)C	caffeine	-12.64
Cn1cnc2c1c(=O)n(c(=O)n2C)C	caffeine	-12.64
Cn1cnc2c1c(=O)n(c(=O)n2C)C	caffeine	-12.64
Cn1cnc2c1c(=O)n(c(=O)n2C)C	caffeine	-12.64
Cn1cnc2c1c(=O)n(c(=O)n2C)C	caffeine	-12.64
CNC	N-methylmethanamine	-4.29
CNC	N-methylmethanamine	-4.29
CNC	N-methylmethanamine	-4.29
CNC	N-methylmethanamine	-4.29
CNC	N-methylmethanamine	-4.29
C(=C(F)F)(C(F)(F)F)F	1,1,2,3,3,3-hexafluoroprop-1-ene	2.93
C(=C(F)F)(C(F)(F)F)F	1,1,2,3,3,3-hexafluoroprop-1-ene	2.93
C(=C(F)F)(C(F)(F)F)F	1,1,2,3,3,3-hexafluoroprop-1-ene	2.93
C(=C(F)F)(C(F)(F)F)F	1,1,2,3,3,3-hexafluoroprop-1-ene	2.93
C(=C(F)F)(C(F)(F)F)F	1,1,2,3,3,3-hexafluoroprop-1-ene	2.93
c1cc(ccc1O)Cl	4-chlorophenol	-7.03
c1cc(ccc1O)Cl	4-chlorophenol	-7.03
c1cc(ccc1O)Cl	4-chlorophenol	-7.03
c1cc(ccc1O)Cl	4-chlorophenol	-7.03
c1cc(ccc1O)Cl	4-chlorophenol	-7.03
C1CCNCC1	piperidine	-5.11
C1CCNCC1	piperidine	-5.11
C1CCNCC1	piperidine	-5.11
C1CCNCC1	piperidine	-5.11
C1CCNCC1	piperidine	-5.11
c1ccc2c(c1)ccc3c2cccc3	phenanthrene	-3.88
c1ccc2c(c1)ccc3c2cccc3	phenanthrene	-3.88
c1ccc2c(c1)ccc3c2cccc3	phenanthrene	-3.88
c1ccc2c(c1)ccc3c2cccc3	phenanthrene	-3.88
c1ccc2c(c1)ccc3c2cccc3	phenanthrene	-3.88
CI	iodomethane	-0.89
CI	iodomethane	-0.89
CI	iodomethane	-0.89
CI	iodomethane	-0.89
CI	iodomethane	-0.89
COc1c(cc(c(c1O)OC)Cl)Cl	3,5-dichloro-2,6-dimethoxyphenol	-6.44
COc1c(cc(c(c1O)OC)Cl)Cl	3,5-dichloro-2,6-dimethoxyphenol	-6.44
COc1c(cc(c(c1O)OC)Cl)Cl	3,5-dichloro-2,6-dimethoxyphenol	-6.44
COc1c(cc(c(c1O)OC)Cl)Cl	3,5-dichloro-2,6-dimethoxyphenol	-6.44
COc1c(cc(c(c1O)OC)Cl)Cl	3,5-dichloro-2,6-dimethoxyphenol	-6.44
C(=C/Cl)\Cl	(E)-1,2-dichloroethylene	-0.78
C(=C/Cl)\Cl	(E)-1,2-dichloroethylene	-0.78
C(=C/Cl)\Cl	(E)-1,2-dichloroethylene	-0.78
C(=C/Cl)\Cl	(E)-1,2-dichloroethylene	-0.78
C(=C/Cl)\Cl	(E)-1,2-dichloroethylene	-0.78
CCCCC	n-pentane	2.3
CCCCC	n-pentane	2.3
CCCCC	n-pentane	2.3
CCCCC	n-pentane	2.3
CCCCC	n-pentane	2.3
CCCC#N	butanenitrile	-3.64
CCCC#N	butanenitrile	-3.64
CCCC#N	butanenitrile	-3.64
CCCC#N	butanenitrile	-3.64
CCCC#N	butanenitrile	-3.64
[C@@H](C(F)(F)F)(F)Br	2-bromo-1,1,1,2-tetrafluoro-ethane	0.5
[C@@H](C(F)(F)F)(F)Br	2-bromo-1,1,1,2-tetrafluoro-ethane	0.5
[C@@H](C(F)(F)F)(F)Br	2-bromo-1,1,1,2-tetrafluoro-ethane	0.5
[C@@H](C(F)(F)F)(F)Br	2-bromo-1,1,1,2-tetrafluoro-ethane	0.5
[C@@H](C(F)(F)F)(F)Br	2-bromo-1,1,1,2-tetrafluoro-ethane	0.5
CC(C)Cc1cnccn1	2-isobutylpyrazine	-5.04
CC(C)Cc1cnccn1	2-isobutylpyrazine	-5.04
CC(C)Cc1cnccn1	2-isobutylpyrazine	-5.04
CC(C)Cc1cnccn1	2-isobutylpyrazine	-5.04
CC(C)Cc1cnccn1	2-isobutylpyrazine	-5.04
CC[C@H](C)O[N+](=O)[O-]	[(2S)-butan-2-yl] nitrate	-1.82
CC[C@H](C)O[N+](=O)[O-]	[(2S)-butan-2-yl] nitrate	-1.82
CC[C@H](C)O[N+](=O)[O-]	[(2S)-butan-2-yl] nitrate	-1.82
CC[C@H](C)O[N+](=O)[O-]	[(2S)-butan-2-yl] nitrate	-1.82
CC[C@H](C)O[N+](=O)[O-]	[(2S)-butan-2-yl] nitrate	-1.82
c1ccc(cc1)c2cc(ccc2Cl)Cl	1,4-dichloro-2-phenyl-benzene	-2.46
c1ccc(cc1)c2cc(ccc2Cl)Cl	1,4-dichloro-2-phenyl-benzene	-2.46
c1ccc(cc1)c2cc(ccc2Cl)Cl	1,4-dichloro-2-phenyl-benzene	-2.46
c1ccc(cc1)c2cc(ccc2Cl)Cl	1,4-dichloro-2-phenyl-benzene	-2.46
c1ccc(cc1)c2cc(ccc2Cl)Cl	1,4-dichloro-2-phenyl-benzene	-2.46
c1ccc(cc1)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-phenyl-benzene	-3.48
c1ccc(cc1)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-phenyl-benzene	-3.48
c1ccc(cc1)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-phenyl-benzene	-3.48
c1ccc(cc1)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-phenyl-benzene	-3.48
c1ccc(cc1)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-phenyl-benzene	-3.48
CC[C@@H](C)C(C)C	2,3-dimethylpentane	2.52
CC[C@@H](C)C(C)C	2,3-dimethylpentane	2.52
CC[C@@H](C)C(C)C	2,3-dimethylpentane	2.52
CC[C@@H](C)C(C)C	2,3-dimethylpentane	2.52
CC[C@@H](C)C(C)C	2,3-dimethylpentane	2.52
C[C@H](CC(C)C)O	4-methylpentan-2-ol	-3.73
C[C@H](CC(C)C)O	4-methylpentan-2-ol	-3.73
C[C@H](CC(C)C)O	4-methylpentan-2-ol	-3.73
C[C@H](CC(C)C)O	4-methylpentan-2-ol	-3.73
C[C@H](CC(C)C)O	4-methylpentan-2-ol	-3.73
C1CCOCC1	tetrahydropyran	-3.12
C1CCOCC1	tetrahydropyran	-3.12
C1CCOCC1	tetrahydropyran	-3.12
C1CCOCC1	tetrahydropyran	-3.12
C1CCOCC1	tetrahydropyran	-3.12
C1CC1	cyclopropane	0.75
C1CC1	cyclopropane	0.75
C1CC1	cyclopropane	0.75
C1CC1	cyclopropane	0.75
C1CC1	cyclopropane	0.75
c1c(cc(c(c1Cl)Cl)Cl)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4,5-trichlorophenyl)benzene	-3.17
c1c(cc(c(c1Cl)Cl)Cl)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4,5-trichlorophenyl)benzene	-3.17
c1c(cc(c(c1Cl)Cl)Cl)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4,5-trichlorophenyl)benzene	-3.17
c1c(cc(c(c1Cl)Cl)Cl)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4,5-trichlorophenyl)benzene	-3.17
c1c(cc(c(c1Cl)Cl)Cl)c2cc(c(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4,5-trichlorophenyl)benzene	-3.17
C=C(Cl)Cl	1,1-dichloroethylene	0.25
C=C(Cl)Cl	1,1-dichloroethylene	0.25
C=C(Cl)Cl	1,1-dichloroethylene	0.25
C=C(Cl)Cl	1,1-dichloroethylene	0.25
C=C(Cl)Cl	1,1-dichloroethylene	0.25
CC(C)CO	2-methylpropan-1-ol	-4.5
CC(C)CO	2-methylpropan-1-ol	-4.5
CC(C)CO	2-methylpropan-1-ol	-4.5
CC(C)CO	2-methylpropan-1-ol	-4.5
CC(C)CO	2-methylpropan-1-ol	-4.5
CCCOC(=O)CC	propyl propanoate	-2.44
CCCOC(=O)CC	propyl propanoate	-2.44
CCCOC(=O)CC	propyl propanoate	-2.44
CCCOC(=O)CC	propyl propanoate	-2.44
CCCOC(=O)CC	propyl propanoate	-2.44
C(C(Cl)(Cl)Cl)(Cl)(Cl)Cl	hexachloroethane	-0.64
C(C(Cl)(Cl)Cl)(Cl)(Cl)Cl	hexachloroethane	-0.64
C(C(Cl)(Cl)Cl)(Cl)(Cl)Cl	hexachloroethane	-0.64
C(C(Cl)(Cl)Cl)(Cl)(Cl)Cl	hexachloroethane	-0.64
C(C(Cl)(Cl)Cl)(Cl)(Cl)Cl	hexachloroethane	-0.64
CSc1ccccc1	methylsulfanylbenzene	-2.73
CSc1ccccc1	methylsulfanylbenzene	-2.73
CSc1ccccc1	methylsulfanylbenzene	-2.73
CSc1ccccc1	methylsulfanylbenzene	-2.73
CSc1ccccc1	methylsulfanylbenzene	-2.73
CCc1ccccc1O	2-ethylphenol	-5.66
CCc1ccccc1O	2-ethylphenol	-5.66
CCc1ccccc1O	2-ethylphenol	-5.66
CCc1ccccc1O	2-ethylphenol	-5.66
CCc1ccccc1O	2-ethylphenol	-5.66
CC(C)(C)Cl	2-chloro-2-methyl-propane	1.09
CC(C)(C)Cl	2-chloro-2-methyl-propane	1.09
CC(C)(C)Cl	2-chloro-2-methyl-propane	1.09
CC(C)(C)Cl	2-chloro-2-methyl-propane	1.09
CC(C)(C)Cl	2-chloro-2-methyl-propane	1.09
CC(=C)C=C	isoprene	0.68
CC(=C)C=C	isoprene	0.68
CC(=C)C=C	isoprene	0.68
CC(=C)C=C	isoprene	0.68
CC(=C)C=C	isoprene	0.68
Cc1ccc(cc1)C(C)C	1-isopropyl-4-methyl-benzene	-0.68
Cc1ccc(cc1)C(C)C	1-isopropyl-4-methyl-benzene	-0.68
Cc1ccc(cc1)C(C)C	1-isopropyl-4-methyl-benzene	-0.68
Cc1ccc(cc1)C(C)C	1-isopropyl-4-methyl-benzene	-0.68
Cc1ccc(cc1)C(C)C	1-isopropyl-4-methyl-benzene	-0.68
Cn1ccnc1	1-methylimidazole	-8.41
Cn1ccnc1	1-methylimidazole	-8.41
Cn1ccnc1	1-methylimidazole	-8.41
Cn1ccnc1	1-methylimidazole	-8.41
Cn1ccnc1	1-methylimidazole	-8.41
C(CO)O	ethylene glycol	-9.3
C(CO)O	ethylene glycol	-9.3
C(CO)O	ethylene glycol	-9.3
C(CO)O	ethylene glycol	-9.3
C(CO)O	ethylene glycol	-9.3
c1ccc(c(c1)Cl)Cl	1,2-dichlorobenzene	-1.36
c1ccc(c(c1)Cl)Cl	1,2-dichlorobenzene	-1.36
c1ccc(c(c1)Cl)Cl	1,2-dichlorobenzene	-1.36
c1ccc(c(c1)Cl)Cl	1,2-dichlorobenzene	-1.36
c1ccc(c(c1)Cl)Cl	1,2-dichlorobenzene	-1.36
c1c(=O)[nH]c(=O)[nH]c1Cl	6-chlorouracil	-15.83
c1c(=O)[nH]c(=O)[nH]c1Cl	6-chlorouracil	-15.83
c1c(=O)[nH]c(=O)[nH]c1Cl	6-chlorouracil	-15.83
c1c(=O)[nH]c(=O)[nH]c1Cl	6-chlorouracil	-15.83
c1c(=O)[nH]c(=O)[nH]c1Cl	6-chlorouracil	-15.83
CCCOC=O	propyl formate	-2.48
CCCOC=O	propyl formate	-2.48
CCCOC=O	propyl formate	-2.48
CCCOC=O	propyl formate	-2.48
CCCOC=O	propyl formate	-2.48
c1ccc2c(c1)Oc3ccc(cc3O2)Cl	2-chlorodibenzo-p-dioxin	-3.1
c1ccc2c(c1)Oc3ccc(cc3O2)Cl	2-chlorodibenzo-p-dioxin	-3.1
c1ccc2c(c1)Oc3ccc(cc3O2)Cl	2-chlorodibenzo-p-dioxin	-3.1
c1ccc2c(c1)Oc3ccc(cc3O2)Cl	2-chlorodibenzo-p-dioxin	-3.1
c1ccc2c(c1)Oc3ccc(cc3O2)Cl	2-chlorodibenzo-p-dioxin	-3.1
CCCCCC(=O)O	hexanoic acid	-6.21
CCCCCC(=O)O	hexanoic acid	-6.21
CCCCCC(=O)O	hexanoic acid	-6.21
CCCCCC(=O)O	hexanoic acid	-6.21
CCCCCC(=O)O	hexanoic acid	-6.21
CCOC(=O)CCC(=O)OCC	diethyl butanedioate	-5.71
CCOC(=O)CCC(=O)OCC	diethyl butanedioate	-5.71
CCOC(=O)CCC(=O)OCC	diethyl butanedioate	-5.71
CCOC(=O)CCC(=O)OCC	diethyl butanedioate	-5.71
CCOC(=O)CCC(=O)OCC	diethyl butanedioate	-5.71
Cc1ccnc(c1)C	2,4-dimethylpyridine	-4.86
Cc1ccnc(c1)C	2,4-dimethylpyridine	-4.86
Cc1ccnc(c1)C	2,4-dimethylpyridine	-4.86
Cc1ccnc(c1)C	2,4-dimethylpyridine	-4.86
Cc1ccnc(c1)C	2,4-dimethylpyridine	-4.86
C1CCC=CC1	cyclohexene	0.14
C1CCC=CC1	cyclohexene	0.14
C1CCC=CC1	cyclohexene	0.14
C1CCC=CC1	cyclohexene	0.14
C1CCC=CC1	cyclohexene	0.14
CN1CCN(CC1)C	1,4-dimethylpiperazine	-7.58
CN1CCN(CC1)C	1,4-dimethylpiperazine	-7.58
CN1CCN(CC1)C	1,4-dimethylpiperazine	-7.58
CN1CCN(CC1)C	1,4-dimethylpiperazine	-7.58
CN1CCN(CC1)C	1,4-dimethylpiperazine	-7.58
c1cc(c(cc1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4-dichlorophenyl)benzene	-3.04
c1cc(c(cc1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4-dichlorophenyl)benzene	-3.04
c1cc(c(cc1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4-dichlorophenyl)benzene	-3.04
c1cc(c(cc1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4-dichlorophenyl)benzene	-3.04
c1cc(c(cc1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(3,4-dichlorophenyl)benzene	-3.04
C1=CC(=O)C=CC1=O	quinone	-6.5
C1=CC(=O)C=CC1=O	quinone	-6.5
C1=CC(=O)C=CC1=O	quinone	-6.5
C1=CC(=O)C=CC1=O	quinone	-6.5
C1=CC(=O)C=CC1=O	quinone	-6.5
COC(=O)CCl	methyl 2-chloroacetate	-4.0
COC(=O)CCl	methyl 2-chloroacetate	-4.0
COC(=O)CCl	methyl 2-chloroacetate	-4.0
COC(=O)CCl	methyl 2-chloroacetate	-4.0
COC(=O)CCl	methyl 2-chloroacetate	-4.0
CCCC=O	butanal	-3.18
CCCC=O	butanal	-3.18
CCCC=O	butanal	-3.18
CCCC=O	butanal	-3.18
CCCC=O	butanal	-3.18
CCc1ccccc1	ethylbenzene	-0.79
CCc1ccccc1	ethylbenzene	-0.79
CCc1ccccc1	ethylbenzene	-0.79
CCc1ccccc1	ethylbenzene	-0.79
CCc1ccccc1	ethylbenzene	-0.79
C(=C(Cl)Cl)Cl	1,1,2-trichloroethylene	-0.44
C(=C(Cl)Cl)Cl	1,1,2-trichloroethylene	-0.44
C(=C(Cl)Cl)Cl	1,1,2-trichloroethylene	-0.44
C(=C(Cl)Cl)Cl	1,1,2-trichloroethylene	-0.44
C(=C(Cl)Cl)Cl	1,1,2-trichloroethylene	-0.44
CCN(CC)CC	N,N-diethylethanamine	-3.22
CCN(CC)CC	N,N-diethylethanamine	-3.22
CCN(CC)CC	N,N-diethylethanamine	-3.22
CCN(CC)CC	N,N-diethylethanamine	-3.22
CCN(CC)CC	N,N-diethylethanamine	-3.22
c1cc2c(cc1Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7-pentachlorodibenzo-p-dioxin	-4.15
c1cc2c(cc1Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7-pentachlorodibenzo-p-dioxin	-4.15
c1cc2c(cc1Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7-pentachlorodibenzo-p-dioxin	-4.15
c1cc2c(cc1Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7-pentachlorodibenzo-p-dioxin	-4.15
c1cc2c(cc1Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7-pentachlorodibenzo-p-dioxin	-4.15
Cc1ccncc1C	3,4-dimethylpyridine	-5.22
Cc1ccncc1C	3,4-dimethylpyridine	-5.22
Cc1ccncc1C	3,4-dimethylpyridine	-5.22
Cc1ccncc1C	3,4-dimethylpyridine	-5.22
Cc1ccncc1C	3,4-dimethylpyridine	-5.22
c1(=O)[nH]c(=O)[nH]c(=O)[nH]1	cyanuric acid	-18.06
c1(=O)[nH]c(=O)[nH]c(=O)[nH]1	cyanuric acid	-18.06
c1(=O)[nH]c(=O)[nH]c(=O)[nH]1	cyanuric acid	-18.06
c1(=O)[nH]c(=O)[nH]c(=O)[nH]1	cyanuric acid	-18.06
c1(=O)[nH]c(=O)[nH]c(=O)[nH]1	cyanuric acid	-18.06
c1ccc(cc1)C=O	benzaldehyde	-4.02
c1ccc(cc1)C=O	benzaldehyde	-4.02
c1ccc(cc1)C=O	benzaldehyde	-4.02
c1ccc(cc1)C=O	benzaldehyde	-4.02
c1ccc(cc1)C=O	benzaldehyde	-4.02
c1ccnc(c1)Cl	2-chloropyridine	-4.39
c1ccnc(c1)Cl	2-chloropyridine	-4.39
c1ccnc(c1)Cl	2-chloropyridine	-4.39
c1ccnc(c1)Cl	2-chloropyridine	-4.39
c1ccnc(c1)Cl	2-chloropyridine	-4.39
C=CCCl	3-chloroprop-1-ene	-0.57
C=CCCl	3-chloroprop-1-ene	-0.57
C=CCCl	3-chloroprop-1-ene	-0.57
C=CCCl	3-chloroprop-1-ene	-0.57
C=CCCl	3-chloroprop-1-ene	-0.57
Cc1ccc(cc1)C(=O)C	1-(p-tolyl)ethanone	-4.7
Cc1ccc(cc1)C(=O)C	1-(p-tolyl)ethanone	-4.7
Cc1ccc(cc1)C(=O)C	1-(p-tolyl)ethanone	-4.7
Cc1ccc(cc1)C(=O)C	1-(p-tolyl)ethanone	-4.7
Cc1ccc(cc1)C(=O)C	1-(p-tolyl)ethanone	-4.7
C=O	formaldehyde	-2.75
C=O	formaldehyde	-2.75
C=O	formaldehyde	-2.75
C=O	formaldehyde	-2.75
C=O	formaldehyde	-2.75
Cc1ccccc1Cl	1-chloro-2-methyl-benzene	-1.14
Cc1ccccc1Cl	1-chloro-2-methyl-benzene	-1.14
Cc1ccccc1Cl	1-chloro-2-methyl-benzene	-1.14
Cc1ccccc1Cl	1-chloro-2-methyl-benzene	-1.14
Cc1ccccc1Cl	1-chloro-2-methyl-benzene	-1.14
CC(=O)N1CCCC1	1-pyrrolidin-1-ylethanone	-9.8
CC(=O)N1CCCC1	1-pyrrolidin-1-ylethanone	-9.8
CC(=O)N1CCCC1	1-pyrrolidin-1-ylethanone	-9.8
CC(=O)N1CCCC1	1-pyrrolidin-1-ylethanone	-9.8
CC(=O)N1CCCC1	1-pyrrolidin-1-ylethanone	-9.8
CC(OC)(OC)OC	1,1,1-trimethoxyethane	-4.42
CC(OC)(OC)OC	1,1,1-trimethoxyethane	-4.42
CC(OC)(OC)OC	1,1,1-trimethoxyethane	-4.42
CC(OC)(OC)OC	1,1,1-trimethoxyethane	-4.42
CC(OC)(OC)OC	1,1,1-trimethoxyethane	-4.42
CCCCc1ccccc1	butylbenzene	-0.4
CCCCc1ccccc1	butylbenzene	-0.4
CCCCc1ccccc1	butylbenzene	-0.4
CCCCc1ccccc1	butylbenzene	-0.4
CCCCc1ccccc1	butylbenzene	-0.4
CN(C)c1ccccc1	N,N-dimethylaniline	-3.45
CN(C)c1ccccc1	N,N-dimethylaniline	-3.45
CN(C)c1ccccc1	N,N-dimethylaniline	-3.45
CN(C)c1ccccc1	N,N-dimethylaniline	-3.45
CN(C)c1ccccc1	N,N-dimethylaniline	-3.45
CC(C)OC	2-methoxypropane	-2.01
CC(C)OC	2-methoxypropane	-2.01
CC(C)OC	2-methoxypropane	-2.01
CC(C)OC	2-methoxypropane	-2.01
CC(C)OC	2-methoxypropane	-2.01
c12c(c(c(c(c1Cl)Cl)Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,6,7,8,9-octachlorodibenzo-p-dioxin	-4.53
c12c(c(c(c(c1Cl)Cl)Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,6,7,8,9-octachlorodibenzo-p-dioxin	-4.53
c12c(c(c(c(c1Cl)Cl)Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,6,7,8,9-octachlorodibenzo-p-dioxin	-4.53
c12c(c(c(c(c1Cl)Cl)Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,6,7,8,9-octachlorodibenzo-p-dioxin	-4.53
c12c(c(c(c(c1Cl)Cl)Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,6,7,8,9-octachlorodibenzo-p-dioxin	-4.53
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)c2c(c(c(c(c2Cl)Cl)Cl)Cl)Cl	1,2,3,4,5-pentachloro-6-(2,3,4,5,6-pentachlorophenyl)benzene	-2.98
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)c2c(c(c(c(c2Cl)Cl)Cl)Cl)Cl	1,2,3,4,5-pentachloro-6-(2,3,4,5,6-pentachlorophenyl)benzene	-2.98
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)c2c(c(c(c(c2Cl)Cl)Cl)Cl)Cl	1,2,3,4,5-pentachloro-6-(2,3,4,5,6-pentachlorophenyl)benzene	-2.98
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)c2c(c(c(c(c2Cl)Cl)Cl)Cl)Cl	1,2,3,4,5-pentachloro-6-(2,3,4,5,6-pentachlorophenyl)benzene	-2.98
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)c2c(c(c(c(c2Cl)Cl)Cl)Cl)Cl	1,2,3,4,5-pentachloro-6-(2,3,4,5,6-pentachlorophenyl)benzene	-2.98
C(C(Cl)Cl)Cl	1,1,2-trichloroethane	-1.99
C(C(Cl)Cl)Cl	1,1,2-trichloroethane	-1.99
C(C(Cl)Cl)Cl	1,1,2-trichloroethane	-1.99
C(C(Cl)Cl)Cl	1,1,2-trichloroethane	-1.99
C(C(Cl)Cl)Cl	1,1,2-trichloroethane	-1.99
CNc1ccccc1	N-methylaniline	-4.69
CNc1ccccc1	N-methylaniline	-4.69
CNc1ccccc1	N-methylaniline	-4.69
CNc1ccccc1	N-methylaniline	-4.69
CNc1ccccc1	N-methylaniline	-4.69
CC(C)OC(=O)C	isopropyl acetate	-2.64
CC(C)OC(=O)C	isopropyl acetate	-2.64
CC(C)OC(=O)C	isopropyl acetate	-2.64
CC(C)OC(=O)C	isopropyl acetate	-2.64
CC(C)OC(=O)C	isopropyl acetate	-2.64
c1ccccc1	benzene	-0.9
c1ccccc1	benzene	-0.9
c1ccccc1	benzene	-0.9
c1ccccc1	benzene	-0.9
c1ccccc1	benzene	-0.9
c1cc(c(c(c1)Cl)Cl)Cl	1,2,3-trichlorobenzene	-1.24
c1cc(c(c(c1)Cl)Cl)Cl	1,2,3-trichlorobenzene	-1.24
c1cc(c(c(c1)Cl)Cl)Cl	1,2,3-trichlorobenzene	-1.24
c1cc(c(c(c1)Cl)Cl)Cl	1,2,3-trichlorobenzene	-1.24
c1cc(c(c(c1)Cl)Cl)Cl	1,2,3-trichlorobenzene	-1.24
CCOP(=S)(OCC)SCSc1ccc(cc1)Cl	4-chlorophenyl)sulfanylmethylsulfanyl-diethoxy-thioxo-$l^{5}-phosphane	-6.5
CCOP(=S)(OCC)SCSc1ccc(cc1)Cl	4-chlorophenyl)sulfanylmethylsulfanyl-diethoxy-thioxo-$l^{5}-phosphane	-6.5
CCOP(=S)(OCC)SCSc1ccc(cc1)Cl	4-chlorophenyl)sulfanylmethylsulfanyl-diethoxy-thioxo-$l^{5}-phosphane	-6.5
CCOP(=S)(OCC)SCSc1ccc(cc1)Cl	4-chlorophenyl)sulfanylmethylsulfanyl-diethoxy-thioxo-$l^{5}-phosphane	-6.5
CCOP(=S)(OCC)SCSc1ccc(cc1)Cl	4-chlorophenyl)sulfanylmethylsulfanyl-diethoxy-thioxo-$l^{5}-phosphane	-6.5
COP(=S)(OC)SCn1c(=O)c2ccccc2nn1	3-(dimethoxyphosphinothioylsulfanylmethyl)-1,2,3-benzotriazin-4-one	-10.03
COP(=S)(OC)SCn1c(=O)c2ccccc2nn1	3-(dimethoxyphosphinothioylsulfanylmethyl)-1,2,3-benzotriazin-4-one	-10.03
COP(=S)(OC)SCn1c(=O)c2ccccc2nn1	3-(dimethoxyphosphinothioylsulfanylmethyl)-1,2,3-benzotriazin-4-one	-10.03
COP(=S)(OC)SCn1c(=O)c2ccccc2nn1	3-(dimethoxyphosphinothioylsulfanylmethyl)-1,2,3-benzotriazin-4-one	-10.03
COP(=S)(OC)SCn1c(=O)c2ccccc2nn1	3-(dimethoxyphosphinothioylsulfanylmethyl)-1,2,3-benzotriazin-4-one	-10.03
c1ccc2c(c1)Oc3c(cc(c(c3O2)Cl)Cl)Cl	1,2,4-trichlorodibenzo-p-dioxin	-4.05
c1ccc2c(c1)Oc3c(cc(c(c3O2)Cl)Cl)Cl	1,2,4-trichlorodibenzo-p-dioxin	-4.05
c1ccc2c(c1)Oc3c(cc(c(c3O2)Cl)Cl)Cl	1,2,4-trichlorodibenzo-p-dioxin	-4.05
c1ccc2c(c1)Oc3c(cc(c(c3O2)Cl)Cl)Cl	1,2,4-trichlorodibenzo-p-dioxin	-4.05
c1ccc2c(c1)Oc3c(cc(c(c3O2)Cl)Cl)Cl	1,2,4-trichlorodibenzo-p-dioxin	-4.05
CC(=C)C(=C)C	2,3-dimethylbuta-1,3-diene	0.4
CC(=C)C(=C)C	2,3-dimethylbuta-1,3-diene	0.4
CC(=C)C(=C)C	2,3-dimethylbuta-1,3-diene	0.4
CC(=C)C(=C)C	2,3-dimethylbuta-1,3-diene	0.4
CC(=C)C(=C)C	2,3-dimethylbuta-1,3-diene	0.4
CCCCC=C	hex-1-ene	1.58
CCCCC=C	hex-1-ene	1.58
CCCCC=C	hex-1-ene	1.58
CCCCC=C	hex-1-ene	1.58
CCCCC=C	hex-1-ene	1.58
S	hydrogen sulfide	-0.7
S	hydrogen sulfide	-0.7
S	hydrogen sulfide	-0.7
S	hydrogen sulfide	-0.7
S	hydrogen sulfide	-0.7
CCOCC	ethoxyethane	-1.59
CCOCC	ethoxyethane	-1.59
CCOCC	ethoxyethane	-1.59
CCOCC	ethoxyethane	-1.59
CCOCC	ethoxyethane	-1.59
CCNc1nc(nc(n1)SC)NC(C)C	2-N-ethyl-6-(methylsulfanyl)-4-N-(propan-2-yl)-1,3,5-triazine-2,4-diamine	-7.65
CCNc1nc(nc(n1)SC)NC(C)C	2-N-ethyl-6-(methylsulfanyl)-4-N-(propan-2-yl)-1,3,5-triazine-2,4-diamine	-7.65
CCNc1nc(nc(n1)SC)NC(C)C	2-N-ethyl-6-(methylsulfanyl)-4-N-(propan-2-yl)-1,3,5-triazine-2,4-diamine	-7.65
CCNc1nc(nc(n1)SC)NC(C)C	2-N-ethyl-6-(methylsulfanyl)-4-N-(propan-2-yl)-1,3,5-triazine-2,4-diamine	-7.65
CCNc1nc(nc(n1)SC)NC(C)C	2-N-ethyl-6-(methylsulfanyl)-4-N-(propan-2-yl)-1,3,5-triazine-2,4-diamine	-7.65
CCCCOC(=O)c1ccc(cc1)O	butyl paraben	-8.72
CCCCOC(=O)c1ccc(cc1)O	butyl paraben	-8.72
CCCCOC(=O)c1ccc(cc1)O	butyl paraben	-8.72
CCCCOC(=O)c1ccc(cc1)O	butyl paraben	-8.72
CCCCOC(=O)c1ccc(cc1)O	butyl paraben	-8.72
CCCCCCOC(=O)C	hexyl acetate	-2.26
CCCCCCOC(=O)C	hexyl acetate	-2.26
CCCCCCOC(=O)C	hexyl acetate	-2.26
CCCCCCOC(=O)C	hexyl acetate	-2.26
CCCCCCOC(=O)C	hexyl acetate	-2.26
C1CCC(=O)C1	cyclopentanone	-4.7
C1CCC(=O)C1	cyclopentanone	-4.7
C1CCC(=O)C1	cyclopentanone	-4.7
C1CCC(=O)C1	cyclopentanone	-4.7
C1CCC(=O)C1	cyclopentanone	-4.7
CCCCC(=O)O	pentanoic acid	-6.16
CCCCC(=O)O	pentanoic acid	-6.16
CCCCC(=O)O	pentanoic acid	-6.16
CCCCC(=O)O	pentanoic acid	-6.16
CCCCC(=O)O	pentanoic acid	-6.16
CCBr	bromoethane	-0.74
CCBr	bromoethane	-0.74
CCBr	bromoethane	-0.74
CCBr	bromoethane	-0.74
CCBr	bromoethane	-0.74
Cc1ccc2cc(ccc2c1)C	2,6-dimethylnaphthalene	-2.63
Cc1ccc2cc(ccc2c1)C	2,6-dimethylnaphthalene	-2.63
Cc1ccc2cc(ccc2c1)C	2,6-dimethylnaphthalene	-2.63
Cc1ccc2cc(ccc2c1)C	2,6-dimethylnaphthalene	-2.63
Cc1ccc2cc(ccc2c1)C	2,6-dimethylnaphthalene	-2.63
CCCCCCO	hexan-1-ol	-4.4
CCCCCCO	hexan-1-ol	-4.4
CCCCCCO	hexan-1-ol	-4.4
CCCCCCO	hexan-1-ol	-4.4
CCCCCCO	hexan-1-ol	-4.4
c1ccc(cc1)c2ccccc2Cl	1-chloro-2-phenyl-benzene	-2.69
c1ccc(cc1)c2ccccc2Cl	1-chloro-2-phenyl-benzene	-2.69
c1ccc(cc1)c2ccccc2Cl	1-chloro-2-phenyl-benzene	-2.69
c1ccc(cc1)c2ccccc2Cl	1-chloro-2-phenyl-benzene	-2.69
c1ccc(cc1)c2ccccc2Cl	1-chloro-2-phenyl-benzene	-2.69
CC1=CCCCC1	1-methylcyclohexene	0.67
CC1=CCCCC1	1-methylcyclohexene	0.67
CC1=CCCCC1	1-methylcyclohexene	0.67
CC1=CCCCC1	1-methylcyclohexene	0.67
CC1=CCCCC1	1-methylcyclohexene	0.67
CCCCCCO[N+](=O)[O-]	hexyl nitrate	-1.66
CCCCCCO[N+](=O)[O-]	hexyl nitrate	-1.66
CCCCCCO[N+](=O)[O-]	hexyl nitrate	-1.66
CCCCCCO[N+](=O)[O-]	hexyl nitrate	-1.66
CCCCCCO[N+](=O)[O-]	hexyl nitrate	-1.66
C(Br)(Br)Br	bromoform	-2.13
C(Br)(Br)Br	bromoform	-2.13
C(Br)(Br)Br	bromoform	-2.13
C(Br)(Br)Br	bromoform	-2.13
C(Br)(Br)Br	bromoform	-2.13
CCc1ccc(cc1)O	4-ethylphenol	-6.13
CCc1ccc(cc1)O	4-ethylphenol	-6.13
CCc1ccc(cc1)O	4-ethylphenol	-6.13
CCc1ccc(cc1)O	4-ethylphenol	-6.13
CCc1ccc(cc1)O	4-ethylphenol	-6.13
CCCOCCO	2-propoxyethanol	-6.4
CCCOCCO	2-propoxyethanol	-6.4
CCCOCCO	2-propoxyethanol	-6.4
CCCOCCO	2-propoxyethanol	-6.4
CCCOCCO	2-propoxyethanol	-6.4
c1ccc(cc1)OC=O	phenyl formate	-3.82
c1ccc(cc1)OC=O	phenyl formate	-3.82
c1ccc(cc1)OC=O	phenyl formate	-3.82
c1ccc(cc1)OC=O	phenyl formate	-3.82
c1ccc(cc1)OC=O	phenyl formate	-3.82
c1c(c(=O)[nH]c(=O)[nH]1)I	5-iodouracil	-18.72
c1c(c(=O)[nH]c(=O)[nH]1)I	5-iodouracil	-18.72
c1c(c(=O)[nH]c(=O)[nH]1)I	5-iodouracil	-18.72
c1c(c(=O)[nH]c(=O)[nH]1)I	5-iodouracil	-18.72
c1c(c(=O)[nH]c(=O)[nH]1)I	5-iodouracil	-18.72
CCCC(=O)O	butyric acid	-6.35
CCCC(=O)O	butyric acid	-6.35
CCCC(=O)O	butyric acid	-6.35
CCCC(=O)O	butyric acid	-6.35
CCCC(=O)O	butyric acid	-6.35
COC(C(F)(F)F)(OC)OC	1,1,1-trifluoro-2,2,2-trimethoxyethane	-0.8
COC(C(F)(F)F)(OC)OC	1,1,1-trifluoro-2,2,2-trimethoxyethane	-0.8
COC(C(F)(F)F)(OC)OC	1,1,1-trifluoro-2,2,2-trimethoxyethane	-0.8
COC(C(F)(F)F)(OC)OC	1,1,1-trifluoro-2,2,2-trimethoxyethane	-0.8
COC(C(F)(F)F)(OC)OC	1,1,1-trifluoro-2,2,2-trimethoxyethane	-0.8
C1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O	(2S,3R,4S,5R)-oxane-2,3,4,5-tetrol	-20.52
C1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O	(2S,3R,4S,5R)-oxane-2,3,4,5-tetrol	-20.52
C1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O	(2S,3R,4S,5R)-oxane-2,3,4,5-tetrol	-20.52
C1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O	(2S,3R,4S,5R)-oxane-2,3,4,5-tetrol	-20.52
C1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O	(2S,3R,4S,5R)-oxane-2,3,4,5-tetrol	-20.52
C(F)(F)(F)Br	bromo-trifluoro-methane	1.79
C(F)(F)(F)Br	bromo-trifluoro-methane	1.79
C(F)(F)(F)Br	bromo-trifluoro-methane	1.79
C(F)(F)(F)Br	bromo-trifluoro-methane	1.79
C(F)(F)(F)Br	bromo-trifluoro-methane	1.79
CCCCO	butan-1-ol	-4.72
CCCCO	butan-1-ol	-4.72
CCCCO	butan-1-ol	-4.72
CCCCO	butan-1-ol	-4.72
CCCCO	butan-1-ol	-4.72
c1ccc(cc1)F	fluorobenzene	-0.8
c1ccc(cc1)F	fluorobenzene	-0.8
c1ccc(cc1)F	fluorobenzene	-0.8
c1ccc(cc1)F	fluorobenzene	-0.8
c1ccc(cc1)F	fluorobenzene	-0.8
CCOC(=O)C	ethyl acetate	-2.94
CCOC(=O)C	ethyl acetate	-2.94
CCOC(=O)C	ethyl acetate	-2.94
CCOC(=O)C	ethyl acetate	-2.94
CCOC(=O)C	ethyl acetate	-2.94
CC(C)COC(=O)C(C)C	isobutyl 2-methylpropanoate	-1.69
CC(C)COC(=O)C(C)C	isobutyl 2-methylpropanoate	-1.69
CC(C)COC(=O)C(C)C	isobutyl 2-methylpropanoate	-1.69
CC(C)COC(=O)C(C)C	isobutyl 2-methylpropanoate	-1.69
CC(C)COC(=O)C(C)C	isobutyl 2-methylpropanoate	-1.69
CC(C)(C)OC	2-methoxy-2-methyl-propane	-2.21
CC(C)(C)OC	2-methoxy-2-methyl-propane	-2.21
CC(C)(C)OC	2-methoxy-2-methyl-propane	-2.21
CC(C)(C)OC	2-methoxy-2-methyl-propane	-2.21
CC(C)(C)OC	2-methoxy-2-methyl-propane	-2.21
C1=C[C@@H]([C@@H]2[C@H]1[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	heptachlor	-2.55
C1=C[C@@H]([C@@H]2[C@H]1[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	heptachlor	-2.55
C1=C[C@@H]([C@@H]2[C@H]1[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	heptachlor	-2.55
C1=C[C@@H]([C@@H]2[C@H]1[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	heptachlor	-2.55
C1=C[C@@H]([C@@H]2[C@H]1[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	heptachlor	-2.55
CCC(=O)CC	pentan-3-one	-3.41
CCC(=O)CC	pentan-3-one	-3.41
CCC(=O)CC	pentan-3-one	-3.41
CCC(=O)CC	pentan-3-one	-3.41
CCC(=O)CC	pentan-3-one	-3.41
COC(=O)C(F)(F)F	methyl 2,2,2-trifluoroacetate	-1.1
COC(=O)C(F)(F)F	methyl 2,2,2-trifluoroacetate	-1.1
COC(=O)C(F)(F)F	methyl 2,2,2-trifluoroacetate	-1.1
COC(=O)C(F)(F)F	methyl 2,2,2-trifluoroacetate	-1.1
COC(=O)C(F)(F)F	methyl 2,2,2-trifluoroacetate	-1.1
c1ccc2ccccc2c1	naphthalene	-2.4
c1ccc2ccccc2c1	naphthalene	-2.4
c1ccc2ccccc2c1	naphthalene	-2.4
c1ccc2ccccc2c1	naphthalene	-2.4
c1ccc2ccccc2c1	naphthalene	-2.4
c1cc(c(c(c1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4-trichlorophenyl)benzene	-4.4
c1cc(c(c(c1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4-trichlorophenyl)benzene	-4.4
c1cc(c(c(c1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4-trichlorophenyl)benzene	-4.4
c1cc(c(c(c1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4-trichlorophenyl)benzene	-4.4
c1cc(c(c(c1c2cc(c(c(c2Cl)Cl)Cl)Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4-trichlorophenyl)benzene	-4.4
CC(=O)Oc1ccccc1C(=O)O	acetylsalicylic acid	-9.94
CC(=O)Oc1ccccc1C(=O)O	acetylsalicylic acid	-9.94
CC(=O)Oc1ccccc1C(=O)O	acetylsalicylic acid	-9.94
CC(=O)Oc1ccccc1C(=O)O	acetylsalicylic acid	-9.94
CC(=O)Oc1ccccc1C(=O)O	acetylsalicylic acid	-9.94
CC(=O)C(C)(C)C	3,3-dimethylbutan-2-one	-3.11
CC(=O)C(C)(C)C	3,3-dimethylbutan-2-one	-3.11
CC(=O)C(C)(C)C	3,3-dimethylbutan-2-one	-3.11
CC(=O)C(C)(C)C	3,3-dimethylbutan-2-one	-3.11
CC(=O)C(C)(C)C	3,3-dimethylbutan-2-one	-3.11
COS(=O)(=O)C	methyl methanesulfonate	-4.87
COS(=O)(=O)C	methyl methanesulfonate	-4.87
COS(=O)(=O)C	methyl methanesulfonate	-4.87
COS(=O)(=O)C	methyl methanesulfonate	-4.87
COS(=O)(=O)C	methyl methanesulfonate	-4.87
CCc1ccncc1	4-ethylpyridine	-4.73
CCc1ccncc1	4-ethylpyridine	-4.73
CCc1ccncc1	4-ethylpyridine	-4.73
CCc1ccncc1	4-ethylpyridine	-4.73
CCc1ccncc1	4-ethylpyridine	-4.73
CC(C)NC(C)C	N-isopropylpropan-2-amine	-3.22
CC(C)NC(C)C	N-isopropylpropan-2-amine	-3.22
CC(C)NC(C)C	N-isopropylpropan-2-amine	-3.22
CC(C)NC(C)C	N-isopropylpropan-2-amine	-3.22
CC(C)NC(C)C	N-isopropylpropan-2-amine	-3.22
c1cc2c(cc1Cl)Oc3ccc(cc3O2)Cl	2,7-dichlorodibenzo-p-dioxin	-3.67
c1cc2c(cc1Cl)Oc3ccc(cc3O2)Cl	2,7-dichlorodibenzo-p-dioxin	-3.67
c1cc2c(cc1Cl)Oc3ccc(cc3O2)Cl	2,7-dichlorodibenzo-p-dioxin	-3.67
c1cc2c(cc1Cl)Oc3ccc(cc3O2)Cl	2,7-dichlorodibenzo-p-dioxin	-3.67
c1cc2c(cc1Cl)Oc3ccc(cc3O2)Cl	2,7-dichlorodibenzo-p-dioxin	-3.67
CCCCCCCN	heptan-1-amine	-3.79
CCCCCCCN	heptan-1-amine	-3.79
CCCCCCCN	heptan-1-amine	-3.79
CCCCCCCN	heptan-1-amine	-3.79
CCCCCCCN	heptan-1-amine	-3.79
CC1CCCC1	methylcyclopentane	1.59
CC1CCCC1	methylcyclopentane	1.59
CC1CCCC1	methylcyclopentane	1.59
CC1CCCC1	methylcyclopentane	1.59
CC1CCCC1	methylcyclopentane	1.59
CCC	propane	2.0
CCC	propane	2.0
CCC	propane	2.0
CCC	propane	2.0
CCC	propane	2.0
C[C@H]1CCCO1	2-methyltetrahydrofuran	-3.3
C[C@H]1CCCO1	2-methyltetrahydrofuran	-3.3
C[C@H]1CCCO1	2-methyltetrahydrofuran	-3.3
C[C@H]1CCCO1	2-methyltetrahydrofuran	-3.3
C[C@H]1CCCO1	2-methyltetrahydrofuran	-3.3
CNC(=O)Oc1cccc2c1cccc2	naphthalen-1-yl N-methylcarbamate	-9.45
CNC(=O)Oc1cccc2c1cccc2	naphthalen-1-yl N-methylcarbamate	-9.45
CNC(=O)Oc1cccc2c1cccc2	naphthalen-1-yl N-methylcarbamate	-9.45
CNC(=O)Oc1cccc2c1cccc2	naphthalen-1-yl N-methylcarbamate	-9.45
CNC(=O)Oc1cccc2c1cccc2	naphthalen-1-yl N-methylcarbamate	-9.45
c1cc(cc(c1)O)C=O	3-hydroxybenzaldehyde	-9.52
c1cc(cc(c1)O)C=O	3-hydroxybenzaldehyde	-9.52
c1cc(cc(c1)O)C=O	3-hydroxybenzaldehyde	-9.52
c1cc(cc(c1)O)C=O	3-hydroxybenzaldehyde	-9.52
c1cc(cc(c1)O)C=O	3-hydroxybenzaldehyde	-9.52
c1ccc2cc3ccccc3cc2c1	anthracene	-3.95
c1ccc2cc3ccccc3cc2c1	anthracene	-3.95
c1ccc2cc3ccccc3cc2c1	anthracene	-3.95
c1ccc2cc3ccccc3cc2c1	anthracene	-3.95
c1ccc2cc3ccccc3cc2c1	anthracene	-3.95
C(Cl)Cl	dichloromethane	-1.31
C(Cl)Cl	dichloromethane	-1.31
C(Cl)Cl	dichloromethane	-1.31
C(Cl)Cl	dichloromethane	-1.31
C(Cl)Cl	dichloromethane	-1.31
CC(C)(C)C(=O)OC	methyl 2,2-dimethylpropanoate	-2.4
CC(C)(C)C(=O)OC	methyl 2,2-dimethylpropanoate	-2.4
CC(C)(C)C(=O)OC	methyl 2,2-dimethylpropanoate	-2.4
CC(C)(C)C(=O)OC	methyl 2,2-dimethylpropanoate	-2.4
CC(C)(C)C(=O)OC	methyl 2,2-dimethylpropanoate	-2.4
C([N+](=O)[O-])(Cl)(Cl)Cl	trichloro(nitro)methane	-1.45
C([N+](=O)[O-])(Cl)(Cl)Cl	trichloro(nitro)methane	-1.45
C([N+](=O)[O-])(Cl)(Cl)Cl	trichloro(nitro)methane	-1.45
C([N+](=O)[O-])(Cl)(Cl)Cl	trichloro(nitro)methane	-1.45
C([N+](=O)[O-])(Cl)(Cl)Cl	trichloro(nitro)methane	-1.45
C1CC[S+2](C1)([O-])[O-]	sulfolane	-8.61
C1CC[S+2](C1)([O-])[O-]	sulfolane	-8.61
C1CC[S+2](C1)([O-])[O-]	sulfolane	-8.61
C1CC[S+2](C1)([O-])[O-]	sulfolane	-8.61
C1CC[S+2](C1)([O-])[O-]	sulfolane	-8.61
Cc1cccc(c1O)C	2,6-dimethylphenol	-5.26
Cc1cccc(c1O)C	2,6-dimethylphenol	-5.26
Cc1cccc(c1O)C	2,6-dimethylphenol	-5.26
Cc1cccc(c1O)C	2,6-dimethylphenol	-5.26
Cc1cccc(c1O)C	2,6-dimethylphenol	-5.26
Cc1cccc(c1)O	m-cresol	-5.49
Cc1cccc(c1)O	m-cresol	-5.49
Cc1cccc(c1)O	m-cresol	-5.49
Cc1cccc(c1)O	m-cresol	-5.49
Cc1cccc(c1)O	m-cresol	-5.49
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)O)N	1-amino-4-hydroxy-9,10-anthracenedione	-9.53
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)O)N	1-amino-4-hydroxy-9,10-anthracenedione	-9.53
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)O)N	1-amino-4-hydroxy-9,10-anthracenedione	-9.53
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)O)N	1-amino-4-hydroxy-9,10-anthracenedione	-9.53
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)O)N	1-amino-4-hydroxy-9,10-anthracenedione	-9.53
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)N)N	1,4-diamino-9,10-anthracenedione	-11.85
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)N)N	1,4-diamino-9,10-anthracenedione	-11.85
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)N)N	1,4-diamino-9,10-anthracenedione	-11.85
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)N)N	1,4-diamino-9,10-anthracenedione	-11.85
c1ccc2c(c1)C(=O)c3c(ccc(c3C2=O)N)N	1,4-diamino-9,10-anthracenedione	-11.85
CCCCCCCC(=O)C	nonan-2-one	-2.49
CCCCCCCC(=O)C	nonan-2-one	-2.49
CCCCCCCC(=O)C	nonan-2-one	-2.49
CCCCCCCC(=O)C	nonan-2-one	-2.49
CCCCCCCC(=O)C	nonan-2-one	-2.49
CCCCN	butan-1-amine	-4.24
CCCCN	butan-1-amine	-4.24
CCCCN	butan-1-amine	-4.24
CCCCN	butan-1-amine	-4.24
CCCCN	butan-1-amine	-4.24
CCCC(=O)OCC	ethyl butanoate	-2.49
CCCC(=O)OCC	ethyl butanoate	-2.49
CCCC(=O)OCC	ethyl butanoate	-2.49
CCCC(=O)OCC	ethyl butanoate	-2.49
CCCC(=O)OCC	ethyl butanoate	-2.49
Cc1ccc(cc1)N	4-methylaniline	-5.57
Cc1ccc(cc1)N	4-methylaniline	-5.57
Cc1ccc(cc1)N	4-methylaniline	-5.57
Cc1ccc(cc1)N	4-methylaniline	-5.57
Cc1ccc(cc1)N	4-methylaniline	-5.57
CCCCCCI	1-iodohexane	0.08
CCCCCCI	1-iodohexane	0.08
CCCCCCI	1-iodohexane	0.08
CCCCCCI	1-iodohexane	0.08
CCCCCCI	1-iodohexane	0.08
C(C(F)(Cl)Cl)(F)(F)Cl	1,1,2-trichloro-1,2,2-trifluoro-ethane	1.77
C(C(F)(Cl)Cl)(F)(F)Cl	1,1,2-trichloro-1,2,2-trifluoro-ethane	1.77
C(C(F)(Cl)Cl)(F)(F)Cl	1,1,2-trichloro-1,2,2-trifluoro-ethane	1.77
C(C(F)(Cl)Cl)(F)(F)Cl	1,1,2-trichloro-1,2,2-trifluoro-ethane	1.77
C(C(F)(Cl)Cl)(F)(F)Cl	1,1,2-trichloro-1,2,2-trifluoro-ethane	1.77
COP(=O)(OC)OC	trimethyl phosphate	-8.7
COP(=O)(OC)OC	trimethyl phosphate	-8.7
COP(=O)(OC)OC	trimethyl phosphate	-8.7
COP(=O)(OC)OC	trimethyl phosphate	-8.7
COP(=O)(OC)OC	trimethyl phosphate	-8.7
c1cc(cc(c1)Cl)Cl	1,3-dichlorobenzene	-0.98
c1cc(cc(c1)Cl)Cl	1,3-dichlorobenzene	-0.98
c1cc(cc(c1)Cl)Cl	1,3-dichlorobenzene	-0.98
c1cc(cc(c1)Cl)Cl	1,3-dichlorobenzene	-0.98
c1cc(cc(c1)Cl)Cl	1,3-dichlorobenzene	-0.98
Cc1cc(c2ccccc2c1)C	1,3-dimethylnaphthalene	-2.47
Cc1cc(c2ccccc2c1)C	1,3-dimethylnaphthalene	-2.47
Cc1cc(c2ccccc2c1)C	1,3-dimethylnaphthalene	-2.47
Cc1cc(c2ccccc2c1)C	1,3-dimethylnaphthalene	-2.47
Cc1cc(c2ccccc2c1)C	1,3-dimethylnaphthalene	-2.47
CCCC(C)C	isohexane	2.51
CCCC(C)C	isohexane	2.51
CCCC(C)C	isohexane	2.51
CCCC(C)C	isohexane	2.51
CCCC(C)C	isohexane	2.51
CCOP(=S)(OCC)Oc1c(cc(c(n1)Cl)Cl)Cl	chlorpyrifos	-5.04
CCOP(=S)(OCC)Oc1c(cc(c(n1)Cl)Cl)Cl	chlorpyrifos	-5.04
CCOP(=S)(OCC)Oc1c(cc(c(n1)Cl)Cl)Cl	chlorpyrifos	-5.04
CCOP(=S)(OCC)Oc1c(cc(c(n1)Cl)Cl)Cl	chlorpyrifos	-5.04
CCOP(=S)(OCC)Oc1c(cc(c(n1)Cl)Cl)Cl	chlorpyrifos	-5.04
C(C(F)(F)F)Cl	2-chloro-1,1,1-trifluoro-ethane	0.06
C(C(F)(F)F)Cl	2-chloro-1,1,1-trifluoro-ethane	0.06
C(C(F)(F)F)Cl	2-chloro-1,1,1-trifluoro-ethane	0.06
C(C(F)(F)F)Cl	2-chloro-1,1,1-trifluoro-ethane	0.06
C(C(F)(F)F)Cl	2-chloro-1,1,1-trifluoro-ethane	0.06
C=C	ethylene	1.28
C=C	ethylene	1.28
C=C	ethylene	1.28
C=C	ethylene	1.28
C=C	ethylene	1.28
CCCCCI	1-iodopentane	-0.14
CCCCCI	1-iodopentane	-0.14
CCCCCI	1-iodopentane	-0.14
CCCCCI	1-iodopentane	-0.14
CCCCCI	1-iodopentane	-0.14
COC(OC)OC	trimethoxymethane	-4.42
COC(OC)OC	trimethoxymethane	-4.42
COC(OC)OC	trimethoxymethane	-4.42
COC(OC)OC	trimethoxymethane	-4.42
COC(OC)OC	trimethoxymethane	-4.42
CCCCCCCCCC	decane	3.16
CCCCCCCCCC	decane	3.16
CCCCCCCCCC	decane	3.16
CCCCCCCCCC	decane	3.16
CCCCCCCCCC	decane	3.16
C[C@@H](CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxypropane	-4.95
C[C@@H](CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxypropane	-4.95
C[C@@H](CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxypropane	-4.95
C[C@@H](CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxypropane	-4.95
C[C@@H](CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxypropane	-4.95
CC=C	prop-1-ene	1.32
CC=C	prop-1-ene	1.32
CC=C	prop-1-ene	1.32
CC=C	prop-1-ene	1.32
CC=C	prop-1-ene	1.32
Cc1c[nH]c2c1cccc2	3-methyl-1H-indole	-5.88
Cc1c[nH]c2c1cccc2	3-methyl-1H-indole	-5.88
Cc1c[nH]c2c1cccc2	3-methyl-1H-indole	-5.88
Cc1c[nH]c2c1cccc2	3-methyl-1H-indole	-5.88
Cc1c[nH]c2c1cccc2	3-methyl-1H-indole	-5.88
COP(=O)([C@H](C(Cl)(Cl)Cl)O)OC	(1R)-2,2,2-trichloro-1-dimethoxyphosphoryl-ethanol	-12.74
COP(=O)([C@H](C(Cl)(Cl)Cl)O)OC	(1R)-2,2,2-trichloro-1-dimethoxyphosphoryl-ethanol	-12.74
COP(=O)([C@H](C(Cl)(Cl)Cl)O)OC	(1R)-2,2,2-trichloro-1-dimethoxyphosphoryl-ethanol	-12.74
COP(=O)([C@H](C(Cl)(Cl)Cl)O)OC	(1R)-2,2,2-trichloro-1-dimethoxyphosphoryl-ethanol	-12.74
COP(=O)([C@H](C(Cl)(Cl)Cl)O)OC	(1R)-2,2,2-trichloro-1-dimethoxyphosphoryl-ethanol	-12.74
C1CCCCC1	cyclohexane	1.23
C1CCCCC1	cyclohexane	1.23
C1CCCCC1	cyclohexane	1.23
C1CCCCC1	cyclohexane	1.23
C1CCCCC1	cyclohexane	1.23
CC(=CCC/C(=C/CO)/C)C	(2E)-3,7-dimethylocta-2,6-dien-1-ol	-4.45
CC(=CCC/C(=C/CO)/C)C	(2E)-3,7-dimethylocta-2,6-dien-1-ol	-4.45
CC(=CCC/C(=C/CO)/C)C	(2E)-3,7-dimethylocta-2,6-dien-1-ol	-4.45
CC(=CCC/C(=C/CO)/C)C	(2E)-3,7-dimethylocta-2,6-dien-1-ol	-4.45
CC(=CCC/C(=C/CO)/C)C	(2E)-3,7-dimethylocta-2,6-dien-1-ol	-4.45
CC(C)c1ccccc1	cumene	-0.3
CC(C)c1ccccc1	cumene	-0.3
CC(C)c1ccccc1	cumene	-0.3
CC(C)c1ccccc1	cumene	-0.3
CC(C)c1ccccc1	cumene	-0.3
CC(C)C(C)C(C)C	2,3,4-trimethylpentane	2.56
CC(C)C(C)C(C)C	2,3,4-trimethylpentane	2.56
CC(C)C(C)C(C)C	2,3,4-trimethylpentane	2.56
CC(C)C(C)C(C)C	2,3,4-trimethylpentane	2.56
CC(C)C(C)C(C)C	2,3,4-trimethylpentane	2.56
CC(C)C(=O)C	3-methylbutan-2-one	-3.24
CC(C)C(=O)C	3-methylbutan-2-one	-3.24
CC(C)C(=O)C	3-methylbutan-2-one	-3.24
CC(C)C(=O)C	3-methylbutan-2-one	-3.24
CC(C)C(=O)C	3-methylbutan-2-one	-3.24
CCCCNCCCC	N-butylbutan-1-amine	-3.24
CCCCNCCCC	N-butylbutan-1-amine	-3.24
CCCCNCCCC	N-butylbutan-1-amine	-3.24
CCCCNCCCC	N-butylbutan-1-amine	-3.24
CCCCNCCCC	N-butylbutan-1-amine	-3.24
CCCCS	butane-1-thiol	-0.99
CCCCS	butane-1-thiol	-0.99
CCCCS	butane-1-thiol	-0.99
CCCCS	butane-1-thiol	-0.99
CCCCS	butane-1-thiol	-0.99
c1ccc2c(c1)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4-tetrachlorodibenzo-p-dioxin	-3.81
c1ccc2c(c1)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4-tetrachlorodibenzo-p-dioxin	-3.81
c1ccc2c(c1)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4-tetrachlorodibenzo-p-dioxin	-3.81
c1ccc2c(c1)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4-tetrachlorodibenzo-p-dioxin	-3.81
c1ccc2c(c1)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4-tetrachlorodibenzo-p-dioxin	-3.81
COc1c(c(c(c(c1Cl)C=O)Cl)OC)O	2,6-dichlorosyringaldehyde	-8.68
COc1c(c(c(c(c1Cl)C=O)Cl)OC)O	2,6-dichlorosyringaldehyde	-8.68
COc1c(c(c(c(c1Cl)C=O)Cl)OC)O	2,6-dichlorosyringaldehyde	-8.68
COc1c(c(c(c(c1Cl)C=O)Cl)OC)O	2,6-dichlorosyringaldehyde	-8.68
COc1c(c(c(c(c1Cl)C=O)Cl)OC)O	2,6-dichlorosyringaldehyde	-8.68
C1CCC(CC1)N	cyclohexanamine	-4.59
C1CCC(CC1)N	cyclohexanamine	-4.59
C1CCC(CC1)N	cyclohexanamine	-4.59
C1CCC(CC1)N	cyclohexanamine	-4.59
C1CCC(CC1)N	cyclohexanamine	-4.59
C(F)(F)Cl	chloro-difluoro-methane	-0.5
C(F)(F)Cl	chloro-difluoro-methane	-0.5
C(F)(F)Cl	chloro-difluoro-methane	-0.5
C(F)(F)Cl	chloro-difluoro-methane	-0.5
C(F)(F)Cl	chloro-difluoro-methane	-0.5
COC(=O)c1ccc(cc1)[N+](=O)[O-]	methyl 4-nitrobenzoate	-6.88
COC(=O)c1ccc(cc1)[N+](=O)[O-]	methyl 4-nitrobenzoate	-6.88
COC(=O)c1ccc(cc1)[N+](=O)[O-]	methyl 4-nitrobenzoate	-6.88
COC(=O)c1ccc(cc1)[N+](=O)[O-]	methyl 4-nitrobenzoate	-6.88
COC(=O)c1ccc(cc1)[N+](=O)[O-]	methyl 4-nitrobenzoate	-6.88
CC(=O)c1cccnc1	1-(3-pyridyl)ethanone	-8.26
CC(=O)c1cccnc1	1-(3-pyridyl)ethanone	-8.26
CC(=O)c1cccnc1	1-(3-pyridyl)ethanone	-8.26
CC(=O)c1cccnc1	1-(3-pyridyl)ethanone	-8.26
CC(=O)c1cccnc1	1-(3-pyridyl)ethanone	-8.26
CC#C	prop-1-yne	-0.48
CC#C	prop-1-yne	-0.48
CC#C	prop-1-yne	-0.48
CC#C	prop-1-yne	-0.48
CC#C	prop-1-yne	-0.48
CCCCCCCCC=O	nonanal	-2.07
CCCCCCCCC=O	nonanal	-2.07
CCCCCCCCC=O	nonanal	-2.07
CCCCCCCCC=O	nonanal	-2.07
CCCCCCCCC=O	nonanal	-2.07
CCC(=O)O	propionic acid	-6.46
CCC(=O)O	propionic acid	-6.46
CCC(=O)O	propionic acid	-6.46
CCC(=O)O	propionic acid	-6.46
CCC(=O)O	propionic acid	-6.46
C(Cl)(Cl)Cl	chloroform	-1.08
C(Cl)(Cl)Cl	chloroform	-1.08
C(Cl)(Cl)Cl	chloroform	-1.08
C(Cl)(Cl)Cl	chloroform	-1.08
C(Cl)(Cl)Cl	chloroform	-1.08
Cc1cccc(c1C)C	1,2,3-trimethylbenzene	-1.21
Cc1cccc(c1C)C	1,2,3-trimethylbenzene	-1.21
Cc1cccc(c1C)C	1,2,3-trimethylbenzene	-1.21
Cc1cccc(c1C)C	1,2,3-trimethylbenzene	-1.21
Cc1cccc(c1C)C	1,2,3-trimethylbenzene	-1.21
C	methane	2.0
C	methane	2.0
C	methane	2.0
C	methane	2.0
C	methane	2.0
c1ccc(cc1)CCl	benzyl chloride	-1.93
c1ccc(cc1)CCl	benzyl chloride	-1.93
c1ccc(cc1)CCl	benzyl chloride	-1.93
c1ccc(cc1)CCl	benzyl chloride	-1.93
c1ccc(cc1)CCl	benzyl chloride	-1.93
CC1CCCCC1	methylcyclohexane	1.7
CC1CCCCC1	methylcyclohexane	1.7
CC1CCCCC1	methylcyclohexane	1.7
CC1CCCCC1	methylcyclohexane	1.7
CC1CCCCC1	methylcyclohexane	1.7
Cc1cccs1	2-methylthiophene	-1.38
Cc1cccs1	2-methylthiophene	-1.38
Cc1cccs1	2-methylthiophene	-1.38
Cc1cccs1	2-methylthiophene	-1.38
Cc1cccs1	2-methylthiophene	-1.38
c1ccncc1	pyridine	-4.69
c1ccncc1	pyridine	-4.69
c1ccncc1	pyridine	-4.69
c1ccncc1	pyridine	-4.69
c1ccncc1	pyridine	-4.69
CCCCCl	1-chlorobutane	-0.16
CCCCCl	1-chlorobutane	-0.16
CCCCCl	1-chlorobutane	-0.16
CCCCCl	1-chlorobutane	-0.16
CCCCCl	1-chlorobutane	-0.16
C[C@H]1CC[C@@H](O1)C	2,5-dimethyltetrahydrofuran	-2.92
C[C@H]1CC[C@@H](O1)C	2,5-dimethyltetrahydrofuran	-2.92
C[C@H]1CC[C@@H](O1)C	2,5-dimethyltetrahydrofuran	-2.92
C[C@H]1CC[C@@H](O1)C	2,5-dimethyltetrahydrofuran	-2.92
C[C@H]1CC[C@@H](O1)C	2,5-dimethyltetrahydrofuran	-2.92
Cc1ccc(c(c1)OC)O	4-methyl-2-methoxyphenol	-5.8
Cc1ccc(c(c1)OC)O	4-methyl-2-methoxyphenol	-5.8
Cc1ccc(c(c1)OC)O	4-methyl-2-methoxyphenol	-5.8
Cc1ccc(c(c1)OC)O	4-methyl-2-methoxyphenol	-5.8
Cc1ccc(c(c1)OC)O	4-methyl-2-methoxyphenol	-5.8
C1[C@H]([C@@H]2[C@H]([C@H]1Cl)[C@]3(C(=C([C@@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	chlordane	-3.44
C1[C@H]([C@@H]2[C@H]([C@H]1Cl)[C@]3(C(=C([C@@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	chlordane	-3.44
C1[C@H]([C@@H]2[C@H]([C@H]1Cl)[C@]3(C(=C([C@@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	chlordane	-3.44
C1[C@H]([C@@H]2[C@H]([C@H]1Cl)[C@]3(C(=C([C@@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	chlordane	-3.44
C1[C@H]([C@@H]2[C@H]([C@H]1Cl)[C@]3(C(=C([C@@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl)Cl	chlordane	-3.44
Cc1ccccc1	toluene	-0.9
Cc1ccccc1	toluene	-0.9
Cc1ccccc1	toluene	-0.9
Cc1ccccc1	toluene	-0.9
Cc1ccccc1	toluene	-0.9
CC(C)COC=O	isobutyl formate	-2.22
CC(C)COC=O	isobutyl formate	-2.22
CC(C)COC=O	isobutyl formate	-2.22
CC(C)COC=O	isobutyl formate	-2.22
CC(C)COC=O	isobutyl formate	-2.22
CCOC(=O)c1ccc(cc1)O	ethyl paraben	-9.2
CCOC(=O)c1ccc(cc1)O	ethyl paraben	-9.2
CCOC(=O)c1ccc(cc1)O	ethyl paraben	-9.2
CCOC(=O)c1ccc(cc1)O	ethyl paraben	-9.2
CCOC(=O)c1ccc(cc1)O	ethyl paraben	-9.2
CCOCCOCC	1,2-diethoxyethane	-3.54
CCOCCOCC	1,2-diethoxyethane	-3.54
CCOCCOCC	1,2-diethoxyethane	-3.54
CCOCCOCC	1,2-diethoxyethane	-3.54
CCOCCOCC	1,2-diethoxyethane	-3.54
CCCCCOC(=O)CC	pentyl propanoate	-2.11
CCCCCOC(=O)CC	pentyl propanoate	-2.11
CCCCCOC(=O)CC	pentyl propanoate	-2.11
CCCCCOC(=O)CC	pentyl propanoate	-2.11
CCCCCOC(=O)CC	pentyl propanoate	-2.11
CCCc1ccc(cc1)O	4-propylphenol	-5.21
CCCc1ccc(cc1)O	4-propylphenol	-5.21
CCCc1ccc(cc1)O	4-propylphenol	-5.21
CCCc1ccc(cc1)O	4-propylphenol	-5.21
CCCc1ccc(cc1)O	4-propylphenol	-5.21
CC=C(C)C	2-methylbut-2-ene	1.31
CC=C(C)C	2-methylbut-2-ene	1.31
CC=C(C)C	2-methylbut-2-ene	1.31
CC=C(C)C	2-methylbut-2-ene	1.31
CC=C(C)C	2-methylbut-2-ene	1.31
C(CCl)Cl	1,2-dichloroethane	-1.79
C(CCl)Cl	1,2-dichloroethane	-1.79
C(CCl)Cl	1,2-dichloroethane	-1.79
C(CCl)Cl	1,2-dichloroethane	-1.79
C(CCl)Cl	1,2-dichloroethane	-1.79
CCC(C)(C)CC	3,3-dimethylpentane	2.56
CCC(C)(C)CC	3,3-dimethylpentane	2.56
CCC(C)(C)CC	3,3-dimethylpentane	2.56
CCC(C)(C)CC	3,3-dimethylpentane	2.56
CCC(C)(C)CC	3,3-dimethylpentane	2.56
Cc1cc2ccccc2cc1C	2,3-dimethylnaphthalene	-2.78
Cc1cc2ccccc2cc1C	2,3-dimethylnaphthalene	-2.78
Cc1cc2ccccc2cc1C	2,3-dimethylnaphthalene	-2.78
Cc1cc2ccccc2cc1C	2,3-dimethylnaphthalene	-2.78
Cc1cc2ccccc2cc1C	2,3-dimethylnaphthalene	-2.78
Cc1cccc(n1)C	2,6-dimethylpyridine	-4.59
Cc1cccc(n1)C	2,6-dimethylpyridine	-4.59
Cc1cccc(n1)C	2,6-dimethylpyridine	-4.59
Cc1cccc(n1)C	2,6-dimethylpyridine	-4.59
Cc1cccc(n1)C	2,6-dimethylpyridine	-4.59
COC(C(Cl)Cl)(F)F	2,2-dichloro-1,1-difluoro-1-methoxy-ethane	-1.12
COC(C(Cl)Cl)(F)F	2,2-dichloro-1,1-difluoro-1-methoxy-ethane	-1.12
COC(C(Cl)Cl)(F)F	2,2-dichloro-1,1-difluoro-1-methoxy-ethane	-1.12
COC(C(Cl)Cl)(F)F	2,2-dichloro-1,1-difluoro-1-methoxy-ethane	-1.12
COC(C(Cl)Cl)(F)F	2,2-dichloro-1,1-difluoro-1-methoxy-ethane	-1.12
CCOCCOC(=O)C	2-ethoxyethyl acetate	-5.31
CCOCCOC(=O)C	2-ethoxyethyl acetate	-5.31
CCOCCOC(=O)C	2-ethoxyethyl acetate	-5.31
CCOCCOC(=O)C	2-ethoxyethyl acetate	-5.31
CCOCCOC(=O)C	2-ethoxyethyl acetate	-5.31
COc1cccc(c1)N	3-methoxyaniline	-7.29
COc1cccc(c1)N	3-methoxyaniline	-7.29
COc1cccc(c1)N	3-methoxyaniline	-7.29
COc1cccc(c1)N	3-methoxyaniline	-7.29
COc1cccc(c1)N	3-methoxyaniline	-7.29
c1cc(cnc1)C=O	pyridine-3-carbaldehyde	-7.1
c1cc(cnc1)C=O	pyridine-3-carbaldehyde	-7.1
c1cc(cnc1)C=O	pyridine-3-carbaldehyde	-7.1
c1cc(cnc1)C=O	pyridine-3-carbaldehyde	-7.1
c1cc(cnc1)C=O	pyridine-3-carbaldehyde	-7.1
CCC(C)(C)O	2-methylbutan-2-ol	-4.43
CCC(C)(C)O	2-methylbutan-2-ol	-4.43
CCC(C)(C)O	2-methylbutan-2-ol	-4.43
CCC(C)(C)O	2-methylbutan-2-ol	-4.43
CCC(C)(C)O	2-methylbutan-2-ol	-4.43
CCc1cccc(c1N(COC)C(=O)CCl)CC	alachlor	-8.21
CCc1cccc(c1N(COC)C(=O)CCl)CC	alachlor	-8.21
CCc1cccc(c1N(COC)C(=O)CCl)CC	alachlor	-8.21
CCc1cccc(c1N(COC)C(=O)CCl)CC	alachlor	-8.21
CCc1cccc(c1N(COC)C(=O)CCl)CC	alachlor	-8.21
Cn1cccc1	1-methylpyrrole	-2.89
Cn1cccc1	1-methylpyrrole	-2.89
Cn1cccc1	1-methylpyrrole	-2.89
Cn1cccc1	1-methylpyrrole	-2.89
Cn1cccc1	1-methylpyrrole	-2.89
COCOC	dimethoxymethane	-2.93
COCOC	dimethoxymethane	-2.93
COCOC	dimethoxymethane	-2.93
COCOC	dimethoxymethane	-2.93
COCOC	dimethoxymethane	-2.93
CCC(CC)O	pentan-3-ol	-4.35
CCC(CC)O	pentan-3-ol	-4.35
CCC(CC)O	pentan-3-ol	-4.35
CCC(CC)O	pentan-3-ol	-4.35
CCC(CC)O	pentan-3-ol	-4.35
CCCCCCCCCC(=O)C	undecan-2-one	-2.15
CCCCCCCCCC(=O)C	undecan-2-one	-2.15
CCCCCCCCCC(=O)C	undecan-2-one	-2.15
CCCCCCCCCC(=O)C	undecan-2-one	-2.15
CCCCCCCCCC(=O)C	undecan-2-one	-2.15
C(CBr)Cl	1-bromo-2-chloro-ethane	-1.95
C(CBr)Cl	1-bromo-2-chloro-ethane	-1.95
C(CBr)Cl	1-bromo-2-chloro-ethane	-1.95
C(CBr)Cl	1-bromo-2-chloro-ethane	-1.95
C(CBr)Cl	1-bromo-2-chloro-ethane	-1.95
c1ccc(cc1)I	iodobenzene	-1.74
c1ccc(cc1)I	iodobenzene	-1.74
c1ccc(cc1)I	iodobenzene	-1.74
c1ccc(cc1)I	iodobenzene	-1.74
c1ccc(cc1)I	iodobenzene	-1.74
CC1=CC(=O)CC(C1)(C)C	3,5,5-trimethylcyclohex-2-en-1-one	-5.18
CC1=CC(=O)CC(C1)(C)C	3,5,5-trimethylcyclohex-2-en-1-one	-5.18
CC1=CC(=O)CC(C1)(C)C	3,5,5-trimethylcyclohex-2-en-1-one	-5.18
CC1=CC(=O)CC(C1)(C)C	3,5,5-trimethylcyclohex-2-en-1-one	-5.18
CC1=CC(=O)CC(C1)(C)C	3,5,5-trimethylcyclohex-2-en-1-one	-5.18
CCI	iodoethane	-0.74
CCI	iodoethane	-0.74
CCI	iodoethane	-0.74
CCI	iodoethane	-0.74
CCI	iodoethane	-0.74
CCCc1ccc(c(c1)OC)O	4-propylguaiacol	-5.26
CCCc1ccc(c(c1)OC)O	4-propylguaiacol	-5.26
CCCc1ccc(c(c1)OC)O	4-propylguaiacol	-5.26
CCCc1ccc(c(c1)OC)O	4-propylguaiacol	-5.26
CCCc1ccc(c(c1)OC)O	4-propylguaiacol	-5.26
CC(C)Br	2-bromopropane	-0.48
CC(C)Br	2-bromopropane	-0.48
CC(C)Br	2-bromopropane	-0.48
CC(C)Br	2-bromopropane	-0.48
CC(C)Br	2-bromopropane	-0.48
Cc1ccc(cc1)Br	1-bromo-4-methyl-benzene	-1.39
Cc1ccc(cc1)Br	1-bromo-4-methyl-benzene	-1.39
Cc1ccc(cc1)Br	1-bromo-4-methyl-benzene	-1.39
Cc1ccc(cc1)Br	1-bromo-4-methyl-benzene	-1.39
Cc1ccc(cc1)Br	1-bromo-4-methyl-benzene	-1.39
c1cc(ccc1C#N)O	4-hydroxybenzonitrile	-10.17
c1cc(ccc1C#N)O	4-hydroxybenzonitrile	-10.17
c1cc(ccc1C#N)O	4-hydroxybenzonitrile	-10.17
c1cc(ccc1C#N)O	4-hydroxybenzonitrile	-10.17
c1cc(ccc1C#N)O	4-hydroxybenzonitrile	-10.17
CS(=O)(=O)C	methylsulfonylmethane	-10.08
CS(=O)(=O)C	methylsulfonylmethane	-10.08
CS(=O)(=O)C	methylsulfonylmethane	-10.08
CS(=O)(=O)C	methylsulfonylmethane	-10.08
CS(=O)(=O)C	methylsulfonylmethane	-10.08
CCc1cccc(c1)O	3-ethylphenol	-6.25
CCc1cccc(c1)O	3-ethylphenol	-6.25
CCc1cccc(c1)O	3-ethylphenol	-6.25
CCc1cccc(c1)O	3-ethylphenol	-6.25
CCc1cccc(c1)O	3-ethylphenol	-6.25
CC1=CC[C@H](C[C@@H]1O)C(=C)C	(1S,5R)-2-methyl-5-(1-methylethenyl)-2-cyclohexen-1-ol	-4.44
CC1=CC[C@H](C[C@@H]1O)C(=C)C	(1S,5R)-2-methyl-5-(1-methylethenyl)-2-cyclohexen-1-ol	-4.44
CC1=CC[C@H](C[C@@H]1O)C(=C)C	(1S,5R)-2-methyl-5-(1-methylethenyl)-2-cyclohexen-1-ol	-4.44
CC1=CC[C@H](C[C@@H]1O)C(=C)C	(1S,5R)-2-methyl-5-(1-methylethenyl)-2-cyclohexen-1-ol	-4.44
CC1=CC[C@H](C[C@@H]1O)C(=C)C	(1S,5R)-2-methyl-5-(1-methylethenyl)-2-cyclohexen-1-ol	-4.44
c1cc(ccc1Br)Br	1,4-dibromobenzene	-2.3
c1cc(ccc1Br)Br	1,4-dibromobenzene	-2.3
c1cc(ccc1Br)Br	1,4-dibromobenzene	-2.3
c1cc(ccc1Br)Br	1,4-dibromobenzene	-2.3
c1cc(ccc1Br)Br	1,4-dibromobenzene	-2.3
COc1c(ccc(c1C(=O)O)Cl)Cl	dicamba	-9.86
COc1c(ccc(c1C(=O)O)Cl)Cl	dicamba	-9.86
COc1c(ccc(c1C(=O)O)Cl)Cl	dicamba	-9.86
COc1c(ccc(c1C(=O)O)Cl)Cl	dicamba	-9.86
COc1c(ccc(c1C(=O)O)Cl)Cl	dicamba	-9.86
CC/C=C\C	pent-2-ene	1.31
CC/C=C\C	pent-2-ene	1.31
CC/C=C\C	pent-2-ene	1.31
CC/C=C\C	pent-2-ene	1.31
CC/C=C\C	pent-2-ene	1.31
CC	ethane	1.83
CC	ethane	1.83
CC	ethane	1.83
CC	ethane	1.83
CC	ethane	1.83
COc1ccccc1OC	1,2-dimethoxybenzene	-5.33
COc1ccccc1OC	1,2-dimethoxybenzene	-5.33
COc1ccccc1OC	1,2-dimethoxybenzene	-5.33
COc1ccccc1OC	1,2-dimethoxybenzene	-5.33
COc1ccccc1OC	1,2-dimethoxybenzene	-5.33
CCSCC	ethylsulfanylethane	-1.46
CCSCC	ethylsulfanylethane	-1.46
CCSCC	ethylsulfanylethane	-1.46
CCSCC	ethylsulfanylethane	-1.46
CCSCC	ethylsulfanylethane	-1.46
c1cc(cnc1)C#N	pyridine-3-carbonitrile	-6.75
c1cc(cnc1)C#N	pyridine-3-carbonitrile	-6.75
c1cc(cnc1)C#N	pyridine-3-carbonitrile	-6.75
c1cc(cnc1)C#N	pyridine-3-carbonitrile	-6.75
c1cc(cnc1)C#N	pyridine-3-carbonitrile	-6.75
c1cc(c(cc1O)Cl)Cl	3,4-dichlorophenol	-7.29
c1cc(c(cc1O)Cl)Cl	3,4-dichlorophenol	-7.29
c1cc(c(cc1O)Cl)Cl	3,4-dichlorophenol	-7.29
c1cc(c(cc1O)Cl)Cl	3,4-dichlorophenol	-7.29
c1cc(c(cc1O)Cl)Cl	3,4-dichlorophenol	-7.29
COc1ccccc1	anisole	-2.45
COc1ccccc1	anisole	-2.45
COc1ccccc1	anisole	-2.45
COc1ccccc1	anisole	-2.45
COc1ccccc1	anisole	-2.45
Cc1ccc(c(c1)O)C	2,5-dimethylphenol	-5.91
Cc1ccc(c(c1)O)C	2,5-dimethylphenol	-5.91
Cc1ccc(c(c1)O)C	2,5-dimethylphenol	-5.91
Cc1ccc(c(c1)O)C	2,5-dimethylphenol	-5.91
Cc1ccc(c(c1)O)C	2,5-dimethylphenol	-5.91
c1cc(ccc1Cl)Cl	1,4-dichlorobenzene	-1.01
c1cc(ccc1Cl)Cl	1,4-dichlorobenzene	-1.01
c1cc(ccc1Cl)Cl	1,4-dichlorobenzene	-1.01
c1cc(ccc1Cl)Cl	1,4-dichlorobenzene	-1.01
c1cc(ccc1Cl)Cl	1,4-dichlorobenzene	-1.01
C(F)Cl	chloro-fluoro-methane	-0.77
C(F)Cl	chloro-fluoro-methane	-0.77
C(F)Cl	chloro-fluoro-methane	-0.77
C(F)Cl	chloro-fluoro-methane	-0.77
C(F)Cl	chloro-fluoro-methane	-0.77
CCCC=C	pent-1-ene	1.68
CCCC=C	pent-1-ene	1.68
CCCC=C	pent-1-ene	1.68
CCCC=C	pent-1-ene	1.68
CCCC=C	pent-1-ene	1.68
c1cc(c(c(c1Cl)Cl)Cl)Cl	1,2,3,4-tetrachlorobenzene	-1.34
c1cc(c(c(c1Cl)Cl)Cl)Cl	1,2,3,4-tetrachlorobenzene	-1.34
c1cc(c(c(c1Cl)Cl)Cl)Cl	1,2,3,4-tetrachlorobenzene	-1.34
c1cc(c(c(c1Cl)Cl)Cl)Cl	1,2,3,4-tetrachlorobenzene	-1.34
c1cc(c(c(c1Cl)Cl)Cl)Cl	1,2,3,4-tetrachlorobenzene	-1.34
CCCCCC#C	hept-1-yne	0.6
CCCCCC#C	hept-1-yne	0.6
CCCCCC#C	hept-1-yne	0.6
CCCCCC#C	hept-1-yne	0.6
CCCCCC#C	hept-1-yne	0.6
CCCCCCCCC(=O)C	decan-2-one	-2.34
CCCCCCCCC(=O)C	decan-2-one	-2.34
CCCCCCCCC(=O)C	decan-2-one	-2.34
CCCCCCCCC(=O)C	decan-2-one	-2.34
CCCCCCCCC(=O)C	decan-2-one	-2.34
c1ccc(cc1)Cl	chlorobenzene	-1.12
c1ccc(cc1)Cl	chlorobenzene	-1.12
c1ccc(cc1)Cl	chlorobenzene	-1.12
c1ccc(cc1)Cl	chlorobenzene	-1.12
c1ccc(cc1)Cl	chlorobenzene	-1.12
CN(C)CCOC(c1ccccc1)c2ccccc2	[2-benzhydryloxyethyl]-dimethyl-amine	-9.34
CN(C)CCOC(c1ccccc1)c2ccccc2	[2-benzhydryloxyethyl]-dimethyl-amine	-9.34
CN(C)CCOC(c1ccccc1)c2ccccc2	[2-benzhydryloxyethyl]-dimethyl-amine	-9.34
CN(C)CCOC(c1ccccc1)c2ccccc2	[2-benzhydryloxyethyl]-dimethyl-amine	-9.34
CN(C)CCOC(c1ccccc1)c2ccccc2	[2-benzhydryloxyethyl]-dimethyl-amine	-9.34
CCCCC=O	pentanal	-3.03
CCCCC=O	pentanal	-3.03
CCCCC=O	pentanal	-3.03
CCCCC=O	pentanal	-3.03
CCCCC=O	pentanal	-3.03
c1ccc(cc1)Oc2ccccc2	diphenyl ether	-2.87
c1ccc(cc1)Oc2ccccc2	diphenyl ether	-2.87
c1ccc(cc1)Oc2ccccc2	diphenyl ether	-2.87
c1ccc(cc1)Oc2ccccc2	diphenyl ether	-2.87
c1ccc(cc1)Oc2ccccc2	diphenyl ether	-2.87
C1CCC(=O)CC1	cyclohexanone	-4.91
C1CCC(=O)CC1	cyclohexanone	-4.91
C1CCC(=O)CC1	cyclohexanone	-4.91
C1CCC(=O)CC1	cyclohexanone	-4.91
C1CCC(=O)CC1	cyclohexanone	-4.91
CCCC[N+](=O)[O-]	1-nitrobutane	-3.09
CCCC[N+](=O)[O-]	1-nitrobutane	-3.09
CCCC[N+](=O)[O-]	1-nitrobutane	-3.09
CCCC[N+](=O)[O-]	1-nitrobutane	-3.09
CCCC[N+](=O)[O-]	1-nitrobutane	-3.09
c1cnccc1C=O	pyridine-4-carbaldehyde	-7.0
c1cnccc1C=O	pyridine-4-carbaldehyde	-7.0
c1cnccc1C=O	pyridine-4-carbaldehyde	-7.0
c1cnccc1C=O	pyridine-4-carbaldehyde	-7.0
c1cnccc1C=O	pyridine-4-carbaldehyde	-7.0
C(CCl)OCCCl	1-chloro-2-(2-chloroethoxy)ethane	-4.23
C(CCl)OCCCl	1-chloro-2-(2-chloroethoxy)ethane	-4.23
C(CCl)OCCCl	1-chloro-2-(2-chloroethoxy)ethane	-4.23
C(CCl)OCCCl	1-chloro-2-(2-chloroethoxy)ethane	-4.23
C(CCl)OCCCl	1-chloro-2-(2-chloroethoxy)ethane	-4.23
CC[N+](=O)[O-]	1-nitroethane	-3.71
CC[N+](=O)[O-]	1-nitroethane	-3.71
CC[N+](=O)[O-]	1-nitroethane	-3.71
CC[N+](=O)[O-]	1-nitroethane	-3.71
CC[N+](=O)[O-]	1-nitroethane	-3.71
c1cc(cnc1)Cl	3-chloropyridine	-4.01
c1cc(cnc1)Cl	3-chloropyridine	-4.01
c1cc(cnc1)Cl	3-chloropyridine	-4.01
c1cc(cnc1)Cl	3-chloropyridine	-4.01
c1cc(cnc1)Cl	3-chloropyridine	-4.01
CBr	bromomethane	-0.82
CBr	bromomethane	-0.82
CBr	bromomethane	-0.82
CBr	bromomethane	-0.82
CBr	bromomethane	-0.82
CO	methanol	-5.1
CO	methanol	-5.1
CO	methanol	-5.1
CO	methanol	-5.1
CO	methanol	-5.1
CCCCCCC=O	heptanal	-2.67
CCCCCCC=O	heptanal	-2.67
CCCCCCC=O	heptanal	-2.67
CCCCCCC=O	heptanal	-2.67
CCCCCCC=O	heptanal	-2.67
c1cc(c(c(c1)Cl)c2c(cccc2Cl)Cl)Cl	1,3-dichloro-2-(2,6-dichlorophenyl)benzene	-2.28
c1cc(c(c(c1)Cl)c2c(cccc2Cl)Cl)Cl	1,3-dichloro-2-(2,6-dichlorophenyl)benzene	-2.28
c1cc(c(c(c1)Cl)c2c(cccc2Cl)Cl)Cl	1,3-dichloro-2-(2,6-dichlorophenyl)benzene	-2.28
c1cc(c(c(c1)Cl)c2c(cccc2Cl)Cl)Cl	1,3-dichloro-2-(2,6-dichlorophenyl)benzene	-2.28
c1cc(c(c(c1)Cl)c2c(cccc2Cl)Cl)Cl	1,3-dichloro-2-(2,6-dichlorophenyl)benzene	-2.28
c1ccc(c(c1)N)[N+](=O)[O-]	2-nitroaniline	-7.37
c1ccc(c(c1)N)[N+](=O)[O-]	2-nitroaniline	-7.37
c1ccc(c(c1)N)[N+](=O)[O-]	2-nitroaniline	-7.37
c1ccc(c(c1)N)[N+](=O)[O-]	2-nitroaniline	-7.37
c1ccc(c(c1)N)[N+](=O)[O-]	2-nitroaniline	-7.37
CN1CCCCC1	1-methylpiperidine	-3.88
CN1CCCCC1	1-methylpiperidine	-3.88
CN1CCCCC1	1-methylpiperidine	-3.88
CN1CCCCC1	1-methylpiperidine	-3.88
CN1CCCCC1	1-methylpiperidine	-3.88
CCCCCCCC=O	octanal	-2.29
CCCCCCCC=O	octanal	-2.29
CCCCCCCC=O	octanal	-2.29
CCCCCCCC=O	octanal	-2.29
CCCCCCCC=O	octanal	-2.29
c1ccc(cc1)[N+](=O)[O-]	nitrobenzene	-4.12
c1ccc(cc1)[N+](=O)[O-]	nitrobenzene	-4.12
c1ccc(cc1)[N+](=O)[O-]	nitrobenzene	-4.12
c1ccc(cc1)[N+](=O)[O-]	nitrobenzene	-4.12
c1ccc(cc1)[N+](=O)[O-]	nitrobenzene	-4.12
C[C@@H]1CC[C@H](C(=O)C1)C(C)C	(2S,5R)-2-isopropyl-5-methylcyclohexanone	-2.53
C[C@@H]1CC[C@H](C(=O)C1)C(C)C	(2S,5R)-2-isopropyl-5-methylcyclohexanone	-2.53
C[C@@H]1CC[C@H](C(=O)C1)C(C)C	(2S,5R)-2-isopropyl-5-methylcyclohexanone	-2.53
C[C@@H]1CC[C@H](C(=O)C1)C(C)C	(2S,5R)-2-isopropyl-5-methylcyclohexanone	-2.53
C[C@@H]1CC[C@H](C(=O)C1)C(C)C	(2S,5R)-2-isopropyl-5-methylcyclohexanone	-2.53
C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O	(2R,3R,4S,5S,6R)-6-(hydroxymethyl)tetrahydropyran-2,3,4,5-tetrol	-25.47
C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O	(2R,3R,4S,5S,6R)-6-(hydroxymethyl)tetrahydropyran-2,3,4,5-tetrol	-25.47
C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O	(2R,3R,4S,5S,6R)-6-(hydroxymethyl)tetrahydropyran-2,3,4,5-tetrol	-25.47
C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O	(2R,3R,4S,5S,6R)-6-(hydroxymethyl)tetrahydropyran-2,3,4,5-tetrol	-25.47
C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O	(2R,3R,4S,5S,6R)-6-(hydroxymethyl)tetrahydropyran-2,3,4,5-tetrol	-25.47
CF	fluoromethane	-0.22
CF	fluoromethane	-0.22
CF	fluoromethane	-0.22
CF	fluoromethane	-0.22
CF	fluoromethane	-0.22
CS(=O)C	methylsulfinylmethane	-9.28
CS(=O)C	methylsulfinylmethane	-9.28
CS(=O)C	methylsulfinylmethane	-9.28
CS(=O)C	methylsulfinylmethane	-9.28
CS(=O)C	methylsulfinylmethane	-9.28
c1ccc2c(c1)Oc3ccccc3O2	dibenzo-p-dioxin	-3.15
c1ccc2c(c1)Oc3ccccc3O2	dibenzo-p-dioxin	-3.15
c1ccc2c(c1)Oc3ccccc3O2	dibenzo-p-dioxin	-3.15
c1ccc2c(c1)Oc3ccccc3O2	dibenzo-p-dioxin	-3.15
c1ccc2c(c1)Oc3ccccc3O2	dibenzo-p-dioxin	-3.15
Cc1ccccc1N	2-methylaniline	-5.53
Cc1ccccc1N	2-methylaniline	-5.53
Cc1ccccc1N	2-methylaniline	-5.53
Cc1ccccc1N	2-methylaniline	-5.53
Cc1ccccc1N	2-methylaniline	-5.53
CCCCBr	1-bromobutane	-0.4
CCCCBr	1-bromobutane	-0.4
CCCCBr	1-bromobutane	-0.4
CCCCBr	1-bromobutane	-0.4
CCCCBr	1-bromobutane	-0.4
CCCCCCCCCO	nonan-1-ol	-3.88
CCCCCCCCCO	nonan-1-ol	-3.88
CCCCCCCCCO	nonan-1-ol	-3.88
CCCCCCCCCO	nonan-1-ol	-3.88
CCCCCCCCCO	nonan-1-ol	-3.88
Cc1ccncc1	4-methylpyridine	-4.93
Cc1ccncc1	4-methylpyridine	-4.93
Cc1ccncc1	4-methylpyridine	-4.93
Cc1ccncc1	4-methylpyridine	-4.93
Cc1ccncc1	4-methylpyridine	-4.93
C(=C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethylene	0.1
C(=C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethylene	0.1
C(=C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethylene	0.1
C(=C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethylene	0.1
C(=C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethylene	0.1
CC(C)(C)Br	2-bromo-2-methyl-propane	0.84
CC(C)(C)Br	2-bromo-2-methyl-propane	0.84
CC(C)(C)Br	2-bromo-2-methyl-propane	0.84
CC(C)(C)Br	2-bromo-2-methyl-propane	0.84
CC(C)(C)Br	2-bromo-2-methyl-propane	0.84
C=C(c1ccccc1)c2ccccc2	1,1-diphenylethene	-2.78
C=C(c1ccccc1)c2ccccc2	1,1-diphenylethene	-2.78
C=C(c1ccccc1)c2ccccc2	1,1-diphenylethene	-2.78
C=C(c1ccccc1)c2ccccc2	1,1-diphenylethene	-2.78
C=C(c1ccccc1)c2ccccc2	1,1-diphenylethene	-2.78
CCc1ccc(cc1)C	1-ethyl-4-methyl-benzene	-0.95
CCc1ccc(cc1)C	1-ethyl-4-methyl-benzene	-0.95
CCc1ccc(cc1)C	1-ethyl-4-methyl-benzene	-0.95
CCc1ccc(cc1)C	1-ethyl-4-methyl-benzene	-0.95
CCc1ccc(cc1)C	1-ethyl-4-methyl-benzene	-0.95
Cc1cccnc1	3-methylpyridine	-4.77
Cc1cccnc1	3-methylpyridine	-4.77
Cc1cccnc1	3-methylpyridine	-4.77
Cc1cccnc1	3-methylpyridine	-4.77
Cc1cccnc1	3-methylpyridine	-4.77
COCC(OC)(OC)OC	1,1,1,2-tetramethoxyethane	-5.73
COCC(OC)(OC)OC	1,1,1,2-tetramethoxyethane	-5.73
COCC(OC)(OC)OC	1,1,1,2-tetramethoxyethane	-5.73
COCC(OC)(OC)OC	1,1,1,2-tetramethoxyethane	-5.73
COCC(OC)(OC)OC	1,1,1,2-tetramethoxyethane	-5.73
c1ccc-2c(c1)Cc3c2cccc3	9H-fluorene	-3.35
c1ccc-2c(c1)Cc3c2cccc3	9H-fluorene	-3.35
c1ccc-2c(c1)Cc3c2cccc3	9H-fluorene	-3.35
c1ccc-2c(c1)Cc3c2cccc3	9H-fluorene	-3.35
c1ccc-2c(c1)Cc3c2cccc3	9H-fluorene	-3.35
CC(=O)N	acetamide	-9.71
CC(=O)N	acetamide	-9.71
CC(=O)N	acetamide	-9.71
CC(=O)N	acetamide	-9.71
CC(=O)N	acetamide	-9.71
COS(=O)(=O)OC	dimethyl sulfate	-5.1
COS(=O)(=O)OC	dimethyl sulfate	-5.1
COS(=O)(=O)OC	dimethyl sulfate	-5.1
COS(=O)(=O)OC	dimethyl sulfate	-5.1
COS(=O)(=O)OC	dimethyl sulfate	-5.1
C(C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethane	-2.37
C(C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethane	-2.37
C(C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethane	-2.37
C(C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethane	-2.37
C(C(Cl)Cl)(Cl)Cl	1,1,2,2-tetrachloroethane	-2.37
COC(=O)C1CCCCC1	methyl cyclohexanecarboxylate	-3.3
COC(=O)C1CCCCC1	methyl cyclohexanecarboxylate	-3.3
COC(=O)C1CCCCC1	methyl cyclohexanecarboxylate	-3.3
COC(=O)C1CCCCC1	methyl cyclohexanecarboxylate	-3.3
COC(=O)C1CCCCC1	methyl cyclohexanecarboxylate	-3.3
CCCCCCBr	1-bromohexane	0.18
CCCCCCBr	1-bromohexane	0.18
CCCCCCBr	1-bromohexane	0.18
CCCCCCBr	1-bromohexane	0.18
CCCCCCBr	1-bromohexane	0.18
CCCCCCCBr	1-bromoheptane	0.34
CCCCCCCBr	1-bromoheptane	0.34
CCCCCCCBr	1-bromoheptane	0.34
CCCCCCCBr	1-bromoheptane	0.34
CCCCCCCBr	1-bromoheptane	0.34
c1ccc2c(c1)Oc3cccc(c3O2)Cl	1-chlorodibenzo-p-dioxin	-3.52
c1ccc2c(c1)Oc3cccc(c3O2)Cl	1-chlorodibenzo-p-dioxin	-3.52
c1ccc2c(c1)Oc3cccc(c3O2)Cl	1-chlorodibenzo-p-dioxin	-3.52
c1ccc2c(c1)Oc3cccc(c3O2)Cl	1-chlorodibenzo-p-dioxin	-3.52
c1ccc2c(c1)Oc3cccc(c3O2)Cl	1-chlorodibenzo-p-dioxin	-3.52
COC(CC#N)(OC)OC	3,3,3-trimethoxypropanenitrile	-6.4
COC(CC#N)(OC)OC	3,3,3-trimethoxypropanenitrile	-6.4
COC(CC#N)(OC)OC	3,3,3-trimethoxypropanenitrile	-6.4
COC(CC#N)(OC)OC	3,3,3-trimethoxypropanenitrile	-6.4
COC(CC#N)(OC)OC	3,3,3-trimethoxypropanenitrile	-6.4
CC[C@H](C)Cl	2-chlorobutane	0.0
CC[C@H](C)Cl	2-chlorobutane	0.0
CC[C@H](C)Cl	2-chlorobutane	0.0
CC[C@H](C)Cl	2-chlorobutane	0.0
CC[C@H](C)Cl	2-chlorobutane	0.0
CCCCCCc1ccccc1	hexylbenzene	-0.04
CCCCCCc1ccccc1	hexylbenzene	-0.04
CCCCCCc1ccccc1	hexylbenzene	-0.04
CCCCCCc1ccccc1	hexylbenzene	-0.04
CCCCCCc1ccccc1	hexylbenzene	-0.04
COc1cc(c(c(c1O)OC)Cl)C=O	2-chlorosyringaldehyde	-7.78
COc1cc(c(c(c1O)OC)Cl)C=O	2-chlorosyringaldehyde	-7.78
COc1cc(c(c(c1O)OC)Cl)C=O	2-chlorosyringaldehyde	-7.78
COc1cc(c(c(c1O)OC)Cl)C=O	2-chlorosyringaldehyde	-7.78
COc1cc(c(c(c1O)OC)Cl)C=O	2-chlorosyringaldehyde	-7.78
c1cc(cc(c1)C(F)(F)F)C(F)(F)F	m-bis(trifluoromethyl)benzene	1.07
c1cc(cc(c1)C(F)(F)F)C(F)(F)F	m-bis(trifluoromethyl)benzene	1.07
c1cc(cc(c1)C(F)(F)F)C(F)(F)F	m-bis(trifluoromethyl)benzene	1.07
c1cc(cc(c1)C(F)(F)F)C(F)(F)F	m-bis(trifluoromethyl)benzene	1.07
c1cc(cc(c1)C(F)(F)F)C(F)(F)F	m-bis(trifluoromethyl)benzene	1.07
c1ccc(cc1)Cn2ccnc2	1-benzylimidazole	-7.63
c1ccc(cc1)Cn2ccnc2	1-benzylimidazole	-7.63
c1ccc(cc1)Cn2ccnc2	1-benzylimidazole	-7.63
c1ccc(cc1)Cn2ccnc2	1-benzylimidazole	-7.63
c1ccc(cc1)Cn2ccnc2	1-benzylimidazole	-7.63
c1ccc2c(c1)cccc2N	naphthalen-1-amine	-7.28
c1ccc2c(c1)cccc2N	naphthalen-1-amine	-7.28
c1ccc2c(c1)cccc2N	naphthalen-1-amine	-7.28
c1ccc2c(c1)cccc2N	naphthalen-1-amine	-7.28
c1ccc2c(c1)cccc2N	naphthalen-1-amine	-7.28
CCOC(=O)CC(=O)OCC	diethyl propanedioate	-6.0
CCOC(=O)CC(=O)OCC	diethyl propanedioate	-6.0
CCOC(=O)CC(=O)OCC	diethyl propanedioate	-6.0
CCOC(=O)CC(=O)OCC	diethyl propanedioate	-6.0
CCOC(=O)CC(=O)OCC	diethyl propanedioate	-6.0
CC(=O)C1CC1	1-cyclopropylethanone	-4.61
CC(=O)C1CC1	1-cyclopropylethanone	-4.61
CC(=O)C1CC1	1-cyclopropylethanone	-4.61
CC(=O)C1CC1	1-cyclopropylethanone	-4.61
CC(=O)C1CC1	1-cyclopropylethanone	-4.61
c1cc[nH]c1	pyrrole	-4.78
c1cc[nH]c1	pyrrole	-4.78
c1cc[nH]c1	pyrrole	-4.78
c1cc[nH]c1	pyrrole	-4.78
c1cc[nH]c1	pyrrole	-4.78
c1cc(c(cc1c2ccc(cc2F)F)C(=O)O)O	diflunisal	-9.4
c1cc(c(cc1c2ccc(cc2F)F)C(=O)O)O	diflunisal	-9.4
c1cc(c(cc1c2ccc(cc2F)F)C(=O)O)O	diflunisal	-9.4
c1cc(c(cc1c2ccc(cc2F)F)C(=O)O)O	diflunisal	-9.4
c1cc(c(cc1c2ccc(cc2F)F)C(=O)O)O	diflunisal	-9.4
CC1CCC(CC1)C	1,4-dimethylcyclohexane	2.11
CC1CCC(CC1)C	1,4-dimethylcyclohexane	2.11
CC1CCC(CC1)C	1,4-dimethylcyclohexane	2.11
CC1CCC(CC1)C	1,4-dimethylcyclohexane	2.11
CC1CCC(CC1)C	1,4-dimethylcyclohexane	2.11
C1CCC(CC1)O	cyclohexanol	-5.46
C1CCC(CC1)O	cyclohexanol	-5.46
C1CCC(CC1)O	cyclohexanol	-5.46
C1CCC(CC1)O	cyclohexanol	-5.46
C1CCC(CC1)O	cyclohexanol	-5.46
CN(C)CCC=C1c2ccccc2CCc3c1cccc3	Amitriptyline	-7.43
CN(C)CCC=C1c2ccccc2CCc3c1cccc3	Amitriptyline	-7.43
CN(C)CCC=C1c2ccccc2CCc3c1cccc3	Amitriptyline	-7.43
CN(C)CCC=C1c2ccccc2CCc3c1cccc3	Amitriptyline	-7.43
CN(C)CCC=C1c2ccccc2CCc3c1cccc3	Amitriptyline	-7.43
c1cc(ccc1O)F	4-fluorophenol	-6.19
c1cc(ccc1O)F	4-fluorophenol	-6.19
c1cc(ccc1O)F	4-fluorophenol	-6.19
c1cc(ccc1O)F	4-fluorophenol	-6.19
c1cc(ccc1O)F	4-fluorophenol	-6.19
c1ccc(c(c1)N)Cl	2-chloroaniline	-4.91
c1ccc(c(c1)N)Cl	2-chloroaniline	-4.91
c1ccc(c(c1)N)Cl	2-chloroaniline	-4.91
c1ccc(c(c1)N)Cl	2-chloroaniline	-4.91
c1ccc(c(c1)N)Cl	2-chloroaniline	-4.91
Cc1ccc(c(c1)C)C	1,2,4-trimethylbenzene	-0.86
Cc1ccc(c(c1)C)C	1,2,4-trimethylbenzene	-0.86
Cc1ccc(c(c1)C)C	1,2,4-trimethylbenzene	-0.86
Cc1ccc(c(c1)C)C	1,2,4-trimethylbenzene	-0.86
Cc1ccc(c(c1)C)C	1,2,4-trimethylbenzene	-0.86
CCc1ccccc1C	1-ethyl-2-methylbenzene	-0.85
CCc1ccccc1C	1-ethyl-2-methylbenzene	-0.85
CCc1ccccc1C	1-ethyl-2-methylbenzene	-0.85
CCc1ccccc1C	1-ethyl-2-methylbenzene	-0.85
CCc1ccccc1C	1-ethyl-2-methylbenzene	-0.85
C[C@@H]1CC[C@H](CC1=O)C(=C)C	(2R,5R)-2-methyl-5-(1-methylethenyl)-cyclohexanone	-3.75
C[C@@H]1CC[C@H](CC1=O)C(=C)C	(2R,5R)-2-methyl-5-(1-methylethenyl)-cyclohexanone	-3.75
C[C@@H]1CC[C@H](CC1=O)C(=C)C	(2R,5R)-2-methyl-5-(1-methylethenyl)-cyclohexanone	-3.75
C[C@@H]1CC[C@H](CC1=O)C(=C)C	(2R,5R)-2-methyl-5-(1-methylethenyl)-cyclohexanone	-3.75
C[C@@H]1CC[C@H](CC1=O)C(=C)C	(2R,5R)-2-methyl-5-(1-methylethenyl)-cyclohexanone	-3.75
c1ccc(cc1)c2ccccc2	biphenyl	-2.7
c1ccc(cc1)c2ccccc2	biphenyl	-2.7
c1ccc(cc1)c2ccccc2	biphenyl	-2.7
c1ccc(cc1)c2ccccc2	biphenyl	-2.7
c1ccc(cc1)c2ccccc2	biphenyl	-2.7
Cc1cccc(c1C)O	2,3-dimethylphenol	-6.16
Cc1cccc(c1C)O	2,3-dimethylphenol	-6.16
Cc1cccc(c1C)O	2,3-dimethylphenol	-6.16
Cc1cccc(c1C)O	2,3-dimethylphenol	-6.16
Cc1cccc(c1C)O	2,3-dimethylphenol	-6.16
COP(=S)(OC)Oc1ccc(cc1)[N+](=O)[O-]	methylparathion	-7.19
COP(=S)(OC)Oc1ccc(cc1)[N+](=O)[O-]	methylparathion	-7.19
COP(=S)(OC)Oc1ccc(cc1)[N+](=O)[O-]	methylparathion	-7.19
COP(=S)(OC)Oc1ccc(cc1)[N+](=O)[O-]	methylparathion	-7.19
COP(=S)(OC)Oc1ccc(cc1)[N+](=O)[O-]	methylparathion	-7.19
CCOP(=S)(OCC)Oc1ccc(cc1)[N+](=O)[O-]	diethoxy-(4-nitrophenoxy)-thioxo-$l^{5}-phosphane	-6.74
CCOP(=S)(OCC)Oc1ccc(cc1)[N+](=O)[O-]	diethoxy-(4-nitrophenoxy)-thioxo-$l^{5}-phosphane	-6.74
CCOP(=S)(OCC)Oc1ccc(cc1)[N+](=O)[O-]	diethoxy-(4-nitrophenoxy)-thioxo-$l^{5}-phosphane	-6.74
CCOP(=S)(OCC)Oc1ccc(cc1)[N+](=O)[O-]	diethoxy-(4-nitrophenoxy)-thioxo-$l^{5}-phosphane	-6.74
CCOP(=S)(OCC)Oc1ccc(cc1)[N+](=O)[O-]	diethoxy-(4-nitrophenoxy)-thioxo-$l^{5}-phosphane	-6.74
CCN(CC)c1c(cc(c(c1[N+](=O)[O-])N)C(F)(F)F)[N+](=O)[O-]	1-N,1-N-diethyl-2,6-dinitro-4-(trifluoromethyl)benzene-1,3-diamine	-5.66
CCN(CC)c1c(cc(c(c1[N+](=O)[O-])N)C(F)(F)F)[N+](=O)[O-]	1-N,1-N-diethyl-2,6-dinitro-4-(trifluoromethyl)benzene-1,3-diamine	-5.66
CCN(CC)c1c(cc(c(c1[N+](=O)[O-])N)C(F)(F)F)[N+](=O)[O-]	1-N,1-N-diethyl-2,6-dinitro-4-(trifluoromethyl)benzene-1,3-diamine	-5.66
CCN(CC)c1c(cc(c(c1[N+](=O)[O-])N)C(F)(F)F)[N+](=O)[O-]	1-N,1-N-diethyl-2,6-dinitro-4-(trifluoromethyl)benzene-1,3-diamine	-5.66
CCN(CC)c1c(cc(c(c1[N+](=O)[O-])N)C(F)(F)F)[N+](=O)[O-]	1-N,1-N-diethyl-2,6-dinitro-4-(trifluoromethyl)benzene-1,3-diamine	-5.66
CSC	methylsulfanylmethane	-1.61
CSC	methylsulfanylmethane	-1.61
CSC	methylsulfanylmethane	-1.61
CSC	methylsulfanylmethane	-1.61
CSC	methylsulfanylmethane	-1.61
C[C@@H](c1cccc(c1)C(=O)c2ccccc2)C(=O)O	ketoprofen	-10.78
C[C@@H](c1cccc(c1)C(=O)c2ccccc2)C(=O)O	ketoprofen	-10.78
C[C@@H](c1cccc(c1)C(=O)c2ccccc2)C(=O)O	ketoprofen	-10.78
C[C@@H](c1cccc(c1)C(=O)c2ccccc2)C(=O)O	ketoprofen	-10.78
C[C@@H](c1cccc(c1)C(=O)c2ccccc2)C(=O)O	ketoprofen	-10.78
C1CCC(C1)O	cyclopentanol	-5.49
C1CCC(C1)O	cyclopentanol	-5.49
C1CCC(C1)O	cyclopentanol	-5.49
C1CCC(C1)O	cyclopentanol	-5.49
C1CCC(C1)O	cyclopentanol	-5.49
CCCCC(=O)OC	methyl pentanoate	-2.56
CCCCC(=O)OC	methyl pentanoate	-2.56
CCCCC(=O)OC	methyl pentanoate	-2.56
CCCCC(=O)OC	methyl pentanoate	-2.56
CCCCC(=O)OC	methyl pentanoate	-2.56
CCCC(=C)C	2-methylpent-1-ene	1.47
CCCC(=C)C	2-methylpent-1-ene	1.47
CCCC(=C)C	2-methylpent-1-ene	1.47
CCCC(=C)C	2-methylpent-1-ene	1.47
CCCC(=C)C	2-methylpent-1-ene	1.47
C[C@@H](c1ccc(c(c1)F)c2ccccc2)C(=O)O	flurbiprofen	-8.42
C[C@@H](c1ccc(c(c1)F)c2ccccc2)C(=O)O	flurbiprofen	-8.42
C[C@@H](c1ccc(c(c1)F)c2ccccc2)C(=O)O	flurbiprofen	-8.42
C[C@@H](c1ccc(c(c1)F)c2ccccc2)C(=O)O	flurbiprofen	-8.42
C[C@@H](c1ccc(c(c1)F)c2ccccc2)C(=O)O	flurbiprofen	-8.42
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])S(=O)(=O)C)[N+](=O)[O-]	nitralin	-7.98
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])S(=O)(=O)C)[N+](=O)[O-]	nitralin	-7.98
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])S(=O)(=O)C)[N+](=O)[O-]	nitralin	-7.98
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])S(=O)(=O)C)[N+](=O)[O-]	nitralin	-7.98
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])S(=O)(=O)C)[N+](=O)[O-]	nitralin	-7.98
C=CCl	chloroethylene	-0.59
C=CCl	chloroethylene	-0.59
C=CCl	chloroethylene	-0.59
C=CCl	chloroethylene	-0.59
C=CCl	chloroethylene	-0.59
Cc1ccc(cc1)C(=O)N(C)C	N,N-4-trimethylbenzamide	-9.76
Cc1ccc(cc1)C(=O)N(C)C	N,N-4-trimethylbenzamide	-9.76
Cc1ccc(cc1)C(=O)N(C)C	N,N-4-trimethylbenzamide	-9.76
Cc1ccc(cc1)C(=O)N(C)C	N,N-4-trimethylbenzamide	-9.76
Cc1ccc(cc1)C(=O)N(C)C	N,N-4-trimethylbenzamide	-9.76
CCCC(=O)CCC	heptan-4-one	-2.92
CCCC(=O)CCC	heptan-4-one	-2.92
CCCC(=O)CCC	heptan-4-one	-2.92
CCCC(=O)CCC	heptan-4-one	-2.92
CCCC(=O)CCC	heptan-4-one	-2.92
COC(=O)c1ccccc1	methyl benzoate	-3.92
COC(=O)c1ccccc1	methyl benzoate	-3.92
COC(=O)c1ccccc1	methyl benzoate	-3.92
COC(=O)c1ccccc1	methyl benzoate	-3.92
COC(=O)c1ccccc1	methyl benzoate	-3.92
Cc1ccc(cc1)C=O	4-methylbenzaldehyde	-4.27
Cc1ccc(cc1)C=O	4-methylbenzaldehyde	-4.27
Cc1ccc(cc1)C=O	4-methylbenzaldehyde	-4.27
Cc1ccc(cc1)C=O	4-methylbenzaldehyde	-4.27
Cc1ccc(cc1)C=O	4-methylbenzaldehyde	-4.27
CCCC(=O)OCCC	propyl butanoate	-2.28
CCCC(=O)OCCC	propyl butanoate	-2.28
CCCC(=O)OCCC	propyl butanoate	-2.28
CCCC(=O)OCCC	propyl butanoate	-2.28
CCCC(=O)OCCC	propyl butanoate	-2.28
C1CNCCN1	piperazine	-7.4
C1CNCCN1	piperazine	-7.4
C1CNCCN1	piperazine	-7.4
C1CNCCN1	piperazine	-7.4
C1CNCCN1	piperazine	-7.4
CCOP(=S)(OCC)S[C@@H](CCl)N1C(=O)c2ccccc2C1=O	dialifor	-5.74
CCOP(=S)(OCC)S[C@@H](CCl)N1C(=O)c2ccccc2C1=O	dialifor	-5.74
CCOP(=S)(OCC)S[C@@H](CCl)N1C(=O)c2ccccc2C1=O	dialifor	-5.74
CCOP(=S)(OCC)S[C@@H](CCl)N1C(=O)c2ccccc2C1=O	dialifor	-5.74
CCOP(=S)(OCC)S[C@@H](CCl)N1C(=O)c2ccccc2C1=O	dialifor	-5.74
CCOCCO	2-ethoxyethanol	-6.69
CCOCCO	2-ethoxyethanol	-6.69
CCOCCO	2-ethoxyethanol	-6.69
CCOCCO	2-ethoxyethanol	-6.69
CCOCCO	2-ethoxyethanol	-6.69
CCC(C)CC	3-methylpentane	2.51
CCC(C)CC	3-methylpentane	2.51
CCC(C)CC	3-methylpentane	2.51
CCC(C)CC	3-methylpentane	2.51
CCC(C)CC	3-methylpentane	2.51
Cc1cnccn1	2-methylpyrazine	-5.51
Cc1cnccn1	2-methylpyrazine	-5.51
Cc1cnccn1	2-methylpyrazine	-5.51
Cc1cnccn1	2-methylpyrazine	-5.51
Cc1cnccn1	2-methylpyrazine	-5.51
CCC[N+](=O)[O-]	1-nitropropane	-3.34
CCC[N+](=O)[O-]	1-nitropropane	-3.34
CCC[N+](=O)[O-]	1-nitropropane	-3.34
CCC[N+](=O)[O-]	1-nitropropane	-3.34
CCC[N+](=O)[O-]	1-nitropropane	-3.34
Cc1cc(cc(c1)C)C	mesitylene	-0.9
Cc1cc(cc(c1)C)C	mesitylene	-0.9
Cc1cc(cc(c1)C)C	mesitylene	-0.9
Cc1cc(cc(c1)C)C	mesitylene	-0.9
Cc1cc(cc(c1)C)C	mesitylene	-0.9
c1c(c(=O)[nH]c(=O)[nH]1)F	5-fluorouracil	-16.92
c1c(c(=O)[nH]c(=O)[nH]1)F	5-fluorouracil	-16.92
c1c(c(=O)[nH]c(=O)[nH]1)F	5-fluorouracil	-16.92
c1c(c(=O)[nH]c(=O)[nH]1)F	5-fluorouracil	-16.92
c1c(c(=O)[nH]c(=O)[nH]1)F	5-fluorouracil	-16.92
CCO	ethanol	-5.0
CCO	ethanol	-5.0
CCO	ethanol	-5.0
CCO	ethanol	-5.0
CCO	ethanol	-5.0
Cc1ccc(c2c1cccc2)C	1,4-dimethylnaphthalene	-2.82
Cc1ccc(c2c1cccc2)C	1,4-dimethylnaphthalene	-2.82
Cc1ccc(c2c1cccc2)C	1,4-dimethylnaphthalene	-2.82
Cc1ccc(c2c1cccc2)C	1,4-dimethylnaphthalene	-2.82
Cc1ccc(c2c1cccc2)C	1,4-dimethylnaphthalene	-2.82
c1c2c(cc(c1Cl)Cl)Oc3cc(c(cc3O2)Cl)Cl	2,3,7,8-tetrachlorodibenzo-p-dioxin	-3.37
c1c2c(cc(c1Cl)Cl)Oc3cc(c(cc3O2)Cl)Cl	2,3,7,8-tetrachlorodibenzo-p-dioxin	-3.37
c1c2c(cc(c1Cl)Cl)Oc3cc(c(cc3O2)Cl)Cl	2,3,7,8-tetrachlorodibenzo-p-dioxin	-3.37
c1c2c(cc(c1Cl)Cl)Oc3cc(c(cc3O2)Cl)Cl	2,3,7,8-tetrachlorodibenzo-p-dioxin	-3.37
c1c2c(cc(c1Cl)Cl)Oc3cc(c(cc3O2)Cl)Cl	2,3,7,8-tetrachlorodibenzo-p-dioxin	-3.37
c1cc(c(c(c1)Cl)C#N)Cl	dichlobenil	-4.71
c1cc(c(c(c1)Cl)C#N)Cl	dichlobenil	-4.71
c1cc(c(c(c1)Cl)C#N)Cl	dichlobenil	-4.71
c1cc(c(c(c1)Cl)C#N)Cl	dichlobenil	-4.71
c1cc(c(c(c1)Cl)C#N)Cl	dichlobenil	-4.71
CCOC=O	ethyl formate	-2.56
CCOC=O	ethyl formate	-2.56
CCOC=O	ethyl formate	-2.56
CCOC=O	ethyl formate	-2.56
CCOC=O	ethyl formate	-2.56
c1c(c(cc(c1Cl)Cl)Cl)Cl	1,2,4,5-tetrachlorobenzene	-1.34
c1c(c(cc(c1Cl)Cl)Cl)Cl	1,2,4,5-tetrachlorobenzene	-1.34
c1c(c(cc(c1Cl)Cl)Cl)Cl	1,2,4,5-tetrachlorobenzene	-1.34
c1c(c(cc(c1Cl)Cl)Cl)Cl	1,2,4,5-tetrachlorobenzene	-1.34
c1c(c(cc(c1Cl)Cl)Cl)Cl	1,2,4,5-tetrachlorobenzene	-1.34
CCOC(OCC)Oc1ccccc1	diethoxymethoxybenzene	-5.23
CCOC(OCC)Oc1ccccc1	diethoxymethoxybenzene	-5.23
CCOC(OCC)Oc1ccccc1	diethoxymethoxybenzene	-5.23
CCOC(OCC)Oc1ccccc1	diethoxymethoxybenzene	-5.23
CCOC(OCC)Oc1ccccc1	diethoxymethoxybenzene	-5.23
c1cc(cc(c1)O)[N+](=O)[O-]	3-nitrophenol	-9.62
c1cc(cc(c1)O)[N+](=O)[O-]	3-nitrophenol	-9.62
c1cc(cc(c1)O)[N+](=O)[O-]	3-nitrophenol	-9.62
c1cc(cc(c1)O)[N+](=O)[O-]	3-nitrophenol	-9.62
c1cc(cc(c1)O)[N+](=O)[O-]	3-nitrophenol	-9.62
CCCCCCCCO	octan-1-ol	-4.09
CCCCCCCCO	octan-1-ol	-4.09
CCCCCCCCO	octan-1-ol	-4.09
CCCCCCCCO	octan-1-ol	-4.09
CCCCCCCCO	octan-1-ol	-4.09
CCC=C	but-1-ene	1.38
CCC=C	but-1-ene	1.38
CCC=C	but-1-ene	1.38
CCC=C	but-1-ene	1.38
CCC=C	but-1-ene	1.38
C(Cl)(Cl)(Cl)Cl	carbon tetrachloride	0.08
C(Cl)(Cl)(Cl)Cl	carbon tetrachloride	0.08
C(Cl)(Cl)(Cl)Cl	carbon tetrachloride	0.08
C(Cl)(Cl)(Cl)Cl	carbon tetrachloride	0.08
C(Cl)(Cl)(Cl)Cl	carbon tetrachloride	0.08
c1ccc(cc1)CCO	2-phenylethanol	-6.79
c1ccc(cc1)CCO	2-phenylethanol	-6.79
c1ccc(cc1)CCO	2-phenylethanol	-6.79
c1ccc(cc1)CCO	2-phenylethanol	-6.79
c1ccc(cc1)CCO	2-phenylethanol	-6.79
CN(C)C(=O)Nc1ccccc1	fenuron	-9.13
CN(C)C(=O)Nc1ccccc1	fenuron	-9.13
CN(C)C(=O)Nc1ccccc1	fenuron	-9.13
CN(C)C(=O)Nc1ccccc1	fenuron	-9.13
CN(C)C(=O)Nc1ccccc1	fenuron	-9.13
CSSC	methyldisulfanylmethane	-1.83
CSSC	methyldisulfanylmethane	-1.83
CSSC	methyldisulfanylmethane	-1.83
CSSC	methyldisulfanylmethane	-1.83
CSSC	methyldisulfanylmethane	-1.83
C1C=CC[C@@H]2[C@@H]1C(=O)N(C2=O)SC(Cl)(Cl)Cl	captan	-9.01
C1C=CC[C@@H]2[C@@H]1C(=O)N(C2=O)SC(Cl)(Cl)Cl	captan	-9.01
C1C=CC[C@@H]2[C@@H]1C(=O)N(C2=O)SC(Cl)(Cl)Cl	captan	-9.01
C1C=CC[C@@H]2[C@@H]1C(=O)N(C2=O)SC(Cl)(Cl)Cl	captan	-9.01
C1C=CC[C@@H]2[C@@H]1C(=O)N(C2=O)SC(Cl)(Cl)Cl	captan	-9.01
CC(=O)OCC(COC(=O)C)OC(=O)C	2,3-diacetoxypropyl acetate	-8.84
CC(=O)OCC(COC(=O)C)OC(=O)C	2,3-diacetoxypropyl acetate	-8.84
CC(=O)OCC(COC(=O)C)OC(=O)C	2,3-diacetoxypropyl acetate	-8.84
CC(=O)OCC(COC(=O)C)OC(=O)C	2,3-diacetoxypropyl acetate	-8.84
CC(=O)OCC(COC(=O)C)OC(=O)C	2,3-diacetoxypropyl acetate	-8.84
COC	methoxymethane	-1.91
COC	methoxymethane	-1.91
COC	methoxymethane	-1.91
COC	methoxymethane	-1.91
COC	methoxymethane	-1.91
CCCCCC	hexane	2.48
CCCCCC	hexane	2.48
CCCCCC	hexane	2.48
CCCCCC	hexane	2.48
CCCCCC	hexane	2.48
C(CBr)Br	1,2-dibromoethane	-2.33
C(CBr)Br	1,2-dibromoethane	-2.33
C(CBr)Br	1,2-dibromoethane	-2.33
C(CBr)Br	1,2-dibromoethane	-2.33
C(CBr)Br	1,2-dibromoethane	-2.33
C(C(Cl)(Cl)Cl)(Cl)Cl	1,1,1,2,2-pentachloroethane	-1.23
C(C(Cl)(Cl)Cl)(Cl)Cl	1,1,1,2,2-pentachloroethane	-1.23
C(C(Cl)(Cl)Cl)(Cl)Cl	1,1,1,2,2-pentachloroethane	-1.23
C(C(Cl)(Cl)Cl)(Cl)Cl	1,1,1,2,2-pentachloroethane	-1.23
C(C(Cl)(Cl)Cl)(Cl)Cl	1,1,1,2,2-pentachloroethane	-1.23
c1c(c(=O)[nH]c(=O)[nH]1)C(F)(F)F	5-trifluoromethyluracil	-15.46
c1c(c(=O)[nH]c(=O)[nH]1)C(F)(F)F	5-trifluoromethyluracil	-15.46
c1c(c(=O)[nH]c(=O)[nH]1)C(F)(F)F	5-trifluoromethyluracil	-15.46
c1c(c(=O)[nH]c(=O)[nH]1)C(F)(F)F	5-trifluoromethyluracil	-15.46
c1c(c(=O)[nH]c(=O)[nH]1)C(F)(F)F	5-trifluoromethyluracil	-15.46
Cc1cccc(c1N)C	2,6-dimethylaniline	-5.21
Cc1cccc(c1N)C	2,6-dimethylaniline	-5.21
Cc1cccc(c1N)C	2,6-dimethylaniline	-5.21
Cc1cccc(c1N)C	2,6-dimethylaniline	-5.21
Cc1cccc(c1N)C	2,6-dimethylaniline	-5.21
CCCOC(=O)C	propyl acetate	-2.79
CCCOC(=O)C	propyl acetate	-2.79
CCCOC(=O)C	propyl acetate	-2.79
CCCOC(=O)C	propyl acetate	-2.79
CCCOC(=O)C	propyl acetate	-2.79
c1ccc2c(c1)cccn2	quinoline	-5.72
c1ccc2c(c1)cccn2	quinoline	-5.72
c1ccc2c(c1)cccn2	quinoline	-5.72
c1ccc2c(c1)cccn2	quinoline	-5.72
c1ccc2c(c1)cccn2	quinoline	-5.72
CCS	ethanethiol	-1.14
CCS	ethanethiol	-1.14
CCS	ethanethiol	-1.14
CCS	ethanethiol	-1.14
CCS	ethanethiol	-1.14
CCSSCC	ethyldisulfanylethane	-1.64
CCSSCC	ethyldisulfanylethane	-1.64
CCSSCC	ethyldisulfanylethane	-1.64
CCSSCC	ethyldisulfanylethane	-1.64
CCSSCC	ethyldisulfanylethane	-1.64
c1ccsc1	thiophene	-1.4
c1ccsc1	thiophene	-1.4
c1ccsc1	thiophene	-1.4
c1ccsc1	thiophene	-1.4
c1ccsc1	thiophene	-1.4
CCc1cccc2c1cccc2	1-ethylnaphthalene	-2.4
CCc1cccc2c1cccc2	1-ethylnaphthalene	-2.4
CCc1cccc2c1cccc2	1-ethylnaphthalene	-2.4
CCc1cccc2c1cccc2	1-ethylnaphthalene	-2.4
CCc1cccc2c1cccc2	1-ethylnaphthalene	-2.4
CCCC(=O)C	pentan-2-one	-3.52
CCCC(=O)C	pentan-2-one	-3.52
CCCC(=O)C	pentan-2-one	-3.52
CCCC(=O)C	pentan-2-one	-3.52
CCCC(=O)C	pentan-2-one	-3.52
c1c(c(c(c(c1Cl)Cl)Cl)Cl)c2c(cc(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4,6-tetrachlorophenyl)benzene	-4.61
c1c(c(c(c(c1Cl)Cl)Cl)Cl)c2c(cc(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4,6-tetrachlorophenyl)benzene	-4.61
c1c(c(c(c(c1Cl)Cl)Cl)Cl)c2c(cc(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4,6-tetrachlorophenyl)benzene	-4.61
c1c(c(c(c(c1Cl)Cl)Cl)Cl)c2c(cc(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4,6-tetrachlorophenyl)benzene	-4.61
c1c(c(c(c(c1Cl)Cl)Cl)Cl)c2c(cc(c(c2Cl)Cl)Cl)Cl	1,2,3,4-tetrachloro-5-(2,3,4,6-tetrachlorophenyl)benzene	-4.61
CCC[N@@](CC1CC1)c2c(cc(cc2[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	profluralin	-2.45
CCC[N@@](CC1CC1)c2c(cc(cc2[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	profluralin	-2.45
CCC[N@@](CC1CC1)c2c(cc(cc2[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	profluralin	-2.45
CCC[N@@](CC1CC1)c2c(cc(cc2[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	profluralin	-2.45
CCC[N@@](CC1CC1)c2c(cc(cc2[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	profluralin	-2.45
CC(=O)O	acetic acid	-6.69
CC(=O)O	acetic acid	-6.69
CC(=O)O	acetic acid	-6.69
CC(=O)O	acetic acid	-6.69
CC(=O)O	acetic acid	-6.69
CC=O	acetaldehyde	-3.5
CC=O	acetaldehyde	-3.5
CC=O	acetaldehyde	-3.5
CC=O	acetaldehyde	-3.5
CC=O	acetaldehyde	-3.5
c1cc(cc(c1)[N+](=O)[O-])N	3-nitroaniline	-8.84
c1cc(cc(c1)[N+](=O)[O-])N	3-nitroaniline	-8.84
c1cc(cc(c1)[N+](=O)[O-])N	3-nitroaniline	-8.84
c1cc(cc(c1)[N+](=O)[O-])N	3-nitroaniline	-8.84
c1cc(cc(c1)[N+](=O)[O-])N	3-nitroaniline	-8.84
CCCCC#C	hex-1-yne	0.29
CCCCC#C	hex-1-yne	0.29
CCCCC#C	hex-1-yne	0.29
CCCCC#C	hex-1-yne	0.29
CCCCC#C	hex-1-yne	0.29
COc1ccccc1N	2-methoxyaniline	-6.12
COc1ccccc1N	2-methoxyaniline	-6.12
COc1ccccc1N	2-methoxyaniline	-6.12
COc1ccccc1N	2-methoxyaniline	-6.12
COc1ccccc1N	2-methoxyaniline	-6.12
c1ccc(cc1)O	phenol	-6.6
c1ccc(cc1)O	phenol	-6.6
c1ccc(cc1)O	phenol	-6.6
c1ccc(cc1)O	phenol	-6.6
c1ccc(cc1)O	phenol	-6.6
CCC#N	propanenitrile	-3.84
CCC#N	propanenitrile	-3.84
CCC#N	propanenitrile	-3.84
CCC#N	propanenitrile	-3.84
CCC#N	propanenitrile	-3.84
c1ccc2c(c1)cccc2O	naphthalen-1-ol	-7.67
c1ccc2c(c1)cccc2O	naphthalen-1-ol	-7.67
c1ccc2c(c1)cccc2O	naphthalen-1-ol	-7.67
c1ccc2c(c1)cccc2O	naphthalen-1-ol	-7.67
c1ccc2c(c1)cccc2O	naphthalen-1-ol	-7.67
CCCCOC(=O)C	butyl acetate	-2.64
CCCCOC(=O)C	butyl acetate	-2.64
CCCCOC(=O)C	butyl acetate	-2.64
CCCCOC(=O)C	butyl acetate	-2.64
CCCCOC(=O)C	butyl acetate	-2.64
CC(C)(/C=N\OC(=O)NC)SC	aldicarb	-9.84
CC(C)(/C=N\OC(=O)NC)SC	aldicarb	-9.84
CC(C)(/C=N\OC(=O)NC)SC	aldicarb	-9.84
CC(C)(/C=N\OC(=O)NC)SC	aldicarb	-9.84
CC(C)(/C=N\OC(=O)NC)SC	aldicarb	-9.84
Cc1ccccc1O	o-cresol	-5.9
Cc1ccccc1O	o-cresol	-5.9
Cc1ccccc1O	o-cresol	-5.9
Cc1ccccc1O	o-cresol	-5.9
Cc1ccccc1O	o-cresol	-5.9
CC(C)C=O	2-methylpropanal	-2.86
CC(C)C=O	2-methylpropanal	-2.86
CC(C)C=O	2-methylpropanal	-2.86
CC(C)C=O	2-methylpropanal	-2.86
CC(C)C=O	2-methylpropanal	-2.86
CCC(=O)N	propionamide	-9.4
CCC(=O)N	propionamide	-9.4
CCC(=O)N	propionamide	-9.4
CCC(=O)N	propionamide	-9.4
CCC(=O)N	propionamide	-9.4
CCCBr	1-bromopropane	-0.56
CCCBr	1-bromopropane	-0.56
CCCBr	1-bromopropane	-0.56
CCCBr	1-bromopropane	-0.56
CCCBr	1-bromopropane	-0.56
CC(C)Cl	2-chloropropane	-0.25
CC(C)Cl	2-chloropropane	-0.25
CC(C)Cl	2-chloropropane	-0.25
CC(C)Cl	2-chloropropane	-0.25
CC(C)Cl	2-chloropropane	-0.25
C(CCl)CCl	1,3-dichloropropane	-1.89
C(CCl)CCl	1,3-dichloropropane	-1.89
C(CCl)CCl	1,3-dichloropropane	-1.89
C(CCl)CCl	1,3-dichloropropane	-1.89
C(CCl)CCl	1,3-dichloropropane	-1.89
c1cc(ccc1[N+](=O)[O-])O	4-nitrophenol	-10.64
c1cc(ccc1[N+](=O)[O-])O	4-nitrophenol	-10.64
c1cc(ccc1[N+](=O)[O-])O	4-nitrophenol	-10.64
c1cc(ccc1[N+](=O)[O-])O	4-nitrophenol	-10.64
c1cc(ccc1[N+](=O)[O-])O	4-nitrophenol	-10.64
C[C@@H](CCl)Cl	1,2-dichloropropane	-1.27
C[C@@H](CCl)Cl	1,2-dichloropropane	-1.27
C[C@@H](CCl)Cl	1,2-dichloropropane	-1.27
C[C@@H](CCl)Cl	1,2-dichloropropane	-1.27
C[C@@H](CCl)Cl	1,2-dichloropropane	-1.27
c1cc(ccc1N)Cl	4-chloroaniline	-5.9
c1cc(ccc1N)Cl	4-chloroaniline	-5.9
c1cc(ccc1N)Cl	4-chloroaniline	-5.9
c1cc(ccc1N)Cl	4-chloroaniline	-5.9
c1cc(ccc1N)Cl	4-chloroaniline	-5.9
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)N	1-amino-9,10-anthracenedione	-9.44
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)N	1-amino-9,10-anthracenedione	-9.44
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)N	1-amino-9,10-anthracenedione	-9.44
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)N	1-amino-9,10-anthracenedione	-9.44
c1ccc2c(c1)C(=O)c3cccc(c3C2=O)N	1-amino-9,10-anthracenedione	-9.44
Cc1cccnc1C	2,3-dimethylpyridine	-4.82
Cc1cccnc1C	2,3-dimethylpyridine	-4.82
Cc1cccnc1C	2,3-dimethylpyridine	-4.82
Cc1cccnc1C	2,3-dimethylpyridine	-4.82
Cc1cccnc1C	2,3-dimethylpyridine	-4.82
c1cnccc1C#N	pyridine-4-carbonitrile	-6.02
c1cnccc1C#N	pyridine-4-carbonitrile	-6.02
c1cnccc1C#N	pyridine-4-carbonitrile	-6.02
c1cnccc1C#N	pyridine-4-carbonitrile	-6.02
c1cnccc1C#N	pyridine-4-carbonitrile	-6.02
CCOP(=S)(OCC)SCSCC	diethoxy-(ethylsulfanylmethylsulfanyl)-thioxo-$l^{5}-phosphane	-4.37
CCOP(=S)(OCC)SCSCC	diethoxy-(ethylsulfanylmethylsulfanyl)-thioxo-$l^{5}-phosphane	-4.37
CCOP(=S)(OCC)SCSCC	diethoxy-(ethylsulfanylmethylsulfanyl)-thioxo-$l^{5}-phosphane	-4.37
CCOP(=S)(OCC)SCSCC	diethoxy-(ethylsulfanylmethylsulfanyl)-thioxo-$l^{5}-phosphane	-4.37
CCOP(=S)(OCC)SCSCC	diethoxy-(ethylsulfanylmethylsulfanyl)-thioxo-$l^{5}-phosphane	-4.37
CC(=O)C1CCCCC1	1-cyclohexylethanone	-3.9
CC(=O)C1CCCCC1	1-cyclohexylethanone	-3.9
CC(=O)C1CCCCC1	1-cyclohexylethanone	-3.9
CC(=O)C1CCCCC1	1-cyclohexylethanone	-3.9
CC(=O)C1CCCCC1	1-cyclohexylethanone	-3.9
Cc1ccccc1C=O	2-methylbenzaldehyde	-3.93
Cc1ccccc1C=O	2-methylbenzaldehyde	-3.93
Cc1ccccc1C=O	2-methylbenzaldehyde	-3.93
Cc1ccccc1C=O	2-methylbenzaldehyde	-3.93
Cc1ccccc1C=O	2-methylbenzaldehyde	-3.93
CC(=O)c1ccncc1	1-(4-pyridyl)ethanone	-7.62
CC(=O)c1ccncc1	1-(4-pyridyl)ethanone	-7.62
CC(=O)c1ccncc1	1-(4-pyridyl)ethanone	-7.62
CC(=O)c1ccncc1	1-(4-pyridyl)ethanone	-7.62
CC(=O)c1ccncc1	1-(4-pyridyl)ethanone	-7.62
c1c2c(cc(c1Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7,8-hexachlorodibenzo-p-dioxin	-3.71
c1c2c(cc(c1Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7,8-hexachlorodibenzo-p-dioxin	-3.71
c1c2c(cc(c1Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7,8-hexachlorodibenzo-p-dioxin	-3.71
c1c2c(cc(c1Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7,8-hexachlorodibenzo-p-dioxin	-3.71
c1c2c(cc(c1Cl)Cl)Oc3c(c(c(c(c3Cl)Cl)Cl)Cl)O2	1,2,3,4,7,8-hexachlorodibenzo-p-dioxin	-3.71
CC(=O)C	acetone	-3.8
CC(=O)C	acetone	-3.8
CC(=O)C	acetone	-3.8
CC(=O)C	acetone	-3.8
CC(=O)C	acetone	-3.8
CC(=C)C	2-methylprop-1-ene	1.16
CC(=C)C	2-methylprop-1-ene	1.16
CC(=C)C	2-methylprop-1-ene	1.16
CC(=C)C	2-methylprop-1-ene	1.16
CC(=C)C	2-methylprop-1-ene	1.16
c1cc(c(cc1Cl)c2cc(c(c(c2)Cl)Cl)Cl)Cl	1,2,3-trichloro-5-(2,5-dichlorophenyl)benzene	-3.61
c1cc(c(cc1Cl)c2cc(c(c(c2)Cl)Cl)Cl)Cl	1,2,3-trichloro-5-(2,5-dichlorophenyl)benzene	-3.61
c1cc(c(cc1Cl)c2cc(c(c(c2)Cl)Cl)Cl)Cl	1,2,3-trichloro-5-(2,5-dichlorophenyl)benzene	-3.61
c1cc(c(cc1Cl)c2cc(c(c(c2)Cl)Cl)Cl)Cl	1,2,3-trichloro-5-(2,5-dichlorophenyl)benzene	-3.61
c1cc(c(cc1Cl)c2cc(c(c(c2)Cl)Cl)Cl)Cl	1,2,3-trichloro-5-(2,5-dichlorophenyl)benzene	-3.61
CCCCC[N+](=O)[O-]	1-nitropentane	-2.82
CCCCC[N+](=O)[O-]	1-nitropentane	-2.82
CCCCC[N+](=O)[O-]	1-nitropentane	-2.82
CCCCC[N+](=O)[O-]	1-nitropentane	-2.82
CCCCC[N+](=O)[O-]	1-nitropentane	-2.82
CCC/C=C/C=O	(2E)-hex-2-enal	-3.68
CCC/C=C/C=O	(2E)-hex-2-enal	-3.68
CCC/C=C/C=O	(2E)-hex-2-enal	-3.68
CCC/C=C/C=O	(2E)-hex-2-enal	-3.68
CCC/C=C/C=O	(2E)-hex-2-enal	-3.68
CN(C)C(=O)c1ccc(cc1)[N+](=O)[O-]	N,N-dimethyl-4-nitro-benzamide	-11.95
CN(C)C(=O)c1ccc(cc1)[N+](=O)[O-]	N,N-dimethyl-4-nitro-benzamide	-11.95
CN(C)C(=O)c1ccc(cc1)[N+](=O)[O-]	N,N-dimethyl-4-nitro-benzamide	-11.95
CN(C)C(=O)c1ccc(cc1)[N+](=O)[O-]	N,N-dimethyl-4-nitro-benzamide	-11.95
CN(C)C(=O)c1ccc(cc1)[N+](=O)[O-]	N,N-dimethyl-4-nitro-benzamide	-11.95
C1CCOC1	tetrahydrofuran	-3.47
C1CCOC1	tetrahydrofuran	-3.47
C1CCOC1	tetrahydrofuran	-3.47
C1CCOC1	tetrahydrofuran	-3.47
C1CCOC1	tetrahydrofuran	-3.47
CCCCCCCC	octane	2.88
CCCCCCCC	octane	2.88
CCCCCCCC	octane	2.88
CCCCCCCC	octane	2.88
CCCCCCCC	octane	2.88
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	trifluralin	-3.25
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	trifluralin	-3.25
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	trifluralin	-3.25
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	trifluralin	-3.25
CCCN(CCC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	trifluralin	-3.25
CC(=CCC[C@](C)(C=C)OC(=O)C)C	(3R)-3,7-Dimethylocta-1,6-dien-3-yl acetate	-2.49
CC(=CCC[C@](C)(C=C)OC(=O)C)C	(3R)-3,7-Dimethylocta-1,6-dien-3-yl acetate	-2.49
CC(=CCC[C@](C)(C=C)OC(=O)C)C	(3R)-3,7-Dimethylocta-1,6-dien-3-yl acetate	-2.49
CC(=CCC[C@](C)(C=C)OC(=O)C)C	(3R)-3,7-Dimethylocta-1,6-dien-3-yl acetate	-2.49
CC(=CCC[C@](C)(C=C)OC(=O)C)C	(3R)-3,7-Dimethylocta-1,6-dien-3-yl acetate	-2.49
C[C@@H](CCO[N+](=O)[O-])O[N+](=O)[O-]	1,3-bis-(nitrooxy)butane	-4.29
C[C@@H](CCO[N+](=O)[O-])O[N+](=O)[O-]	1,3-bis-(nitrooxy)butane	-4.29
C[C@@H](CCO[N+](=O)[O-])O[N+](=O)[O-]	1,3-bis-(nitrooxy)butane	-4.29
C[C@@H](CCO[N+](=O)[O-])O[N+](=O)[O-]	1,3-bis-(nitrooxy)butane	-4.29
C[C@@H](CCO[N+](=O)[O-])O[N+](=O)[O-]	1,3-bis-(nitrooxy)butane	-4.29
CC(C)OC(C)C	2-isopropoxypropane	-0.53
CC(C)OC(C)C	2-isopropoxypropane	-0.53
CC(C)OC(C)C	2-isopropoxypropane	-0.53
CC(C)OC(C)C	2-isopropoxypropane	-0.53
CC(C)OC(C)C	2-isopropoxypropane	-0.53
CCCCC(C)C	2-methylhexane	2.93
CCCCC(C)C	2-methylhexane	2.93
CCCCC(C)C	2-methylhexane	2.93
CCCCC(C)C	2-methylhexane	2.93
CCCCC(C)C	2-methylhexane	2.93
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)N(=O)=O	pentachloronitrobenzene	-5.22
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)N(=O)=O	pentachloronitrobenzene	-5.22
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)N(=O)=O	pentachloronitrobenzene	-5.22
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)N(=O)=O	pentachloronitrobenzene	-5.22
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)N(=O)=O	pentachloronitrobenzene	-5.22
[C@@H](C(F)(F)F)(Cl)Br	2-bromo-2-chloro-1,1,1-trifluoro-ethane	-0.11
[C@@H](C(F)(F)F)(Cl)Br	2-bromo-2-chloro-1,1,1-trifluoro-ethane	-0.11
[C@@H](C(F)(F)F)(Cl)Br	2-bromo-2-chloro-1,1,1-trifluoro-ethane	-0.11
[C@@H](C(F)(F)F)(Cl)Br	2-bromo-2-chloro-1,1,1-trifluoro-ethane	-0.11
[C@@H](C(F)(F)F)(Cl)Br	2-bromo-2-chloro-1,1,1-trifluoro-ethane	-0.11
CCCCOCCCC	1-butoxybutane	-0.83
CCCCOCCCC	1-butoxybutane	-0.83
CCCCOCCCC	1-butoxybutane	-0.83
CCCCOCCCC	1-butoxybutane	-0.83
CCCCOCCCC	1-butoxybutane	-0.83
CCCCCC1CCCC1	pentylcyclopentane	2.55
CCCCCC1CCCC1	pentylcyclopentane	2.55
CCCCCC1CCCC1	pentylcyclopentane	2.55
CCCCCC1CCCC1	pentylcyclopentane	2.55
CCCCCC1CCCC1	pentylcyclopentane	2.55
CC(C)CC(C)C	2,4-dimethylpentane	2.83
CC(C)CC(C)C	2,4-dimethylpentane	2.83
CC(C)CC(C)C	2,4-dimethylpentane	2.83
CC(C)CC(C)C	2,4-dimethylpentane	2.83
CC(C)CC(C)C	2,4-dimethylpentane	2.83
Cc1ccc(nc1)C	2,5-dimethylpyridine	-4.72
Cc1ccc(nc1)C	2,5-dimethylpyridine	-4.72
Cc1ccc(nc1)C	2,5-dimethylpyridine	-4.72
Cc1ccc(nc1)C	2,5-dimethylpyridine	-4.72
Cc1ccc(nc1)C	2,5-dimethylpyridine	-4.72
C/C=C/C=O	but-2-enal	-4.22
C/C=C/C=O	but-2-enal	-4.22
C/C=C/C=O	but-2-enal	-4.22
C/C=C/C=O	but-2-enal	-4.22
C/C=C/C=O	but-2-enal	-4.22
CCC[C@H](C)CC	3-methylhexane	2.71
CCC[C@H](C)CC	3-methylhexane	2.71
CCC[C@H](C)CC	3-methylhexane	2.71
CCC[C@H](C)CC	3-methylhexane	2.71
CCC[C@H](C)CC	3-methylhexane	2.71
c1cc(c(c(c1)Cl)c2c(cc(cc2Cl)Cl)Cl)Cl	1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene	-1.96
c1cc(c(c(c1)Cl)c2c(cc(cc2Cl)Cl)Cl)Cl	1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene	-1.96
c1cc(c(c(c1)Cl)c2c(cc(cc2Cl)Cl)Cl)Cl	1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene	-1.96
c1cc(c(c(c1)Cl)c2c(cc(cc2Cl)Cl)Cl)Cl	1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene	-1.96
c1cc(c(c(c1)Cl)c2c(cc(cc2Cl)Cl)Cl)Cl	1,3,5-trichloro-2-(2,6-dichlorophenyl)benzene	-1.96
c1ccc(cc1)O[C@@H](C(F)F)F	1,2,2-trifluoroethoxybenzene	-1.29
c1ccc(cc1)O[C@@H](C(F)F)F	1,2,2-trifluoroethoxybenzene	-1.29
c1ccc(cc1)O[C@@H](C(F)F)F	1,2,2-trifluoroethoxybenzene	-1.29
c1ccc(cc1)O[C@@H](C(F)F)F	1,2,2-trifluoroethoxybenzene	-1.29
c1ccc(cc1)O[C@@H](C(F)F)F	1,2,2-trifluoroethoxybenzene	-1.29
COCCOC	1,2-dimethoxyethane	-4.84
COCCOC	1,2-dimethoxyethane	-4.84
COCCOC	1,2-dimethoxyethane	-4.84
COCCOC	1,2-dimethoxyethane	-4.84
COCCOC	1,2-dimethoxyethane	-4.84
CC[C@H](C)c1ccccc1	sec-butylbenzene	-0.45
CC[C@H](C)c1ccccc1	sec-butylbenzene	-0.45
CC[C@H](C)c1ccccc1	sec-butylbenzene	-0.45
CC[C@H](C)c1ccccc1	sec-butylbenzene	-0.45
CC[C@H](C)c1ccccc1	sec-butylbenzene	-0.45
c1ccc(cc1)CCCO	3-phenylpropan-1-ol	-6.92
c1ccc(cc1)CCCO	3-phenylpropan-1-ol	-6.92
c1ccc(cc1)CCCO	3-phenylpropan-1-ol	-6.92
c1ccc(cc1)CCCO	3-phenylpropan-1-ol	-6.92
c1ccc(cc1)CCCO	3-phenylpropan-1-ol	-6.92
CC[C@@H](C)c1cc(cc(c1O)[N+](=O)[O-])[N+](=O)[O-]	2-[(1R)-1-methylpropyl]-4,6-dinitro-phenolate	-6.23
CC[C@@H](C)c1cc(cc(c1O)[N+](=O)[O-])[N+](=O)[O-]	2-[(1R)-1-methylpropyl]-4,6-dinitro-phenolate	-6.23
CC[C@@H](C)c1cc(cc(c1O)[N+](=O)[O-])[N+](=O)[O-]	2-[(1R)-1-methylpropyl]-4,6-dinitro-phenolate	-6.23
CC[C@@H](C)c1cc(cc(c1O)[N+](=O)[O-])[N+](=O)[O-]	2-[(1R)-1-methylpropyl]-4,6-dinitro-phenolate	-6.23
CC[C@@H](C)c1cc(cc(c1O)[N+](=O)[O-])[N+](=O)[O-]	2-[(1R)-1-methylpropyl]-4,6-dinitro-phenolate	-6.23
COc1ccc(cc1)C(=O)OC	methyl 4-methoxybenzoate	-5.33
COc1ccc(cc1)C(=O)OC	methyl 4-methoxybenzoate	-5.33
COc1ccc(cc1)C(=O)OC	methyl 4-methoxybenzoate	-5.33
COc1ccc(cc1)C(=O)OC	methyl 4-methoxybenzoate	-5.33
COc1ccc(cc1)C(=O)OC	methyl 4-methoxybenzoate	-5.33
CCC(=O)Nc1ccc(c(c1)Cl)Cl	N-(3,4-dichlorophenyl)propanimidic acid	-7.78
CCC(=O)Nc1ccc(c(c1)Cl)Cl	N-(3,4-dichlorophenyl)propanimidic acid	-7.78
CCC(=O)Nc1ccc(c(c1)Cl)Cl	N-(3,4-dichlorophenyl)propanimidic acid	-7.78
CCC(=O)Nc1ccc(c(c1)Cl)Cl	N-(3,4-dichlorophenyl)propanimidic acid	-7.78
CCC(=O)Nc1ccc(c(c1)Cl)Cl	N-(3,4-dichlorophenyl)propanimidic acid	-7.78
C[C@@H](c1ccc2cc(ccc2c1)OC)C(=O)O	naproxen	-10.21
C[C@@H](c1ccc2cc(ccc2c1)OC)C(=O)O	naproxen	-10.21
C[C@@H](c1ccc2cc(ccc2c1)OC)C(=O)O	naproxen	-10.21
C[C@@H](c1ccc2cc(ccc2c1)OC)C(=O)O	naproxen	-10.21
C[C@@H](c1ccc2cc(ccc2c1)OC)C(=O)O	naproxen	-10.21
C1(C(C(C1(F)F)(F)F)(F)F)(F)F	octafluorocyclobutane	3.43
C1(C(C(C1(F)F)(F)F)(F)F)(F)F	octafluorocyclobutane	3.43
C1(C(C(C1(F)F)(F)F)(F)F)(F)F	octafluorocyclobutane	3.43
C1(C(C(C1(F)F)(F)F)(F)F)(F)F	octafluorocyclobutane	3.43
C1(C(C(C1(F)F)(F)F)(F)F)(F)F	octafluorocyclobutane	3.43
CC(C)CCOC(=O)C	isopentyl acetate	-2.21
CC(C)CCOC(=O)C	isopentyl acetate	-2.21
CC(C)CCOC(=O)C	isopentyl acetate	-2.21
CC(C)CCOC(=O)C	isopentyl acetate	-2.21
CC(C)CCOC(=O)C	isopentyl acetate	-2.21
CCCCCCCl	1-chlorohexane	0.0
CCCCCCCl	1-chlorohexane	0.0
CCCCCCCl	1-chlorohexane	0.0
CCCCCCCl	1-chlorohexane	0.0
CCCCCCCl	1-chlorohexane	0.0
CC(C)CC(=O)C	4-methylpentan-2-one	-3.05
CC(C)CC(=O)C	4-methylpentan-2-one	-3.05
CC(C)CC(=O)C	4-methylpentan-2-one	-3.05
CC(C)CC(=O)C	4-methylpentan-2-one	-3.05
CC(C)CC(=O)C	4-methylpentan-2-one	-3.05
CCCCCC=O	hexanal	-2.81
CCCCCC=O	hexanal	-2.81
CCCCCC=O	hexanal	-2.81
CCCCCC=O	hexanal	-2.81
CCCCCC=O	hexanal	-2.81
c1cc(cc(c1)Cl)N	3-chloroaniline	-5.82
c1cc(cc(c1)Cl)N	3-chloroaniline	-5.82
c1cc(cc(c1)Cl)N	3-chloroaniline	-5.82
c1cc(cc(c1)Cl)N	3-chloroaniline	-5.82
c1cc(cc(c1)Cl)N	3-chloroaniline	-5.82
C1COCCN1	morpholine	-7.17
C1COCCN1	morpholine	-7.17
C1COCCN1	morpholine	-7.17
C1COCCN1	morpholine	-7.17
C1COCCN1	morpholine	-7.17
CCOC(C)OCC	1,1-diethoxyethane	-3.28
CCOC(C)OCC	1,1-diethoxyethane	-3.28
CCOC(C)OCC	1,1-diethoxyethane	-3.28
CCOC(C)OCC	1,1-diethoxyethane	-3.28
CCOC(C)OCC	1,1-diethoxyethane	-3.28
CCCC[N@](CC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	N-butyl-N-ethyl-2,6-dinitro-4-(trifluoromethyl)aniline	-3.51
CCCC[N@](CC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	N-butyl-N-ethyl-2,6-dinitro-4-(trifluoromethyl)aniline	-3.51
CCCC[N@](CC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	N-butyl-N-ethyl-2,6-dinitro-4-(trifluoromethyl)aniline	-3.51
CCCC[N@](CC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	N-butyl-N-ethyl-2,6-dinitro-4-(trifluoromethyl)aniline	-3.51
CCCC[N@](CC)c1c(cc(cc1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]	N-butyl-N-ethyl-2,6-dinitro-4-(trifluoromethyl)aniline	-3.51
CS	methanethiol	-1.2
CS	methanethiol	-1.2
CS	methanethiol	-1.2
CS	methanethiol	-1.2
CS	methanethiol	-1.2
C1[C@@H]2[C@H](COS(=O)O1)[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl	endosulfan alpha	-4.23
C1[C@@H]2[C@H](COS(=O)O1)[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl	endosulfan alpha	-4.23
C1[C@@H]2[C@H](COS(=O)O1)[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl	endosulfan alpha	-4.23
C1[C@@H]2[C@H](COS(=O)O1)[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl	endosulfan alpha	-4.23
C1[C@@H]2[C@H](COS(=O)O1)[C@@]3(C(=C([C@]2(C3(Cl)Cl)Cl)Cl)Cl)Cl	endosulfan alpha	-4.23
CC(=O)c1ccc(cc1)OC	1-(4-methoxyphenyl)ethanone	-4.4
CC(=O)c1ccc(cc1)OC	1-(4-methoxyphenyl)ethanone	-4.4
CC(=O)c1ccc(cc1)OC	1-(4-methoxyphenyl)ethanone	-4.4
CC(=O)c1ccc(cc1)OC	1-(4-methoxyphenyl)ethanone	-4.4
CC(=O)c1ccc(cc1)OC	1-(4-methoxyphenyl)ethanone	-4.4
C=CCO	prop-2-en-1-ol	-5.03
C=CCO	prop-2-en-1-ol	-5.03
C=CCO	prop-2-en-1-ol	-5.03
C=CCO	prop-2-en-1-ol	-5.03
C=CCO	prop-2-en-1-ol	-5.03
CCSC	methylsulfanylethane	-1.5
CCSC	methylsulfanylethane	-1.5
CCSC	methylsulfanylethane	-1.5
CCSC	methylsulfanylethane	-1.5
CCSC	methylsulfanylethane	-1.5
CCCCCOC(=O)C	pentyl acetate	-2.51
CCCCCOC(=O)C	pentyl acetate	-2.51
CCCCCOC(=O)C	pentyl acetate	-2.51
CCCCCOC(=O)C	pentyl acetate	-2.51
CCCCCOC(=O)C	pentyl acetate	-2.51
c1c(cc(c(c1Cl)Cl)Cl)Cl	1,2,3,5-tetrachlorobenzene	-1.62
c1c(cc(c(c1Cl)Cl)Cl)Cl	1,2,3,5-tetrachlorobenzene	-1.62
c1c(cc(c(c1Cl)Cl)Cl)Cl	1,2,3,5-tetrachlorobenzene	-1.62
c1c(cc(c(c1Cl)Cl)Cl)Cl	1,2,3,5-tetrachlorobenzene	-1.62
c1c(cc(c(c1Cl)Cl)Cl)Cl	1,2,3,5-tetrachlorobenzene	-1.62
CC(=O)c1ccccc1	1-phenylethanone	-4.58
CC(=O)c1ccccc1	1-phenylethanone	-4.58
CC(=O)c1ccccc1	1-phenylethanone	-4.58
CC(=O)c1ccccc1	1-phenylethanone	-4.58
CC(=O)c1ccccc1	1-phenylethanone	-4.58
CCCl	chloroethane	-0.63
CCCl	chloroethane	-0.63
CCCl	chloroethane	-0.63
CCCl	chloroethane	-0.63
CCCl	chloroethane	-0.63
CCCC1CCCC1	propylcyclopentane	2.13
CCCC1CCCC1	propylcyclopentane	2.13
CCCC1CCCC1	propylcyclopentane	2.13
CCCC1CCCC1	propylcyclopentane	2.13
CCCC1CCCC1	propylcyclopentane	2.13
c1c(cc(cc1Cl)Cl)Cl	1,3,5-trichlorobenzene	-0.78
c1c(cc(cc1Cl)Cl)Cl	1,3,5-trichlorobenzene	-0.78
c1c(cc(cc1Cl)Cl)Cl	1,3,5-trichlorobenzene	-0.78
c1c(cc(cc1Cl)Cl)Cl	1,3,5-trichlorobenzene	-0.78
c1c(cc(cc1Cl)Cl)Cl	1,3,5-trichlorobenzene	-0.78
CCCOC(=O)c1ccc(cc1)O	propyl paraben	-9.37
CCCOC(=O)c1ccc(cc1)O	propyl paraben	-9.37
CCCOC(=O)c1ccc(cc1)O	propyl paraben	-9.37
CCCOC(=O)c1ccc(cc1)O	propyl paraben	-9.37
CCCOC(=O)c1ccc(cc1)O	propyl paraben	-9.37
c1cc(cc(c1)Cl)O	3-chlorophenol	-6.62
c1cc(cc(c1)Cl)O	3-chlorophenol	-6.62
c1cc(cc(c1)Cl)O	3-chlorophenol	-6.62
c1cc(cc(c1)Cl)O	3-chlorophenol	-6.62
c1cc(cc(c1)Cl)O	3-chlorophenol	-6.62
CC(C)CCO	3-methylbutan-1-ol	-4.42
CC(C)CCO	3-methylbutan-1-ol	-4.42
CC(C)CCO	3-methylbutan-1-ol	-4.42
CC(C)CCO	3-methylbutan-1-ol	-4.42
CC(C)CCO	3-methylbutan-1-ol	-4.42
CCCCCN	pentan-1-amine	-4.09
CCCCCN	pentan-1-amine	-4.09
CCCCCN	pentan-1-amine	-4.09
CCCCCN	pentan-1-amine	-4.09
CCCCCN	pentan-1-amine	-4.09
Cc1c(c(=O)n(c(=O)[nH]1)C(C)(C)C)Cl	terbacil	-11.14
Cc1c(c(=O)n(c(=O)[nH]1)C(C)(C)C)Cl	terbacil	-11.14
Cc1c(c(=O)n(c(=O)[nH]1)C(C)(C)C)Cl	terbacil	-11.14
Cc1c(c(=O)n(c(=O)[nH]1)C(C)(C)C)Cl	terbacil	-11.14
Cc1c(c(=O)n(c(=O)[nH]1)C(C)(C)C)Cl	terbacil	-11.14
CC(C)CCC(C)(C)C	2,2,5-trimethylhexane	2.93
CC(C)CCC(C)(C)C	2,2,5-trimethylhexane	2.93
CC(C)CCC(C)(C)C	2,2,5-trimethylhexane	2.93
CC(C)CCC(C)(C)C	2,2,5-trimethylhexane	2.93
CC(C)CCC(C)(C)C	2,2,5-trimethylhexane	2.93
CCCCOCCO	2-butoxyethanol	-6.25
CCCCOCCO	2-butoxyethanol	-6.25
CCCCOCCO	2-butoxyethanol	-6.25
CCCCOCCO	2-butoxyethanol	-6.25
CCCCOCCO	2-butoxyethanol	-6.25
C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C@@]5(C(=C([C@]3(C5(Cl)Cl)Cl)Cl)Cl)Cl	endrin	-4.82
C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C@@]5(C(=C([C@]3(C5(Cl)Cl)Cl)Cl)Cl)Cl	endrin	-4.82
C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C@@]5(C(=C([C@]3(C5(Cl)Cl)Cl)Cl)Cl)Cl	endrin	-4.82
C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C@@]5(C(=C([C@]3(C5(Cl)Cl)Cl)Cl)Cl)Cl	endrin	-4.82
C1[C@@H]2[C@H]3[C@@H]([C@H]1[C@H]4[C@@H]2O4)[C@@]5(C(=C([C@]3(C5(Cl)Cl)Cl)Cl)Cl)Cl	endrin	-4.82
c1ccc(cc1)C(=O)N	benzamide	-11.0
c1ccc(cc1)C(=O)N	benzamide	-11.0
c1ccc(cc1)C(=O)N	benzamide	-11.0
c1ccc(cc1)C(=O)N	benzamide	-11.0
c1ccc(cc1)C(=O)N	benzamide	-11.0
CC(C)[N+](=O)[O-]	2-nitropropane	-3.13
CC(C)[N+](=O)[O-]	2-nitropropane	-3.13
CC(C)[N+](=O)[O-]	2-nitropropane	-3.13
CC(C)[N+](=O)[O-]	2-nitropropane	-3.13
CC(C)[N+](=O)[O-]	2-nitropropane	-3.13
C(C(CO)O)O	glycerol	-13.43
C(C(CO)O)O	glycerol	-13.43
C(C(CO)O)O	glycerol	-13.43
C(C(CO)O)O	glycerol	-13.43
C(C(CO)O)O	glycerol	-13.43
CCCI	1-iodopropane	-0.53
CCCI	1-iodopropane	-0.53
CCCI	1-iodopropane	-0.53
CCCI	1-iodopropane	-0.53
CCCI	1-iodopropane	-0.53
COCCN	2-methoxyethanamine	-6.55
COCCN	2-methoxyethanamine	-6.55
COCCN	2-methoxyethanamine	-6.55
COCCN	2-methoxyethanamine	-6.55
COCCN	2-methoxyethanamine	-6.55
C(C(Cl)(Cl)Cl)Cl	1,1,1,2-tetrachloroethane	-1.43
C(C(Cl)(Cl)Cl)Cl	1,1,1,2-tetrachloroethane	-1.43
C(C(Cl)(Cl)Cl)Cl	1,1,1,2-tetrachloroethane	-1.43
C(C(Cl)(Cl)Cl)Cl	1,1,1,2-tetrachloroethane	-1.43
C(C(Cl)(Cl)Cl)Cl	1,1,1,2-tetrachloroethane	-1.43
CCC(=O)OC	methyl propanoate	-2.93
CCC(=O)OC	methyl propanoate	-2.93
CCC(=O)OC	methyl propanoate	-2.93
CCC(=O)OC	methyl propanoate	-2.93
CCC(=O)OC	methyl propanoate	-2.93
C1CCCC1	cyclopentane	1.2
C1CCCC1	cyclopentane	1.2
C1CCCC1	cyclopentane	1.2
C1CCCC1	cyclopentane	1.2
C1CCCC1	cyclopentane	1.2
CCc1cccnc1	3-ethylpyridine	-4.59
CCc1cccnc1	3-ethylpyridine	-4.59
CCc1cccnc1	3-ethylpyridine	-4.59
CCc1cccnc1	3-ethylpyridine	-4.59
CCc1cccnc1	3-ethylpyridine	-4.59
Cc1cc(cnc1)C	3,5-dimethylpyridine	-4.84
Cc1cc(cnc1)C	3,5-dimethylpyridine	-4.84
Cc1cc(cnc1)C	3,5-dimethylpyridine	-4.84
Cc1cc(cnc1)C	3,5-dimethylpyridine	-4.84
Cc1cc(cnc1)C	3,5-dimethylpyridine	-4.84
COCCO	2-methoxyethanol	-6.62
COCCO	2-methoxyethanol	-6.62
COCCO	2-methoxyethanol	-6.62
COCCO	2-methoxyethanol	-6.62
COCCO	2-methoxyethanol	-6.62
COC=O	methyl formate	-2.78
COC=O	methyl formate	-2.78
COC=O	methyl formate	-2.78
COC=O	methyl formate	-2.78
COC=O	methyl formate	-2.78
c1ccc2cc(ccc2c1)N	naphthalen-2-amine	-7.47
c1ccc2cc(ccc2c1)N	naphthalen-2-amine	-7.47
c1ccc2cc(ccc2c1)N	naphthalen-2-amine	-7.47
c1ccc2cc(ccc2c1)N	naphthalen-2-amine	-7.47
c1ccc2cc(ccc2c1)N	naphthalen-2-amine	-7.47
Cc1c[nH]cn1	4-methyl-1H-imidazole	-10.27
Cc1c[nH]cn1	4-methyl-1H-imidazole	-10.27
Cc1c[nH]cn1	4-methyl-1H-imidazole	-10.27
Cc1c[nH]cn1	4-methyl-1H-imidazole	-10.27
Cc1c[nH]cn1	4-methyl-1H-imidazole	-10.27
Cc1cccc(c1)[N+](=O)[O-]	1-methyl-3-nitro-benzene	-3.45
Cc1cccc(c1)[N+](=O)[O-]	1-methyl-3-nitro-benzene	-3.45
Cc1cccc(c1)[N+](=O)[O-]	1-methyl-3-nitro-benzene	-3.45
Cc1cccc(c1)[N+](=O)[O-]	1-methyl-3-nitro-benzene	-3.45
Cc1cccc(c1)[N+](=O)[O-]	1-methyl-3-nitro-benzene	-3.45
C(CCCl)CCl	1,4-dichlorobutane	-2.32
C(CCCl)CCl	1,4-dichlorobutane	-2.32
C(CCCl)CCl	1,4-dichlorobutane	-2.32
C(CCCl)CCl	1,4-dichlorobutane	-2.32
C(CCCl)CCl	1,4-dichlorobutane	-2.32
CC(=O)CO[N+](=O)[O-]	nitroxyacetone	-5.99
CC(=O)CO[N+](=O)[O-]	nitroxyacetone	-5.99
CC(=O)CO[N+](=O)[O-]	nitroxyacetone	-5.99
CC(=O)CO[N+](=O)[O-]	nitroxyacetone	-5.99
CC(=O)CO[N+](=O)[O-]	nitroxyacetone	-5.99
CC(C)(C)c1ccccc1	tert-butylbenzene	-0.44
CC(C)(C)c1ccccc1	tert-butylbenzene	-0.44
CC(C)(C)c1ccccc1	tert-butylbenzene	-0.44
CC(C)(C)c1ccccc1	tert-butylbenzene	-0.44
CC(C)(C)c1ccccc1	tert-butylbenzene	-0.44
CCCCCC(=O)OC	methyl hexanoate	-2.49
CCCCCC(=O)OC	methyl hexanoate	-2.49
CCCCCC(=O)OC	methyl hexanoate	-2.49
CCCCCC(=O)OC	methyl hexanoate	-2.49
CCCCCC(=O)OC	methyl hexanoate	-2.49
C[C@@H](C(F)(F)F)O	1,1,1-trifluoropropan-2-ol	-4.16
C[C@@H](C(F)(F)F)O	1,1,1-trifluoropropan-2-ol	-4.16
C[C@@H](C(F)(F)F)O	1,1,1-trifluoropropan-2-ol	-4.16
C[C@@H](C(F)(F)F)O	1,1,1-trifluoropropan-2-ol	-4.16
C[C@@H](C(F)(F)F)O	1,1,1-trifluoropropan-2-ol	-4.16
CCCCCBr	1-bromo-pentane	-0.1
CCCCCBr	1-bromo-pentane	-0.1
CCCCCBr	1-bromo-pentane	-0.1
CCCCCBr	1-bromo-pentane	-0.1
CCCCCBr	1-bromo-pentane	-0.1
CCCCCCC=C	oct-1-ene	1.92
CCCCCCC=C	oct-1-ene	1.92
CCCCCCC=C	oct-1-ene	1.92
CCCCCCC=C	oct-1-ene	1.92
CCCCCCC=C	oct-1-ene	1.92
CC1=CC(=O)[C@@H](CC1)C(C)C	6-isopropyl-3-methyl-1-cyclohex-2-enone	-4.51
CC1=CC(=O)[C@@H](CC1)C(C)C	6-isopropyl-3-methyl-1-cyclohex-2-enone	-4.51
CC1=CC(=O)[C@@H](CC1)C(C)C	6-isopropyl-3-methyl-1-cyclohex-2-enone	-4.51
CC1=CC(=O)[C@@H](CC1)C(C)C	6-isopropyl-3-methyl-1-cyclohex-2-enone	-4.51
CC1=CC(=O)[C@@H](CC1)C(C)C	6-isopropyl-3-methyl-1-cyclohex-2-enone	-4.51
CC(C)O	propan-2-ol	-4.74
CC(C)O	propan-2-ol	-4.74
CC(C)O	propan-2-ol	-4.74
CC(C)O	propan-2-ol	-4.74
CC(C)O	propan-2-ol	-4.74
CCCCCCN	hexan-1-amine	-3.95
CCCCCCN	hexan-1-amine	-3.95
CCCCCCN	hexan-1-amine	-3.95
CCCCCCN	hexan-1-amine	-3.95
CCCCCCN	hexan-1-amine	-3.95
C(CO[N+](=O)[O-])CO[N+](=O)[O-]	3-nitrooxypropyl nitrate	-4.8
C(CO[N+](=O)[O-])CO[N+](=O)[O-]	3-nitrooxypropyl nitrate	-4.8
C(CO[N+](=O)[O-])CO[N+](=O)[O-]	3-nitrooxypropyl nitrate	-4.8
C(CO[N+](=O)[O-])CO[N+](=O)[O-]	3-nitrooxypropyl nitrate	-4.8
C(CO[N+](=O)[O-])CO[N+](=O)[O-]	3-nitrooxypropyl nitrate	-4.8
Cc1ccc(c(c1)C)O	2,4-dimethylphenol	-6.01
Cc1ccc(c(c1)C)O	2,4-dimethylphenol	-6.01
Cc1ccc(c(c1)C)O	2,4-dimethylphenol	-6.01
Cc1ccc(c(c1)C)O	2,4-dimethylphenol	-6.01
Cc1ccc(c(c1)C)O	2,4-dimethylphenol	-6.01
CCCCCO	pentan-1-ol	-4.57
CCCCCO	pentan-1-ol	-4.57
CCCCCO	pentan-1-ol	-4.57
CCCCCO	pentan-1-ol	-4.57
CCCCCO	pentan-1-ol	-4.57
CCC[C@@H](C)O	pentan-2-ol	-4.39
CCC[C@@H](C)O	pentan-2-ol	-4.39
CCC[C@@H](C)O	pentan-2-ol	-4.39
CCC[C@@H](C)O	pentan-2-ol	-4.39
CCC[C@@H](C)O	pentan-2-ol	-4.39
CCCC[C@@H](C)CC	3-methylheptane	2.97
CCCC[C@@H](C)CC	3-methylheptane	2.97
CCCC[C@@H](C)CC	3-methylheptane	2.97
CCCC[C@@H](C)CC	3-methylheptane	2.97
CCCC[C@@H](C)CC	3-methylheptane	2.97
C[C@@H](c1ccc(cc1)CC(C)C)C(=O)O	ibuprofen	-7.0
C[C@@H](c1ccc(cc1)CC(C)C)C(=O)O	ibuprofen	-7.0
C[C@@H](c1ccc(cc1)CC(C)C)C(=O)O	ibuprofen	-7.0
C[C@@H](c1ccc(cc1)CC(C)C)C(=O)O	ibuprofen	-7.0
C[C@@H](c1ccc(cc1)CC(C)C)C(=O)O	ibuprofen	-7.0
CCOC(=O)C[C@H](C(=O)OCC)SP(=S)(OC)OC	diethyl (2R)-2-dimethoxyphosphinothioylsulfanylbutanedioate	-8.15
CCOC(=O)C[C@H](C(=O)OCC)SP(=S)(OC)OC	diethyl (2R)-2-dimethoxyphosphinothioylsulfanylbutanedioate	-8.15
CCOC(=O)C[C@H](C(=O)OCC)SP(=S)(OC)OC	diethyl (2R)-2-dimethoxyphosphinothioylsulfanylbutanedioate	-8.15
CCOC(=O)C[C@H](C(=O)OCC)SP(=S)(OC)OC	diethyl (2R)-2-dimethoxyphosphinothioylsulfanylbutanedioate	-8.15
CCOC(=O)C[C@H](C(=O)OCC)SP(=S)(OC)OC	diethyl (2R)-2-dimethoxyphosphinothioylsulfanylbutanedioate	-8.15
Cc1ccc(cc1C)O	3,4-dimethylphenol	-6.5
Cc1ccc(cc1C)O	3,4-dimethylphenol	-6.5
Cc1ccc(cc1C)O	3,4-dimethylphenol	-6.5
Cc1ccc(cc1C)O	3,4-dimethylphenol	-6.5
Cc1ccc(cc1C)O	3,4-dimethylphenol	-6.5
Cc1cc(ccc1Cl)O	4-chloro-3-methyl-phenol	-6.79
Cc1cc(ccc1Cl)O	4-chloro-3-methyl-phenol	-6.79
Cc1cc(ccc1Cl)O	4-chloro-3-methyl-phenol	-6.79
Cc1cc(ccc1Cl)O	4-chloro-3-methyl-phenol	-6.79
Cc1cc(ccc1Cl)O	4-chloro-3-methyl-phenol	-6.79
CCCC/C=C/C	hept-2-ene	1.68
CCCC/C=C/C	hept-2-ene	1.68
CCCC/C=C/C	hept-2-ene	1.68
CCCC/C=C/C	hept-2-ene	1.68
CCCC/C=C/C	hept-2-ene	1.68
CCCOCCC	1-propoxypropane	-1.16
CCCOCCC	1-propoxypropane	-1.16
CCCOCCC	1-propoxypropane	-1.16
CCCOCCC	1-propoxypropane	-1.16
CCCOCCC	1-propoxypropane	-1.16
C[C@@H]1CC[C@H]([C@@H](C1)O)C(C)C	(1R,2S,5R)-2-isopropyl-5-methylcyclohexanol	-3.2
C[C@@H]1CC[C@H]([C@@H](C1)O)C(C)C	(1R,2S,5R)-2-isopropyl-5-methylcyclohexanol	-3.2
C[C@@H]1CC[C@H]([C@@H](C1)O)C(C)C	(1R,2S,5R)-2-isopropyl-5-methylcyclohexanol	-3.2
C[C@@H]1CC[C@H]([C@@H](C1)O)C(C)C	(1R,2S,5R)-2-isopropyl-5-methylcyclohexanol	-3.2
C[C@@H]1CC[C@H]([C@@H](C1)O)C(C)C	(1R,2S,5R)-2-isopropyl-5-methylcyclohexanol	-3.2
CCNc1nc(nc(n1)SC)NC(C)(C)C	terbutryn	-6.68
CCNc1nc(nc(n1)SC)NC(C)(C)C	terbutryn	-6.68
CCNc1nc(nc(n1)SC)NC(C)(C)C	terbutryn	-6.68
CCNc1nc(nc(n1)SC)NC(C)(C)C	terbutryn	-6.68
CCNc1nc(nc(n1)SC)NC(C)(C)C	terbutryn	-6.68
CC(C)CC(C)(C)C	2,2,4-trimethylpentane	2.89
CC(C)CC(C)(C)C	2,2,4-trimethylpentane	2.89
CC(C)CC(C)(C)C	2,2,4-trimethylpentane	2.89
CC(C)CC(C)(C)C	2,2,4-trimethylpentane	2.89
CC(C)CC(C)(C)C	2,2,4-trimethylpentane	2.89
CCCCC(=O)CCCC	nonan-5-one	-2.64
CCCCC(=O)CCCC	nonan-5-one	-2.64
CCCCC(=O)CCCC	nonan-5-one	-2.64
CCCCC(=O)CCCC	nonan-5-one	-2.64
CCCCC(=O)CCCC	nonan-5-one	-2.64
CCCCN(CC)C(=O)SCCC	pebulate	-3.64
CCCCN(CC)C(=O)SCCC	pebulate	-3.64
CCCCN(CC)C(=O)SCCC	pebulate	-3.64
CCCCN(CC)C(=O)SCCC	pebulate	-3.64
CCCCN(CC)C(=O)SCCC	pebulate	-3.64
CCCCCC=C	hept-1-ene	1.66
CCCCCC=C	hept-1-ene	1.66
CCCCCC=C	hept-1-ene	1.66
CCCCCC=C	hept-1-ene	1.66
CCCCCC=C	hept-1-ene	1.66
CC(C)OC=O	isopropyl formate	-2.02
CC(C)OC=O	isopropyl formate	-2.02
CC(C)OC=O	isopropyl formate	-2.02
CC(C)OC=O	isopropyl formate	-2.02
CC(C)OC=O	isopropyl formate	-2.02
CC(OC(=O)C)OC(=O)C	1-acetoxyethyl acetate	-4.97
CC(OC(=O)C)OC(=O)C	1-acetoxyethyl acetate	-4.97
CC(OC(=O)C)OC(=O)C	1-acetoxyethyl acetate	-4.97
CC(OC(=O)C)OC(=O)C	1-acetoxyethyl acetate	-4.97
CC(OC(=O)C)OC(=O)C	1-acetoxyethyl acetate	-4.97
c1c(c(=O)[nH]c(=O)[nH]1)Cl	5-chlorouracil	-17.74
c1c(c(=O)[nH]c(=O)[nH]1)Cl	5-chlorouracil	-17.74
c1c(c(=O)[nH]c(=O)[nH]1)Cl	5-chlorouracil	-17.74
c1c(c(=O)[nH]c(=O)[nH]1)Cl	5-chlorouracil	-17.74
c1c(c(=O)[nH]c(=O)[nH]1)Cl	5-chlorouracil	-17.74
CC(=C)c1ccccc1	isopropenylbenzene	-1.24
CC(=C)c1ccccc1	isopropenylbenzene	-1.24
CC(=C)c1ccccc1	isopropenylbenzene	-1.24
CC(=C)c1ccccc1	isopropenylbenzene	-1.24
CC(=C)c1ccccc1	isopropenylbenzene	-1.24
CCC(C)C	isopentane	2.38
CCC(C)C	isopentane	2.38
CCC(C)C	isopentane	2.38
CCC(C)C	isopentane	2.38
CCC(C)C	isopentane	2.38
CCCCO[N+](=O)[O-]	butyl nitrate	-2.09
CCCCO[N+](=O)[O-]	butyl nitrate	-2.09
CCCCO[N+](=O)[O-]	butyl nitrate	-2.09
CCCCO[N+](=O)[O-]	butyl nitrate	-2.09
CCCCO[N+](=O)[O-]	butyl nitrate	-2.09
c1ccc(cc1)Br	bromobenzene	-1.46
c1ccc(cc1)Br	bromobenzene	-1.46
c1ccc(cc1)Br	bromobenzene	-1.46
c1ccc(cc1)Br	bromobenzene	-1.46
c1ccc(cc1)Br	bromobenzene	-1.46
CC(Cl)(Cl)Cl	1,1,1-trichloroethane	-0.19
CC(Cl)(Cl)Cl	1,1,1-trichloroethane	-0.19
CC(Cl)(Cl)Cl	1,1,1-trichloroethane	-0.19
CC(Cl)(Cl)Cl	1,1,1-trichloroethane	-0.19
CC(Cl)(Cl)Cl	1,1,1-trichloroethane	-0.19
CC(=C)[C@H]1CCC(=CC1)C=O	4-(1-Methylethenyl)-1-cyclohexene-1-carboxaldehyde	-4.09
CC(=C)[C@H]1CCC(=CC1)C=O	4-(1-Methylethenyl)-1-cyclohexene-1-carboxaldehyde	-4.09
CC(=C)[C@H]1CCC(=CC1)C=O	4-(1-Methylethenyl)-1-cyclohexene-1-carboxaldehyde	-4.09
CC(=C)[C@H]1CCC(=CC1)C=O	4-(1-Methylethenyl)-1-cyclohexene-1-carboxaldehyde	-4.09
CC(=C)[C@H]1CCC(=CC1)C=O	4-(1-Methylethenyl)-1-cyclohexene-1-carboxaldehyde	-4.09
Cc1ccccc1[N+](=O)[O-]	1-methyl-2-nitro-benzene	-3.58
Cc1ccccc1[N+](=O)[O-]	1-methyl-2-nitro-benzene	-3.58
Cc1ccccc1[N+](=O)[O-]	1-methyl-2-nitro-benzene	-3.58
Cc1ccccc1[N+](=O)[O-]	1-methyl-2-nitro-benzene	-3.58
Cc1ccccc1[N+](=O)[O-]	1-methyl-2-nitro-benzene	-3.58
CCCCCCCI	1-iodoheptane	0.27
CCCCCCCI	1-iodoheptane	0.27
CCCCCCCI	1-iodoheptane	0.27
CCCCCCCI	1-iodoheptane	0.27
CCCCCCCI	1-iodoheptane	0.27
c1cc2ccc3cccc4c3c2c(c1)cc4	pyrene	-4.52
c1cc2ccc3cccc4c3c2c(c1)cc4	pyrene	-4.52
c1cc2ccc3cccc4c3c2c(c1)cc4	pyrene	-4.52
c1cc2ccc3cccc4c3c2c(c1)cc4	pyrene	-4.52
c1cc2ccc3cccc4c3c2c(c1)cc4	pyrene	-4.52
CCCCCCl	1-chloro-pentane	-0.1
CCCCCCl	1-chloro-pentane	-0.1
CCCCCCl	1-chloro-pentane	-0.1
CCCCCCl	1-chloro-pentane	-0.1
CCCCCCl	1-chloro-pentane	-0.1
CC(C)COC(=O)C	isobutyl acetate	-2.36
CC(C)COC(=O)C	isobutyl acetate	-2.36
CC(C)COC(=O)C	isobutyl acetate	-2.36
CC(C)COC(=O)C	isobutyl acetate	-2.36
CC(C)COC(=O)C	isobutyl acetate	-2.36
CCC(C)(C)C	2,2-dimethylbutane	2.51
CCC(C)(C)C	2,2-dimethylbutane	2.51
CCC(C)(C)C	2,2-dimethylbutane	2.51
CCC(C)(C)C	2,2-dimethylbutane	2.51
CCC(C)(C)C	2,2-dimethylbutane	2.51
c1cc(ccc1N)N(=O)=O	4-nitroaniline	-9.82
c1cc(ccc1N)N(=O)=O	4-nitroaniline	-9.82
c1cc(ccc1N)N(=O)=O	4-nitroaniline	-9.82
c1cc(ccc1N)N(=O)=O	4-nitroaniline	-9.82
c1cc(ccc1N)N(=O)=O	4-nitroaniline	-9.82
COC(=O)CC#N	methyl 2-cyanoacetate	-6.72
COC(=O)CC#N	methyl 2-cyanoacetate	-6.72
COC(=O)CC#N	methyl 2-cyanoacetate	-6.72
COC(=O)CC#N	methyl 2-cyanoacetate	-6.72
COC(=O)CC#N	methyl 2-cyanoacetate	-6.72
COc1ccc(cc1)N	4-methoxyaniline	-7.48
COc1ccc(cc1)N	4-methoxyaniline	-7.48
COc1ccc(cc1)N	4-methoxyaniline	-7.48
COc1ccc(cc1)N	4-methoxyaniline	-7.48
COc1ccc(cc1)N	4-methoxyaniline	-7.48
CC(C)Cc1ccccc1	isobutylbenzene	0.16
CC(C)Cc1ccccc1	isobutylbenzene	0.16
CC(C)Cc1ccccc1	isobutylbenzene	0.16
CC(C)Cc1ccccc1	isobutylbenzene	0.16
CC(C)Cc1ccccc1	isobutylbenzene	0.16
c1ccc(cc1)c2c(cc(cc2Cl)Cl)Cl	1,3,5-trichloro-2-phenyl-benzene	-2.16
c1ccc(cc1)c2c(cc(cc2Cl)Cl)Cl	1,3,5-trichloro-2-phenyl-benzene	-2.16
c1ccc(cc1)c2c(cc(cc2Cl)Cl)Cl	1,3,5-trichloro-2-phenyl-benzene	-2.16
c1ccc(cc1)c2c(cc(cc2Cl)Cl)Cl	1,3,5-trichloro-2-phenyl-benzene	-2.16
c1ccc(cc1)c2c(cc(cc2Cl)Cl)Cl	1,3,5-trichloro-2-phenyl-benzene	-2.16
CN	methanamine	-4.55
CN	methanamine	-4.55
CN	methanamine	-4.55
CN	methanamine	-4.55
CN	methanamine	-4.55
c1ccc(c(c1)O)Cl	2-chlorophenol	-4.55
c1ccc(c(c1)O)Cl	2-chlorophenol	-4.55
c1ccc(c(c1)O)Cl	2-chlorophenol	-4.55
c1ccc(c(c1)O)Cl	2-chlorophenol	-4.55
c1ccc(c(c1)O)Cl	2-chlorophenol	-4.55
c1ccc2c(c1)C(=O)c3ccc(cc3C2=O)N	2-amino-9,10-anthraquinone	-11.53
c1ccc2c(c1)C(=O)c3ccc(cc3C2=O)N	2-amino-9,10-anthraquinone	-11.53
c1ccc2c(c1)C(=O)c3ccc(cc3C2=O)N	2-amino-9,10-anthraquinone	-11.53
c1ccc2c(c1)C(=O)c3ccc(cc3C2=O)N	2-amino-9,10-anthraquinone	-11.53
c1ccc2c(c1)C(=O)c3ccc(cc3C2=O)N	2-amino-9,10-anthraquinone	-11.53
C(=C\Cl)\Cl	(Z)-1,2-dichloroethylene	-1.17
C(=C\Cl)\Cl	(Z)-1,2-dichloroethylene	-1.17
C(=C\Cl)\Cl	(Z)-1,2-dichloroethylene	-1.17
C(=C\Cl)\Cl	(Z)-1,2-dichloroethylene	-1.17
C(=C\Cl)\Cl	(Z)-1,2-dichloroethylene	-1.17
CCCCC(=O)C	hexan-2-one	-3.28
CCCCC(=O)C	hexan-2-one	-3.28
CCCCC(=O)C	hexan-2-one	-3.28
CCCCC(=O)C	hexan-2-one	-3.28
CCCCC(=O)C	hexan-2-one	-3.28
C(CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxyethane	-5.73
C(CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxyethane	-5.73
C(CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxyethane	-5.73
C(CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxyethane	-5.73
C(CO[N+](=O)[O-])O[N+](=O)[O-]	1,2-dinitroxyethane	-5.73
c1ccc(c(c1)O)F	2-fluorophenol	-5.29
c1ccc(c(c1)O)F	2-fluorophenol	-5.29
c1ccc(c(c1)O)F	2-fluorophenol	-5.29
c1ccc(c(c1)O)F	2-fluorophenol	-5.29
c1ccc(c(c1)O)F	2-fluorophenol	-5.29
Cc1c(nc(nc1OC(=O)N(C)C)N(C)C)C	pirimor	-9.41
Cc1c(nc(nc1OC(=O)N(C)C)N(C)C)C	pirimor	-9.41
Cc1c(nc(nc1OC(=O)N(C)C)N(C)C)C	pirimor	-9.41
Cc1c(nc(nc1OC(=O)N(C)C)N(C)C)C	pirimor	-9.41
Cc1c(nc(nc1OC(=O)N(C)C)N(C)C)C	pirimor	-9.41
C=Cc1ccccc1	styrene	-1.24
C=Cc1ccccc1	styrene	-1.24
C=Cc1ccccc1	styrene	-1.24
C=Cc1ccccc1	styrene	-1.24
C=Cc1ccccc1	styrene	-1.24
CCOP(=O)(OCC)OCC	triethylphosphate	-7.5
CCOP(=O)(OCC)OCC	triethylphosphate	-7.5
CCOP(=O)(OCC)OCC	triethylphosphate	-7.5
CCOP(=O)(OCC)OCC	triethylphosphate	-7.5
CCOP(=O)(OCC)OCC	triethylphosphate	-7.5
C(C(F)(F)F)O	2,2,2-trifluoroethanol	-4.31
C(C(F)(F)F)O	2,2,2-trifluoroethanol	-4.31
C(C(F)(F)F)O	2,2,2-trifluoroethanol	-4.31
C(C(F)(F)F)O	2,2,2-trifluoroethanol	-4.31
C(C(F)(F)F)O	2,2,2-trifluoroethanol	-4.31
CCCCOC[C@H](C)O	1-butoxy-2-propanol	-5.73
CCCCOC[C@H](C)O	1-butoxy-2-propanol	-5.73
CCCCOC[C@H](C)O	1-butoxy-2-propanol	-5.73
CCCCOC[C@H](C)O	1-butoxy-2-propanol	-5.73
CCCCOC[C@H](C)O	1-butoxy-2-propanol	-5.73
CCCO	propan-1-ol	-4.85
CCCO	propan-1-ol	-4.85
CCCO	propan-1-ol	-4.85
CCCO	propan-1-ol	-4.85
CCCO	propan-1-ol	-4.85
Cc1ccccc1C	o-xylene	-0.9
Cc1ccccc1C	o-xylene	-0.9
Cc1ccccc1C	o-xylene	-0.9
Cc1ccccc1C	o-xylene	-0.9
Cc1ccccc1C	o-xylene	-0.9
CC(C)(C)C	neopentane	2.51
CC(C)(C)C	neopentane	2.51
CC(C)(C)C	neopentane	2.51
CC(C)(C)C	neopentane	2.51
CC(C)(C)C	neopentane	2.51
CCCC#C	pent-1-yne	0.01
CCCC#C	pent-1-yne	0.01
CCCC#C	pent-1-yne	0.01
CCCC#C	pent-1-yne	0.01
CCCC#C	pent-1-yne	0.01
c1ccc2c(c1)C(=O)NC2=O	phthalimide	-9.61
c1ccc2c(c1)C(=O)NC2=O	phthalimide	-9.61
c1ccc2c(c1)C(=O)NC2=O	phthalimide	-9.61
c1ccc2c(c1)C(=O)NC2=O	phthalimide	-9.61
c1ccc2c(c1)C(=O)NC2=O	phthalimide	-9.61
CCCCI	1-iodobutane	-0.25
CCCCI	1-iodobutane	-0.25
CCCCI	1-iodobutane	-0.25
CCCCI	1-iodobutane	-0.25
CCCCI	1-iodobutane	-0.25
Cc1ccc(cc1)O	p-cresol	-6.13
Cc1ccc(cc1)O	p-cresol	-6.13
Cc1ccc(cc1)O	p-cresol	-6.13
Cc1ccc(cc1)O	p-cresol	-6.13
Cc1ccc(cc1)O	p-cresol	-6.13
CC(C)I	2-iodopropane	-0.46
CC(C)I	2-iodopropane	-0.46
CC(C)I	2-iodopropane	-0.46
CC(C)I	2-iodopropane	-0.46
CC(C)I	2-iodopropane	-0.46
COc1ccccc1O	2-methoxyphenol	-5.94
COc1ccccc1O	2-methoxyphenol	-5.94
COc1ccccc1O	2-methoxyphenol	-5.94
COc1ccccc1O	2-methoxyphenol	-5.94
COc1ccccc1O	2-methoxyphenol	-5.94
C1CC=CC1	cyclopentene	0.56
C1CC=CC1	cyclopentene	0.56
C1CC=CC1	cyclopentene	0.56
C1CC=CC1	cyclopentene	0.56
C1CC=CC1	cyclopentene	0.56
C[C@H](C(F)(F)F)O	111-trifluoropropan-2-ol	-4.2
C[C@H](C(F)(F)F)O	111-trifluoropropan-2-ol	-4.2
C[C@H](C(F)(F)F)O	111-trifluoropropan-2-ol	-4.2
C[C@H](C(F)(F)F)O	111-trifluoropropan-2-ol	-4.2
C[C@H](C(F)(F)F)O	111-trifluoropropan-2-ol	-4.2
CCCN	propan-1-amine	-4.39
CCCN	propan-1-amine	-4.39
CCCN	propan-1-amine	-4.39
CCCN	propan-1-amine	-4.39
CCCN	propan-1-amine	-4.39
c1ccc(c(c1)[N+](=O)[O-])O	2-nitrophenol	-4.58
c1ccc(c(c1)[N+](=O)[O-])O	2-nitrophenol	-4.58
c1ccc(c(c1)[N+](=O)[O-])O	2-nitrophenol	-4.58
c1ccc(c(c1)[N+](=O)[O-])O	2-nitrophenol	-4.58
c1ccc(c(c1)[N+](=O)[O-])O	2-nitrophenol	-4.58
Cc1cccc2c1cccc2	1-methylnaphthalene	-2.44
Cc1cccc2c1cccc2	1-methylnaphthalene	-2.44
Cc1cccc2c1cccc2	1-methylnaphthalene	-2.44
Cc1cccc2c1cccc2	1-methylnaphthalene	-2.44
Cc1cccc2c1cccc2	1-methylnaphthalene	-2.44
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)Cl	hexachlorobenzene	-2.33
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)Cl	hexachlorobenzene	-2.33
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)Cl	hexachlorobenzene	-2.33
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)Cl	hexachlorobenzene	-2.33
c1(c(c(c(c(c1Cl)Cl)Cl)Cl)Cl)Cl	hexachlorobenzene	-2.33
CCCCC/C=C/C=O	oct-2-enal	-3.43
CCCCC/C=C/C=O	oct-2-enal	-3.43
CCCCC/C=C/C=O	oct-2-enal	-3.43
CCCCC/C=C/C=O	oct-2-enal	-3.43
CCCCC/C=C/C=O	oct-2-enal	-3.43
CCCCCCC#C	oct-1-yne	0.71
CCCCCCC#C	oct-1-yne	0.71
CCCCCCC#C	oct-1-yne	0.71
CCCCCCC#C	oct-1-yne	0.71
CCCCCCC#C	oct-1-yne	0.71
CCOP(=S)(OCC)Oc1cc(nc(n1)C(C)C)C	diazinon	-6.48
CCOP(=S)(OCC)Oc1cc(nc(n1)C(C)C)C	diazinon	-6.48
CCOP(=S)(OCC)Oc1cc(nc(n1)C(C)C)C	diazinon	-6.48
CCOP(=S)(OCC)Oc1cc(nc(n1)C(C)C)C	diazinon	-6.48
CCOP(=S)(OCC)Oc1cc(nc(n1)C(C)C)C	diazinon	-6.48
CCCCCCCC(=O)OC	methyl octanoate	-2.04
CCCCCCCC(=O)OC	methyl octanoate	-2.04
CCCCCCCC(=O)OC	methyl octanoate	-2.04
CCCCCCCC(=O)OC	methyl octanoate	-2.04
CCCCCCCC(=O)OC	methyl octanoate	-2.04
C1CCNC1	pyrrolidine	-5.48
C1CCNC1	pyrrolidine	-5.48
C1CCNC1	pyrrolidine	-5.48
C1CCNC1	pyrrolidine	-5.48
C1CCNC1	pyrrolidine	-5.48
c1cc(ccc1C=O)O	4-hydroxybenzaldehyde	-8.83
c1cc(ccc1C=O)O	4-hydroxybenzaldehyde	-8.83
c1cc(ccc1C=O)O	4-hydroxybenzaldehyde	-8.83
c1cc(ccc1C=O)O	4-hydroxybenzaldehyde	-8.83
c1cc(ccc1C=O)O	4-hydroxybenzaldehyde	-8.83
CCCCCCCCl	1-chloroheptane	0.29
CCCCCCCCl	1-chloroheptane	0.29
CCCCCCCCl	1-chloroheptane	0.29
CCCCCCCCl	1-chloroheptane	0.29
CCCCCCCCl	1-chloroheptane	0.29
C1COCCO1	1,4-dioxane	-5.06
C1COCCO1	1,4-dioxane	-5.06
C1COCCO1	1,4-dioxane	-5.06
C1COCCO1	1,4-dioxane	-5.06
C1COCCO1	1,4-dioxane	-5.06
